### ISSUE TITLE
Please can the historical data for NY0516 be re-instated? It seems that the recorder deleted it...

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#10]

**Comment by Gary-van-Breda** [comment]
I've looked into this. - I'm assuming we are talking about WCBS-BC site NY0516.
NY0516 was created as part of the original wcbs squares upload.
There were no samples uploaded as part of the historic WCBS visits upload.
The original square (id 118690) was deleted, and then recreated (id 163900): this new square has 7 visits registered on it from 2016/06/25 onwards, all of which are visible in the user's My Walks page, and on the Annual Summary page. These were all created on 2016/10/04. The first of these visits was originally created on 2016/09/20, but was later deleted on 2016/09/29 before being recreated.

There is no evidence of any visits registered to the original location, or any other visits on the new location.

@zrandle : what historical data are you expectig to see?

**Comment by zrandle** [comment]
my mistake - just checked and  your're right nothing to re-insate. Sorry for the confusion. All is well.
