### ISSUE TITLE
UKBMS performance

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#100]
Hi there, the site has got incredibly slow again. Can this be looked at? Thanks Zoe

**Comment by zrandle** [comment]
Here we go again!! All sites page:

here was an SQL error: ERROR: canceling statement due to statement timeout - SELECT l.id as "id", l.name as "name", l.centroid_sref as "centroid_sref", CASE WHEN lsub.occurrences IS NULL THEN 0 ELSE lsub.occurrences END as "occurrences", CASE WHEN lsub.taxa IS NULL THEN 0 ELSE lsub.taxa END as "taxa", CASE WHEN lsub.groups IS NULL THEN 0 ELSE lsub.groups END as "groups", l.code as "code", location57.id as attr_id_location_57, location57.int_value as attr_location_57 FROM locations l JOIN locations_websites lw ON l.id=lw.location_id AND lw.deleted=false LEFT JOIN ( SELECT section.parent_id as id, COUNT(DISTINCT o.id) AS occurrences, COUNT(DISTINCT o.taxon_meaning_id) AS taxa, COUNT(DISTINCT o.taxon_group_id) AS groups FROM cache_occurrences_functional o JOIN locations section ON o.location_id=section.id AND section.deleted=FALSE WHERE o.zero_abundance='f' AND o.website_id in (27) GROUP BY section.parent_id ) AS lsub on l.id=lsub.id LEFT JOIN location_attribute_values location57 ON location57.location_id=l.id AND location57.location_attribute_id=57 AND location57.deleted=false WHERE l.deleted=false AND (l.code = '' OR l.code IS NULL OR 'no'!='yes') AND l.location_type_id=777 AND (lw.website_id in (27) or lw.website_id is null) ORDER BY occurrences DESC, taxa DESC, name LIMIT 2001

**Comment by DavidRoy** [comment]
Performance issues are being addressed elsewhere by switching slow reports to an alternative data model.  It will take time to complete this work.  I could not replicate your error on the sites page and managed to download the site/section details for all but the Transect-section report.  I will send them to you separately by email.

**Comment by zrandle** [comment]
The system is becoming unworkable again. many issues this morning with time-out. This is the latest - trying to download data for a site ...

{"error":"There was an SQL error: ERROR:  canceling statement due to statement timeout - SELECT vt.sample_id as main_id,\r\n      vt.text_value, vt.float_value, vt.int_value, vt.date_start_value, vt.date_end_value, vt.date_type_value,\r\n      at.id, at.caption, at.data_type, at.termlist_id, at.multi_value  FROM samples lt0 INNER JOIN sample_attribute_values vt ON (vt.sample_id =  lt0.id and vt.deleted = FALSE)  INNER JOIN sample_attributes at ON (vt.sample_attribute_id = at.id and at.deleted = FALSE)  INNER JOIN sample_attributes_websites rt ON (rt.sample_attribute_id = at.id and rt.deleted = FALSE and (rt.restrict_to_survey_id = 64 or rt.restrict_to_survey_id is null))  WHERE lt0.deleted = FALSE       and lt0.parent_id IS NULL       and lt0.survey_id = 64       AND (''='' OR CAST(lt0.created_by_id AS character varying)='')       AND lt0.date_end >= CAST(COALESCE('01\/01\/2016','1500-01-01') as date)       AND lt0.date_start <= CAST(COALESCE('31\/12\/2016','1500-01-01') as date) ORDER BY rt.form_structure_block_id, rt.weight, at.id, lt0.id ","code":44,"file":"D:\\websites\\warehouse\\system\\libraries\\drivers\\Database\\Pgsql.php","line":342,"trace":[]}

**Comment by Gary-van-Breda** [comment]
John has said that said that he discovered the primary culprit was a report left on a publically accessible page which had a pager on it that was being paged all the way through (presumably by bots). As the report was complex, it was a killer for the warehouse. (sorry I don't know which report or even which website). It meant that a tipping point was reached where some of the scheduled tasks were not finishing (like the code to generated the estimates for the annual summary).
I assume he has addressed this, as it does not seem to be an issue now.
