### ISSUE TITLE
Dodgy accounts

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#101]
@DavidRoy @BirenRathod

Hi, We've jumped back to receiving a lot of bogus new accounts on the UKBMS website again.
300 new accounts overnight last night with accompanying Spam Forum posts. I'm in the process of deleting them, but is there anything else we could do to reduce them?

The majority of these accounts have email addresses that end with .ru , so is there any way we could simply block all .ru emails from registering on the site? 
I can't think of any legitimate accounts with Russian email addresses.

Thanks Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook @DavidRoy 

East way to restrict them via user restriction, Just add a rule for that email address you can find link here ->http://www.ukbms.org/mydata/admin/config/people/user-restrictions

I have just added one for .ru.
Also,  I'm deleting all those forums.

**Comment by BirenRathod** [comment]
@IanMiddlebrook 

All forums from .ru user have now deleted. Also, I noticed that there is no new post in forum since 5/2017. so I presumed this is right if not there may be some post deleted by mistake. so appologise for that.

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod . I tried that link http://www.ukbms.org/mydata/admin/config/people/user-restrictions but don't seem to have access?

**Comment by BirenRathod** [comment]
@IanMiddlebrook 
I just implemented the permission, so you should be able to access the link.

**Comment by IanMiddlebrook** [comment]
Excellent - thanks @BirenRathod
