### ISSUE TITLE
Annual summary table failing to update

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#103]
Hi @Gary-van-Breda @DavidRoy @BirenRathod

I'm not sure who deals with this, but it looks like the Annual Summary table has not been updating for quite some time.

Looking at the Summary Table for 2018, for All Sites/All Recorders, I know there are a string of silly early records (Week 0) for unlikely species which were all deleted at least 2 months ago, but are still showing up in the summary table.

I also know that a recorder has been entering data for Bradfield Woods (2 transects) over the last couple of weeks, but none of these records show up in the Summary Table (the Raw Data table only shows date, sun & temp for each walk.

Could we please get this sorted before the new season starts?

Many thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook 
I think @Gary-van-Breda should be dealing with this.

**Comment by DavidRoy** [comment]
@IanMiddlebrook  To ease the performance issues a few weeks ago, we switched off the element of the scheduled task that updates these tables.  We'll re-instigate in time for the formal start of the season on 1st April.

**Comment by Gary-van-Breda** [comment]
This has now been reinstated, and the catch up process run.
@IanMiddlebrook : can you check again, and if there is data missing that you expect to be there, can you let me know what dates? Any extra info that can identify where an example issue exists helps.

**Comment by IanMiddlebrook** [comment]
Thanks
