### ISSUE TITLE
Annual Summary page error

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#105]
Hi @Gary-van-Breda @DavidRoy 

When loading up the Annual summary page and selecting data from 'All recorders', I keep getting the following lengthy error message: 

_Invalid response received from Indicia Warehouse. Array ( [result] => [output] => [{"date_start":"2019-03-25","date_end":"2019-03-31","date_type":"DD","type":"W","period_number":"0","taxa_taxon_list_id":"283094","taxonomic_sort_order":"49","taxon":"Vanessa (Cynthia) cardui","preferred_taxon":"Vanessa (Cynthia) cardui","default_common_name":"Painted Lady","taxon_meaning_id":"127679","count":"0","estimate":"0"},{"date_start":"2019-04-08","date_end":"2019-04-14","date_type":"DD","type":"W","period_number":"2","taxa_taxon_list_id":"283047","taxonomic_sort_order":"16","taxon":"Brimstone","preferred_taxon":"Gonepteryx rhamni","default_common_name":"Brimstone","taxon_meaning_id":"127655","count":null,"estimate":"0"},{"date_start":"2019-03-25","date_end":"2019-03-31","date_type":"DD","type":"W","period_number":"0","taxa_taxon_list_id":"283105","taxonomic_sort_order":"54","taxon":"Comma","preferred_taxon":"Polygonia c-album","default_common_name":"Comma","taxon_meaning_id":"127684","count":"0","estimate":"0"},{"date_start":"2019-03-25","date_end":"2019-03-31","date_type":"DD","type":"W","period_number":"0","taxa_taxon_list_id":"283047","taxonomic_sort_order":"16","taxon":"Brimstone","preferred_taxon":"Gonepteryx rhamni","default_common_name":"Brimstone","taxon_meaning_id":"127655","count":"2","estimate":"2"},{"date_start":"2019-04-01","date_end":"2019-04-07","date_type":"DD","type":"W","period_number":"1","taxa_taxon_list_id":"283047","taxonomic_sort_order":"16","taxon":"Brimstone","preferred_taxon":"Gonepteryx rhamni","default_common_name":"Brimstone","taxon_meaning_id":"127655","count":"0","estimate":"0"},{"date_start":"2019-04-01","date_end":"2019-04-07","date_type":"DD","type":"W","period_number":"1","taxa_taxon_list_id":"283105","taxonomic_sort_order":"54","taxon":"Comma","preferred_taxon":"Polygonia c-album","default_common_name":"Comma","taxon_meaning_id":"127684","count":"1","estimate":"1"},{"date_start":"2019-04-08","date_end":"2019-04-14","date_type":"DD","type":"W","period_number":"2","taxa_taxon_list_id":"283105","taxonomic_sort_order":"54","taxon":"Comma","preferred_taxon":"Polygonia c-album","default_common_name":"Comma","taxon_meaning_id":"127684","count":null,"estimate":"1"},{"date_start":"2019-04-01","date_end":"2019-04-07","date_type":"DD","type":"W","period_number":"1","taxa_taxon_list_id":"283056","taxonomic_sort_order":"23","taxon":"Callophrys rubi","preferred_taxon":"Callophrys rubi","default_common_name":"Green Hairstreak","taxon_meaning_id":"127660","count":"1","estimate":"1"},{"date_start":"2019-04-08","date_end":"2019-04-14","date_type":"DD","type":"W","period_number":"2","taxa_taxon_list_id":"283056","taxonomic_sort_order":"23","taxon":"Callophrys rubi","preferred_taxon":"Callophrys rubi","default_common_name":"Green Hairstreak","taxon_meaning_id":"127660","count":null,"estimate":"1"},{"date_start":"2019-04-01","date_end":"2019-04-_

etc.

The page was working OK earlier in the week, and it's still OK for just 'My Data', but for All Recorders, this message comes up for each year I've tried.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@johnvanbreda
This looks like the insert into the request log is failing, possibly because the report request has a user_id parameter set to "NULL", and it looks like this has overridden the user_id which holds who has requested the report, & it is trying to insert this text value into an integer database field.
Who looks after this?
Has there been any recent changes in this area?

**Comment by johnvanbreda** [comment]
Yes - recent changes to request logging due to persistent issues with performance. I'll look into this right now.

**Comment by johnvanbreda** [comment]
I've rolled out a fix for this. The user_id parameter normally infers the logged in user so if it is a choice in the report parameter it might be better to choose a different parameter name? Not a high priority though.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : I've tested this on the Live Annual summary, and it looks like its working now.

**Comment by IanMiddlebrook** [comment]
Great, thanks
