### ISSUE TITLE
Additional WCBS-BBS squares to be added to the system

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#106]
Hi

Please can these WCBS-BBS squares be added to the system. 
SH8618
SJ0237
SJ0245
SH7220
SJ0948
SH8119
SH7432
SH7510
SH8634
SH6824

Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
Done

**Comment by zrandle** [comment]
thank you
