### ISSUE TITLE
incorrect count value warnings on Walk Data Entry

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#107]
Hi @Gary-van-Breda @DavidRoy 

Something seems to have gone wrong on the Walk Data Entry page with the pop-up warnings for high counts - they are coming up for much lower numbers.

Eg. I've just tried to enter 3 Orange-tips (Warning: The value entered for this taxon on this transect section (3) exceeds the expected maximum (20)), 
or 2 Green Hairstreaks (Warning: The value entered for this taxon on this transect section (2) exceeds the expected maximum (10))
or 2 Small Heaths (Warning: The value entered for this taxon on this transect section (2) exceeds the expected maximum (100))

Fairly sure these were all working fine last year, so I wonder what's changed?

Thanks,

Ian

**Comment by DavidRoy** [comment]
@BirenRathod can you advise on this while Gary is away this week.  Has the walk data entry page changed recently with the other changes taking place?  I think this relates to the rule checking happening at the section level whereas they should be applied at the whole walk level 

Original issue is #62

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy @BirenRathod 
Just to clarify, the checks should be happening at individual section level - not the whole walk. That particular issue was cleared up in #62

**Comment by IanMiddlebrook** [comment]
But the current warnings are happening way below the threshold in any case.

**Comment by DavidRoy** [comment]
Sorry, I didn't read your message carefully enough and jumpted to the wrong conclusion.  It might be simplest to leave to Gary when he's back

**Comment by Gary-van-Breda** [comment]
Not sure why it has started acting the way it has now (has there been a PHP version change?).
Anyway, @BirenRathod , can you unzip the following file and drop it into the UKBMS iform/client_helpers/prebuilt_forms/js directory? Thanks
[ukbms_sectioned_transects_input_sample.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3076510/ukbms_sectioned_transects_input_sample.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
There is a updated version of PHP which is 7.2.16

This file has gone on live UKBMS.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
Seems to be behaving itself again.
