### ISSUE TITLE
Branch Co-ordinators unable to load Branch Sites

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#108]
Hi @DavidRoy @Gary-van-Breda 

Many Branch Co-ordinators are still unable to load up their 'Branch Sites' page due to a time-out issue. This seems to mainly affect the Branches with the most site - so the page does work for some people but constantly times out for others. (Issue was raised with David via Martin Raper a couple of weeks ago, but I realised there was no GitHub issue to keep track of any progress).

The time out message reads:
There was an SQL error: ERROR: canceling statement due to statement timeout - SELECT l.id as "id", l.name as "name", COUNT(DISTINCT o.id) as "occurrences", COUNT(DISTINCT o.taxon_meaning_id) as "taxa", COUNT(DISTINCT o.taxon_group_id) as "groups", ( SELECT string_agg(mvattr_id_location_81.id::text, ', ') FROM location_attribute_values mvattr_id_location_81 WHERE mvattr_id_location_81.location_id=l.id AND mvattr_id_location_81.location_attribute_id=81 AND deleted = FALSE ) as attr_id_location_81, (select string_agg(mvattr_location_81.int_value::text, ', ') from location_attribute_values mvattr_location_81 where mvattr_location_81.location_id=l.id and mvattr_location_81.location_attribute_id=81 AND deleted = FALSE) as attr_location_81 FROM locations_websites lw JOIN locations l ON l.id=lw.location_id and l.deleted=false LEFT JOIN cache_termlists_terms ctt on ctt.id=l.location_type_id LEFT JOIN (samples sp JOIN samples s ON s.parent_id=sp.id ) ON sp.location_id=l.id LEFT JOIN cache_occurrences_functional o ON o.sample_id = s.id and o.survey_id=s.survey_id and o.website_id in (27) WHERE (lw.website_id in (27) or lw.website_id is null) AND (o.zero_abundance='f' OR o.id IS NULL) AND (CAST(o.survey_id AS character varying)='' OR ''='') AND (CAST(l.location_type_id AS character varying)='777' OR '777'='' OR ctt.term='777') AND (trim('')='' OR ''='Click here' OR s.date_end >= CAST(COALESCE('','1500-01-01') as date)) AND (trim('')='' OR ''='Click here' OR s.date_start <= CAST(COALESCE('','1500-01-01') as date)) AND EXISTS( SELECT mvattr_location_81.int_value FROM location_attribute_values mvattr_location_81 WHERE mvattr_location_81.location_id=l.id AND mvattr_location_81.location_attribute_id=81 AND mvattr_location_81.int_value = 208 AND mvattr_location_81.deleted = false ) GROUP BY l.id, l.name ORDER BY occurrences DESC, taxa DESC, name ASC LIMIT 21

Thanks, Ian

**Comment by DavidRoy** [comment]
I think this is a candidate for switching to Elastic?
@johnvanbreda - could you take this on under ABLE funding as it will help the European schemes too

**Comment by johnvanbreda** [comment]
I've had an explore. First, looking at the query which runs, it is fairly complex with several subqueries and some stuff that looks unnecessary for the output:
```sql
SELECT l.id as "id",
l.name as "name",
COUNT(DISTINCT o.id) as "occurrences",
COUNT(DISTINCT o.taxon_meaning_id) as "taxa",
COUNT(DISTINCT o.taxon_group_id) as "groups",
(
  SELECT string_agg(mvattr_id_location_81.id::text, ', ')
  FROM location_attribute_values mvattr_id_location_81
  WHERE mvattr_id_location_81.location_id=l.id
  AND mvattr_id_location_81.location_attribute_id=81
  AND deleted = FALSE
) as attr_id_location_81,
(select string_agg(mvattr_location_81.int_value::text, ', ')
  from location_attribute_values mvattr_location_81
  where mvattr_location_81.location_id=l.id and mvattr_location_81.location_attribute_id=81 AND deleted = FALSE) as attr_location_81
      FROM locations_websites lw
      JOIN locations l ON l.id=lw.location_id and l.deleted=false
      LEFT JOIN cache_termlists_terms ctt on ctt.id=l.location_type_id
      LEFT JOIN (samples sp 
        JOIN samples s ON s.parent_id=sp.id
      ) ON sp.location_id=l.id
      LEFT JOIN cache_occurrences_functional o ON o.sample_id = s.id and o.survey_id=s.survey_id and o.website_id in (27)
      
      WHERE (lw.website_id in (27) or lw.website_id is null)
      AND (o.zero_abundance='f' OR o.id IS NULL)
      AND (CAST(o.survey_id AS character varying)='' OR ''='')
      AND (CAST(l.location_type_id AS character varying)='777' OR '777'='' OR ctt.term='777')
      AND (trim('')='' OR ''='Click here' OR s.date_end >= CAST(COALESCE('','1500-01-01') as date))
      AND (trim('')='' OR ''='Click here' OR s.date_start <= CAST(COALESCE('','1500-01-01') as date))
      AND EXISTS(
  SELECT mvattr_location_81.int_value
  FROM location_attribute_values mvattr_location_81
  WHERE mvattr_location_81.location_id=l.id AND mvattr_location_81.location_attribute_id=81
  AND mvattr_location_81.int_value = 205
  AND mvattr_location_81.deleted = false
)

GROUP BY l.id, l.name  ORDER BY occurrences DESC, taxa DESC, name ASC LIMIT 21;
```

This could be tidied up to just what is needed for this page:
```
SELECT l.id as "id",
l.name as "name",
COUNT(DISTINCT o.id) as "occurrences",
COUNT(DISTINCT o.taxon_meaning_id) as "taxa"
FROM locations_websites lw
      JOIN locations l ON l.id=lw.location_id and l.deleted=false AND l.location_type_id=777 
	  JOIN location_attribute_values mvattr_location_81 ON mvattr_location_81.location_id=l.id
	    AND mvattr_location_81.location_attribute_id=81 AND mvattr_location_81.deleted = FALSE
		AND mvattr_location_81.int_value = 205
      LEFT JOIN samples sp ON sp.location_id=l.id
      LEFT JOIN cache_occurrences_functional o ON o.parent_sample_id = sp.id 
	    AND o.zero_abundance=false
      WHERE lw.website_id in (27)  
GROUP BY l.id, l.name  ORDER BY occurrences DESC, taxa DESC, name ASC LIMIT 21;
```

However, on examining this query I find that it is not much faster. Nearly all the time in this case is used by an index scan on cache_occurrences_functional(parent_sample_id) - even though there are only about 800 samples to scan in this case, it's taking nearly 0.1s per scan so adds up to about 1 minute to run the query. I'm very surprised that an index scan would be this slow to be honest.

Staying within possible PostgreSQL solutions, a nightly process could build a table of UKBMS occurrences with just the occurrence_id, parent_location_id and taxon_meaning_ids, with an index on parent_location_id. Then the query would be loading the minimal data possible to count the records and species so would be as fast as the disk allows. 

Looking at Elasticsearch as a solution, the first thing to note is that Elasticsearch will not know which locations are linked to which branch coordinator, so we have to do a pre-query in PostgreSQL to find the parameter list of location IDs. Fortunately this query is quick:

```sql
SELECT l.id as "id",
l.name as "name"
FROM locations l 
JOIN locations_websites lw on lw.location_id=l.id and lw.website_id=27 and lw.deleted=false	
JOIN location_attribute_values mvattr_location_81 ON mvattr_location_81.location_id=l.id
    AND mvattr_location_81.location_attribute_id=81 AND mvattr_location_81.deleted = FALSE
	AND mvattr_location_81.int_value = 205
WHERE l.deleted=false AND l.location_type_id=777;
```

Now we know the list of location IDs for the branch coordinator we can feed them into an Elasticsearch query such as:
```
GET /occurrence_brc1_v1/_search
{
  "aggs": {
    "2": {
      "terms": {
        "field": "location.parent.name.keyword",
        "size": 1000,
        "order": {
          "_count": "desc"
        }
      },
      "aggs": {
        "count_species": {
          "cardinality": {
            "field": "taxon.species_taxon_id"
          }
        },
        "4": {
          "cardinality": {
            "field": "taxon.accepted_taxon_id"
          }
        }
      }
    }
  },
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "terms": {
            "location.parent.location_id": [
              15998, 
              2811, 
              2785, 
              2553, 
              2820, 
              2536
            ]
          }
        },
        {
          "match_phrase": {
            "occurrence.zero_abundance": {
              "query": false
            }
          }
        }
      ]
    }
  }
}
```

This data can be easily added to a grid loaded from Elasticsearch and it takes ~25ms to run the aggregation in Elasticsearch. 

The area of functionality on this page which is significant that we don't yet have an easy approach for in Elasticsearch are the 3 GIS section download formats. Can these links be left as is for now? If so then I think the way forward is:
1. I'll code changes to the dynamic_elasticsearch prebuilt form so it is possible to use a Warehouse report to grab data which can then be fed through to an Elasticsearch datasource as a parameter.
2. I'll then be able to provide Gary with a demo page that shows how this works, loading the list of location IDS from the warehouse, feeding them into an Elasticsearch datasource as a parameter, then displaying a report grid plus download button.
3. Gary can then integrate this into UKBMS and use JavaScript to recreate the 3 section GIS links.

Does that sound like the correct approach?

**Comment by DavidRoy** [comment]
Thanks @johnvanbreda.  Before we decide on the best solution - @IanMiddlebrook can you confirm what is needed on this page and what is used for.  How useful is the calculated values of number of records and number of sites for example.  Could the GIS downloads be delivered via a different route - e.g. a Downloads page that allows access to the various downloads across the site.

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy @johnvanbreda 
The fundamental pupose of this page is for Branch Co-ordinators to access the details of transects in their area, check the route maps and assign new recorders to their transects.
The counts of records and species are only of secondary interest, although sometimes useful in quickly distinguishing between current and discontinued transects with similar names.
Would the report be produced much quicker if we only counted 'samples' (ie, no. of walks) rather than all records?
The GIS downloads will only be used on rare occasions, so could certainly be delivered via a different route.

**Comment by DavidRoy** [comment]
Thanks @IanMiddlebrook.  In a similar vein, can you confirm what is needed on the all-sites page - http://www.ukbms.org/mydata/all-sites.  Do you need the counts and downloads on this page?

**Comment by johnvanbreda** [comment]
Yes, counting samples alone will be much quicker. From cold, the original query took 1 minute, but a samples only version takes 5 seconds:
```sql
SELECT l.id as "id",
l.name as "name",
COUNT(DISTINCT s.id) as "samples"
FROM locations_websites lw
      JOIN locations l ON l.id=lw.location_id and l.deleted=false AND l.location_type_id=777 
	  JOIN location_attribute_values mvattr_location_81 ON mvattr_location_81.location_id=l.id
	    AND mvattr_location_81.location_attribute_id=81 AND mvattr_location_81.deleted = FALSE
		AND mvattr_location_81.int_value = 205
      LEFT JOIN samples sp ON sp.location_id=l.id
      WHERE lw.website_id in (27)  
GROUP BY l.id, l.name  ORDER BY samples DESC, name ASC LIMIT 21;
```

**Comment by DavidRoy** [comment]
@johnvanbreda Please make this simple change in that case and we can consider wider changes in due course

**Comment by IanMiddlebrook** [comment]
@DavidRoy 
Again with the 'All Sites' page, the counts are of limited interest, and a count of samples wold suffice. The GIS downloads could certainly be accessed from a separate page.

**Comment by DavidRoy** [comment]
@johnvanbreda please can you also simplify this report for the all-sites page 
http://www.ukbms.org/mydata/all-sites

**Comment by johnvanbreda** [comment]
Done for branch and all sites pages.

**Comment by Gary-van-Breda** [comment]
@DavidRoy & @IanMiddlebrook : Should we use this on the "My sites" page as well?

**Comment by DavidRoy** [comment]
My sites is typically only a few sites so performance is not an issue?  So good to give the extra information

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : can you tweak the branch report - we intend on using the same report for EBMS/ABLE, and the hardcoded attribute id value 81 is going to be a problem - can we hand this ID is as a report parameter? It will also help if we ever decide to use it on the "My sites" page.

**Comment by johnvanbreda** [comment]
Done - the parameter is `user_link_attr_id`.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda Thanks : now implemented on ABLE.

**Comment by DavidRoy** [comment]
Thanks for resolving.  Now closing this issue
