### ISSUE TITLE
UKBMS security

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#111]
Hi 
I've had an email from a Branch Champion re UKBMS security. See below:
"Just one thing on providing site owner information on the UKBMS system - every time I log onto the UKBMS system my machine tell me that the site is 'not secure' (it shows in red as I log on).  This appears throughout my sessions on the site in the same position as the little padlock appears on sites that I would expect to be secure - for example if entering payment details when ideally I not only look for the little padlock but prefer it to be green.  I have just gone into the new 'Site Owner' tab on the UKBMS system and it still shows as 'Not Secure' on my computer. " 

Is this being looked at?

Thanks

Zoe

**Comment by DavidRoy** [comment]
It is being dealt with when we update the UKBMS website.  This work is underway

**Comment by DavidRoy** [comment]
This has been resolved.  The site now has https implemented.  Closing the issue
