### ISSUE TITLE
Recorder's Name field missing from Walk data Entry page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#112]
@DavidRoy @Gary-van-Breda 

The Walk Data Entry page for UKBMS appears to have lost the field for ‘Recorder’s Name’.

Has this form changed recently? I presume it’s not deliberate.

This seems to apply to both the Transect and the WCBS entry pages.

Could the field please be re-instated asap.

Thanks, Ian

**Comment by DavidRoy** [comment]
Should be fixed.  Please close if so.

Thanks

**Comment by IanMiddlebrook** [comment]
Thanks, seems to be fixed, so I'll close the issue.
But we now have 94 transect walks with no Recorder Name.

Regards, Ian
