### ISSUE TITLE
Section Plot week number offset

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#113]
Hi @Gary-van-Breda @DavidRoy 

A volunteer has drawn my attention to a problem with the Section Plots. It seems that the week numbers are all offset by 1. So if you select Week 2 it shows data for Week 1, if you select Week 10 it shows data for Week 9 etc.

I confess I've never looked at the Section Plot week by week before, but it seems to be consistent across sites and years. 

I also checked whether this had any implication on the totals for 'All in-season weeks (1-26)'. I found that this wasn't working correctly either. In the example I checked (year 2018, Abbotts Hall Farm 1) the section totals for weeks 1-26 were exactly the same as section totals for all weeks (-3 to 30), even though there was a walk in week 27 with 10 butterflies counted.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@BirenRathod : Can you unzip the attached file deploy the files in it into the UKBMS iform/client_helpers directory, and its subdirectories (the JS file should go in  iform/client_helpers/prebuilt_forms/js)
[UKBMS Issue 113.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3613169/UKBMS.Issue.113.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda & @DavidRoy 
These files have now uploaded to live site.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : can you review and hopefully close? There is now a difference between the 1->26 and -3->30 week totals for year 2018, Abbotts Hall Farm 1

**Comment by IanMiddlebrook** [comment]
Seems to be OK

Many thanks Gary
