### ISSUE TITLE
Annual Summary page not loading

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#116]
@Gary-van-Breda 

Gary – This particular page is failed to load due to this error 
“The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.”

Could be some compatibility issue with https.

Biren

**Comment by DavidRoy** [comment]
@IanMiddlebrook annual report for all recorders/all sites works fine for me now.  Can you confirm and close issue if now resolved

**Comment by IanMiddlebrook** [comment]
Thanks
