### ISSUE TITLE
UKBMS not working at all now

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#117]
I cannot access even the home page. Same on my mobile phone... 

This page isn’t working www.ukbms.org redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by Gary-van-Breda** [comment]
I have cleared all the site caches: its working OK for me now. Can you try again?

**Comment by zrandle** [comment]
Yes it seems ok again now. Thanks.

**Comment by DavidRoy** [comment]
Thanks, closing issue
