### ISSUE TITLE
recorders unable to find ukbms.org/mydata

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#118]
Hi @Gary-van-Breda , @BirenRathod

Several recorders still seem to be having trouble getting on to the UKBMS website. 
I believe this is a hangover from whatever happened over the weekend, but I'm struggling to respond usefully to the recorders as I'm unable to replicate their problems.

Typically, they just keep getting re-directed to https://www.ukbms.org/  and even clicking on the 'My Data' link from that page just brings them back to the same page.

Some have tried going directly to https://www.ukbms.org/mydata/user/login  but are greeted with an error message:
**Server Error in '/' Application.
________________________________________
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

Requested URL: /user/login.aspx**

Most such recorders are using Google Chrome, although I also use Google Chrome and am having no trouble.

One recorder found that the links worked fine on Safari and MS Edge, but not Google Chrome, although he has always used that in the past with no trouble.

Others have tried clearing their caches, but still no joy.

Do you have any ideas what their problems might be?

Thanks,

Ian

**Comment by zrandle** [comment]
Many WCBS recorders had been in touch having the same problem. I think it could be their bookmarks or computers using a cached webpage. A lady managed to get in via internet explorer (not her usual browser) but could not get in via chrome. I got her to simply google ukbms my data and then she managed to get in via chrome...

**Comment by BirenRathod** [comment]
@zrandle & @IanMiddlebrook 
After migration, the UKBMS site has been now forced to use https. This is part of our policy of security. The people in the past have used this website, they need to clear the cookies on their regular browser otherwise they might end up with error page.

**Comment by BirenRathod** [comment]
Also, if they have accessed the website on Friday, they still required to clear the cookies.

**Comment by IanMiddlebrook** [comment]
Hi @BirenRathod   Would that explain ALL the problems mentioned above - ie. even if they click on an https: link, or they click on 'My Data' from the UKBMS home page, they still have problems?

Thanks, Ian

**Comment by BirenRathod** [comment]
Yes, I have tried everything what you mentioned above and found no problem now.

**Comment by IanMiddlebrook** [comment]
lol, well so have I and I have found no problem, but I'm asking on behalf of the recorders who are having problems.

**Comment by BirenRathod** [comment]
@IanMiddlebrook 
No problem. Please do mention to them as you are the primary contact person.

**Comment by IanMiddlebrook** [comment]
Hi @BirenRathod 
final query on this one:

a user is having trouble getting to https://www.ukbms.org/mydata/my-walks

She can login, which gets her to https://www.ukbms.org/mydata/user/28205  
but when she clicks on 'My Walks' it takes her to https://www.ukbms.org/my-walks  and an error message (in other words, /mydata/ is missing from the link). 
Again, I can't replicate this - but where could that problem come from?

thanks, Ian

**Comment by BirenRathod** [comment]
One possibility is she must have accessed the page when error had triggered and resides in her cookies. So again solution is she needs to clear cookies from beginning. if she clears cookies last week or or month which might not work in this case.

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod 
she has managed to sort this out by clearing her cookies as suggested.
