### ISSUE TITLE
New species missing from annual summary tables

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#119]
Hi @Gary-van-Breda 

A recorder has noted:
"I was excited to discover a couple of Wall Browns on the new Kerridge Hill transect on 14 September. I entered all the records that evening but when I looked just now at the Annual Summary for the transect in Reporting, the record is not there; all my other records for the same transect walk are present and correct, it's just the Wall Browns that are missing! The record is still there in My Walks, so what is going on here? "

I know there's usually a slight delay in picking up new species in the Summary Tables, but this is still missing after nearly 2 weeks.

Is there a catch up that can, or needs to, be run to remedy this and perhaps other new species missing from the tables for other sites?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@johnvanbreda , There are errors on the job queue - are they related to this?

@IanMiddlebrook : with the recent changes to the annual summary builder, there is no longer a concept of a catch up. Each change is queued, and the previous situation where a max limit of 1000(?) between runs of the estimation process was exceeded no longer applies.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda there are 3 errors in the work queue which relate to the bug you've already fixed in the develop branch. I'll clear them when I deploy the code. The errors relate to locations 220749, 217921 and 216737.

**Comment by Gary-van-Breda** [comment]
OK, ta.
I'll look for something else then. There are many other Wall Brown records.

**Comment by Gary-van-Breda** [comment]
Update to the summary builder sent for deployment.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
It looks like the Wall Browns at Kerridge Bay are now showing.
Do you think this issue is completely resolved?

Thanks, Ian
