### ISSUE TITLE
SP4778

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#12]
Hi the historical data for SP4778 are not displaying. Please can the old data be linked to this square?

**Comment by Gary-van-Breda** [comment]
Now done.

**Comment by DavidRoy** [comment]
@zrandle please close this issue if you are happy with this

**Comment by zrandle** [comment]
I've checked but cannot see any occurrence data for the 4 visits in 2015. I haven't checked previous years...

**Comment by Gary-van-Breda** [comment]
Data for SP4778 2015 now uploaded.

**Comment by zrandle** [comment]
Thanks
