### ISSUE TITLE
slow site

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#120]
Hi there I am trying to download the data from the system but it keeps timing out. Please can the performance issue be re-visited?

Thanks Zoe

**Comment by DavidRoy** [comment]
Which download is timing out?

**Comment by zrandle** [comment]
it was the occurrences for WCBS. I got there eventually but had to try a couple of times.

Thanks

Zoe

**Comment by zrandle** [comment]
actually it was samples. 

records and visits would be better names for the downloads. Occurrences and samples takes a bit more thinking about!

**Comment by DavidRoy** [comment]
I'll close this and pick up changes alongside other updates to the UKBMS website, including some of the recent developments for ABLE that can be brought across
