### ISSUE TITLE
Choosing default species list

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#121]
Following up on a much-requested feature:

Would it be possible for recorders to set a default for their preferred Species List on the Walk Data Entry page?

At present, it defaults to 'All Species', but many/most recorders would prefer 'Species Known at This Site'. It would, however, be awkward to use that as an overall default (because it would be blank, and thus confusing, for new transects).

So would it be possible either for recorders to set a default preference in their account settings, or perhaps for their cookies (I think) to remember their most recent choice (much like the website remembers the preferred Site Type across My Sites/My Walks etc.)?

Many thanks,

Ian

**Comment by Gary-van-Breda** [comment]
This functionality was already present in the form, and I have just configured it.
On the user settings page there is a new "Preferences" vertical tab near the "What you record": in this there is a new field which will allow the user to choose which list is displayed.
@IanMiddlebrook : can you give this a test?

**Comment by IanMiddlebrook** [comment]
Many thanks Gary,

This seems to be working for me. 
There is just a mismatch between the two lists of options. Under Preferences there is an additional option of a Species list associated with the Branch I record in.  This option does not appear on the Walk Data Entry page (and if I select this option, I just end up with the Full Species List).

Thanks,

Ian

**Comment by Gary-van-Breda** [comment]
On the User profile page, in approximately the same area as above, there is a "Your branch" vertical tab. In here the user can select the branch(es) that they records for. If there is a branch specific species list defined for the branch that the user has selected, then an extra option is added to the Walk Data Entry page.
Currrently, I think there is only one branch list defined, for Northern Ireland.

**Comment by DavidRoy** [comment]
@Gary-van-Breda how do we configure branch lists?

**Comment by Gary-van-Breda** [comment]
These are configured on the walk data entry form configuration, much like the common taxon list is.

**Comment by Gary-van-Breda** [comment]
See #61
