### ISSUE TITLE
Summary Table Updates

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#122]
Hi @Gary-van-Breda 

A recorder initially made a mistake when entering data, by entering it for the wrong date. When he noticed the error, he edited the walk by changing the date on the Walk Data Entry page.

Now, when he looks at the Annual Summary page, he finds that the date change has been picked up in the Raw Data table, but still appears in the wrong week under the Summary and Estimate tables (nearly 3 weeks after making the change).

This refers to Killard Nature Reserve (2018), the walk originally being entered for 19th May (week 7) but now changed to 19th June (week 12).

Is there a reason that this type of change would be missed by the Summary/Estimates Tables?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
This is a misunderstanding on my part - I did not pick up the fact that the date could be changed from the UKBMS front end.
Summary Builder Code altered and sent for deployment on the warehouse (see https://github.com/Indicia-Team/warehouse/pull/338). This includes a database update script.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : when is the deadline for entry of all the 2019 data? @johnvanbreda I think we need to get the deployment done by then.

**Comment by IanMiddlebrook** [comment]
The main deadline is/was 31st October, though there will still be more data entered up to the end of the year, after a gentle reminder. Branch Co-ordinators will be doing much of their checking/collating/validating over the next few weeks.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda I've deployed the summary builder changes.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : the data fix changes have now worked their way through the system: the Killard Nature Reserve data has moved on the Annual summary.
Can you confirm you are happy, and hopefully close this issue?

**Comment by IanMiddlebrook** [comment]
Thanks Gary,  looks good to me.

Ian
