### ISSUE TITLE
Walks missing from Annual Summary Table

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#124]
Hi @Gary-van-Breda ,

A co-ordinator has noted a couple of 2019 walks missing from the Summary Table, although they appear in the Raw Data table.

The walks are samples 6879351 and 6879362, for Park Wood Chaffcombe, dated 13th and 20th September 2019.

The data were entered some time ago, but have been missed by the Summary Table builder.

I guess it's possible there are others walks in the same situation?

Many thanks,

Ian

**Comment by DavidRoy** [comment]
@IanMiddlebrook is this still an issue?

**Comment by IanMiddlebrook** [comment]
@DavidRoy  yes

**Comment by Gary-van-Breda** [comment]
These 2 walks have now been included in the Summary Table.
