### ISSUE TITLE
Upload historic UKBMS data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#125]
@Gary-van-Breda as discussed, here is the format of the data to upload.  Can you confirm the process
@johnvanbreda need your view on implications for warehouse given the size of this import.  5.2 million occurrences!
@kitenetter for information
@IanMiddlebrook - for information.  Having considered this and discussed with Gary and Marc, I think we should import the historic (i.e. records not input originally using the online system) raw occurrences rather than a summary dataset.

Process: Import to match survey_id = 64.  Locations already setup.  Import against 'ukbms' user = warehouse_id [10 195]

**Three stages (or two?)**
_Stage 1. Upload visit information with the following format:_
- Site [match location_id in warehouse]. Mandatory
- Date. Mandatory
- Recorder [match sample_attribute_id = 127]. Mandatory
- Start_time [287]. Mandatory
- End_time [288]. Non-mandatory
- Temp [289]. Mandatory
- %sun [286]. Non-mandatory
- Wind direction [291]. Non-mandatory
- Wind speed [290]. Non-mandatory
- Visit_reliability [new attribute required]

315491 visits to import (as of 17/1/2020)

_Stage 2.  Upload sub-samples with following format:_

- Sample_id - from stage 1 above
- Section - [match location_id in warehouse]
- %sun [286]

_Stage 3.  Upload occurrences_

- Sample_id - from stage 2 above
- taxon - [against UKBMS list = http://warehouse1.indicia.org.uk/index.php/taxon_list/edit/51]
- Abundance count [occurrence_id = 40]
- Record_status - set to verified

5212893 occurrences to import (as of 17/1/2020)

**Comment by Gary-van-Breda** [comment]
Can I assume there is no overlap? i.e. no occurrences in the upload already exist in the database?
  
Stage 1 should be done separately, stage 2 & 3 done together within the same file.  
  
Stage 1:  
Site should either be the name used in the Warehouse, or the site code.  
The temp, wind direction and Wind speed are all lookup lists, so the values in the old system will need to be mapped to the terms in the lookup lists before upload.  
This may also apply to the Visit reliability, depending on the details of the new attribute.  
In addition, it would help if there was a unique key we could use when referencing the walk in stage2/3: this would be loaded into the external_key field in the warehouse as part of the upload.  
This can be broken down into as many files as required: I don't what the current file upload and post size limits are on warehouse1.  

Stage 2/3:
This will need to be broken up. The only thing would be to try and keep the records for each sample together, and not split over multiple files.
The main sample (from stage 1) can either be referenced using the external key mentioned above, or a combination of location name and date - this would require these two columns to be present.  
The sub-sample data should be duplicated on each occurrence row on the sub-sample.  
The section should be represented as name of the section "{site name} - S{N}".  
The taxon names should match those held in the warehouse: does this require mapping?
We will need an extra column to hold a 'V' character in each row, in order to set the record status.

**Comment by IanMiddlebrook** [comment]
Overlap: Depends what data CEH are providing, but I'd be surprised if there was no overlap at all. I suspect some recorders have entered historic data of their own volition sothat they can make better use of the plots.

Stage 1: Sites must be identified by the Site Code (as there are several sites withe the same name, but Site Codes are unique.

**Comment by DavidRoy** [comment]
Overlap: we will exclude data already in Indicia.  There will need to be a separate reconciliation of records that have changed in the UKBMS Oracle database but not replicated in Indicia.

**Comment by DavidRoy** [comment]
@Gary-van-Breda 

Here is the first samples (visits) file I attempted to load on the dev warehouse (via import .csv on http://devwarehouse.indicia.org.uk/index.php/sample)
.
[Visits 1973.txt](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4275769/Visits.1973.txt)

Here is what I set on the first screen:
![screen import 1](https://user-images.githubusercontent.com/2699478/75683370-e37db800-5c8e-11ea-93e7-001fae62b812.png)

But on the second screen, match column names there are fields not appearing (e.g. Start Time, Wind Speed etc)
![screen import 2](https://user-images.githubusercontent.com/2699478/75683406-f7291e80-5c8e-11ea-9f94-e97a3de0d07d.png)

**Comment by DavidRoy** [comment]
@Gary-van-Breda 
Am getting further but still having issues. Now I can match all the attributes, after selecting Sample Method = Transect

For Lookup of existing records, I am selecting 'Location Record and Date'.

The import returns an error for each row of:
array_map(): Expected parameter 2 to be an array, object given

Any suggestions?!?

**Comment by Gary-van-Breda** [comment]
@DavidRoy At this point, if you are uploading new data, do not set the existing record lookup. You don't need it, it has a performance impact, and that's where the error is.

**Comment by DavidRoy** [comment]
@Gary-van-Breda but then a spatial reference or grid ref has to be supplied as part of the upload?  Or could I add a location ID to the upload file?

**Comment by Gary-van-Breda** [comment]
@DavidRoy 
No - that's for looking up existing sample records.   
You need to change the mapping for "Location name" to lookup the location record - I think it is "Location (from controlled termlist)"

**Comment by DavidRoy** [comment]
The options on the page for 'lookup of existing records' are:
![import options](https://user-images.githubusercontent.com/2699478/76201538-53d68d00-61eb-11ea-94b0-d18fcce0dfd9.png)

When selecting 'location record and date' the import still gives the error of 'array_map(): Expected parameter 2 to be an array, object given'

Here is the file i'm trying to import (saved as .csv version for uploading).
[Visits 1973.txt](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4305844/Visits.1973.txt)

@Gary-van-Breda please advise as it is becoming urgent to start the upload

**Comment by Gary-van-Breda** [comment]
In this field ("Lookup of existing records": "Sample records") choose "Do not look up existing Records".

**Comment by DavidRoy** [comment]
ok, am slowly making progress.  now am having problems with missing values for end_time, temperature, wind direction

Options are that these are set to non-mandatory fields or assign a missing value (e.g. -1 for temperature)

@Gary-van-Breda what's your advice on this.  The historic data has gaps

**Comment by Gary-van-Breda** [comment]
For the end time: probably best to set to non-mandatory on the warehouse - though the settings are cached, so may not be possible to use immediately after being changed. The default cache timeout is 30minutes, though I don't know if this has been changed for warehouse1.
Temperature and Wind Speed: set all the empty values in the file to "Not recorded/no data".  

For the Wind Direction, you need to apply this mapping:

blank => Not recorded/no data 
0 => 0. Smoke rises vertically
1 => 1. Slight smoke drift
2 => 2. Wind felt on face, leaves rustle
3 => 3. Leaves and twigs in slight motion
4 => 4. Dust raised and small branches move
5 => 5. Small trees in leaf begin to sway
6 => 6. Large branches move and trees sway

**Comment by DavidRoy** [comment]
@Gary-van-Breda 
The import is progressing.

Where is best location for checking the import via the annual-report report?
https://dev-butterfly-monitoring.pantheonsite.io/?

**Comment by DavidRoy** [comment]
@Gary-van-Breda when importing the occurrences for stage 2/3 I have adopted the location name for import.  Matching 'Location (from controlled list)'

But the import throws up this error for every occurrence:
Sname: Could not find "Monks Wood NNR - S2" in Location Name

I think this is because we don't have the section locations in the warehouse.  So maybe need a step to create these?

**Comment by IanMiddlebrook** [comment]
I think there are 2 different versions of Section locations in the system. Most site are like "Monks Wood NNR - S2", but some of the older/original transect are only identified by their Site Code.Section no - eg. 2173.5  ...

This seems to depend on the state of the GPS file when the routes were uploaded.

**Comment by DavidRoy** [comment]
You are right.  Monks wood sections are in as '4.1' etc.  

@IanMiddlebrook what is your preference for site/section naming as we should adopt a consistent approach.  now is the time to put some dedicated effort into this

I suggest:

Name:
Monks Wood NNR
Monks Wood NNR S1
Monks Wood NNR S2 etc

Code: 
4
4.1
4.2

**Comment by kitenetter** [comment]
We get regular complaints from verifiers on iRecord that the transect site names are inconsistent and that many of them just show the rather anonymous codes with no actual site name, so if there is anything that can be done to address this across the board for UKBMS that would go down very well.

**Comment by DavidRoy** [comment]
Yes, the location name is what is shown to iRecord so my suggestion would address this requirement.   The code is then an internal UKBMS system that is not widely shown/used

**Comment by IanMiddlebrook** [comment]
Yes, much prefer to see the name of the site identified alongside the section number, rather than a 
 site code.

**Comment by IanMiddlebrook** [comment]
Remembering only that some Site names are duplicated, whereas Site Codes are unique, so the code is still required to properly identify a unique section.

**Comment by DavidRoy** [comment]
To summarise, the imports worked ok.   Next steps:
1. Harmonise location names/codes.  I think we should aim to make the location names unique as well as the codes. @IanMiddlebrook - do you agree?
2. Match species names to those used in the UKBMS taxon list. We should probably also review this nomenclature given recent changes
3. import against location names and species names

**Comment by Gary-van-Breda** [comment]
Everything above matches  my understanding.
For testing: if it has gone into the devwarehouse for UKBMS, it should appear in https://dev-ukbms8.pantheonsite.io/annual-summary?locationID=1973&caching=false&year=1973&userID=all
, assuming all the job queue has cleared.

**Comment by Gary-van-Breda** [comment]
Sorry url above is wrongs:
https://dev-ukbms8.pantheonsite.io/annual-summary?locationID=all&caching=false&year=1973&userID=all

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy 
I agree it would be good to make location names unique, but htere may be practial difficulties with that to overcome. 
Firstly, for various reasons, I'm not sure that there is consistency with location names across all databases - ie. the names in Oracle may be slightly different to those in our Access database, and different again to those names on ukbms.org/mydata 
Secondly, when Users set up new transects they have a free field for location name and can quite easily replicate something already in the database.

**Comment by DavidRoy** [comment]
@Gary-van-Breda 
Presumably need to be logged in to access:
https://dev-ukbms8.pantheonsite.io/annual-summary?locationID=all&caching=false&year=1973&userID=all

**Comment by Gary-van-Breda** [comment]
Yes.  
However it looks like the section level samples haven't attached to the main samples. Can you post the file used for stage 2/3?

**Comment by DavidRoy** [comment]
[VisitCounts 1973.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4317978/VisitCounts.1973.zip)

**Comment by DavidRoy** [comment]
@IanMiddlebrook I think the steps are:
1. consolidate the ORACLE - Indicia site naming, removing any duplicates
2. then your internal Access database should match this location naming
3. for new sites each year, we'll need a process of review to ensure the names remain unique

Does that sound workable?

**Comment by Gary-van-Breda** [comment]
The visits file needs either the parent samples' Indicia ID or the parent samples' External Key (as loaded in the Visits file), in addition to what it has currently got.

**Comment by DavidRoy** [comment]
ok, will incorporate in next test

**Comment by Gary-van-Breda** [comment]
The Indicia location form is undergoing a review at the moment as part of the move to Drupal 8 - we could add a uniqueness check into it, to ensure only unique location names are chosen.

**Comment by IanMiddlebrook** [comment]
That sounds OK @DavidRoy, except that I presume Step 1 would involve 'renaming' duplicates rather than 'removing' them?
In recent years, a couple of co-ordinators have renamed sites online in order to clarify their location, so perhaps start by use the Indicia name as default where possible.

**Comment by Gary-van-Breda** [comment]
We also need a 4th Step: we need to update the Indicia section locations so their location names match the format "&lt;site name&gt; - &lt;section number&gt;"

**Comment by DavidRoy** [comment]
@IanMiddlebrook
"In recent years, a couple of co-ordinators have renamed sites online in order to clarify their location, so perhaps start by use the Indicia name as default where possible."

Yes, I am increasingly of the view that the Indicia dataset is the master copy

**Comment by DavidRoy** [comment]
@Gary-van-Breda 
"We also need a 4th Step: we need to update the Indicia section locations so their location names match the format "<site name> - <section number>""

Yes, I was including section names as part of the harmonisation.  Standardising to "&lt;site name&gt; - &lt;section number&gt;""

**Comment by DavidRoy** [comment]
@Gary-van-Breda have uploaded some test data, samples and occurrences for 1973.

Would like to test via:
https://dev-ukbms8.pantheonsite.io/annual-summary?locationID=all&caching=false&year=1973&userID=all

but get an error message:
The website encountered an unexpected error. Please try again later.

InvalidArgumentException: Field field_background_image is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of core/lib/Drupal/Core/Entity/ContentEntityBase.php).

**Comment by DavidRoy** [comment]
@Gary-van-Breda have also hit a problem with the occurrence import not recognising taxa_taxon_list_ids

Is this related to importer bug?
https://github.com/Indicia-Team/warehouse/issues/345

**Comment by johnvanbreda** [comment]
Indicia-Team/warehouse#345 is now fixed, but I'm not sure this is the same issue.

**Comment by DavidRoy** [comment]
@Gary-van-Breda is it possible to get the annual summary page working so I can confirm that uploads are working.
https://dev-ukbms8.pantheonsite.io/annual-summary?locationID=all&caching=false&year=1973&userID=all

error message:
_The website encountered an unexpected error. Please try again later.

InvalidArgumentException: Field field_background_image is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of core/lib/Drupal/Core/Entity/ContentEntityBase.php)._

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Annual summary now working on DEV.
It looks like there was an update for the theme from Julian(?) a couple of weeks back that assumes there is a background image field on each node. I have made this optional.

**Comment by Gary-van-Breda** [comment]
That said, there is nothing for 1973: I need to investigate

**Comment by DavidRoy** [comment]
Thanks.  The only data I have loaded is:

external key | taxa_taxon_list_id | sample_id | location | Date | Abundance Count | Record_status
-- | -- | -- | -- | -- | -- | --
2097005 | 283104 | 5679447 | 4.7 | 31/07/1973 | 1 | V
2097006 | 283134 | 5679447 | 4.7 | 31/07/1973 | 21 | V
2097007 | 283046 | 5679447 | 4.7 | 31/07/1973 | 1 | V

Which seems ok in the warehouse:
http://devwarehouse.indicia.org.uk/index.php/sample/edit/5679447

with three associated occurrences as expected.

**Comment by Gary-van-Breda** [comment]
@DavidRoy This has uploaded OK in of itself, but it has not linked to any supersample (walk level). Could you attach the 2 files uploaded?

**Comment by DavidRoy** [comment]
@Gary-van-Breda here are the files.

[UKBMS VisitCount Test Load 2020 04 17.txt](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4491545/UKBMS.VisitCount.Test.Load.2020.04.17.txt)

[UKBMS Visits Test Load 2020 04 17.txt](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4491546/UKBMS.Visits.Test.Load.2020.04.17.txt)

**Comment by DavidRoy** [comment]
Have just tried again, to confirm the import settings.  This document gives the options I used.
[UKBMS import documentation.docx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4491623/UKBMS.import.documentation.docx)

**Comment by Gary-van-Breda** [comment]
There are a couple of changes required to the data entered on the second pages of both the sample and occurrence uploads. I'll provide an updated version of the import document after the following change is made:  
A change is required to the warehouse: when the taxon taxa list id is provided, it is still expecting the Taxon or species name itself to be provided.

**Comment by DavidRoy** [comment]
Thanks. Is this quick to resolve?

**Comment by Gary-van-Breda** [comment]
I've done the change - I just need to test it.

**Comment by DavidRoy** [comment]
@Gary-van-Breda any progress on this?

**Comment by Gary-van-Breda** [comment]
Sent to @johnvanbreda to review / merge / deploy code: initial deployment should be to devwarehouse.

**Comment by DavidRoy** [comment]
@johnvanbreda can I bump this up as it's holding up the loading

**Comment by Gary-van-Breda** [comment]
@DavidRoy New version of document: note this requires the deployment of the code as at least one option is not available upto this point:
[UKBMS.import.documentation.asd.docx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4529487/UKBMS.import.documentation.asd.docx)

**Comment by johnvanbreda** [comment]
Ok - a possible typo spotted during review before merge @Gary-van-Breda.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : that has now been deployed onto the devwarehouse, if you'd like to test.

**Comment by DavidRoy** [comment]
Thanks. Will test tomorrow

**Comment by DavidRoy** [comment]
@Gary-van-Breda still having issues.  I followed your new instructions.  Samples loaded fine, but hit issues with occurrences.  **Please could you investigate as a priority as ideally this loading starts in the next week**

For occurrence import, I get the problem description message = sample_id: Could not find "5679859" in Sample Id

This results from your instructions to link 'Sample Id' (which is created from the samples import) to [Parent (from controlled termlist)] in the importer interface.

By mistake I initially imported occurrence against 'Sample Id' = Sample.id but I realise this is wrong as it links to the parent sample.

Here is the error file from the occurrence import.
[visitcounts 1975.zip.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4533466/visitcounts.1975.zip.zip)

**Comment by Gary-van-Breda** [comment]
I agree the samples loaded fine initially.  
When the occurrences were loaded in the first time, with the incorrect mapping, that "'Sample Id' = Sample.id" caused each section sample to be loaded over the top of the walk sample, corrupting it. As well as loading all the occurrences for a walk into the one sample, it converted that sample from a Transect method to a "Transect section" type, pointing to the last section location for which data existed.
When the second upload was attempted, it tried to find the parent sample (as a Transect method), but that no longer existed - it had been converted to a "Transect Section".
I believe the process and code are correct.

**Comment by DavidRoy** [comment]
Glad to know it was my incompetence.

I've loaded in all samples/visits from 1976
and associated occurrences for location_id = 1977, code = 4, Monks Wood NNR

The loading all went through ok.

@Gary-van-Breda does all look in order?

Should I expect the data to appear at:
https://dev-ukbms8.pantheonsite.io/annual-summary?taxon_list_id=false&caching=false&year=1976&locationID=all&userID=all

**Comment by DavidRoy** [comment]
Data now appearing on annual summary page as expected.  Will start the update on the live site with data from 1973 - 1975 as next test.  Thanks @Gary-van-Breda for resolving issues.  Will retain this issue but now assigned to me

**Comment by DavidRoy** [comment]
@Gary-van-Breda @johnvanbreda 
Does the importer on warehouse1 need to be brought in line with the one the development warehouse?

When trying to import UKBMS sample data on warehouse 1, there is not the option to link samples to [Location Indicia ID (from controlled termlist)] for example

**Comment by Gary-van-Breda** [comment]
Yes...  
@johnvanbreda : can we have the branch merged and deployed to warehouse1 (I assume as an official release), thanks.

**Comment by DavidRoy** [comment]
@johnvanbreda bumping this one so we can make progress with the data loading

**Comment by johnvanbreda** [comment]
Done.

**Comment by DavidRoy** [comment]
Thanks John!

@Gary-van-Breda. For info, I added a new sample attribute (reliable_visit) to warehouse1 to match the setup on devwarehouse.

Also set [end-time] as not required for the UKBMS transect survey
http://warehouse1.indicia.org.uk/index.php/attribute_by_survey/edit/844?type=sample

**Comment by Gary-van-Breda** [comment]
End time has been left optional in the warehouse on all 3 surveys, and set to mandatory on the forms.

**Comment by Gary-van-Breda** [comment]
@DavidRoy Has this issue been addressed?

**Comment by DavidRoy** [comment]
Yes, thanks.  I will raise new issues for follow-on requirements
