### ISSUE TITLE
Allocated WCBS Holiday squares

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#126]
When a holiday square is allocated can the colour of it change to indicate it is allocated? Examples include the following squares: NJ0934, NJ1740, NN0785 Thanks Zoe

**Comment by Gary-van-Breda** [comment]
@zrandle : Do you want the text in the table to also indicate that a site is assigned to someone else?

**Comment by zrandle** [comment]
Yes please that would be helpful. Thanks Z

**Comment by Gary-van-Breda** [comment]
@BirenRathod 

[ukbms_assign_transects.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4150600/ukbms_assign_transects.zip)

Can you unzip the attached file, and deploy the files as follows:

- the .php file should go into UKBMS iform client_helpers/prebuilt_forms directory, replacing the existing file
- the .js file should go into UKBMS iform client_helpers/prebuilt_forms/js directory, replacing the existing file

Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
These gone on to live now.

**Comment by Gary-van-Breda** [comment]
@BirenRathod Thanks
@zrandle : deployed and checked. The key has been updated: red are yours, green are other peoples, blue are unallocated, and the grid underneath now mirrors this.

**Comment by zrandle** [comment]
Great thanks :)
