### ISSUE TITLE
load in additional WCBS-BTO squares

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#128]
New BBS squares to be added to the system...
SP0114
SP1234
ST7699
SO9526
SO9319
SO9723
SO7523
SP1835
ST8493
SO6415
SP2629
SO7408
ST7292
SO7225
SO7118
SO8625
SO8925
SO5201
SP1912
SO9811

**Comment by Gary-van-Breda** [comment]
Done.
