### ISSUE TITLE
Upload 2016 data entered on old system  

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#13]
Hi Please can the 2016 data that was entered on the old system be uploaded and linked to the new online system as soon as possible?

**Comment by zrandle** [comment]
Hi is there any progress on this to report? NY0287 does not have any historical data associated with it.

Thanks

Zoe

**Comment by zrandle** [comment]
2015 and 2016 data for SU0096 not visible

**Comment by Gary-van-Breda** [comment]
I think all 2016 that I have from old system data now uploaded.
I don't have any 2015 or 2016 data for SU0096 (data [present for 2009-2014)
Similarly I don't have any 2016 data for NY0287 (data present for 2012-2015)

**Comment by zrandle** [comment]
Hi Gary

I don't understand why it is missing. I have attached the species data and the visit data in the spreadsheet.
 
[missing data.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1051945/missing.data.xlsx)

Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
OK, these weren't in my data dump (think that was dated june 2016 anyway)..
Is there any way I can get a full up-to date data dump from the old system, preferably in the previous visits and occurrences format? It may also be worth doing a final square check as well.
I'll then run the process through again - hopefully we can knock this and the other historic data issues on the head with one fell swoop.

**Comment by zrandle** [comment]
Yes, that was exactly what I was thinking. I'll sort it out and send you the data.

**Comment by zrandle** [comment]
@Gary-van-Breda Here are the data for the new data dump. 
[REFERENCE VISITS 2006-2016.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1139299/REFERENCE.VISITS.2006-2016.xlsx)
[REFERENCE RECORDS 2006-2016.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1139298/REFERENCE.RECORDS.2006-2016.xlsx)

Here is the squares list too - BC squares, non random and NT in one worksheet and BBS in the other worksheet.
[WCBS sqs for Gary 11_07_2017.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1139305/WCBS.sqs.for.Gary.11_07_2017.xlsx)
Thanks Zoe

**Comment by Gary-van-Breda** [comment]
Obviously there are various stages to this, so first **BC** squares:
The vast majority are OK.
The Northern Irish squares have all been renamed, so do not have "I" on the front of them
There are extra squares in the location list in the database: H2633 (IH2633) and H4092 (IH4092): I have left these in place at the moment: @zrandle do you want them deleted?
Only missing square is NY7907: I will add this.
Duplicates exist for squares TQ8664, TQ9432, TR1062, TR1337. I will remove the duplicates.

**Comment by Gary-van-Breda** [comment]
**BC** squares:
Duplicate squares removed (they had no samples stored against them).
@zrandle : the original NY7907 looks like it was renamed to NY7906. Do you want a new NY7907 to be created?

**Comment by zrandle** [comment]
@Gary-van-Breda yes please do create a new NY7907. 
H2633 (IH2633) and H4092 (IH4092) can be deleted as they are largely aquatic!
Thanks

**Comment by Gary-van-Breda** [comment]
BC squares now correct:
New NY7907 created.
H2633 (IH2633) and H4092 (IH4092) deleted.
I will do the same process for the BBS squares, then do the visits for both.

**Comment by Gary-van-Breda** [comment]
**BBS** squares:
Again, the vast majority are OK.
(In this case the Northern Irish squares have not been renamed, so have "I" on the front of them)
There are more extra squares in the location list in the database: HU3629, HU4537, HU5265, HU5339, IJ6455 (J6455), NG3917, NG4046, NJ9705, NK0022, NM3790, NN7058, NT1955, NT3265, NU0832, NY6263, NY9510, SJ3193, SJ3979, SJ6338, SK3009, SK6071, SK7885, SK9300, ST3667, ST4877, TM0001: @zrandle can you confirm that you want these deleted as well?
Five missing squares: NG7323, NJ3106, NJ4121, NZ0040, SK9973: I will them.
No Duplicate squares.

**Comment by zrandle** [comment]
I will check with Sarah Harris at BTO

**Comment by Gary-van-Breda** [comment]
@zrandle : have you had a chance to talk to Sarah Harris?

**Comment by zrandle** [comment]
I contacted her in early August and again last week! I'll pester her again.

**Comment by zrandle** [comment]
Here is info from Sarah 

SJ6338 is the only one not a BBS square - so should be removed. 

Remove these: 
SJ3193
IJ6455
SK3009
NY9510
NU0832
TM0001
NK0022
NT3265
SK7885
SK6071
SJ3979
SK9300
HU3629
HU4537
HU5265
HU5339
NG3917
NN7058
ST3667
ST4877
NJ9705
NM3790
NG4046
NT1955

The list below, are normal BBS squares and should be kept: 

SK9973
NJ3106
NJ4121
NZ0040
NY6263
NG7323

Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
All the squares are now sorted.
 
[Stage 2 reporting.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1275503/Stage.2.reporting.xlsx)

Total Number of visits in provided data: 14131
There are 11726 visits in the data which are already in the database (tagged as “Valid Existing Visit/Sample”).
There are 1901 visits against squares that have not already been loaded (tagged as “No matching Indicia Sample found”). I will load these.
**Error Statuses:**
There  were 381 visits for which the GRID_REF provided did not match one of the squares provided (tagged as “No Location Found For Sample”). I will not load in this data. CAN YOU LET ME KNOW WHAT SQUARES THESE ARE?

There are 53 visits where there is a date mismatch between the data provided above and the previously supplied data (tagged as “Date Mismatch”). Looking at the data, my suspicion is that the original data was wrong – some of these are for the same square on the same date. I will flag these as deleted and reload the visits using the new data. OK

There are also 53 visits where it is not possible to distinguish between which square to load the data into (tagged as “Multiple Possible Locations For This Sample”): this is because there are two squares with the same grid reference: a BBS square and a BC square. I will not load in this data, unless you can tell which they should be attached to. CAN YOU LET ME KNOW WHAT SQUARES THESE ARE AND I WILL LET YOU KNOW WHAT ORGANISATION TO ASSIGN THEM TO.

There are 5 visits that are flagged as being for NY9707 that were previously loaded in: this square was moved to NY9706 and took these with them, and a new NY9707 created (Tagged as “Indicia Location ID mismatch”). The samples have kept the NY7907 Grid Ref, even though they are attached to NY7906. I will leave these alone. GREAT

There are 12 visits whose Grid Ref has changed (tagged as “Sref Mismatch”). I will assume that the new data is correct, so I will flag these as deleted and reload the visits using the new data. CAN YOU LET ME KNOW WHAT SQUARES THESE ARE?

@zrandle : are you ok with this plan?

**Comment by Gary-van-Breda** [comment]
@zrandle 
Picking up from #43, there are many visits which do not have an average sun value. It is my intention to use the mean of the relevant sector sunshine values, if it is not provided.
What is the difference between the start/end time 10 & 20 values, and which one should I use? Currently only 1 time period is stored in the Indicia system.

Yes use the mean of the relevant sector sunshine values.

I'm not sure what 10 & 20 values you are referring to... Could it be the older visits when people used to do 20 sections of 100m as opposed to 10 sections of 200m? 

Use the earliest start time and the latest finish time.

**Comment by Gary-van-Breda** [comment]
Does the visits data given above include the visits in #31 ?

Yes it does

**Comment by Gary-van-Breda** [comment]
Srefs which have visits in the visits data, but do not have squares (First Error Status case above):
IH5351, NG4426, NH3934, NH5411, NH5828, NH6916, NH9545, NN6998, NN9355, NO2306, NR6346, NR7232, NS9877, NT2607, NT9222, NX5372, NY5506, NY7968, NZ1212, SD4050, SD4577, SD5582, SD6027, SD9767, SE1867, SE2611, SE2906, SE6218, SE6418, SE8481, SE8786, SH8104, SH9123, SH9223, SH9323, SH9824, SH9918, SH9919, SJ0120, SJ0121, SJ0217, SJ0218, SJ0317, SJ0318, SJ1381, SJ2938, SJ2946, SJ3326, SJ6869, SK2313, SK6330, SK7099, SK8487, SK9520, SN0007, SN2542, SN6456, SN8026, SN9711, SO4786, SO7651, SO7907, SO9173, SO9327, SP0848, SP1807, SP4656, SP5310, SP5633, SP6527, SP7921, SP9512, SS4430, SS8342, SS8343, SS8444, SS8545, SS8932, SS8933, SS8941, SS8942, SS9041, SS9042, ST2183, ST5537, ST6260, ST7043, ST7258, ST8027, ST8677, SU2932, SU3823, SU3834, SU4859, SU4929, SU5828, SU5910, SU6473, SU7765, SU8890, SU9155, SX1091, SX6768, SX6779, SX6781, SX6879, SX6880, SX8767, SY6768, SY6769, SY6868, SY7782, SY7784, SY7881, SY8081, SY8181, SY8184, SY8283, SY8284, SY8482, SY8483, SY9582, SZ1691, TA0135, TF6106, TF6803, TF7228, TF7234, TF7644, TF9808, TF9811, TF9913, TG0307, TG1008, TG2410, TL0025, TL0591, TL1030, TL1112, TL1309, TL3850, TL4764, TL5070, TL6096, TL6255, TL6698, TL6807, TM1683, TM4293, TQ1085, TQ1208, TQ2611, TQ2752, TQ3833, TQ4256, TQ4257, TQ5906, TQ6048, TQ6212, TQ6487, TQ7057, TQ8559, TQ9741, TR0138


Please add these squares to the BC list - some are pilot squares from the early years.

**Comment by Gary-van-Breda** [comment]
Srefs which have both BBS and BC squares, so can't distinguish (third Error Status case above) - generally they have multiple visits each.
IJ2191, NO2602, NX4438, SD6168, SK1787, ST3547, SU0805, SU5554, SY4392, TL3207

Here are the squares with their organisation:


IJ2191 | BBS-- | --
NO2602 | BBS
NX4438 | BBS
SD6168 | BC
SK1787 | BBS
ST3547 | BC
SU0805 | BBS
SU5554 | BBS
SY4392 | BBS
TL3207 | BBS

**Comment by Gary-van-Breda** [comment]
Visits with changes Grid references relative to previous data (fifth Error Status case above)
Provided   Key | Grid Ref | Date | Status | Indicia Sample ID | Survey
-- | -- | -- | -- | -- | --
10270 | NS9972 | 14/07/2011 | Sref Mismatch : Visit Grid Ref NS9972 : Grid Ref in existing sample   NS9872 | 1504635 | BC
15309 | NY7482 | 23/07/2012 | Sref Mismatch : Visit Grid Ref NY7482 : Grid Ref in existing sample   NY7189 | 1504951 | BC
6949 | SD7716 | 01/09/2010 | Sref Mismatch : Visit Grid Ref SD7716 : Grid Ref in existing sample   SD7715 | 1491568 | BBS
2426 | SO2712 | 25/07/2009 | Sref Mismatch : Visit Grid Ref SO2712 : Grid Ref in existing sample   SO4304 | 1492805 | BBS
10122 | SO8933 | 31/07/2011 | Sref Mismatch : Visit Grid Ref SO8933 : Grid Ref in existing sample   SO9224 | 1506219 | BC
14375 | SO9849 | 08/07/2012 | Sref Mismatch : Visit Grid Ref SO9849 : Grid Ref in existing sample   SO9848 | 1493008 | BBS
25473 | ST9911 | 23/08/2014 | Sref Mismatch : Visit Grid Ref ST9911 : Grid Ref in existing sample   ST9910 | 1507504 | BC
13219 | TL0787 | 08/08/2012 | Sref Mismatch : Visit Grid Ref TL0787 : Grid Ref in existing sample   TL0687 | 2377246 | BC
13782 | TL0787 | 31/08/2012 | Sref Mismatch : Visit Grid Ref TL0787 : Grid Ref in existing sample   TL0687 | 2377247 | BC
14637 | TL8536 | 07/09/2012 | Sref Mismatch : Visit Grid Ref TL8536 : Grid Ref in existing sample   TL7320 | 1509721 | BC
2485 | TM0582 | 25/07/2009 | Sref Mismatch : Visit Grid Ref TM0582 : Grid Ref in existing sample   TM0587 | 1495333 | BBS
9539 | TQ9159 | 10/08/2011 | Sref Mismatch : Visit Grid Ref TQ9159 : Grid Ref in existing sample   TQ9747 | 1496133 | BBS

Something fishy has happened here! I've cross referenced the Provided Key with the original database and in all cases the Visit Grid Refs are correct and the Grid Ref in existing sample is incorrect.

**Comment by zrandle** [comment]
what is next then?

**Comment by Gary-van-Breda** [comment]
Squares detailed in the first post from 13th Sept now added.

@BirenRathod or @JimBacon 
Can you run the following SQL statements against warehouse1 ? Thanks

They remove the samples with second and fifth error cases above: they will be reloaded. It also removes the 2007 and prior data, as these will be reloaded with extra processing to deal with the fact that data up to that point had 20 sections, not 10.

```
UPDATE samples 
SET deleted = 't', updated_on = now(), updated_by_id = 1
WHERE parent_id IN (
2377064,2377205,1504549,1504635,1504799,1504951,1491494,1491568,1491620,1492108,
1505427,1505436,1492174,1492259,1492291,1492416,1505956,1492805,1492921,1506219,
1492949,1493008,1506609,1493230,1506920,1506921,1506923,1506924,1506925,1506926,
1507181,1507466,1507504,1493847,1507615,1507624,1507670,1507693,1507709,1493867,
1507875,1507896,1508060,1494829,1509003,1509181,1509224,1509308,1509309,2377246,
2377247,1494978,1509721,1495333,1495338,1495342,1510013,1510057,1495555,1495557,
1510344,1510568,1496010,1496133,1496176)
AND survey_id IN (305, 306);

UPDATE samples 
SET deleted = 't', updated_on = now(), updated_by_id = 1
WHERE date_start < '2008-01-01'
AND deleted = 'f'
AND parent_id IS NOT NULL
AND survey_id IN (305, 306);

UPDATE samples 
SET deleted = 't', updated_on = now(), updated_by_id = 1
WHERE id IN (
2377064,2377205,1504549,1504635,1504799,1504951,1491494,1491568,1491620,1492108,
1505427,1505436,1492174,1492259,1492291,1492416,1505956,1492805,1492921,1506219,
1492949,1493008,1506609,1493230,1506920,1506921,1506923,1506924,1506925,1506926,
1507181,1507466,1507504,1493847,1507615,1507624,1507670,1507693,1507709,1493867,
1507875,1507896,1508060,1494829,1509003,1509181,1509224,1509308,1509309,2377246,
2377247,1494978,1509721,1495333,1495338,1495342,1510013,1510057,1495555,1495557,
1510344,1510568,1496010,1496133,1496176)
AND survey_id IN (305, 306);

UPDATE samples 
SET deleted = 't', updated_on = now(), updated_by_id = 1
WHERE date_start < '2008-01-01'
AND deleted = 'f'
AND parent_id IS NULL
AND survey_id IN (305, 306);

DELETE FROM summary_occurrences
WHERE date_start < '2008-01-01'
AND survey_id IN (305, 306);
```

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @JimBacon 
Can you also run the following: this corrects an issue with the warehouse location upload where it attaches the location_type_id to the sample_method_id termlist value for "Transect Section" by mistake.
```
UPDATE locations
SET location_type_id = 778, updated_on = now(), updated_by_id = 1
WHERE location_type_id = 776 AND deleted = false
AND id in (select location_id from locations_websites WHERE website_id = 27 and deleted = false);
```

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda 
All queries ran successfully. 
Also, deleted 24276 and updated 7919.

**Comment by Gary-van-Breda** [comment]
Thanks.
Samples now all uploaded. Occurrences and their counts now to do.

@zrandle : can you have a look at the file you supplied above (REFERENCE RECORDS 2006-2016.xlsx) - this has columns :
VISIT_ID | SECTION_LENGTH(M) | SECTION | COUNT | BMSCODE

I was expecting something like
RECORDKEY | SAMPLEKEY | SECTION | COMMON_NAME | COUNT

I assume that the VISIT_KEY = SAMPLEKEY, COUNT is obvious, as is SECTION, but how do I determine the species?

**Comment by zrandle** [comment]
Species is determined by BMS code. Do you want me to add the common name to the file I sent you?

**Comment by Gary-van-Breda** [comment]
Yes please, and also the old system record key: I use this to check if the record is already loaded. Don't worry if the recordkey is not possible.

**Comment by Gary-van-Breda** [comment]
Would be even better if it was the latin name, as there are some species which share common names.

**Comment by zrandle** [comment]
ok will do.  Can I also give you an additional 12 visits for 2017 and their associated records that were entered via the old system? Thanks

**Comment by Gary-van-Breda** [comment]
Yes, thats fine, add the 2017 data.

**Comment by zrandle** [comment]
Hi Gary Here are the records files for the 2006-2016 data. You may want to remove the unidentified hawker, unidentified chasers etc. 
[REFERENCE.RECORDS.2006-2016 GVB.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1582621/REFERENCE.RECORDS.2006-2016.GVB.xlsx)
The 12 visits and associated records entered via the old system for upload are here: 
[REFERENCE VISITS 2017 GVB.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1582623/REFERENCE.VISITS.2017.GVB.xlsx)
[REFERENCE RECORDS 2017 GVB.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1582627/REFERENCE.RECORDS.2017.GVB.xlsx)

Cheers

Zoe

**Comment by Gary-van-Breda** [comment]
Sorry to be a pain again, but our first files to be loaded had a "RECORDKEY" entry: I use this to identify if we have loaded this record before. Is it possible to have this included as well?

**Comment by zrandle** [comment]
I do not have this information. This maybe something that CEH add. @DavidRoy  can advise.

**Comment by DavidRoy** [comment]
Sorry for the delay with this one.  It's not straightforward to provide the RECORDKEY.  Can you check that there is no existing data for these site/year combinations?

**Comment by Gary-van-Breda** [comment]
That's OK, I'm working on a workaround.

**Comment by zrandle** [comment]
Hi any progress on this? Thanks Zoe

**Comment by Gary-van-Breda** [comment]
All data uploaded (2017 included, 292527 counts in total)
The following is a summary of rows that have not been loaded:

- 1018 had blank section numbers
- 1054 had invalid section numbers (outside the range 1-10 post 2007, 1-20 2007 and before)
- 980 had invlaid taxa (e.g. the "unidentified" records)

The BBS annual summary summariser is running in catch up mode at the moment: I'll leave it running like that over night, then switch over to running the BC in catch up mode. There is a significant performance hit running in catch up mode, and I don't want both doing so at the same time.

Can someone check that they are happy with this - and maybe at long last we can finish this ;-)

**Comment by zrandle** [comment]
I'll check it when I get an opportunity to do so. Thanks Zoe

**Comment by zrandle** [comment]
I have not had the time to check it yet...

**Comment by zrandle** [comment]
Hi, I've checked this. There is a mismatch between the number of records for 2006 in my access database and the online system.  4,885 butterfly records in access v 1,393 in the online system.  Could this be due to the missing sections or is it something else? Thanks Z

**Comment by zrandle** [comment]
Just realised I still need to check the 2017 data...will do this now :)

**Comment by zrandle** [comment]
2017 checked and all OK. 

Only 2006 with a problem.

**Comment by DavidRoy** [comment]
@Gary-van-Breda this seems close to finishing.  Is this back with you to sort out 2006 data issues?

**Comment by Gary-van-Breda** [comment]
I have gone though the entire process again, and made sure the late data from #31 is included.
@zrandle : yes the shorfall in the number of records is a combination of blank section numbers, section numbers outside the range (above 20 for year 2006), the use of taxa like "unidentified darter", and the merging of sections so that 20 sections go into 10 (ie 1&2 merged into 1, 3&4 into 2, 5&6 into 3 etc)
