### ISSUE TITLE
Drupal 8 site: composer issue.

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/UKBMS-online#130]
When I do a "composer update" after cloning the ukbms d8 site from pantheon (twice in order to get to a stable state), it deletes / upgrades a whole set of packages. This implies that the code tree is not in step with the composer files.  
Whilst this is not really an issue, there are 6 Drupal modules which are removed which are enabled on the DEV or TEST sites: this is not good.

Item | Used in DEV | Used in TEST
-- | -- | --
drupal/admin_toolbar | Y | Y
drupal/mailchimp | Y | N
drupal/responsivewrappers | Y | Y
drupal/search_api_pantheon | Y | Y
drupal/shs | Y | Y
drupal/token_filter | Y | Y

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Please do not run composer update for Drupal's contrib modules. They should delete as they get modules update from BRC upstream which is a master repository for all Drupal 8 base BRC sites on Pantheon. if you need a update, please let me know. If you update on ukbms site level, it will create massive discrepancy. It took me three weeks to resolve that.
