### ISSUE TITLE
Hide 'reliability' field on Drupal8 input-data form

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#131]
https://test-ukbms8.pantheonsite.io/input-data

Field for ‘reliability’ to be hidden on form as only for admin use
![reli](https://user-images.githubusercontent.com/2699478/81557769-6eacb580-9384-11ea-9a37-25e8ffbe1b6e.png)

**Comment by Gary-van-Breda** [comment]
How is this field going to be used?

**Comment by DavidRoy** [comment]
As a flag for admin to use when transect walks don't meet the criteria - e.g. when the weather criteria were not met.

Can the flag be hidden from general users but available to those with admin access?

**Comment by DavidRoy** [comment]
@Gary-van-Breda can the reliability field be hidden on the current live site:
https://www.ukbms.org/mydata/input-data

Ideally as soon as possible now the scheme has started up again and we don't want to confuse recorders

**Comment by Gary-van-Breda** [comment]
I've left the attribute attached to the survey, but made it so that it is restricted to the "Unknown" sample method: this has removed it from the data entry page.  
This attribute was present only on the Transect survey, not either of the WCBS ones.

**Comment by DavidRoy** [comment]
Thanks.  Will this affect the data import for survey = 'UKBMS Transect' where this attribute is needed?

**Comment by DavidRoy** [comment]
I linked the attribute back to the 'Transect' survey to enable imports.  Will revert when done.

**Comment by Gary-van-Breda** [comment]
Done on Drupal 8 version of the form. Deployed to Test. Permission set so that normal recorders can see it, but branch managers and admin users etc can.
I was having some problems with the performance of the page, so a couple of updated reports have been deployed. 
Also have tweaked the CSS so that the checkbox is not overlayed on the label.

**Comment by DavidRoy** [comment]
thanks

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy @Gary-van-Breda 

If this 'reliable visit' box is going to remain on the live site for the time being (for transect data entry), could it at least have a note for recorders to ignore it?

I'm getting a few queries about this field now that we're back in action.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@BirenRathod Can we have the following file unzipped and deployed into the iform/client_helpers/prebuilt_forms directory on the Live Drupal7 UKBMS site?

[ukbms_sectioned_transects_input_sample.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4666642/ukbms_sectioned_transects_input_sample.zip)

Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
It has gone one live.

**Comment by Gary-van-Breda** [comment]
Live UKBMS configured to hide the reliability attribute for all but people with "region coordinator" permission

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda ,
As far as I can see, the 'reliable visit' box is only seen by 'Admin' users on the live site (which is ideal).
On the Drupal 8 version it can be seen by Admin and Branch Co-ordinators. Branch Co-ordinators don't need to see this box.

BW, Ian

**Comment by Gary-van-Breda** [comment]
Now switched to Admin only on D8 version

**Comment by IanMiddlebrook** [comment]
Thanks
