### ISSUE TITLE
Improve page layout on input-data form as part of Drupal 8 migration

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#132]
Currently there is a lot of blank space, e.g. short fields spanning the page width.  Could a page be formatted to include most/all the information on the screen without needing scrolling?

**Comment by Gary-van-Breda** [comment]
Deployed to Test.
It is responsive. For full size screens the transect and date share a line, and each attribute takes a third of the width. As the screen shrinks, the attributes then take half the width, before on small screens each takes up the full width.
As the Notes are a text box, I've left that as full width.

**Comment by DavidRoy** [comment]
Works well, thanks

**Comment by DavidRoy** [comment]
Suggested change to make page more logical.
Two column layout with:
Site name | Date
Start time | End time
% sun | temperature
Wind speed | wind direction
Reliability [only shown for admin)
Notes

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Where do you want the Recorder name?

**Comment by DavidRoy** [comment]
Sorry, my mistake:
Transect name
Recorder name | Date
Start time | End time
% sun | temperature
Wind speed | wind direction
Reliability [only shown for admin)
Notes

**Comment by Gary-van-Breda** [comment]
Done: code changes deployed to Test, and config done.

**Comment by DavidRoy** [comment]
Thanks
