### ISSUE TITLE
Site Details page on Drupal 8 - is 'Country' needed as a drop-down option?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#133]
The spatial information is best coming from the site location information?

Suggest this field is removed from the form.

@IanMiddlebrook - do you agree?

https://test-ukbms8.pantheonsite.io/site-details

**Comment by IanMiddlebrook** [comment]
Country or County?

I only see a County field. I find this useful when a recorder has set up a new site, so that I can quickly see which co-ordinators need to be linked up.

**Comment by DavidRoy** [comment]
Sorry, I meant County.  If you find it useful we'll keep it in.

**Comment by IanMiddlebrook** [comment]
If it could be generated automatically from the central grid ref, that would be just as good (more reliable). 
But that might be unnecessary levels of sophistication when the recorder can just select it.

**Comment by Gary-van-Breda** [comment]
The County field is a termlist, and is not connected to any location records. It has no concept of the geography associated with the county, so would require quite a bit of work in order to auto fill-in.

**Comment by DavidRoy** [comment]
Thanks for confirming.  We therefore leave 'as is'
