### ISSUE TITLE
Site Details page, formatting bug for 'Confidential' field Drupal8 version

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#134]
https://test-ukbms8.pantheonsite.io/site-details

Formatting bug
![pic2](https://user-images.githubusercontent.com/2699478/81580436-5a2ce500-93a5-11ea-89af-7459658cdf5f.png)

**Comment by Gary-van-Breda** [comment]
Fixed and deployed to Test

**Comment by DavidRoy** [comment]
Thanks
