### ISSUE TITLE
Site Details page additional notes, Drupal 8 version

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#135]
https://test-ukbms8.pantheonsite.io/site-details

When creating a new site.

The [Site Code:] field is greyed out.  An explanation note is needed to explain that this code will be assigned automatically

The [Overall length(m)] field is greyed out.  An explanation note is needed to explain that the length will be calculated once the transect route is entered.

**Comment by Gary-van-Breda** [comment]
Fixed and deployed to Test.

**Comment by DavidRoy** [comment]
Closing, thanks
