### ISSUE TITLE
Broken link on Drupal8 site assignment page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#137]
https://test-ukbms8.pantheonsite.io/node/282

2.	download link takes back to home page, e.g.
https://test-ukbms8.pantheonsite.io/iform/ajax/ebms_transects_allocation/downloadSiteAllocations/282?location_type_ids=777&attribute_id=58&region_location_type_id=1103

**Comment by Gary-van-Breda** [comment]
Fixed and deployed to Test.
Form bootstrapped. Bug fixed in filtering of site drop down linked to branch.

**Comment by DavidRoy** [comment]
Thanks
