### ISSUE TITLE
Warning note in input-data page on Drupal 8 version

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#138]
https://test-ukbms8.pantheonsite.io/input-data?sample_id=5624248

After entering first page information, then selecting 'Next' the following page has warning messages:
![pic4](https://user-images.githubusercontent.com/2699478/81582234-b264e680-93a7-11ea-80d5-711057d593d5.png)

**Comment by Gary-van-Breda** [comment]
Fixed, on Test.

**Comment by DavidRoy** [comment]
Thanks
