### ISSUE TITLE
Drupal8 Input data form.  Species list search box too small

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#139]
https://test-ukbms8.pantheonsite.io/input-data?sample_id=5624248

On species entry grid page, species search box too small
![pic5](https://user-images.githubusercontent.com/2699478/81582444-fb1c9f80-93a7-11ea-9ec3-a5e561af4c15.png)

**Comment by Gary-van-Breda** [comment]
Fixed, on Test.

**Comment by DavidRoy** [comment]
Thanks
