### ISSUE TITLE
SW6616 and SW7220

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#14]
Hi 

Please can the historical data for these squares be uploaded to the system?

Thanks
Zoe

**Comment by Gary-van-Breda** [comment]
@zrandle Can you confirm the names of these squares? Are they the WCBS-BC squares called "non random SW6616" and "non random SW7220"?

**Comment by zrandle** [comment]
Yes that's right.

**Comment by Gary-van-Breda** [comment]
Data now uploaded into system.
Slight oddity - although I have visit data for 2013, 14 and 15,  I do not have occurrence data for these squares for 2015 - only 2013 and 2014.
@zrandle : is this correct?

**Comment by DavidRoy** [comment]
@zrandle please review and if ok, please close this issue

**Comment by zrandle** [comment]
There are occurrence data for 2015 for both squares. It is in this file
[SW6616 and SW7220 2015.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/928541/SW6616.and.SW7220.2015.xlsx)

**Comment by Gary-van-Breda** [comment]
These 2015 occurrences have now been uploaded.
@zrandle : is this OK now?

**Comment by zrandle** [comment]
These data are not visible from the annual summary page http://www.ukbms.org/mydata/annual-summary?locationID=167146&caching=false&userID=542&locationType=5196&year=2015 

In addition to this there should be 6 visits to SW6616 in 2015 but none show in the my walks calendar when masquerading as John Foster the same is true for SW7220.

**Comment by DavidRoy** [comment]
The data will not appear against John Foster's 'my walks' because you did not specify who these data belonged to.  You need to select 'All recorders' in the drop-down list to see the data.  

@Gary-van-Breda the data for the 7th June visit are wrong as the counts are all set to 1 when they were not in the original data.  I haven't done an exhaustive check though

![image](https://cloud.githubusercontent.com/assets/2699478/25482355/505ad69e-2b49-11e7-8926-f94ee3dab049.png)

**Comment by Gary-van-Breda** [comment]
The wcbs_occurrences file I received on 1st June last year has all occurrences for SAMPLEKEY=31198 with a count of 1: it matches the data uploaded.

**Comment by DavidRoy** [comment]
But didn't match the subsequent spreadsheet sent by @zrandle - see above.  I suggest that @zrandle advises why they are different

**Comment by zrandle** [comment]
I've checked and 31195 (7/06/2015) has counts of 1 for all species recorded.

**Comment by DavidRoy** [comment]
why is the attached spreadsheet within this github issue thread difference?  Am I missing something?
https://github.com/BiologicalRecordsCentre/UKBMS-online/files/928541/SW6616.and.SW7220.2015.xlsx

**Comment by zrandle** [comment]
are you looking at the final column which is for section? third column is count

**Comment by DavidRoy** [comment]
oops, yes. I'll get my coat

**Comment by DavidRoy** [comment]
@zrandle please close this issue if this is complete, or advise on required action
