### ISSUE TITLE
Drupal8 site Annual summary page - Site Type option box too small

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#140]
https://test-ukbms8.pantheonsite.io/annual-summary

![pic6](https://user-images.githubusercontent.com/2699478/81936695-8be2bd80-95ea-11ea-9ae5-3272608cbd95.png)

**Comment by Gary-van-Breda** [comment]
Done, deployed to UKBMS8 test.
I've also made the look and feel of the whole filter bar consistent, and tidied up the Year control.

**Comment by DavidRoy** [comment]
Thanks
