### ISSUE TITLE
Zero abundance records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/UKBMS-online#141]
We have had a few enquiries from verifiers on iRecord about the 'strikethrough' records that appear on their verification pages, e.g.:

![image](https://user-images.githubusercontent.com/16039111/81953655-db7fb400-95ff-11ea-94de-8137b555814b.png)

The strikethrough indicates that the record has an abundance of zero, i.e. it is a record of absence rather than of presence. Verifiers usually have to mark these records as "not accepted - unable to verify", because it is not clear how one can verify an absence. This is not really a good use of verifiers' time.

Do transect recorders expect to be able to record zero counts, and is this data useful to anyone? If not, can we set the transect data entry to disallow such data, or alternatively should we find a way of excluding zero counts from the verifiers' view on iRecord?

**Comment by DavidRoy** [comment]
The ukbms should not generate zero counts.  I'll investigate these IDs.  It is possible a zero is created if a count is initially entered and then deleted/set to zero

**Comment by DavidRoy** [comment]
@Gary-van-Breda do you know why the UKBMS input form should create a record with the [zero abundance] set to true
![pic7](https://user-images.githubusercontent.com/2699478/81955052-880e6580-9601-11ea-8d44-02890f139f54.png)

**Comment by Gary-van-Breda** [comment]
There were some changes done way back in 2013 (2013-08-09): these clarified the processing of zero abundance records for UKBMS:

- If an occurrence field is blank, no occurrence is recorded.
- If an occurrence field is zero "0", a zero abundance record is created.

It has been like this ever since.
Do you wish me to alter this so that zeroes are treated like blanks?

**Comment by DavidRoy** [comment]
yes please.  Zeros should be treated like blanks

**Comment by Gary-van-Breda** [comment]
Can this wait until the Drupal 8, or do you want this in Drupal 7?

**Comment by DavidRoy** [comment]
Drupal 8 is fine.  We will also need to remove existing zero-abundance records from the UKBMS in the database

**Comment by Gary-van-Breda** [comment]
I've done a tweak to a couple of the reports to address a performance issue with this form. @birenrathod or @johnvanbreda : can I have the master branch of the brc_reports deployed onto warehouse1? Thanks (two new reports which will replace ones on the main warehouse reports module)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I pulled your reports now.

**Comment by Gary-van-Breda** [comment]
Code now fixed, on Test. New form configuration flag set to not allow zero abundance records.
The data fix will have to wait until after D8 goes live.

**Comment by kitenetter** [comment]
Do we yet have an estimate of when the D8 change will happen, and thus when the zero abundance records will stop? Have been asked about it again today.

**Comment by DavidRoy** [comment]
We won't switch over till November to minimise disruption mid-season

**Comment by Gary-van-Breda** [comment]
It looks like the last zero_abundance record was created just before the D8 release (Transect and WCBS surveys). There are approximately 26k zero abundance records from before this point.
@DavidRoy : Do you want these deleted, or just left now?

**Comment by DavidRoy** [comment]
@Gary-van-Breda yes, please delete the zero records for the UKBMS Transects survey

**Comment by Gary-van-Breda** [comment]
@DavidRoy @MeganLowe : do I delete the zero_abundance records in the two WCBS surveys as well? (There are 694 on BBS and 999 on BC)

**Comment by Gary-van-Breda** [comment]
All the Zero abundance records have been set to deleted for the UKBMS Transects survey.

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda, yes please to the WCBS surveys too.

**Comment by Gary-van-Breda** [comment]
All the Zero abundance records have been set to deleted for the WCBS-BBS and WCBS-BC surveys. All cache_occurrence* entries removed for these (and zero abundance Transect occurrence records). Zero abundance records are excluded from the Annual Summary calculations, so no need to re-run any of them.
Closing.
