### ISSUE TITLE
D8 migration: Users

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/UKBMS-online#142]
Currently the users are allowed to self register for UKBMS. When we come to switch on the D8 version, we must make sure that all newly registered users are migrated over.

see https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/51#issuecomment-632130897

**Comment by DavidRoy** [comment]
@Gary-van-Breda we can start the migration, including turning off the new user registration
Please confirm the timeframe...

@IanMiddlebrook for info...

**Comment by Gary-van-Breda** [comment]
@DavidRoy @IanMiddlebrook @MeganLowe : can you confirm there are no open D8 issues that must be addressed before we go Live?

**Comment by DavidRoy** [comment]
Good to go from my perspective.
@IanMiddlebrook @MeganLowe have looked more closely at the recording/site forms.  Can you confirm that issues have been addressed for you?

**Comment by IanMiddlebrook** [comment]
@MeganLowe  do you think issue #176 needs to be sorted before we go live? 
https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/176

**Comment by MeganLowe** [comment]
@IanMiddlebrook @Gary-van-Breda @DavidRoy ideally #176 needs looking at before going live, or at least before any new users register as I'm concerned there's no user agreement etc on this page currently (do we need this for GDPR etc?), plus I'm not sure whether there's an automatic email attached to this registration process or what that may currently say?
