### ISSUE TITLE
D8 Holiday squares page errors

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#143]
https://test-ukbms8.pantheonsite.io/holiday-squares

The page gives the error message:
×Error message
Notice: Array to string conversion in lang::applyArgs() (line 108 of modules/custom/iform/client_helpers/lang.php).

There is no 'Find place' control above the map.  Instead there is text:
The georeference lookup control requires an API key configured for the place search API in use.

**Comment by Gary-van-Breda** [comment]
Code Fixed and deployed to Test.

**Comment by DavidRoy** [comment]
Thanks
