### ISSUE TITLE
D8 Site details page - zoom out to extent of transect route

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#144]
https://test-ukbms8.pantheonsite.io/site-details-map?location_id=1977

Currently the map zooms to the transect centroid.
![pic10](https://user-images.githubusercontent.com/2699478/82641856-ed1b1a00-9c04-11ea-83de-cb3b54fa2fdf.png)

It should zoom to the extend of all the spatial information, e.g. when the section routes are available
![pic11](https://user-images.githubusercontent.com/2699478/82641907-fc01cc80-9c04-11ea-9645-01f86510f805.png)

**Comment by Gary-van-Breda** [comment]
@DavidRoy Can I confirm we are talking about
https://test-ukbms8.pantheonsite.io/site-details?id=1977, not
https://test-ukbms8.pantheonsite.io/site-details-map?location_id=1977

**Comment by DavidRoy** [comment]
Yes, mystake.  sorry for the confusion
https://test-ukbms8.pantheonsite.io/site-details?id=1977

**Comment by Gary-van-Breda** [comment]
Code Fixed and deployed to Test.

**Comment by DavidRoy** [comment]
Thanks
