### ISSUE TITLE
D8 Site details - how to add a route to a site?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#145]
This site has no route, but it is not clear how one is added by the user or admin?
https://test-ukbms8.pantheonsite.io/site-details?id=2511

**Comment by Gary-van-Breda** [comment]
@DavidRoy : are you happy with what is now displayed/available for this site? The page has had a lot done to it in the last year, and it is now displaying all the sections, and has an "Insert section" button.

**Comment by DavidRoy** [comment]
Thanks. Page looks great
