### ISSUE TITLE
D8 Walk entry page - move %sun row above data grid

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#146]
https://test-ukbms8.pantheonsite.io/input-data?sample_id=5552216

%sun columns are better placed below 'Species sort order options' and above the data grid column headings (S1, S2 etc).

**Comment by Gary-van-Breda** [comment]
Code Fixed and deployed to Test.

**Comment by DavidRoy** [comment]
Not yet showing where suggested.
![pic16](https://user-images.githubusercontent.com/2699478/83129790-3bcd2600-a0d5-11ea-81ff-6505306ca4b2.png)

**Comment by DavidRoy** [comment]
Thanks, now working as expected

**Comment by Gary-van-Breda** [comment]
@DavidRoy : updated form now deployed to Test.

**Comment by DavidRoy** [comment]
Thanks
