### ISSUE TITLE
D8 Section plot and year-by-year index plot: change text colour

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#147]
https://test-ukbms8.pantheonsite.io/section-plot
https://test-ukbms8.pantheonsite.io/year-plot

Red/orange text on a blue/purple background does not work well.  Maybe change to blank or white?

**Comment by Gary-van-Breda** [comment]
Code changed and deployed to Test (also converted forms to bootstrap style, improves the appearance).

**Comment by DavidRoy** [comment]
Thanks
