### ISSUE TITLE
D8 branch functionality not working?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#148]
When masquerading as a user with role = Branch Co-ordinator
https://test-ukbms8.pantheonsite.io/branch-sites-list
Does not show all sites in branch

https://test-ukbms8.pantheonsite.io/branch-walks?year=2019
Does not show all walks in branch

**Comment by Gary-van-Breda** [comment]
It looks OK to me, in that the branch functionality is the same as the D7 version.
UKBMS is different to ABLE, in that each location in a branch has to be assigned individually to the branch coordinator at a branch level. ABLE handles the assignment through the scheme: there is no equivalent field on a location to do this with. We would need to create a field similar to the ABLE country field to hold the recording branch, and then use this as the link. @DavidRoy is this want you mean/want?

**Comment by DavidRoy** [comment]
Closing as superseded by #151
