### ISSUE TITLE
D8 Annual summary - option to have hover-over information text

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#149]
https://test-ukbms8.pantheonsite.io/annual-summary

The explanatory text takes up a lot of room.  Could this text be put in hover-over information text, linked from 'information about this report' text?

**Comment by Gary-van-Breda** [comment]
@DavidRoy Fix deployed and configured on Test.

**Comment by DavidRoy** [comment]
That works well, thanks
