### ISSUE TITLE
D8 input-data form not working corrected on tabs for moths, dragonflies, other

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#150]
e.g. https://test-ukbms8.pantheonsite.io/input-data?sample_id=5552216
click on moths and the list includes ladybirds, orthoptera, mammals etc
![pic1](https://user-images.githubusercontent.com/2699478/82645257-80a31980-9c0a-11ea-8bc6-ac40a7cdda30.jpg)

Should work as on old site, https://www.ukbms.org/mydata/input-data?sample_id=5552216
moths just gives moths
![pic2](https://user-images.githubusercontent.com/2699478/82645280-87ca2780-9c0a-11ea-9d6d-db238c274582.jpg)

Others gives the rest
![pic3](https://user-images.githubusercontent.com/2699478/82645302-91538f80-9c0a-11ea-8486-489a33b8f6c2.jpg)

**Comment by Gary-van-Breda** [comment]
Code Fixed and deployed to Test.

**Comment by DavidRoy** [comment]
This now works fine, thanks
