### ISSUE TITLE
D8 Annual summary - not working as previous version

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#151]
The D8 version works in different ways to the D7 version
@IanMiddlebrook has confirmed the expected behaviour as defined below...

**As a basic user:**
Filter by Recorder should have 2 options: My Data (default), All Recorders
When they select ‘My Data’ then Filter by Site should just list their sites and ‘combine data for all your sites’, 
when they select ‘All Recorders’ then Filter by Site should list, ‘combine data for all your sites’, ‘combine data for all sites’, all their own sites plus all other non-confidential sites. (Ideally, their own sites would be listed above all the other sites, so still easier to find in the list).

**As a branch co-ordinator:**
Filter by Recorder should have 3 options: My Data (default), Branch Data, All Recorders
When they select ‘My Data’ then Filter by Site should just list their sites and ‘combine data for all your sites’, 
When they select ‘Branch Data’ then Filter by Site should list ‘combine data for all your sites’, ‘combine data for all your branch sites’,  and then all their Branch sites
when they select ‘All Recorders’ then Filter by Site should list ‘combine data for all your sites’, ‘combine data for all your branch sites’,  ‘combine data for all sites’, all their own sites and Branch Sites plus all other non-confidential sites.

**As Admin:**
the same 3 options as branch co-ordinator, the only difference being:
when they select ‘All Recorders’ then Filter by Site should list every site, including confidential sites (italicised in the list)

**Comment by Gary-van-Breda** [comment]
This form has benefitted from some further development curtesy of ABLE/EBMS. I'll go through and work out the delta, and you can decide if you want to keep the changes for UBMS.

**Comment by Gary-van-Breda** [comment]
Current D7
**As a basic user:**
Filter by Recorder should have 2 options: "My Data" (default), "All Recorders"

- When they select ‘My Data’, the “Filter by Site” has option ‘All my sites’, and lists each of the logged in user’s sites – assigned as recorder.
- When they select ‘All recorders’, the “Filter by Site” has option ‘All sites’, and lists all non sensitive sites plus any sensitive sites allocated to the logged in user.

**As a branch co-ordinator:**
Filter by Recorder has 3 options: "My Data" (default), "Branch Data", "All Recorders"

- When they select ‘My Data’, the “Filter by Site” has option ‘All my sites’, and lists each of the logged in user’s sites – assigned as recorder.
- When they select ‘Branch data’ then “Filter by Site” has option ‘All branch sites’, and lists each of the logged in user’s sites – assigned as branch manager.
- When they select ‘All recorders’ then “Filter by Site” has option ‘All sites’, and lists all non sensitive sites plus any sensitive sites allocated to the logged in user as either recorder or branch manager.

**As Admin:**
the same 3 options as branch co-ordinator, plus the list of each user that has entered any data (created a walk).

- When they select either ‘My Data’ or any specified user, the “Filter by Site” has option ‘All my sites’, and lists each of the selected user’s sites – assigned as recorder.
- When they select ‘Branch data’ then “Filter by Site” has option ‘All branch sites’, and lists each of the logged in user’s sites – assigned as branch manager.
- When they select ‘All recorders’ then “Filter by Site” has option ‘All sites’, and lists all sites.

In all case all sensitive sites appear as italic in the location list, and the location list is in simple alphabetic order.

**Comment by Gary-van-Breda** [comment]
There has been a bit of a "clarification" in how the branch is viewed: it is seen as a collection of locations, so the branch functionality has been moved under the location filter.
In addition, for EBMS/ABLE the users were not allowed to see pan European data, only the data within their own branch, so access to the whole list of locations was removed.
It is also notable that the location filter does not indicate if the listed locations are assigned to the user at a branch or normal user level.
I suggest :

- Leave the user filter as is,
- Add option groups to the location filter, which will show the locations assigned to the user at normal recorder level, and another group for Branch level assigned locations
- For UKBMS only, allow users to see the entire list of other locations (with confidential filtering if appropriate), within another option group.

 @DavidRoy @IanMiddlebrook Is this OK? Do you wish me to re-instate the branch within the user filter?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
My overwhelming preference (on behalf of existing users) would be for functionality to be as similar as possible to the existing system (much of it is already quite different). I'm acutely conscious of 2,000 odd active users needing to completely re-learn how to use the website, and I'll be the one in the firing line. Though I realise this shouldn't stand in the way of clear improvements.

As it currently works, the selection under 'filter by recorder' determines the list of sites seen under 'filter by sites'. This seems to make sense and works well. Eg. you would only see a list of All sites if you selected All recorders, or a list of Branch sites if you selected Branch Data.

Does the proposed change mean that the site list for every user would always show all (non-sensitive) sites, even if they have selected My Data? If so, it's really important that their individual sites, or branch sites can be easily found at the top of the list.

**Comment by IanMiddlebrook** [comment]
Thinking further, if my final point is taken on board, then that would be an improvement on the current set up. 
At present, once a User selects All Recorders, their own Sites get lost in the middle of a long list. So I've always told people to select their site first, and then change to All Recorders, if they want to see what other people have recorded on their sites.

**Comment by DavidRoy** [comment]
Thanks for looking at this.  I'm happy for @IanMiddlebrook to define what is sensible to improve

**Comment by Gary-van-Breda** [comment]
On Test : "Branch Data" has been re-instated to the "recorder" filter, and "site" filter functionality amended as detailed in the summary provided by David above: only deviation is that there has never been a ‘combine data for all your sites’ when selecting 'Branch Data', only a ‘combine data for all your branch sites’.

Within the "site" filter the list of locations is now separated out into option groups for the users own sites, their branch sites, and other sites; with each group's visibility determined by the specific value in the "recorder" filter (i.e. user data, branch data or all data). This should address Ian's point above.

Note that, in terms of data returned, selecting the "Branch Data", and then any option in the "site" filter (which can be ‘combine data for all your branch sites’ or a branch site), is identical to selecting 'combine data for all users’ and the equivalent "site" filter. The only difference is a much reduced set of options in the "site" filter when specifying the "Branch Data".

**Comment by IanMiddlebrook** [comment]
Excellent, thanks @Gary-van-Breda, looks good to me.

**Comment by DavidRoy** [comment]
Thanks for checking @IanMiddlebrook.  Happy to close this now
