### ISSUE TITLE
D8: Add site download to 'my-sites' and 'branch-sites'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#154]
Follow-on from #153 

Add same site download report to:
https://www.ukbms.org/mydata/sites-list
https://www.ukbms.org/mydata/branch-sites-list

**Comment by Gary-van-Breda** [comment]
Do #153 first. D7 and D8 sites.

**Comment by Gary-van-Breda** [comment]
I've added the same sites download report to the "My Sites" and "Branch Sites" pages on Live that is on the "All Sites" page. When #153 is done, the extra data will appear here as well, as they use the same report on the warehouse.
I've checked that they are both working correctly,
@DavidRoy : if you are happy, can you close this issue?

**Comment by DavidRoy** [comment]
Thanks
