### ISSUE TITLE
D8 version - data entry, validation rules missing?

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#155]
Hi,

I just used the D8 version to enter my data for Stoborough Heath today.

I recorded 124 Silver-studded Blue in section 5, and this was accepted without question. I know that when I enter these figures on the live version, a validation check appears for counts above 50 for Silver-studded Blue.

Without wishing to check every single validation rule, is it possible to say which rules have been incorporated into D8 and which have not? - phenology, geography, numerical?

Thanks,

Ian

**Comment by Gary-van-Breda** [comment]
I have checked this, and only one section level validation rule had been set up on this version of the form (for Chequered Skipper). I have now copied over the remaining section level validation rules.  
  
The phenology and geography checks are taken from the warehouse rather than being specified on the form. These should both have been carried over automatically.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
I've had another look, but I can't get any of these abundance warning messages to work, not even Chequered Skipper.
I'm on Microsoft Edge.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook : sorry I had missed a new config item for this new form version. I've fixed this, and tried a few and it now looks like it is working OK to me - could you have another go?
Thanks

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
So it now looks like it's picking up the excessive counts ok.

There is another slightly strange thing happening now though.

If I decide I've made a mistake and try to delete an entry, the high count warning message comes up, asking if I still want to enter this data. If I click No, then it doesn't delete the record I was trying to delete.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook : I've deployed a change to Test, so that is does not do the limit checks when clearing the data.

**Comment by IanMiddlebrook** [comment]
Excellent - thanks @Gary-van-Breda
