### ISSUE TITLE
D8 version - data entry, keeping track of columns

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#156]
Hi,

Another observation from doing data entry today. The live system has a couple of tricks to help you keep track of the section columns as you move down the page. Firstly the column headings remain visible on your webpage, even when you've scrolled down to the bottom of the form. Secondly, there are dashed vertical lines between every 5 sections.

Could these aids please be added to the D8 version?

Thanks,

Ian

**Comment by Gary-van-Breda** [comment]
Now added on Test

**Comment by IanMiddlebrook** [comment]
Excellent - thanks Gary
