### ISSUE TITLE
D8 version - data entry preferences/defaults

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#157]
Hi,

On the butterfly data entry pages, the ordering seems to default to the alphabetical ordering of 'Common Name'. I always change this to taxonomic order, but it still reverts to alphabetical order the next time I try.
If there is no way of setting a preference, then this needs to default to taxonomic order, because that it what recorders will expect, and it ties in with their standard recording forms.

Also, on the current version, under my account details, I'm able to select a preference for the species list - eg. Species known at this site etc. I don't see a way to set that preference on the D8 version? If that could be added, then perhaps it would also be useful to set a preference for taxonomic or alphabetical ordering at the same time.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
I've changed the default order of the Butterflies grid to be Taxonomic. Currently there is no way of setting a personal preference for this.  
  
I have created the user account field that links into the page to set the personal preference for the species list: this is called "Default species view" and can be set on you account page in a similar manner to the existing system. This functionality already existed - I just hadn't created the user field.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
That seems to be working better, apart from one thing.

When the species list first loads up in taxonomic order, all looks good. Then after a few seconds, sometimes more, the Skippers seem to redistribute themselves randomly throughout the species list. Eg. Small Skipper ends up between Small White and Green-veined White, Lulworth Skipper ends up between Painted Lady and Small Tortoiseshell, Large Skipper down with Marbled White and Grayling etc.

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook : I've applied a bugfix for the species list reordering, which is on Test.  
This bug is also present on the Live (D7 system), though is only visible if you change the sort order to common name, then back again to taxonomic.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
Not sure if the fix has been applied yet, but it's definitely still happening for me, without changing any settings.

i.e. I go on to the data entry page, with the list already ordered taxonomically, and just wait about 5 seconds before the Skippers disperse amongst the list.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : could you make sure to clear your browser cache?

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda, yes that seems to be stable now.
