### ISSUE TITLE
Annual Summary species missing

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#159]
Hi @Gary-van-Breda 

The recorder at Thorpe Marsh Nature Reserve has noted that both Small Skipper and Large Skipper are missing from his data when he looks at the Annual Summary page, on Summary Table and also in Raw Data table.
He has been recording these 2 species for the last 5 weeks.

Is there a reason why the Annual Summary tables might have missed these species here (and possibly others elsewhere)?

Thanks,  Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : when I masquerade in, I can see the two species' data, in both Summary and Raw data: can you confirm that this is still an issue?

**Comment by IanMiddlebrook** [comment]
looks like the problem has gone away.
