### ISSUE TITLE
Issues with Mother Shipton name

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#16]
3 Mother Shipton moths were recorded at Ryton Meadows on 5-jun-2016 (week 10).
On the data entry form, where Mother Shipton were entered, hovering over the name gives a scientific name of _Euclidia mi_.
On the Annual Summary - Summary or Estimate Table, these moths appear as Mother Shipton, but hovering over the name gives a scientific name of _Callistege mi_. Not a major problem - at least they show.
However, on the Annual Summary - Raw Data table, these moths do not appear at all. There is a row for Mother Shipton (Callistege mi), but it is empty.
In the Downloads, these moths appear as _Euclidia mi_ in both the 'Species' and 'Preferred' column, rather than Mother Shipton.

Is this all due to an underlying confusion between 2 scientific names?

**Comment by Gary-van-Breda** [comment]
Yes(?). There are 2 relevant entries in the UK Master list on the Warehouse:
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/400621
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/65957
Both are on the UK Master List, both have the same taxon_meaning_id, and both are flagged as preferred. Is this a valid situation?
I think we could do with sorting this out (and any similar?) before we look to see if there is anything wrong with the code.

**Comment by DavidRoy** [comment]
@johnvanbreda is this related to recent issue with UKSI and common names for moths?  Has the UKSI issue been resolved, or has this uncovered a further bug to fix?

**Comment by johnvanbreda** [comment]
I don't think this is related to the other (now fixed) issue, #126 and I don't actually think there is anything wrong with the UKSI import in this case. Euclidia mi is a synonym of Callistege mi as it is marked as preferred=false in the database. @Gary-van-Breda I'm not sure why you thought Eucladia mi was preferred - it looks correct to me in both the taxa_taxon_lists and cache_taxa_taxon_lists tables? The common name Mother Shipton also correctly points to C. mi as it's preferred name.

I am assuming that Euclidia mi was the preferred name prior to the last update last Autumn, hence all records before then are for E. mi and all records after then are for C. mi as the preferred name has changed.

Is there something wrong in the reports?

**Comment by Gary-van-Breda** [comment]
Just putting this in to keep track - not expecting a response from anyone.
I've had another look at this. When the preferred name was changed from C.mi to E.mi, the taxon_meaning_id also changed. This has led to a mismatch between the cached data in the summary_occurrences table (used for the Annual Summary), and that returned by the raw data report (which looks at the current cache_taxa_taxon_lists).
The summary builder needs to either detect the changes to the taxon list, and rebuild the affected entries, or perhaps have a continual rebuild facility (or both).

**Comment by DavidRoy** [comment]
Closing this issue for the UKBMS, but will raise as a general Indicia issue

**Comment by Gary-van-Breda** [comment]
An update: A change was put into the summary builder which checks for changes to the taxa and rebuilds the data as appropriate. This has finished its scan now, and the problem highlighted above should now be sort of resolved in that the raw data now matches with the summary data for Mother shipton/E. m and the data is displayed in the raw data tablei, but the taxon data change has meant that the taxon displayed for the old data is now C. mi/E. mi, not Mother shipton/E. mi .

**Comment by DavidRoy** [comment]
Thanks Gary.  @IanMiddlebrook - please can you check this is resolved and close the issue if so

**Comment by IanMiddlebrook** [comment]
Is this entirely resolved? not sure.
It's certainly improved, because the moths always appear where they should now, but ...
Looking at the entry for Ryton Meadows on 5-jun-2016, the Data Entry form is fine, shows Mother Shipton (hovering over gives Euclidia mi).
The Annual Summary and Raw Data tables now show Callistege mi (hovering - Euclidia mi). Why not Mother Shipton?
The various downloads now show Euclidia mi (hovering - Euclidia mi). Again, why not Mother Shipton.
So the preferred/scientific name is always the same, but the normal Species Name is displayed in 3 different ways depending on where you look.

**Comment by Gary-van-Breda** [comment]
Related to but slightly different to #32

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @JimBacon : can you run the following SQL against warehouse1?
```
DELETE FROM indicia.summary_occurrences
WHERE taxa_taxon_list_id IN (65957, 65958, 65959, 65960)
AND website_id=27;

UPDATE indicia.occurrences
SET taxa_taxon_list_id = 400621, updated_by_id = 1, updated_on = now()
WHERE taxa_taxon_list_id IN (65957, 65958, 65959, 65960)
AND website_id=27;
```
Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
First query returns with 19821 records, Is it ok to delete?

**Comment by Gary-van-Breda** [comment]
Yes: these records will be recreated by the summary_builder once the second update statement is run.

**Comment by BirenRathod** [comment]
Done.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : following the data fix above, it all now looks consistent.
Close?

**Comment by IanMiddlebrook** [comment]
That's great - thanks Gary
