### ISSUE TITLE
WCBS Squares to add to UKBMS online

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#161]
Please can you add these WCBS-BC squares to the online system. Thank you, Megan.
[BC sqs to add to UKBMS.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/4995381/BC.sqs.to.add.to.UKBMS.xlsx)

**Comment by Gary-van-Breda** [comment]
Done.

**Comment by DavidRoy** [comment]
@MeganLowe can you close the issue if resolved for you?
