### ISSUE TITLE
add a total at the bottom right on the recording page

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/UKBMS-online#162]
Hi there,
>>
>>Just a little request to add a total at the bottom right on the 
>>recording page so it totals all the butterfly species count across the 
>>whole walk.  That would be lovely.
>>
>>Thanks,
>>
>>Sandy (Dundon Beacon and Lollover in Somerset)

**Comment by Gary-van-Breda** [comment]
When the new version of the website is released (hopefully soon), this will feature a total figure at the bottom right of each species grid, as requested.

**Comment by Gary-van-Breda** [comment]
@marcbotham : now that we have gone Live with the new website version, and the total total value is present, could you check to confirm it now does as requested?
