### ISSUE TITLE
Removal of Delete Option on WCBS Squares

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#163]
Hi, we've had a few instances of WCBS normal users accidentally deleting their WCBS squares. This is currently an option to normal users if the square does not have any records attached to it. Please can we remove this option? This applies for both WCBS-BC and WCBS-BBS squares.
Thanks, Megan.

**Comment by Gary-van-Breda** [comment]
With the new version of the Site data entry page, the Delete Site option is not currently enabled for any users

**Comment by Gary-van-Breda** [comment]
@MeganLowe: Can you confirm that the new site does not allow WCBS squares to be deleted by normal users?
(See #194)

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda apologies for the delay. Thanks - looks good for normal users. How do admins delete the site though (for instance if they're unsuitable)? Is it this button that I've circled in red?

![image](https://user-images.githubusercontent.com/64081219/115364798-aee2fd80-a1bb-11eb-8dd3-3344b84c4a23.png)

**Comment by Gary-van-Breda** [comment]
No - that is for deleting the whole form!
The site deletion is currently not working, and is covered by #194

**Comment by MeganLowe** [comment]
Ah I won't click that one then! Must have missed #194, great you're already on the case. All looks fine for normal users in terms of deletion rights on WCBS squares - shall I close this particular issue now?

**Comment by Gary-van-Breda** [comment]
I think so.

**Comment by MeganLowe** [comment]
Brill, thanks @Gary-van-Breda
