### ISSUE TITLE
WCBS-BBS Squares to be added to UKBMS online

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#164]
Hi, please can we have the following WCBS-BBS squares added to the online system:
[WCBS-BBS squares to be added to UKBMS.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/5269241/WCBS-BBS.squares.to.be.added.to.UKBMS.xlsx)

**Comment by Gary-van-Breda** [comment]
Done.
Note that 2 of these already existed as WCBS-BBS locations with the same grid ref:

- "SO5683" as "SO5683 The Thrift, Stokegorse, Clee St Margaret"
- "SO5685" as "SO5685 Heath Farm, Heath, Clee St Margaret"

I have not uploaded these.

**Comment by DavidRoy** [comment]
@MeganLowe please close if resolved
