### ISSUE TITLE
Issues downloading site section data

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/UKBMS-online#165]
When trying to download the section data from TW online ‘Full Site Sections data download (CSV)’  I get this error message:

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 8192 bytes) in D:\websites\warehouse\system\libraries\drivers\Database\Pgsql.php on line 436

**Comment by Gary-van-Breda** [comment]
@DavidRoy : this report is returning all the site attributes as well as the section attributes, for each section. It is just huge. Do we need all the site attributes? If not, which ones can we omit?
