### ISSUE TITLE
Annual Summary page hanging with non-butterfly species

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#166]
Hi,

When viewing the Annual Summary page, there appears to be a problem when you 'include non-butterfly species' if you are looking at a lot of sites (eg. All Sites or Branch Sites).

The Summary/Estimate Tables load with data, but the Charts do not develop (perhaps because there are too many species?). 

One result is that the tabs do not form - the tables/charts are all visible on one page (see image).
The other consequence is that the page stops working - ie. you can't change the display by changing any of the settings (eg. de-selecting non-butterfly species, or choosing an individual site does nothing). You have to go back out of the page to start again.

I've checked this on the D8 version of the site, and exactly the same thing happens.

![image](https://user-images.githubusercontent.com/24699793/96453929-10c5a900-1213-11eb-9640-b4993b1af7bc.png)

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Fixed in Drupal8 version of the site.
The `Stonechat "hibernans"` species name has double quotes in it: this was causing a problem in a part of the code.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda @DavidRoy 

I'm re-opening this issue because it has returned - manifesting itself in exactly the same way.

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Fix applied, and deployed to test.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 

Looks good to me

**Comment by Gary-van-Breda** [comment]
Now pushed to Live. Changes confirmed as deployed.
Closing
