### ISSUE TITLE
Add Login/Register link in header bar of new website

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#167]
Hi, please can we add a link to 'Login/Register' on the header bar of the new UKBMS website - perhaps to the right of the other header links. Can this then change to a 'Logout' link once a user is logged in? 
Thanks, Megan

**Comment by DavidRoy** [comment]
hi Megan
The login is under the 'My Data' menu.  Given many users of the website won't be submitting data, I think it's ok to have this less prominent?
David

**Comment by MeganLowe** [comment]
Hi David
Thanks for your reply. I think it needs to be a bit more obvious, particularly for new users to find where to register. Perhaps a button on the homepage would be better? On the right under search? I was going to ask to include a Go to Data Entry button anyway, so this could be login/register instead. It needs to be easy for those who do submit data as that may be all they use the website for.
Thanks, Megan

**Comment by DavidRoy** [comment]
@BirenRathod can you implement this suggestion of a home page button

**Comment by BirenRathod** [comment]
@DavidRoy 
Is it ok if I moved login link at the right side of the main menu?

**Comment by DavidRoy** [comment]
I'm not sure there is room?

**Comment by BirenRathod** [comment]
@DavidRoy 
I have added the login link at the right side of the menu. see if that is ok. It may be a problem for smaller screen. If it is let me know.

**Comment by DavidRoy** [comment]
Thanks.
@MeganLowe does this work for you?  Close issue if resolved?

**Comment by MeganLowe** [comment]
Looks good to me and seems to work fine on a few different screen sizes. Thanks both.
