### ISSUE TITLE
New Website Username Login

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#168]
Is it possible to allow users to use their email address OR ukbms username as the username to login in to the new website please? At the moment it will only allow you to use your UKBMS username (the old website lets you use email). Many users can never remember what their username is (me included...).
Thanks
Megan

**Comment by DavidRoy** [comment]
@BirenRathod can you implement this please

**Comment by BirenRathod** [comment]
@DavidRoy  & @MeganLowe I have made changes on the website, so it is now possible to login with email or username.

**Comment by MeganLowe** [comment]
Great, thank you. Worked fine for me this morning 👍
