### ISSUE TITLE
Changes to My Sites page on new website

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#170]
On the My Sites page of new website:
-  please can you remove the text 'Report Parameters'.
- make the Site Type drop down menu default to \<please select> for normal users (or all users if it's not possible to make a default for just normal users). 
- move the Run Report button up slightly so to create a gap between this and the site list table below.
- make the text for all download options towards the bottom of this page smaller or a different colour so they don't stand out so much.
- Put the Add Transect link in a button similar to Run Report. 
- If there is room to the right of the Add Transect button please can you include a note to say: 'For new WCBS sites please contact your Regional Champion or WCBS Officer.' (with a link to the contact us page)?
Thanks
Megan

**Comment by DavidRoy** [comment]
@BirenRathod can you make these changes to https://test-ukbms8.pantheonsite.io/my-sites

**Comment by BirenRathod** [comment]
@MeganLowe 
I have made below amendments.

- Removed 'Report Parameters' text.
- @Gary-van-Breda can you set the default to `please select`?
- Run Report button moved up.
- all download link text is now resized and different color match to site theme.
- Button style created for Add Transect link.
- Added text below to Add Transect button as it doesn't add next to button.

**Comment by Gary-van-Breda** [comment]
@BirenRathod @MeganLowe : the default Site Type should be remembered across the different reporting pages, so if the user chooses site type "WCBS-BBS" in the Annual summary, it should be the default the next time the My Sites is brought up.

**Comment by BirenRathod** [comment]
@Gary-van-Breda yes, I missed the remembering part. So no change requires.

**Comment by MeganLowe** [comment]
@Gary-van-Breda : I find that the My Sites page defaults to Transect on first open. It may change after you've been to the Annual Summary page (I haven't tested this) but most people would go to My Sites first. The trouble is we often find that WCBS recorders struggle to find their squares if the drop down box defaults to transect and then they create a new transect instead (not what we want). If it's too tricky to change the default then I will just write some clearer instructions on the page - not a problem.

**Comment by MeganLowe** [comment]
@Gary-van-Breda @BirenRathod : sorry, also just noticed 'Report Parameters' text is still present on the My Sites page.

**Comment by Gary-van-Breda** [comment]
@MeganLowe : I've changed the default default (sic) to "please select" on "My sites" only.

**Comment by BirenRathod** [comment]
@MeganLowe I implemented the style. 'Report Parameters' text is hidden now.

**Comment by MeganLowe** [comment]
@Gary-van-Breda thanks. Is it possible to make the page automatically show all the sites assigned to you (as if the ‘Run Report’ button had already been pressed)? Then the filter just provides the user with the option to limit the list if they want to. Also, it would be useful if there was an additional column for ‘Site Type’ in the table that is shown. So that when all your sites are showing it’s easy to differentiate between eg. WCBS-BC and WCBS-BBS squares. Is that possible please? Thanks, Megan (and Ian)

**Comment by Gary-van-Breda** [comment]
@MeganLowe : I've tweaked it so the report now runs automatically with no site type filter applied.
@BirenRathod : Can you deploy the current master Branch of the BRC reports (https://github.com/BiologicalRecordsCentre/indicia-reports) into warehouse1? Thanks (@MeganLowe this report update is required so we can get access to the location type for the report grid)

**Comment by BirenRathod** [comment]
@Gary-van-Breda I have pulled that report now.

**Comment by Gary-van-Breda** [comment]
@MeganLowe : back to you to check that this is what you want...

**Comment by MeganLowe** [comment]
@Gary-van-Breda this is fantastic! Just one other small thing, please can you make the space between the 'Run Report' button and the table below ever so slightly bigger?

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you do the "make the space between the 'Run Report' button and the table below ever so slightly bigger" ?

**Comment by BirenRathod** [comment]
@Gary-van-Breda & @MeganLowe I have increased a space now.

**Comment by MeganLowe** [comment]
Brilliant, looks great thank you.
