### ISSUE TITLE
Changes to Site Details pages on new website

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#171]
Please can you make the following changes to ALL Site Details pages on new website:
- Remove top paragraph beginning 'By submitting...' - this needs to be moved to the My Walks page.
- Move the 'Confidential' tick box up so it is directly above the yellow text box explaining why to tick it.
- Make text in yellow box slightly smaller. Change the word 'Sensitive' to 'Confidential'.
- Remove excess headings 'Site Details' and 'Details' from above County.

Thanks, Megan

**Comment by DavidRoy** [comment]
@BirenRathod can you make these changes to the Site Details page, e.g. https://test-ukbms8.pantheonsite.io/site-details?id=1977

**Comment by BirenRathod** [comment]
@MeganLowe 
I have made below amendments.

- Top paragraph now removed and added on to My Walks page.
- @DavidRoy could you ask @Gary-van-Breda to move this confidential box above the yellow message box. This needs amendment in indicia code.
- Yellow textbox's text has resized now.
- Removed excess headings from above County.

**Comment by Gary-van-Breda** [comment]
Yellow message has been moved to be the help text on the Confidential box, and styled to be the yellow box.  
@MeganLowe : do you need the Confidential box moved up above the County?

**Comment by MeganLowe** [comment]
@Gary-van-Breda No I think that looks great, thank you.
