### ISSUE TITLE
Route Map Edit Permissions

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#173]
Hi again, just want to check that normal users will not have permission to edit route maps once a site has records entered for it on the new website?
At the moment it seems I can add, edit, or remove sections to a WCBS route that has butterfly records when masquerading as a normal user?!

Thanks
Megan

**Comment by Gary-van-Breda** [comment]
@MeganLowe : See #169. Code deployed to Test to fix this.

**Comment by MeganLowe** [comment]
Map permissions seem fine now - thanks Gary.
