### ISSUE TITLE
Satellite Map on New UKBMS

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#174]
Hi, is it possible to add a satellite image layer for the site route maps as well as, or instead of, Open Street Map? Satellite is far easier to use to draw a route than street map as you can see environmental features etc.
Thank you
Megan

**Comment by Gary-van-Breda** [comment]
Yes: we can.
The problem here is that the test environments have a URL which does not match with the Google Maps API key (which is registered against ukbms.org). Once the new UKBMS site goes live (and has a ukbms.org URL) we will be able to add the Google Maps.
This is also the reason why the Place search does not work at the moment in the test/dev environments.

**Comment by MeganLowe** [comment]
Ah that makes sense, thanks Gary - I'll close this issue now.

**Comment by DavidRoy** [comment]
@Gary-van-Breda @BirenRathod is this up and running now the new site has gone live

**Comment by BirenRathod** [comment]
@DavidRoy & @Gary-van-Breda , I noticed that there was no google api stored in indicia settings. I just add it and it works fine for satellite map search.

**Comment by DavidRoy** [comment]
Thanks @BirenRathod, yes that was the previous discussion on this

@IanMiddlebrook @MeganLowe please close if happy with this now

**Comment by IanMiddlebrook** [comment]
@DavidRoy @BirenRathod 
Here we go again!  
I'm afraid I don't see any satellite map option when I look at existing sites or set up a new transect.

Also, the search box now seems to be less useful. When I used it this morning, it would come up with several suggestions. Now, it just goes to where it thinks I mean. 
For example, if I type Newport and press search, it takes me straight to Newport in South Wales, with no options. But there are lots of places called Newport that I might mean.

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
Thanks @DavidRoy @BirenRathod, I can get the satellite maps now.

I'm still puzzled by the lack of options from the search box, but hopefully it won't cause too many problems.

Best wishes, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook: It is odd, but the Google Place search API is returning only a single entry, even though if you enter "Newport, Essex" or "Newport, Isle of Wight" you get these returned correctly. I'm not sure there is much we can do about this, other than suggest the users add the county to their search if they don't get the response they expect with the more general search. Equally, I'm at a bit of a loss as to what makes the search provide a list to select from (often holding a single entry),  or just jump straight there. again, I'm not sure there is much we can do about this.
Is this OK to close?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
Yes, happy to close, it's only a minor irritation for me because I grew up in Newport (Isle of Wight) :-)
