### ISSUE TITLE
Holiday Square page on new ukbms

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#175]
Hello, I'm unable to edit the text on the holiday squares web page of the new website. I presume because it is embedded within a text box of sorts. Are you able to add this text in to the main introductory page text and remove the yellow text box please so I can edit it in the future?
Thanks, Megan

**Comment by Gary-van-Breda** [comment]
Change deployed to test environment: intro text has been moved to the page intro text, and removed from the iform code.

**Comment by MeganLowe** [comment]
Looks good to me, thanks.
