### ISSUE TITLE
Changes to Create New Account form

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#176]
Hello, I have a few suggested changes for the Create New Account (registration) form on the new ukbms as follows:
- make first name and last name compulsory fields
- there are two red stars indicating a compulsory field at the moment - is it possible to remove one of these so only one red star remains on each compulsory field?
- I'm not sure if this is the right place to select your preferred default species view? Does it also appear elsewhere on the website for users to change it in the future? Could it be better to include this option under 'My Account' instead of the sign up page?
- remove 'upload picture' and 'upload files' options as I don't think these are needed and may cause us issues.
- add in a text box called 'About your surveys - please let us know the names of the transects/sites you are planning to survey' 
- @DavidRoy do we need to add the website Terms of Use here along with a tick box for people to agree to them? The current UKBMS also has a tick box for under 16 yr olds - do we need to include this due to safeguarding issues?

For info here's the link to the current registration form on ukbms: https://www.ukbms.org/mydata/user/register

We may need to review the automated email reply too - how can I find/amend this?

Thanks, Megan

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Should this be done by @BirenRathod or me?

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you pick this up and involve @BirenRathod as needed. Thanks

**Comment by BirenRathod** [comment]
Yes, that's right. @Gary-van-Breda let me know if you need anything.

**Comment by Gary-van-Breda** [comment]
- First and last names now compulsory.
- Preferred Species view removed from registration form only (still present on profile).
- 'Upload picture' and 'Upload files' removed from both registration and profile.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : there seems to be 2 CSS definitions for `.form-required:after`: one in the UKBMS theme `overrides.min.css`, and one in `https://cdn.jsdelivr.net/npm/@unicorn-fail/drupal-bootstrap-styles@0.0.2/dist/3.4.0/8.x-3.x/drupal-bootstrap.css`. These each add one of the asterisks, but the overrides does not switch off the bootstrap derived one.  
Can you sort this out?

**Comment by Gary-van-Breda** [comment]
@DavidRoy : did we not take a conscious decision to remove both the under 16 and "About your surveys" fields? I can't find an evidence trail.

**Comment by Gary-van-Breda** [comment]
@MeganLowe : the email templates can be found at the bottom of https://test-ukbms8.pantheonsite.io/admin/config/people/accounts  
I've given permissions top access this to the site editor role, so you should now be able to see it. Please be careful about the other fields on this page.

**Comment by BirenRathod** [comment]
> @BirenRathod : there seems to be 2 CSS definitions for `.form-required:after`: one in the UKBMS theme `overrides.min.css`, and one in `https://cdn.jsdelivr.net/npm/@unicorn-fail/drupal-bootstrap-styles@0.0.2/dist/3.4.0/8.x-3.x/drupal-bootstrap.css`. These each add one of the asterisks, but the overrides does not switch off the bootstrap derived one.
> Can you sort this out?

@Gary-van-Breda Which page is this on? I know I could find in the css file but I need to see on the page too.

**Comment by BirenRathod** [comment]
@Gary-van-Breda Don't worry, I found it now.

**Comment by BirenRathod** [comment]
@Gary-van-Breda It has resolved now. that overrides.min.css file is the old version of bootstrap subtheme code. It should not be there in theory. I haven't removed yet, I'm not sure will that cause any thing else but I found other way round to solve this problem by tweaking theme settings to custom instead of using jsdeliver. 

Let me know if you see any other problem due to this, otherwise we stick with this.

**Comment by Gary-van-Breda** [comment]
@MeganLowe : can you review this and check if it has been completed to your satisfaction?

**Comment by MeganLowe** [comment]
Looks good, thanks @Gary-van-Breda
