### ISSUE TITLE
Gap between header and main body of text

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#177]
Hello, on new UKBMS is it possible to make the gap between the header bar and the main body of text smaller (perhaps half what it is now)? I presume this is a design feature to show off the background image, but I'm finding on smaller screens you have to scroll down to find the main content of the page and it isn't always clear whether the page is just loading or hidden out of view. I'm not sure if I've explained that very well so I've made a quick PDF to demonstrate what I mean (attached).
Thanks, Megan
[Decreasing gap example.pdf](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/5819719/Decreasing.gap.example.pdf)

**Comment by DavidRoy** [comment]
I agree.  @BirenRathod could you make this change?

**Comment by BirenRathod** [comment]
@MeganLowe I have decreased the gap of top banner and main content.

**Comment by MeganLowe** [comment]
Fantastic thanks @BirenRathod
