### ISSUE TITLE
Test UKBMS Drupal 7 site: add walk page missing

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#18]
Add walk page missing, accessed from http://192.171.199.230/ukbms/mydata/my-walks, i.e. click on a date gives an error:
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

Example is: http://192.171.199.230/mydata/input-data?location_type_id=777&date=18/04/2016

**Comment by DavidRoy** [comment]
Also, add timed count page missing
http://192.171.199.230/mydata/input-timed-counts?date=04/04/2016

**Comment by Gary-van-Breda** [comment]
Fixed: Configuration on "My Walks", "Branch Walks", "Timed Counts" and "All Timed Counts" grid forms changed.
