### ISSUE TITLE
BBS Squares on Sites Map

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#181]
Hi everyone, I've just spoken to the BTO and they have requested that we remove the BBS squares from the site details map on the new website. They have a few reasons for this (happy to forward all on if needed) but to put it briefly it's due to their policy of only displaying 10km resolution of BBS squares/records. 
Instead I will include a sentence in the intro text on this page that mentions BBS squares and how to contact BTO.

**Comment by Gary-van-Breda** [comment]
@MeganLowe : just to be absolutely sure we do the right one(s), can you give us the test site URL(s) of the page(s) affected?

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda yes of course it's this map: https://test-ukbms8.pantheonsite.io/sites  
Essentially we just need to hide the BBS squares, everything else is fine I think.

Not sure whether the same applies to the 'Explore Map': https://test-ukbms8.pantheonsite.io/explore-map I can't see what this looks like as there haven't been any recent records, but presumably this will be ok as the user has to be logged in and the map only displays recent records rather than all sites?!

**Comment by DavidRoy** [comment]
@MeganLowe do we also need to hide BBS from here - https://test-ukbms8.pantheonsite.io/sites

**Comment by MeganLowe** [comment]
@DavidRoy yes that's the one.

**Comment by DavidRoy** [comment]
Thanks.  That's one for @burkmarr 

Rich - can you exclude the WCBS-BBS sites from these pages

**Comment by burkmarr** [comment]
I've updated the report in https://github.com/BiologicalRecordsCentre/indicia-reports that retrieves the sites for the cluster mapping. @BirenRathod - how does this get propogated to the Pantheon dev/test site?

**Comment by BirenRathod** [comment]
@burkmarr if you can pull the repository, you will see iform module in custom folder in the module folder, where you can make changes.

**Comment by BirenRathod** [comment]
@burkmarr you can get the github repo link from pantheon. you have already got an access for pantheon of UKBMS. Also reports are on test or dev warehouse. so you need to check, which warehouse is linked with website?

**Comment by Gary-van-Breda** [comment]
@BirenRathod @burkmarr : The test D8 site is actually linked to the Live warehouse, so we need the updated report dropped into warehouse1

**Comment by BirenRathod** [comment]
Thanks, @Gary-van-Breda. 
@burkmarr you can look on live warehouse in modules\brc_reports\reports\projects\ukbms folder

**Comment by burkmarr** [comment]
Thanks @BirenRathod - I can't log into the warehouse server at the moment as you and @johnvanbreda are logged in.

**Comment by BirenRathod** [comment]
@burkmarr I was updating reports folder for Andy, so I just logged out now. all yours now.

**Comment by burkmarr** [comment]
Thanks @Biren - that pulled in the report I changed too so the BBS sites are no longer appearing on the cluster map: https://test-ukbms8.pantheonsite.io/sites

**Comment by Gary-van-Breda** [comment]
@MeganLowe : back to you to review and close.

**Comment by MeganLowe** [comment]
Looks good to me, thanks everyone!
