### ISSUE TITLE
Additional text field required on registration

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#182]
@Gary-van-Breda further change needed as part of D8 migration #180 

Registration form requires a text field for
‘Tell us which transects or WCBS squares you are walking’

As currently exists on the https://www.ukbms.org/mydata/ site

**Comment by Gary-van-Breda** [comment]
@DavidRoy This was one of the things we left out of the migration: do we need to re-instate all the data from the old system?

**Comment by DavidRoy** [comment]
@IanMiddlebrook question for Ian whether the historic data in the user accounts needs brining over.  Or whether this is more about capturing for new registrations so we can check how to link new users to existing transects

**Comment by IanMiddlebrook** [comment]
@DavidRoy  It's not something that I look at after the initial registration, so not critical to migrate across.
Thanks, Ian

**Comment by DavidRoy** [comment]
Thanks Ian. 
@Gary-van-Breda therefore no migration needed but this question needs to be on the new registration page

**Comment by Gary-van-Breda** [comment]
@DavidRoy I see Biren has set up the Live pantheon environment (currently at https://live-ukbms8.pantheonsite.io/)  
Can I assume we are implementing the workflows as follows:  
Code: Dev->Test->Live  
Data: Dev<-Test<-Live ?  
In which case I will add the field in the Live environment.

**Comment by DavidRoy** [comment]
yes, thanks.  We'll switch the url (www.ukbms.org) to live when ready.

**Comment by Gary-van-Breda** [comment]
@DavidRoy Additional "Intended Transects" field added, and made available on Registration form, on Live environment.

**Comment by DavidRoy** [comment]
Thanks.  @IanMiddlebrook  please close if now resolved for you

**Comment by IanMiddlebrook** [comment]
@Gary-van-Breda 
Hi, I don't see the new field here: https://test-ukbms8.pantheonsite.io/user/register 
Am I looking in the wrong place?
Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Yes: I've put it into the Live area, and not pulled that back to test.
Check here https://live-ukbms8.pantheonsite.io/user/register

**Comment by IanMiddlebrook** [comment]
@DavidRoy @Gary-van-Breda 
Ah OK. Megan and myself have been making changes to the test version. 
Should we have been working in the Live area? Will all our changes get lost?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
It that's the case, we'll push everything from the test to Live before we go live. I'll drop the new field into test as well.
@BirenRathod : Is there anything we'll need to re-apply to live if we do this?

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Now put on test site.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
So, just to clarify, we can continue making our changes to the test version?
BW, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Yes

**Comment by BirenRathod** [comment]
@Gary-van-Breda Nothing from me. Let me know when you all ready.

**Comment by Gary-van-Breda** [comment]
See #176
