### ISSUE TITLE
Finalise revised Terms of use

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#183]
@IanMiddlebrook to review

https://test-ukbms8.pantheonsite.io/terms_of_use

**Comment by IanMiddlebrook** [comment]
Hi David,

I've just amended this paragraph slightly to reference the fact that 'sites' can be marked as confidential.

Where sites and/or species are deemed to be “sensitive” the record may have its location blurred, or may be treated as confidential. Lists of sensitive species may include, but may not be limited by, lists agreed with the UK government conservation agencies.

Also changed paragraph title - 'linking to the iRecord website' to 'linking to the UKBMS website'

**Comment by DavidRoy** [comment]
Excellent, thanks for spotting this important point and mention of iRecord I missed
