### ISSUE TITLE
Stop most users from adding WCBS squares

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#186]
At present, it looks like any user can add new WCBS squares to the system.

We need to change this so that ordinary users and branch co-ordinators can only add new Transects - so when they click on 'Add Transect' they go straight through to the fresh Site Details page for a new Transect.

Admin should be the only users presented with an option to add either type of WCBS square.

Thanks,  Ian

**Comment by DavidRoy** [comment]
@Gary-van-Breda please can you resolve this issue needed for D8 switch-over #180 

WCBS squares are typically loaded directly into the data warehouse so, if easiest, the create-site form could be restricted to Transects for all users?

**Comment by Gary-van-Breda** [comment]
Code fix deployed to Test: please review.

**Comment by DavidRoy** [comment]
@IanMiddlebrook @MeganLowe could you check this is ok for you and close if appropriate

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda ,

It looks good for normal users now, but it still looks like Branch Co-ordinators are able to add WCBS squares. Only Admin should be able to do so.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Code fix extended to allow restriction of branch manager creation.
Deployed to Test: @IanMiddlebrook can you try again?

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda , that seems to be working fine.
