### ISSUE TITLE
No Search Box for finding location of new transects

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#187]
Hi, When setting up a new transect, on the Site Details page a text box says:
 "Use the **search box** to find a nearby town or village ..."
but there is no Search box.

Thanks,

Ian

**Comment by Gary-van-Breda** [comment]
Hi Ian,  
see https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/174#issuecomment-762931426  
Basically the Google API keys won't work on the test env.

**Comment by IanMiddlebrook** [comment]
Right, so there will be a search box when we go live?

Fair enough, I was just trying to get a useful screenshot for the guidance notes, but I can't highlight a non-existent search box!

I'll work around it.

Thanks, Ian

**Comment by DavidRoy** [comment]
part if #180

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you configure on https://live-ukbms8.pantheonsite.io/ so we can check and then close this issue?

**Comment by Gary-van-Breda** [comment]
The problem is the URL itself, so any of the pantheon ones will have this problem.  
@BirenRathod : can we add the pantheon urls to the list that the api keys apply for? This and the captcha as well would be brill.

**Comment by BirenRathod** [comment]
@Gary-van-Breda For location search, I recon if current website ukbms.org has got no problem then it will be no problem once site goes live. the API key is bind to use with ukbms.org url.

**Comment by DavidRoy** [comment]
@Gary-van-Breda @BirenRathod any action needed on this one now the site has gone live?

**Comment by BirenRathod** [comment]
@DavidRoy do you know the URL of this page?

**Comment by BirenRathod** [comment]
@DavidRoy I have just implemented the search box, so it is working now.

**Comment by IanMiddlebrook** [comment]
@DavidRoy  Yes, search box looks fine.

But are we going to be getting the satellite map option as before? 
Could be difficult to draw some routes without that.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : google satellite layer has been added to the Site Details page, for both Site and Section maps. Are you happy to close?

**Comment by IanMiddlebrook** [comment]
Yes, thanks
