### ISSUE TITLE
Problems with Creating a New Site

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#189]
Hi @DavidRoy  @Gary-van-Breda ,

It doesn't seem to be possible to fully test the setting up of a new transect at the moment.

There is no map at all on the Site details page, and even if I enter a grid reference, I'm not able to continue.

One thing that stood out is the 'Overall Length' box. This appears to be asterisked as an essential field to complete, but there is also a note to say that it will be calculated automatically? Presumably in this case, the box should be grayed out rather than marked as essential?

In any case, even if I complete all the essential fields, the 'Save' button does not work, I just get a 'no entry' sign on my cursor.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
I think this was a cache issue: I've cleared the caches, and it looks OK to me.  
@IanMiddlebrook could you try again.

**Comment by IanMiddlebrook** [comment]
thanks @Gary-van-Breda , I'm making some progress now, but it seems very confusing as to what is being saved or not.

I can set up basic site details, click save, and it takes me to Section 1 (slightly confusing that it takes you to the bottom of the page, rather than back to the top so that you can see where you are).
If I draw in Section 1, and click Save, it tells me it has saved the Section, but it doesn't move me on to Section 2, and when I look at the Section details, it has calculated the grid reference, but not the length.
If I work my way through additional sections, Saving as I go, and then click 'Finish', it tells me that my edits have not been Saved.
![image](https://user-images.githubusercontent.com/24699793/111333331-7dca5700-866a-11eb-8262-95b6a1c2894d.png)

This is very confusing.
If I then click on 'continue, but Save all changes first', it does something, but I don't leave the page. If I click 'Finish' again, it just comes back with the same message.
If I click 'continue without saving', then it takes me back to My Sites.
When I go back to look at the new site I've created, I see that it has saved the route, and it has calculated an overall transect length, but the individual sections do not have a Section length.

It's clearly not working quite right, but I can't really work out what the problem is.

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
Incidentally, I also updated another test route that I'd set up previously. I added an extra section. Again it didn't set a length for that  section, although it did appear to add that section to the overall transect length.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook New version deployed to test site to be checked.  This should fix the section/transect calculation issues and the "saved but not thinking its saved" issue.  
Note that the site/sections where the auto calculate length did not previously work will need **_all_** their iffy routes slightly tweaked and re-saved in order to redo the calculations.  
The only time the displayed tab should change is on the initial save of the site, when the first section route is displayed. All other saves should leave you where you are.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda , that's great.

All seems to work well for me now.

Thanks, Ian
