### ISSUE TITLE
Test UKBMS Drupal 7 site: my sites page has two [add site] buttons

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#19]
http://192.171.199.230/ukbms/mydata/sites-list

Has two 'Add site' buttons.  Should only have one at the bottom and should be labelled 'Add Transect'.
See live site for comparison: http://www.ukbms.org/mydata/sites-list

**Comment by Gary-van-Breda** [comment]
Fixed in form configuration. Button changed to match live CSS. Applied to both "My Sites" and "Branch Sites".
