### ISSUE TITLE
UKBMS.org website homepage recording method link appears to go to a placeholder page

### ISSUE THREAD

**Issue by colinharrower** [BiologicalRecordsCentre/UKBMS-online#190]
The recording method link in the text on the home page seems to go to a methods page url (https://ukbms.org/methods) but the content on that page seems to be placeholder (a copy of the home page but without the social media pane on the right). Should this link go to the same methods page as the methods page accessible from the get involved drop down (https://ukbms.org/methods-recording-butterfly-transects), or is the content for this page still to be created?

**Comment by BirenRathod** [comment]
@colinharrower & @DavidRoy This has resolved now. It is now ukbs.org/methods
