### ISSUE TITLE
UKBMS.org website WCBS page guidance and resource link appears to go to a placeholder page

### ISSUE THREAD

**Issue by colinharrower** [BiologicalRecordsCentre/UKBMS-online#191]
The guidance and resources link in the text on the WCBS page (https://ukbms.org/wider-countryside-butterfly-survey) goes to a url https://ukbms.org/guidance which appears to be a placeholder page (a copy of the home page without the social media pane). Should this link go to the same url/page as the link from the photo on the right hand site of the WCBS page which goes to the url https://ukbms.org/guidance-recording-forms which does seem to have guidance and resources content, or is there supposed to be different content for this link that is still to be created?

**Comment by BirenRathod** [comment]
@colinharrower & @DavidRoy The URL of guidance link changed to guidance-recording-forms. This will resolved the issue of the link reference on ukbms website.

@DavidRoy if you have referenced this link ukbms.org/guidance externally then I recon, I should amend all guidance-recording-forms link to guidance. do you want me to do that? let me know.

**Comment by DavidRoy** [comment]
I don't think we have used this url externally.  Closing now and will create new issues if any problems reported
