### ISSUE TITLE
Site details link from UKBMS.org version of site map going to pantheonsite.io version of site

### ISSUE THREAD

**Issue by colinharrower** [BiologicalRecordsCentre/UKBMS-online#192]
Clicking on the site details link for a site displayed on the site leaflet map on the sites page (https://ukbms.org/sites) is currently directing you to a site details page on the patheonsite.io version. Should the site details link on the live site take you to live site version of the site details page, otherwise people can end up browsing the test version content after being taken there by that link (could be an issue if they have different content), without a way of getting back to the live server?

**Comment by BirenRathod** [comment]
@colinharrower & @DavidRoy The test URL has updated to live one now.

**Comment by DavidRoy** [comment]
Thanks
