### ISSUE TITLE
timeout on https://ukbms.org/my-sites

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#193]
This page does not load for me, nor when masquerading as other recorders. I get
The application did not respond in time.

**Comment by BirenRathod** [comment]
@DavidRoy I don't see that problem by masquerading as you. Of course I checked after I cleaned the cache.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Are you happy to close this as a duplicate of #207?
