### ISSUE TITLE
Unable to Remove Sites

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#194]
Hi @Gary-van-Breda @DavidRoy 

A recorder tried to set up a new transect site and made a bit of a mess. So a second site was set up. But I now see that it's not possible to Delete the first attempt - even for a Site Admin.

Could we please have a Delete button on the Site Details page that Admin can use to Remove a site from the database (as there was on the old website).

Many thanks,

Ian

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 

This issue is starting to become fairly urgent. There are now dozens of new sites that I need to remove from the system to avoid confusion. These are typically duplicate failed attempts to set up new routes by recorders struggling with the website (or failing to follow clear instructions!).

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : code change deployed to Test, for you to check. Just to re-iterate, the Test environment actually points to the Live warehouse: if you use Test to delete a site it will be deleted on Live.  
The "Delete site" button is at the bottom of the main "Site Details" tab, coloured red. It is visible only on existing sites (it won't appear when creating a new site), and is currently only available to supermanagers.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda , that 's working well on the test site.

Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : This is now deployed to Live

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 

Tried this on live, but just met the circle of doom.
On the test version, if I click on Delete, I get a warning message pop up. when I click Yes it proceeds to delete the site.
No warning message is popping up on the live site.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : I reset the Javascript code cache and checked - I'm getting the warning message when I press the button. The deployment button on the environment gives the option of clearing the caches, but it obviously isn't working as it should... I'll make a note to do this manually from now on.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda  that's working OK now

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda @DavidRoy 

This issue seems to have reappeared now.
Each time I try to Delete a Site I'm greeted by the eternal circle of doom.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : can you let me know a couple of sites that you want deleted, so that I can test this? Thanks.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
Any site with '(ignore)' in the site name - e.g. site ID 256903  or 262106

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Code fix applied and deployed to Test for review. I've deleted 2 of the 'ignore' sites, during my testing, but not all of them.
This may take a few seconds depending on the number of walks associated with the site.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 

Yes, this is working for me.

**Comment by Gary-van-Breda** [comment]
Code deployed to Live. Checked - deleted an 'ignore' Transect successfully.
Closing Issue
