### ISSUE TITLE
Old links in Raw Data tables

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#195]
Hi @Gary-van-Breda @DavidRoy 

I just tried to go to a Walk Data entry page from the link on the Annual summary - Raw Data table.

The link still seems to point to the development site:
https://test-ukbms8.pantheonsite.io/input-data?sample_id=8824575 

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : should be fixed now

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 

Yes, seems to work well now. I notice that the link appears to have an extra slash after ukbms.org, 
eg. https://ukbms.org//input-data?sample_id=8167074

but the browser just removes that and still finds the page.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : I've removed the additional slash. Are you happy to Close?
