### ISSUE TITLE
Highlighting row and column when entering data

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#196]
Hi @DavidRoy @Gary-van-Breda 

A comment from a user this morning when entering butterfly counts - Walk Data Entry, second page:

_Previously when you were in a cell, the column and row were highlighted. So if you wanted to make sure you were on section 3 you looked up at the top of the column and the column heading you were in was highlighted.  I now have to go to the cell and follow up the column, taking longer and open to error._  

Could this feature please be instated on the new website?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Fix applied. Both Section number at top of the grid and the Taxon at the row start are highlighted for the currently focused cell in the species grid.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
Is this on test or live? I'm not seeing anything highlighted on the live site, in Chrome or Firefox.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Sorry - site caching issue. Can you try again?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda  Yes, working well on Chrome and Firefox now.

Thanks, Ian
