### ISSUE TITLE
active grid reference display when drawing route maps

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#197]
Hi @Gary-van-Breda @DavidRoy 

The next comment through from a co-ordinator:

_But what is lost from before is the ability to plot points on the map from grid references taken on the ground.
If this functionality is lost it will make drawing new routes more difficult – and inaccurate._

What he's referring to is the boxes at the foot of the route map in the old version that showed the actual grid reference of the cursor, as you moved it round the map. So, when drawing in the sections, you could align this with the grid references recorded on the ground when planning the route.
It would be good to see this again.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : are these OSGB or GPS Lat/Long?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 

My recollection is that they were OSGB, but displayed entirely numerically, rather than with letter prefixes.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : change applied and deployed to Test for review.
It now appears at the top of the map, next to the tool buttons on the sections map.
It will display in the same format as that selected for the main square grid reference, be that OSGB, OSIE or normal Lat/Long.
At the moment it displays 10 digits for the OSGB/OSIE, but this is a form config and can be changed easily.
Similarly, it displays Degrees/Minutes Lat/Long, but this is a form config and can be changed easily to degrees only or Degrees/minutes/seconds..

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
That looks good, but I can only seem to bring it up when I look at Section 1. It's not there when I move on to further sections?
I've looked at a few sites - all the same issue.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : fix applied for it only appearing on section 1: deployed to Test for review.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
Yes, that's working for me now on all sections.

**Comment by Gary-van-Breda** [comment]
Code deployed to Live. Checked - Map reference appears on multiple section maps, S1, S2 etc..
Closing Issue
