### ISSUE TITLE
New sites not being added to My Sites for Branch Co-ordinators

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#198]
Hi @DavidRoy @Gary-van-Breda 

A few branch co-ordinators have now tried setting up new transects. They each seem to be having some issues, but one main problem is they have no idea if the new transect has Saved when they finish, because the site doesn't appear on their Site List.

Could you please arrange that any new transect set up by a Branch Co-Ordinator is automatically added to their list of Sites (as it did before).

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook 
New panel added to bottom of first page when adding a site, visible for branch managers only. Contains 2 checkboxes, one allowing the site to be allocated to the user as a normal user, and one as a branch manager: they get to choose.  
Deployed to Live.

**Comment by IanMiddlebrook** [comment]
That's great - thanks
