### ISSUE TITLE
Invisible Add Transect button on My Sites page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#199]
Hi @DavidRoy @Gary-van-Breda 

Hopefully an easy one to rectify. 
The 'Add Transect' button on the 'My Sites' page is virtually invisible - white text on a pale grey background. Could this please be made more visible (eg. like the 'Run Report' button).

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : I've added extra classes to the link in the table footer for "My Sites" and "Branch Sites": this should make the look of the link consistent across both pages, and more visible.

**Comment by IanMiddlebrook** [comment]
That's great - thanks @Gary-van-Breda
