### ISSUE TITLE
Test UKBMS Drupal 7 site: captcha missing from login page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#20]
http://192.171.199.230/ukbms/mydata/user/login should have Captcha implements as for live site:
http://www.ukbms.org/mydata/user/login

**Comment by Gary-van-Breda** [comment]
Captcha has been configured on http://test.brc.ac.uk/ukbms/mydata

**Comment by DavidRoy** [comment]
thanks
