### ISSUE TITLE
Wrong link in side menu

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#201]
Hi @DavidRoy @BirenRathod,

If you go to https://ukbms.org/get-involved 
the box down the right hand side for Standard Survey Methods has the wrong link. It points to https://ukbms.org/methods-recording-butterfly-transects but that just goes back to the welcome page. It needs to point to https://ukbms.org/methods 

I'm afraid the same problem applies to all the pages in that group, which have the same set of boxes down the right hand side (/wider-countryside-butterfly-survey , /guidance-recording-forms , /regional-co-ordinators , /health-safety)

I guess the methods page should look the same as those other pages, but it doesn't have the boxes down the right hand side.

Sorry, I don't know how to rectify this.

The link in the drop down menu is fine.

Thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook
It has implemented now.

**Comment by IanMiddlebrook** [comment]
That's great - thanks @BirenRathod
