### ISSUE TITLE
Confidential Site showing in overall Sites map

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#202]
Hi @DavidRoy 

A recorder contacted me yesterday asking for his transect site to be made 'confidential' so that it couldn't be seen by the public on here: https://ukbms.org/sites .
I marked the transect (Sutherland Beck) as confidential yesterday, but it still appears on the Sites map today.

Is there much of a delay in the Sites map picking up changes to confidentiality?

Thanks, Ian

**Comment by DavidRoy** [comment]
@burkmarr could you pick up this one too please

**Comment by burkmarr** [comment]
The report didn't check for site confidentiality. I've amended report and will post here when implemented on live site.

**Comment by burkmarr** [comment]
The report is now updated to exclude confidential sites. @IanMiddlebrook - Sutherland Beck is no longer shown (and neither should be any other confidential sites - or those you subsequently mark as confidential).

**Comment by IanMiddlebrook** [comment]
That's great - thanks @burkmarr
