### ISSUE TITLE
Grid references for WCBS squares

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#204]
Hi, please can we restrict editing of grid references on all WCBS-BC and WCBS-BBS squares to admin users only regardless of whether the sites have records or not? This applies to just WCBS, not Transects. I have a feeling this was resolved before, but I've just found that squares with no records still allow normal users to edit the grid reference (problem being that recorders may be tempted to change the location of their square). Thank you, Megan.

**Comment by Gary-van-Breda** [comment]
@MeganLowe : changed so only those who can create WCBS squares can modify the square grid reference.
Fix applied to Test for review.

**Comment by MeganLowe** [comment]
Looks good to me @Gary-van-Breda Thank you.

**Comment by Gary-van-Breda** [comment]
Code deployed to Live.
Closing Issue
