### ISSUE TITLE
Section Grid Reference and Length

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#206]
Hi @DavidRoy @Gary-van-Breda 

A branch co-ordinator has just set up a new transect. It seemed to be successful - the route map looks fine with 10 sections.

However, looking at the Section Details - it has not calculated the individual section grid reference or length.

All the section Grid References just show the same Grid Reference at the overall Site, while the Section Length fields are just blank.
This despite having calculated the overall transect length.

The Transect is called Whitchurch (Mill-trail)

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @DavidRoy 
I've identified the coding issue that caused this, and have fixed and deployed it. I now need to do the data fix.
FYI, it was storing the length in a "Transect length" attribute associated with the section, instead of the "Section length" attribute.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @DavidRoy I've applied the section length data fix now as well: it affected 114 sections in total. All sections of Whitchurch now display a section length.
Still to Do: the Grid ref data fix.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @DavidRoy
I've applied a code fix for the section Sref issue, and also applied the data fix.
  
This is now ready for you to check it is fixed to your satisfaction....
