### ISSUE TITLE
WCBS-BC data entry

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#208]
Hello, found another issue (sorry...). Having a problem with WCBS-BC data entry on the My Walks page. When I select a date in the calendar it takes me back to the homepage instead of the data entry form. Seems to work fine with WCBS-BBS and Transects so it's only WCBS-BC that it won't let you enter data for. Thanks, Megan

**Comment by Gary-van-Breda** [comment]
@MeganLowe : custom URL on BC walk input page was omitted, now fixed, so this is now working.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda
