### ISSUE TITLE
Data Entry Problems on different Browsers

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#209]
Hi @DavidRoy @Gary-van-Breda 

I'm starting to hear of a few problems with data entry - possibly browser related?

One recorder, using Microsoft Explorer, got through the first Walk Data Entry page, but was unable to bring up any sort of species list on the second page. I managed to help him progress using Google Chrome instead.

Another recorder is unable to proceed beyond the first Walk Data Entry page. He is using Microsoft Edge:
_I couldn't get beyond the screen requiring start/end times, etc. I input the start time using 24 hour format, as requested. It immediately turned it into 12 hour format. When I eventually clicked on next, I got the red message shown in the screen shot asking for %S. I've no idea what this means. Can you help? Also, do the two hyphens after the hour and minute fields mean anything?_
![2021-03-31](https://user-images.githubusercontent.com/24699793/113134355-987aff00-9218-11eb-928a-90fb1da8c00a.png)
![2021-03-31 (1)](https://user-images.githubusercontent.com/24699793/113134359-99ac2c00-9218-11eb-90d0-75e13e0e7482.png)
Screenshots attached.

I'm having no trouble with Microsoft Edge - Version 89.0.774.63 (Official build) (64-bit).
But I wonder if it's to do with time settings on his computer?

Any help appreciated.

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
Hi, additional comment from the second user above:
_Actually, I was using Mozilla Firefox. I have Edge available [89.0.774.63 (Official build) (64-bit)]. When I log in using Edge, I still get the same 6 date format hyphens and it changes my input to 12 hour format, but it does at least accept my entry and let me proceed to inputting my sightings._

**Comment by IanMiddlebrook** [comment]
Hi, Just to confirm the first point - I've had feedback from another user of Microsoft Explorer who cannot get a species list up on data entry.

**Comment by IanMiddlebrook** [comment]
Hi, Another report of the second problem:
_I use Mozilla Firefox as the default on my laptop. I then tried Microsoft Edge. Same problem. 
Moved to the wife's desktop, which uses Bing - problem solved!_

Obviously not clear whether it was the change of browser or change of computer that solved  the problem.

**Comment by DavidRoy** [comment]
Bing is a search engine, not a browser. 
@IanMiddlebrook can you test on FireFox please

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy 
It works OK on Firefox for me. 
I suspect it's an issue with time settings on each computer? But that's just a layman's guess!
Thanks, Ian

**Comment by DavidRoy** [comment]
shall we close this issue as it could eat up a lot of time resolving?

**Comment by IanMiddlebrook** [comment]
Surely it needs to be resolved if several recorders are not able to enter their data!

**Comment by DavidRoy** [comment]
Sorry, yes.  I'd forgotten this was not an isolated issue.

**Comment by Gary-van-Breda** [comment]
Yes, this is a computer settings problem.   
As discussed in " https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time ", the input field takes its 12/24 hour setting from the (local) operating system: as can be seen in the bottom right hand corner of the screenshots above, the time is being displayed in 12 hour mode on the computer.  
**IMPORTANT: even though the time is being displayed in 12 hour mode in the input control, it is still stored as 24 hour.**  
  
There are 2 ways around this:  

- Get the users to set their local machine time setting to 24hour. They will need to restart their browser after doing any settings changes.
- Don't insist on the users entering in 24hour mode: change the instructions to let them know they can enter in 12hour mode, with the note that the extra 2 dashes after the time should be "AM" or "PM". We would need to change the language strings for the attribute titles, and give a more helpful helptext under it.

@IanMiddlebrook @DavidRoy : what is your preference?

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda @DavidRoy 
Surprising, as this wasn't a problem on the old website.
I don't use any other website that insists I change my local settings in order for them to work, and the second solution sounds a bit convoluted.
Is there no way this field could operate without taking its setting from the operating system?

I've added a note to the top of the page for now.

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 

There is also the issue of no species list appearing in Microsoft Explorer. Should I separate  this one?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook Can you confirm the operating system and IE version of the person who is having problems?  
  
With the upgrade to Drupal 8 from 7, we have got a more up to date version of the IForm Library within which the ukbms forms are built. This has seen development to bring it in line with HTML5: so the control for entering the time is no longer a text field with an enforced format (which was the case in the old site), but now uses the new HTML5 time field type - this should provide the same time interface across all websites which use it, making it more familiar to the user. It does have this downside - there does not seem to be any way to override the operating system setting.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda - not sure which of the problems you're asking about, but it's not just one person, it's several (for both problems).

For the problem with species lists not appearing at Data Entry, the first few people who had the problem were all using Internet Explorer. I've just opened this up and had a go. Sure enough, it did not give me any species list to enter data. This is my version:
![image](https://user-images.githubusercontent.com/24699793/113870278-94675800-97a9-11eb-807e-19382d5ac100.png)
I also noticed that the search box for adding new species to your list didn't work, and was much smaller than
However, I should also note, the most recent person to complain of this problem said they were using Chrome (now resolved).

For the problem with the start/finish time fields, these users tried a range of browsers and had problems with all of them. However, since I put up the explanatory note on the data entry page about entering AM or PM, I've not had any more problems reported.
I will just add here, that when I just tried Internet Explorer, the start/finish time fields were not populated with the colon - I had to type the colon myself. not a problem, but it clearly behaves differently.

Hope that helps.

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda,

Sorry, have just realised another recorder with this problem of no species list is using a Mac:
_I signed in (or my mac did) and entered the walk details OK, however, when it came to entering data I could not further than the position shown on the screen shot - no way to display the species and then enter data._ 
_My operating system is OS X 10.9.5
 and I’m using Safari as my browser._

**Comment by IanMiddlebrook** [comment]
Just quickly - the Chrome user who reported no species list has now been successful, so it's down to Explorer and Safari.

**Comment by IanMiddlebrook** [comment]
The latest user to have no species list - _Microsoft Explorer ( Windows 8.1)_ - has resolved using Chrome.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @DavidRoy Fix applied to live to remove what is know as an "arrow function call": this is a modern Javascript innovation that IE can't handle, and possibly Safari as well.  
Whilst I have checked IE on my machine, and that is working OK, I have not been able to check Safari. Could you arrange for the user to try again?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda  

Has this fix definitely gone live? I've tried again in IE, cleared cookies etc, but still can't bring up a species list.
I've asked the Safari user to have another go.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook Yes - I've just had a look at it, and it is definitely there: can you try again?

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda  - yes, it's worked this time.

Many thanks, Ian

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda  The Safari user has now got back to me and has been successful.

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : is there anything outstanding on this issue now?

**Comment by IanMiddlebrook** [comment]
@Gary-van-Breda  Only if a neat solution can be found for the 12 hour display problem, but that's not critical.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
I can't see one: @johnvanbreda - do you have any thoughts?

**Comment by johnvanbreda** [comment]
@Gary-van-Breda I wasn't aware that the time_input control has changed due to the adoption of HTML5 for the date_picker. How exactly is the time input control being added to the page, and which prebuilt form is this for?

**Comment by Gary-van-Breda** [comment]
Sorry, my mistake - this is specific to this form: @johnvanbreda please ignore. The time fields are specifically changed in the form: I'll investigate further.

**Comment by Gary-van-Breda** [comment]
The code to switch the time input types to HTML5 compliant (type="time") has been in place since June 2016 (this was done as part of the requirements to not have to type the colon). This functionality has not changed since the previous D7 site, and is also the case for EBMS/ABLE. Are we OK with it?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
I've not had any more comments from recorders on this issue since I added a note to the data entry form 13 days ago.
So I'm happy to close it now.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Note to @johnvanbreda : the timeentry code (time_input control) suffers from the $.browser issue. We re not using that here.
