### ISSUE TITLE
Not able to see entire Annual Summary table - no scrolling

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#210]
Hi @DavidRoy @Gary-van-Breda 

There appears to be no means of scrolling horizontally when looking at the Annual Summary Table, and it doesn't all fit onto the screen, so it's not possible to see the totals in the right hand column.
See screenshot from recorder:
![Screenshot (5)](https://user-images.githubusercontent.com/24699793/113150454-01b83d80-922c-11eb-97d9-0eef2b5c4e7d.png)

I've tried this in Microsoft Edge and Google Chrome with the same result. True of Summary Table, Estimate Table and Raw Data.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Fix applied and deployed to Live.
A scroll bar has been added to the bottom of the viewport.

**Comment by IanMiddlebrook** [comment]
thanks @Gary-van-Breda  - able to scroll in Chrome, Edge and Firefox
