### ISSUE TITLE
Permissions on Reporting pages

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#213]
Hello, please can we ensure that 'normal users' only have access to download their own data from the reporting pages (annual summary etc) as per the old website. At the moment it seems a 'normal user' can download any data from any site. Thanks, Megan

**Comment by Gary-van-Breda** [comment]
@MeganLowe : I've switched off the Form config parameter which allows branch managers and normal users to see the entire location list in the Annual summary page.

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda I think it's ok for the branch managers and normal users to see the entire location list (minus the 'confidential' sites), but it's what they can download that's the issue. I'll try and explain what I mean per user type below:

Normal Users:
In the 'filter by recorder' drop down list they should be able to filter by 'My Data' and 'Combine data for all recorders'. In the 'filter by site' drop down they can 'combine data for all my sites', 'combine data for all sites', 'my sites', and all 'other sites' (apart from those marked as confidential). Under the downloads tab they should only be able to download their own data from the sites they are assigned to. @IanMiddlebrook may be able to remember which specific downloads were available to them in the past.

Branch Managers:
In filter by recorder they should be able to filter by 'My data', 'Branch data' and 'combine data for all recorders'. In the filter by site they can filter by: 'combine data for all my sites', 'combine data for all sites', 'combine data for all branch sites', 'my sites', and all 'other sites'. Under the downloads tab they should have permission to be able to download their own data and those from their branch area.

@IanMiddlebrook have I got this right?

Thanks, Megan

**Comment by IanMiddlebrook** [comment]
Hi,

I think the only problem here is with the downloads.

As I recall from the old website, when a normal user is looking at data from all recorders, they should only be able to download the grids (Summary Grid, Estimates Grid, Raw Data Grid).
They should only have access to the other 4 downloads when they are just looking at their own data.

Branch Co-ordinators should have access to all downloads when looking at Branch Data, but they should only be able to download the 3 grids if they are looking at data from all recorders on sites outside their own branch.

**Comment by Gary-van-Breda** [comment]
@MeganLowe @IanMiddlebrook : I've applied a fix that should sort this out for both normal users and branch managers.  
I've also switched back on the the Form config parameter which allows branch managers and normal users to see the entire location list.

**Comment by IanMiddlebrook** [comment]
That's great, thanks @Gary-van-Breda
