### ISSUE TITLE
unable to download shapefile from My Sites

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#214]
Hi @DavidRoy @Gary-van-Breda 

A user has identified a problem downloading the shapefile from My Sites. I tried and the same thing happened. The error message is:

<_ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wfs/1.0.0/OGC-exception.xsd">
<ServiceException> java.lang.RuntimeException: java.io.IOException java.io.IOExceptionorg.postgresql.util.PSQLException: ERROR: invalid input syntax for integer: "" Position: 350 ERROR: invalid input syntax for integer: "" Position: 350 </ServiceException>
</ServiceExceptionReport_>

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : the reason is that there is no location type selected by default: whilst I figure out how to sort this, the work around is to select the location type in the filter (e.g. Transect), then re-run the report: the link should then work.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda, I've passed that on to the recorder.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : fix applied to footer definition, which removes the location_type_id filter from the download url if not provided.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda
