### ISSUE TITLE
Missing Map View for some WCBS-BC

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#216]
Hi, on the site details page for **some** WCBS-BC sites the map is missing completely (it doesn't appear on the site details page, or when selecting any of the sections under the route or section details tabs). I've attached a screenshot below of square SU1301 which seems to have this problem. For some sites the map appears fine, others are blank, but I can't work out what the common theme is. I haven't extensively tested the WCBS-BBS or Transects so not sure if this issue extends to them too - I've opened a few and they have all seemed fine. Please can someone take a look? Thanks, Megan.

![image](https://user-images.githubusercontent.com/64081219/114373870-f2fe4e80-9b7a-11eb-8260-c6cc9c508f19.png)

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda @DavidRoy @BirenRathod

Yes, this issue is definitely also happening on transect site details. I can't see a map on any of my Site Details pages, and the Norfolk Co-ordinator (Alan Dawson) has just said the same thing.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@BirenRathod @DavidRoy @IanMiddlebrook @MeganLowe
Related to #206: Fix applied to Live

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda  All my maps have reappeared, so looks resolved for me. 
@MeganLowe ?

**Comment by MeganLowe** [comment]
Looks good to me too. Thanks @Gary-van-Breda !
