### ISSUE TITLE
Issue with Saving Site Details pages

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#218]
Hello, I've had a recorder get in touch with a few bugs he has found when trying to edit/save the Site Details pages as follows:
- if making edits to just the box titled 'Notes on Land Use and Management' the 'Save' button is not enabled so you have to edit something else before the page gives you the option to click 'save'. This seems to apply to all sites regardless of whether a transect, WCBS-BC or WCBS-BBS. 
- he found that clicking 'Finish' and then 'Continue, but save all changes first' didn't actually save anything that he had edited on the Site Details pages. This was for a WCBS-BBS square but I've just tried a WCBS-BC and the same thing happens so could also be the same for transects.

Thanks, Megan

**Comment by Gary-van-Breda** [comment]
@MeganLowe Bugfix applied to Live.
Can you double check these, and if still a problem, could you let me know what type of machine the problem was observed on (PC, Mac, etc), browser being used, and an example site where you have the problem.

**Comment by MeganLowe** [comment]
Thanks!
