### ISSUE TITLE
Test UKBMS Drupal 7 site: All Sites page should allow option to filter by 'Location Type'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#22]
http://192.171.199.230/ukbms/mydata/all-sites

should provide option to filter by location-type.  See live site equivalent:
http://www.ukbms.org/mydata/all-sites

**Comment by DavidRoy** [comment]
Also, applies to Visit summary http://www.ukbms.org/mydata/visit-summary

**Comment by Gary-van-Breda** [comment]
Complete list of forms to be check for this:
MY Sites, My Walks, Branch Sites, Branch walks, All Sites, Annual summary, Visits Summary.
Also need to set up the Year ploat and Section plot forms, and the data upload form

**Comment by DavidRoy** [comment]
Location Type should be restricted to UKBMS location types only: 
Transect, WCBS-BBS and WCBS-BC

All-sites page dropdown shows full set of Indicia location types
