### ISSUE TITLE
Not saving User Assignments

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#220]
Hi @Gary-van-Breda 

On the Site Details page, User Assignments tab, if I make any additions or deletions to the User assignments, the Save button remains grey, although the page heading shows _User Assignments (Edited)_.
If I click Finish, it tells me I have unsaved changes, but if I click 'continue and save the changes', it doesn't actually save the changes.

So I'm not able to save any new assignments in this way. 

A Branch Co-ordinator has just contacted me with the same problem, and they have no other means of making user assignments.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Javascript caching issue following fix for #218 deployed yesterday: Caches cleared, and tested.
@IanMiddlebrook : can you have another go?

**Comment by IanMiddlebrook** [comment]
All good, thanks Gary
