### ISSUE TITLE
Section Sun % disappearing

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#221]
Hi @Gary-van-Breda 
Sorry, I'm sure this issue came up recently and was resolved, but it's come back and I can't find the original issue.

A user (Tony Goddard) has reported entering sun% values for each section on the Walk Data Entry page, but when he goes back to that page the values have disappeared.

The walk in question is https://ukbms.org/input-data?sample_id=14288883 
I can see that the values must be saved on the database, because the raw data table and sample downloads give an average sun% of 81.25, but the values are now blank on the walk data entry page. 

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Originally raised as part of #212

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : can you confirm whether this is still a problem? I haven't done anything to fix this, but it looks to be working OK now.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
No, it doesn't seem to be a problem any longer. I'll close.
