### ISSUE TITLE
Species Summaries showing contradictions

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#222]
Hi @DavidRoy @BirenRathod

There seem to be some problems with the species summaries on the website, with lots of contradicting statements over species trends, as well as outdated trends.

Eg. Adonis Blue https://ukbms.org/species/adonis-blue shows:
_Status since 1979 is **Rapid increase** with a **decrease** of 134.0%_ - is it increasing or decreasing?
_Status over the last 10 years is Stable with a **increase** of **-47.1%**_ - is it increasing by a negative value?

It looks like there is a default trend of decrease, decrease, increase, for the long-term, 20-yr and 10yr trends respectively, regardless of the actual trend.
I also think these figure come from 2017, rather than 2020.

Thanks, Ian

**Comment by DavidRoy** [comment]
@marcbotham - can you liaise with @BirenRathod to update this?

**Comment by marcbotham** [comment]
I already have been but I still haven’t had anything back about the summaries. The plots I updated after some toing and froing as upload didn’t work to start with, but I can’t do the summaries unless I do them all individually. I have provided Biren with a csv of the relevant data and will email him again to make it sound more urgent ☺

**Comment by DavidRoy** [comment]
thanks Marc.  @BirenRathod - we'll need to update this data every year so can you work with @marcbotham to provide a solution that does not involve a lot of manual updates

**Comment by BirenRathod** [comment]
@DavidRoy & @IanMiddlebrook  yes, I'm already started working on it.

@marcbotham I will send you upload csv procedure tomorrow.

**Comment by BirenRathod** [comment]
@marcbotham Although, I mentioned to send you tomorrow, I finished testing data and fields format in file, so I sent you today. Please check your email.

**Comment by marcbotham** [comment]
Thanks Biren.

Have created the csv file following the template and then followed your instructions but it hasn't worked I'm afraid. The error message suggests to me that the formatting of the columns might not be what it is expecting for the website? I've emailed you separately with a copy of the error message

**Comment by BirenRathod** [comment]
@marcbotham I have emailed you the problem, so please try again.

**Comment by marcbotham** [comment]
working on it now, thanks Biren

**Comment by marcbotham** [comment]
This has now been sorted. Thanks Biren. We have slightly altered some the generic text which was a hangover from old website and doesn't automatically update e.g. a decrease of, an increase of.  Have simply called it a change of, otherwise we have to go in every year for every species and change when and if the trends change. We did this very quickly so if you have a better suggestion for the working please let me know and we can change it again but wanted to get the stuff up and running so it is at least factually correct :)

**Comment by IanMiddlebrook** [comment]
Thanks for this @marcbotham @BirenRathod
