### ISSUE TITLE
List of 'Common' species on Data Entry page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#223]
Hi @Gary-van-Breda @DavidRoy 

A co-ordinator has commented on how limited the 'Common' species list is, when selected on the data entry page.

I must admit I hadn't realised how short this list was, and don't remember it being quite so short before (but I never used it, so can't be sure).

There are 12 species on the 'common' list - missing things like Small White, Green-veined White, Holly Blue, Small Tortoiseshell, Comma, Small Heath.

Would it be possible to add these species to that list?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@DavidRoy @IanMiddlebrook : The current common list is:

-      Polyommatus icarus
-       "Inachis io",
-       "Pararge aegeria",
-       "Lycaena phlaeas",
-       "Gonepteryx rhamni",
-       "Pyronia tithonus",
-       "Aphantopus hyperantus",
-       "Maniola jurtina",
-       "Vanessa (Cynthia) cardui",
-       "Vanessa atalanta",
-       "Anthocharis cardamines",
-       "Pieris brassicae",
-       "Common Blue"

Is there a definitive list of which taxa you'd like?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda @DavidRoy 
I'd go with this list:

Brimstone
Large White
Small White
Green-veined White
Orange-tip
Small Copper
Common Blue
Holly Blue
Small Tortoiseshell
Peacock
Comma
Speckled Wood
Marbled White
Gatekeeper
Meadow Brown
Ringlet
Small Heath
Red Admiral
Painted Lady

Should be enough to get most new sites started.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : New common species list deployed to test for review (all 3 surveys - Transects, WCBS BBS and BC).
This implements a new way of indicating the inclusion on the list: there is now an attribute on the taxon with a Yes/No value (UKBMS Species list only at the moment) which can be changed for individual species in the warehouse front end, rather than relying on form configuration.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
Common species list looks OK to me

**Comment by Gary-van-Breda** [comment]
Deployed to Live. Checked.
Closing
