### ISSUE TITLE
Flag to indicate all data entered for year

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#226]
Hi @DavidRoy @Gary-van-Breda 

I'm just putting this here as a marker, since it crops up from time to time. Some co-ordinators have suggested it would be useful to know when a recorder has completed their data entry for the year.

I guess it would be simple enough to put a flag below the calendar on 'My Walks' that a recorder can tick when they've entered their last walk for a year.
The more complicated issue would be making that fact available to Branch Co-ordinators. I guess they would need to see a list of all users assigned to sites in their 'Branch', along with their flag status for any given year.

Also, when they tick the box to say they've entered all their data, could we display a thank you message :-)

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Code deployed to Test site for review.

A Block has been added after the "My Walks" grid to allow users to set their status. (This is also visible as a field on their normal Drupal account/profile page).

Branch Coordinators have an extra link under the "My Data->Walks" Menu, called "Branch Users" which lists the recorders assigned to sites which the currently logged in user is assigned at Branch level. This includes a Yes/No as to whether the recorders have finished for the year.

Can you have a think about the message you wish to display as a "thank you"?

### Reset each year:  
Log in as an admin user:
Edit the field: /admin/config/people/accounts/fields/user.user.field_finished_for_year  
Ensure the Default value is unchecked.  
Ensure the "Overwrite existing..." is checked.  
Save the settings.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
The list of Users on the Branch Data page seems to be a bit random. Would it be possible to sort the list by Last Name, to make it easier for Co-ordinators to check through?

message:
"Thank you for confirming you have submitted all your data for the current year. 
This flag will be reset before the next season begins."

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : the people list on the branch users page has been changed to sort by last_name, and the message has been updated.
Deployed to test for review.

**Comment by IanMiddlebrook** [comment]
Looks good - thanks @Gary-van-Breda

**Comment by Gary-van-Breda** [comment]
Deployed to Live: checked - OK.
Closing
