### ISSUE TITLE
issues with adding a new name into the recorder field at data entry

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#227]
Hi @Gary-van-Breda 

When a User is entering data for a different recorder, they can enter their name into the recorder box at data entry.

However, if the name was not already on their drop down list (names they've used before) this can cause issues.

If you use 'tab' to get to the next field, the recorder name reverts to the name at the top of the drop down list.

If you don't use tab, and just click in another field, the new name sticks, but the drop down box remains in view, obscuring fields below.
![image](https://user-images.githubusercontent.com/24699793/117632830-5e850d00-b175-11eb-97e8-2506ac2330c1.png)

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @johnvanbreda: can you copy the new [ukbms_recorder_names.xml](https://github.com/BiologicalRecordsCentre/indicia-reports/blob/master/reports/projects/ukbms/ukbms_recorder_names.xml) to the appropriate reports directory on Warehouse1? Thanks.

**Comment by BirenRathod** [comment]
@Gary-van-Breda  I have pulled this report on live warehouse now.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Fix deployed to Test for review.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
Yes, that looks to be working better now.

**Comment by Gary-van-Breda** [comment]
Deployed to Live. Checked.
Closing.
