### ISSUE TITLE
Default Site Type

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#228]
Hi, just wondering whether it is possible to change the default settings so the Site Type drop down boxes on the pages All Sites, Branch Sites, and My Walks defaults to the site type the user last selected? It's been raised by a WCBS co-ordinator, but I'm also starting to find it frustrating to have to keep waiting for it to reload WCBS after defaulting back to Transect. Thanks, Megan

**Comment by MeganLowe** [comment]
Hi @DavidRoy, I would like to bump this up the priority list please. The default to 'Transect' is becoming an issue on the 'My Walks' data entry page. Recorders enter a count for WCBS, select 'Finish and Return to Walk List' and it takes them back to a blank calendar as the My Walks page has defaulted back to Transect again. This is leading to confusion, duplicate submissions and new transects being set up in the place of WCBS squares. I'm going to see what I can do on the page itself to make the Site Type drop down menu more clear, but it would be a huge help if when you select 'Finish and return..' it took you back to the My Walks page set to the site type you have just entered data for. Hope that's possible. Thanks very much, Megan

**Comment by DavidRoy** [comment]
@Gary-van-Breda is this simple to address

**Comment by Gary-van-Breda** [comment]
The pantheon environment (now) requires all cookies names to be prefixed with the string "STYXKEY" in order to be accepted.  

@MeganLowe : Code change deployed to Test for review - interconnected pages are My Walks, Branch Walks, My Sites, Branch Sites, All Sites, Annual Summary, Section plot and Year plot.

**Comment by Gary-van-Breda** [comment]
This has been pushed through to Live. I have configured it and checked on Live, and it looks good to me.
Note that the "Finish and return" was addressed as part of #259 
Closing
