### ISSUE TITLE
Test UKBMS Drupal 7 site: file downloads from Annual summary page do not work

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#23]
Example:
http://192.171.199.230/ukbms/mydata/annual-summary?caching=false&locationID=41305&year=2016

Goto Downloads tab.  Select file to download.  The file explorer opens as expected, with right suggested filename.  But the file does not download.  Gives error message against filename of 'Failed - No file'.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : new code is requesting the creation of a directory - "sites/www.ukbms.org.mydata/files/reportsDownloads/"
Can you do this? This is where the reports to be downloaded will be stored. It should be writeable by the webserver - probably the same permissions as the other subdirectories at the same level.

Can we also have a similar directory created for EBMS? "sites/www.butterfly-monitoring.net/files/reportsDownloads/"

**Comment by BirenRathod** [comment]
@Gary-van-Breda : Both sites have got this folder now.

**Comment by Gary-van-Breda** [comment]
@DavidRoy - file downloads are now working on the D7 site Annual summary.
