### ISSUE TITLE
Route Disappearing on Site Details pages

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#230]
Hello. A minor issue, but I've noticed that when on any Site Details page if you go to any of the other tabs (i.e. site details, contact details etc) and return to the Site Details tab the route disappears off of the map and the only way I've found to get it back is to refresh the page. Not sure if there is a little bug in there... Thanks, Megan.

**Comment by Gary-van-Breda** [comment]
@MeganLowe Can you give me the following details:

- Browser and Operating system
- User you are logged in as
- Example site this happens to you with,
- The exact steps you follow to get this to occur.

Thanks

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda this doesn't seem to be an issue anymore so will close. Thanks, Megan
