### ISSUE TITLE
Adjust layout of Section Route page for setting up new transects

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#231]
Hi @Gary-van-Breda 

A lot of recorders are getting into a mess when setting up new transects because, after drawing a section route, they are clicking on 'Insert Section' rather than going to the Next section. Some are also clicking on 'Delete Section' when they go wrong, rather than erase vertex, or just starting again.

All this despite the guidance notes and the additional text on the Section Route page.

I think this is because the Insert Section and Delete Section buttons are quite prominent at the top of the map, whereas the Prev/Next buttons have disappeared off the top of the page by the time you've drawn your route.

Could we move the Insert/Delete Section buttons somewhere more discrete (perhaps also make them red), and move the Prev/Next buttons to a more obvious position - perhaps also renaming them 'Previous Section' 'Next Section'?

Perhaps the explanatory text could be split, with the text about the insert/delete section buttons going below the map, and the to buttons going below that.
Then the Prev/Next buttons could replace them above the map?

Thanks,

Ian

**Comment by DavidRoy** [comment]
@Gary-van-Breda quite urgent (not crtical) as this is catching people out and taking up time to resolve

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @DavidRoy : Code deployed onto Test site ready for you to check.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 

That looks great - much clearer - no more excuses to mess up!

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Deployed to Live, Caches reset, and checked: looks OK.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda  looks good to me
