### ISSUE TITLE
Odonata Recording on WCBS-BC Form

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#233]
Hi, the Odonata recording form for WCBS-BC is not displaying any species when you type in the search box. Any Odonata species 'known to site' appear in the 'Other' species tab rather than Odonata. This seems to only be a problem for WCBS-BC as the Odonata tab for WCBS-BBS and Transect recording forms is functioning correctly. Thanks, Megan.

**Comment by Gary-van-Breda** [comment]
Form config error: it was trying to look up species list 235 (not available to this site) with a min ranking filter of 15, rather than the other way around.  
@MeganLowe Now fixed.

**Comment by MeganLowe** [comment]
Great thanks @Gary-van-Breda
