### ISSUE TITLE
changing years on My Walks page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#235]
Hi @Gary-van-Breda ,

On the My Walks page (and the Branch Walks page), it only seems to be possible to change years one at a time. I don't think this is what was intended, since there is a drop-down option, but this is not populating properly.

The drop-down box for the year only seems to populate itself with a range of years after you have clicked on the arrow, and loaded new pages, enough times to get to the year you want. Even then, the drop-down list won't go any further back without more clicking on the arrow (although you can short-cut to a year by changing the URL).

This is in contrast to the Annual Summary page where the drop-down box has all years available from the outset.

Many thanks,

Ian

**Comment by Gary-van-Breda** [comment]
Code change applied to re-instate the drop-down year control.
"My walks" provides list of years back to the earliest Walk uploaded by the person logged in.
"Branch walks" configured to display back to 1973 (mirrors the Annual Summary page limit).

@IanMiddlebrook : Deployed to Test: once you are happy I will push to Live.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
Yes, looks good to me.
Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Now pushed to Live. Changes confirmed as deployed.
Closing
