### ISSUE TITLE
Satellite Map required for Timed Counts

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#237]
Hi @Gary-van-Breda @DavidRoy 

A recorder has pointed out that Google Satellite map view is not available on the Timed Count Data Entry page.

This is quite critical for mapping remote sites with few (or no) standard map features in OpenStreetMap view.

Many thanks,

Ian

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda @DavidRoy @BirenRathod

further to this issue, it seems that there is now no map whatsoever available on the timed-count data entry page, so it's just not possible to draw a flight area and enter any timed-counts now. This may also connected to the loss of Google Satellite maps (issue #246 ) but could be something different. Nevertheless, the satellite map option is critical for timed-counts.

Thanks, Ian

**Comment by DavidRoy** [comment]
@BirenRathod can you look into this please

**Comment by BirenRathod** [comment]
@IanMiddlebrook Google Satellite map is back. 
There was a jQuery problem in date format. due to that map was not displaying correctly.

**Comment by IanMiddlebrook** [comment]
Hi @BirenRathod 
Where is Google Satellite view back? 
I don't see it anywhere on UKBMS.
Still no map of any sort in Timed Count data entry.
Still no Google Satellite in Site Details or Section Routes.

Thank, Ian

**Comment by BirenRathod** [comment]
Hi @IanMiddlebrook 
I attached screenshot of timed count age which shows google satellite map.
![image](https://user-images.githubusercontent.com/5941255/138689960-92d7c148-c20a-4d9e-ab42-730562a59d36.png)

**Comment by BirenRathod** [comment]
@IanMiddlebrook I don't what Google Satellite view back but I'm resolving other two issues of map on site details & section details.

**Comment by IanMiddlebrook** [comment]
thanks @BirenRathod 
I checked a few times this morning and there was still no map. 
So I've done my usual trick of going off to have lunch, and then it all looks good when I come back 😊.

Best wishes, Ian
