### ISSUE TITLE
Captcha issues for the colour blind

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#239]
Hi @BirenRathod ,

I had this feedback from a volunteer:

_I am red green colour-blind. The Captcha security for forgotten passwords which uses letters against a dotted background is really hard for me to use and I had to do it 4 or 5 times. Please can you change this?_

The captcha for logging in is simple arithmetic - perhaps we could also use that for requesting a new password?

Thanks, 
Ian

**Comment by BirenRathod** [comment]
Hello @IanMiddlebrook 
I increased the font size now.

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod  - I'm no expert on colour-blindness, but I'm not sure how much the font size will improve contrast between reds and greens?

**Comment by BirenRathod** [comment]
@IanMiddlebrook Same for me and I can't control the color produced by the module, so I increased the font size which should help .

**Comment by DavidRoy** [comment]
@BirenRathod can we switch to using the same captcha that is used for logging in.  This just asks for the answer to a maths problem

**Comment by BirenRathod** [comment]
@DavidRoy & @IanMiddlebrook I have changed that to math one but leave it captcha for registration page to image one.

**Comment by DavidRoy** [comment]
@BirenRathod I would prefer to use the math one throughout

**Comment by BirenRathod** [comment]
@DavidRoy It has implemented on all forms now.

**Comment by DavidRoy** [comment]
Thanks.  @IanMiddlebrook please close if resolved

**Comment by IanMiddlebrook** [comment]
Many thanks
