### ISSUE TITLE
Unable to download all data

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#240]
Hi @Gary-van-Breda @DavidRoy @BirenRathod

I'm trying to download the data so far this year (ideally 'occurrences', though summary or section level would be a start).

Unfortunately I'm getting a fatal error at each attempt: e.g.

_Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in D:\websites\warehouse\application\helpers\vague_date.php on line 768_

_Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in D:\websites\warehouse\system\libraries\drivers\Database\Pgsql.php on line 436_

I'm assuming this is something at the server end rather than local to me?

Would appreciate some help.

Many thanks, Ian

**Comment by BirenRathod** [comment]
@johnvanbreda or @Gary-van-Breda  Can you look into please? This doesn't seem problem of php memory limit as it is running on maximum limit. This could be due to not converting some data to particular data type.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : What is the limit set at for PHP? 128M is going to be too small...

**Comment by BirenRathod** [comment]
@Gary-van-Breda It is set to 128M which is recommended to perform number of processes on the server. This is per script size. So it can perform many scripts at once. 

Although, I have increased that to 512M, see if that makes different. Also, I need to see if server is not running its maximum limit after changing this. If that is the case then I will revert that back to 128M.

**Comment by IanMiddlebrook** [comment]
Hi @BirenRathod @Gary-van-Breda 
I did manage to download the Occurrences Table a few weeks ago after this change, but now I'm trying to get an update I get the following message:
_Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in D:\websites\warehouse\application\helpers\vague_date.php on line 831_

Any suggestions?

Thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook I have increased the memory, so should be fine by now but do let me know if that doesn't work.

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod 

Have managed to download the Occurrences table now.

Ian
