### ISSUE TITLE
Estimates table download

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#241]
Hi @Gary-van-Breda @DavidRoy 

Following a request from  couple of branch co-ordinators, would it be possible to create a further download which provides the figures displayed on the 'Estimate Table', so that it would be possible for them to download these figures for the whole branch in one go.
The key fields for the download would include:
Site Name, Week No., Species Name, Count, (and I guess an additional field which indicates whether that count is real or estimated).
Are the figures for these tables stored in a way which would make that download fairly easy to produce?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Report deployed to Test, available on Downloads tab of Annual Summary.
Note this is at a site level, so if produced for a "Combined" location option, there will be data for multiple sites in the report.
There have been some associated tweaks to the other 4 download reports, so it is worth double checking their contents as well.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
This seems to do the job.

**Comment by Gary-van-Breda** [comment]
Deployed to Live, and checked OK.
Closing
