### ISSUE TITLE
Error message on data entry form

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#243]
A minor issue, but the error message pictured below could do with re-wording. It appears when a user has forgotten to select which transect (or WCBS site) they are entering data for on the first page of the data entry form. Perhaps it could say "Please select site" instead?

![image](https://user-images.githubusercontent.com/64081219/131639109-aa1f3227-c398-487a-9cbe-60b4948471f6.png)

Thanks, Megan

**Comment by Gary-van-Breda** [comment]
@MeganLowe : Can you confirm this is still the case? I can not replicate it. Thanks.

**Comment by MeganLowe** [comment]
Hi @Gary-van-Breda, it seems to be working fine now, thanks.
