### ISSUE TITLE
Several pages unable to load - error messages

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#244]
Hi @BirenRathod @Gary-van-Breda 

Several pages are currently unable to load full details, with the pages showing Invalid responses received from Indicia Warehouse:

any Site Details page (eg. https://ukbms.org/site-details?id=2813 ) 
_Invalid response received from Indicia Warehouse. Array ( [result] => 1 [output] => [request] => index.php/services/data/sample?mode=json&deleted=f&view=detail&nonce=670d29d4c09d36f0683d633b3a611a78a397e9cc&location_id=2813&auth_token=02b1b89678ea173cb0047822f622bfdac8de27de )_

All Sites page ( https://ukbms.org/all-sites )
_Invalid response received from Indicia Warehouse. Array ( [result] => 1 [output] => [request] => index.php/services/report/requestReport?report=projects/ukbms/all_sites.xml&reportSource=local&mode=json&nonce=dd8f5f4f5db930a6eefaf520aca5f9966db9bdb4&auth_token=f11171c44c4c8e9e1c1c2656f51ec2589d6436dc&limit=2001&offset=0&wantColumns=1&wantParameters=1&wantCount=1¶msFormExcludes=["date_from","date_to","survey_id","locattrs","user_id"]&blank_code=no&location_type_id=777&date_from=&date_to=&survey_id=&locattrs=245&user_id=18532 )_

Section Plot (https://ukbms.org/section-plot)
_Invalid response received from Indicia Warehouse. Array ( [result] => 1 [output] => [request] => index.php/services/report/requestReport?report=library/locations/locations_list_exclude_sensitive.xml&reportSource=local&mode=json&nonce=dd8f5f4f5db930a6eefaf520aca5f9966db9bdb4&auth_token=f11171c44c4c8e9e1c1c2656f51ec2589d6436dc&website_id=27&location_type_id=777&sensattr=&exclude_sensitive=&locattrs=245&auth_token=f11171c44c4c8e9e1c1c2656f51ec2589d6436dc&nonce=dd8f5f4f5db930a6eefaf520aca5f9966db9bdb4&idlist= )_

Year by Year Plot (https://ukbms.org/year-plot)
Invalid response received from Indicia Warehouse. Array ( [result] => 1 [output] => [request] => index.php/services/report/requestReport?report=library/locations/locations_list_exclude_sensitive.xml&reportSource=local&mode=json&nonce=dd8f5f4f5db930a6eefaf520aca5f9966db9bdb4&auth_token=f11171c44c4c8e9e1c1c2656f51ec2589d6436dc&website_id=27&location_type_id=777&sensattr=&exclude_sensitive=&locattrs=245&auth_token=f11171c44c4c8e9e1c1c2656f51ec2589d6436dc&nonce=dd8f5f4f5db930a6eefaf520aca5f9966db9bdb4&idlist= )__

Thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook It has resolved now.

**Comment by IanMiddlebrook** [comment]
Brilliant - thanks @BirenRathod
