### ISSUE TITLE
Google Satellite maps missing

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#246]
Hi @BirenRathod @DavidRoy 

It looks like we've lost the Google Satellite views on the Site Details pages of the website. I guess related to the Drupal switch?

The option of Google Satellite is also missing from the Timed-Count data entry page. I'm fairly sure it was there before - certainly needs to be.

Many thanks,

Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook While I'm investigating the problem with Google Map, the page now displays with Openstreet map.

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy @BirenRathod 
This issue is becoming rather urgent - certainly the most complained about problem at the moment, with co-ordinators trying to draw up new transects for the new season.
The Satellite view is there somewhere, but only seems to appear in very few situations.

**Comment by BirenRathod** [comment]
@IanMiddlebrook This has now resolved.

**Comment by IanMiddlebrook** [comment]
Hi @BirenRathod 

Many thanks for making the Satellite maps visible again - that's great to see.

I suspect related to this - the default zoom level for the Site Details page now shows the entire British Isles. 
Previously the default zoom was, I think, as close as possible with the whole route in view. Is it possible/easy to return this setting?

Many thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook Zoom facility has been restored now. please close if you satisfy with it.

**Comment by IanMiddlebrook** [comment]
Hi @BirenRathod 

My comment relates to the default zoom level when you first arrive on a Site Details page.
For example, it now looks like this:
![image](https://user-images.githubusercontent.com/24699793/149736912-0d6ff228-f1e3-4812-8f80-4a677f7d34fc.png)
and I need to zoom in several times before I see anything meaningful.

Previously, it would would already be zoomed in to a suitable level.

Thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook Yes, that has resolved. you just need to clear cache to see that.

**Comment by IanMiddlebrook** [comment]
Aargh, sorry @BirenRathod , that always catches me out.

Many thanks, Ian
