### ISSUE TITLE
Error Messages on Annual Summary

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#250]
Hello, I'm having some trouble with the Annual Summary page. It won't let me filter by 'Branch Data' (filter by recorder option) for WCBS-BC and throws up two different error messages as follows: 

![image](https://user-images.githubusercontent.com/64081219/137492515-5e5113dd-9248-4638-8677-2b69847f839b.png)

![image](https://user-images.githubusercontent.com/64081219/137493069-2ca4428f-23d1-41b8-8331-77bda99a4245.png)

It seems to work fine if I masquerade as another Branch Manager so could just be a problem with my account?
Thanks
Megan

**Comment by IanMiddlebrook** [comment]
Hi Megan,

Even though you're a Site Admin, I noticed that you were not also flagged as a Branch Co-ordinator. I've update this, so the problem should have gone away.

BW, Ian

**Comment by MeganLowe** [comment]
Ah that explains it, thanks @IanMiddlebrook !
