### ISSUE TITLE
Order of fields on Site and Section Details pages

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#252]
Hi @Gary-van-Breda @DavidRoy 

Another issue which has occurred recently - perhaps since the switch to Drupal 9 - is that all the fields in the Site and Sections details pages are in a very strange order.

For Section details, it appears that everything below the Section Grid Ref, is in reverse order to what it was before.

For Site Details, I think everything between Site Code and Habitat is in reverse order, while at the bottom of the page, all the fields under Habitat are also reversed.

Thanks, Ian

**Comment by DavidRoy** [comment]
@BirenRathod can you look into this please

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook (@DavidRoy ) Fix applied and deployed to Test for review.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
That looks much better now.

**Comment by Gary-van-Breda** [comment]
Code deployed to Live. Checked - attributes appear in correct order on Site and Section tabs.
Closing Issue
