### ISSUE TITLE
Site Assignment page not working

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#253]
Hi @Gary-van-Breda @DavidRoy 

The Site Assignment page (https://ukbms.org/site-assignment) is no longer working as it should.
Loading up branch sites etc is fine, but trying to assign or unassign recorders by checking/unchecking the boxes just doesn't work. The tick appears or disappears, but then checking the Site Details shows that the sites are not being assigned (or unassigned) to the recorder.

I don't know if this will be similar to the previous problem with this page, dealt wish in issue #205 .

User Assignment is still possible through the individual Site details pages, but that is labour intensive for a new branch co-ordinator or WCBS champion who may need to be assigned to 50+ transects/squares.

Thanks, Ian

**Comment by MeganLowe** [comment]
Hi, the site assignment page is not working at all now. The 'search' button doesn't seem to activate anything and I can't get it to give me a list of all sites for a particular region. Please can you let us know when this may be fixed? - I have two new Champions starting this month so without the site assignment page I will need to visit 120 individual site details pages to assign them.. Thanks, Megan

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @MeganLowe Fix deployed to Test environment. Let me know if you are happy with it, and I'll push to Live

**Comment by IanMiddlebrook** [comment]
Forgive me @Gary-van-Breda , but I'm not sure where to find the Test environment. 
The only link I have no longer seems to be active: https://test-ukbms8.pantheonsite.io/ 
Could you send a link so that we can test?
Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook Following the Drupal9 upgrade, it is now held at https://test-brc-ukbms.pantheonsite.io/

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 

Yes, Site Assignment page looks to be working as expected on test environment. Good to go live.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Now pushed to Live. Changes confirmed as deployed.
Closing
