### ISSUE TITLE
Branch co-ordinator access

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#256]
Hi @DavidRoy @BirenRathod @Gary-van-Breda 

Happy New Year!

I've just returned to a barrage of emails from Branch Co-ordinators who can no longer see their branch data.
It seems all their permissions have disappeared over the break, and they can now only see their own data, no more than any other user.
No Branch sites, No Branch Walks, and no Branch options on the Annual Summary page.

Could we please get their Branch Co-ordinator permissions returned ASAP?

Many thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook The permission for branch coordinator has been implemented now. Sorry for trouble experienced by users.

**Comment by IanMiddlebrook** [comment]
Brilliant - thanks for sorting so quickly @BirenRathod 

Best wishes, Ian
