### ISSUE TITLE
Annual Summary page changes?

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#257]
Hi @DavidRoy @Gary-van-Breda 

It seems that some changes have recently been made to the Annual Summary page, which have made things more difficult for recorders and co-ordinators.

Firstly, under 'filter by sites', the 'Branch Data' option has been removed for branch co-ordinators. I realise this option had pretty much the same effect as 'combine data for all recorders', so perhaps this is deliberate, albeit confusing for co-ordinators, in which case we'll need to adjust their guidance notes.

Secondly, under 'filter by site', recorders and co-ordinators are no longer able to pull up the full list of individual sites to review their summary counts. Previously, under that filter, a co-ordinator would see a list with their own sites at the top, followed by their branch sites, followed by all the remaining (non-sensitive) sites. 

Thirdly, with a full year of data loaded in the table, it's not possible to see the full table beyond July/August, because the page doesn't scroll from left to right.

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
Hi, Further examination shows that the Annual Summary table is not distinguishing properly between 'data for branch sites' and 'data for all sites'. So a branch co-ordinator can choose 'combine data for all recorders', but then 'combine data for sites allocated to you as branch sites' returns exactly the same figures as 'combine data for all sites'. The figures reflect the latter option, despite not all sites being available to the co-ordinator in the drop down list.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Fixes applied and deployed to Test for review.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
This looks good and now displays all the correct data and relevant list of sites.

The only remaining issue is an error message that can pop up when you change the filter by recorder - usually if you switch back from a long site list to a shorter site list (eg. from 'combine data for all recorders' to 'my data'):

_The full location data set summary is either invalid for this recorder filter value, or you do not have sufficient privileges to see it.._

The message does not actually stop you viewing the data you've selected, but could be confusing for users.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook : I've removed the error messages, and put in defaults instead.
These messages were occurring when the selected location in the site filter was not in the location list associated with the new "filter by recorder" value.
The location defaults are now the "Combined" values appropriate for the "filter by recorder" value: if a user is chosen, then it is the combined sites for that user, similar for branch, and all locations when viewing all recorders' data.

Deployed to Test for review.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
The error messages have gone, which is great.

However, I'm not quite sure the selections are working exactly as you describe.

With 'combine data for all recorders', I looked at a single site (not one of mine) - all good.
I change to 'My Data' - it displays 'combine data for all my sites' - all good.
I change back to 'Combine Data for All Recorders', and it goes back to showing me data from that single site, rather than all sites - it has retained the locationID in the URL all the time I've been changing the recorder filter: 
https://test-brc-ukbms.pantheonsite.io/annual-summary?userID=4&locationID=2058&year=2021
https://test-brc-ukbms.pantheonsite.io/annual-summary?userID=all&locationID=2058&year=2021

I don't think it's a major problem, but just in case it's a quick fix.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook : I've dropped a tweak into Test, so that the URL should now keep up with the defaulted changes: it wasn't making the defaulted values persistent.
Ready for (hopefully?) a final review.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
Well it solved that particular issue, but I'm not sure it's quite there, unless I'm misunderstanding.

Here's my sequence:
I go to Annual Summary and change to a useful year:
https://test-brc-ukbms.pantheonsite.io/annual-summary?year=2021  - showing My Data for all My Sites - all good.
I change to All Recorders:
https://test-brc-ukbms.pantheonsite.io/annual-summary?userID=all&year=2021 - it's showing data from all recorders, but still just for all My Sites
I can change to show data for all sites:
https://test-brc-ukbms.pantheonsite.io/annual-summary?locationID=all&userID=all&year=2021  - all good
I can change to show data for one site:
https://test-brc-ukbms.pantheonsite.io/annual-summary?locationID=2058&userID=all&year=2021  - all good
I can change back to just look at My Data:
https://test-brc-ukbms.pantheonsite.io/annual-summary?userID=4&locationID=2058&year=2021 - the location has retained in the URL, but it is only showing My Data for My Sites - so OK.
I change back to All Recorders:
https://test-brc-ukbms.pantheonsite.io/annual-summary?userID=all&locationID=users:4&year=2021 - the URL has ditched the locationID as expected, but it's still only showing data from My Sites, because locationID has changed to _=users:4_

I don't think it's a big problem - the table always shows the data according to what is highlighted in the filters, but not necessarily the default of My Data > My Sites, All Recorders > All sites.

But I think that's OK. If I'm looking at all My Sites, and I change to All Recorders, I probably, initially, only want to see what others have recorded on My Sites.

I'm happy to sign this one off.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Now pushed to Live. Changes confirmed as deployed.
Closing
