### ISSUE TITLE
Branch Co-ordinator unable to download data

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#258]
Hi @DavidRoy @Gary-van-Breda 

This is no doubt linked to the changes going on with the Annual Summary page #257 

A co-ordinator (HarryClarke) has let me know that he can no longer download the Branch Data.
If he loads up 'combine data for all recorders' with 'combine data for all sites allocated to your branch' he is offered all the expected downloads. However when he tries to download the Occurrences, Samples, Section Level or Summary Level files, he gets the error:
 **HTTP Error 414. The request URL is too long.**
In fact, I pasted one of the URLs into Word, and it stretched to 8 pages!

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Correct: related to #257 

@IanMiddlebrook : Fixes applied and deployed to Test for review.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda,

I've tried it for a co-ordinator with a big branch, and that seems to be working.

**Comment by Gary-van-Breda** [comment]
Now pushed to Live. Changes confirmed as deployed.
Closing
