### ISSUE TITLE
entering historic data

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/UKBMS-online#259]
when entering older data once you have added a walk and submitted it takes you back to current year and you need to then navigate back to the year you are entering data for. with a full year of counts this is quite tedious and time consuming and I wondered whether there might be a way to stay on the year of entry or have an option to enter past data where the default is to stay on the year of entry?

**Comment by Gary-van-Breda** [comment]
@DavidRoy @IanMiddlebrook @marcbotham : links sorted out between "Walk DE" and "My Walks". Should now keep track of the year, the site type and the site (if selected). Applied to "Cancel" and "Finish and return to walk".

**Comment by marcbotham** [comment]
This isn't working for me I'm afraid. Weirdly, it takes me back to 2021 rather than current year when I press finish and return to walk

**Comment by Gary-van-Breda** [comment]
@marcbotham : Sorry to be a pain, but can you detail the steps you are taking to get this behaviour? Thanks.

**Comment by Gary-van-Breda** [comment]
@marcbotham : Apologies again - this has only been deployed to the test site so far.

**Comment by marcbotham** [comment]
Ah that probably explains it then :) How do I get to test site (sorry I'm a luddite) please? The website currently starts at 2021 for My Walks rather than 2022, which is why it also returns to that when i press finish. It may be I have missed a discussion where it was thought that people are more likely to be entering previous years data in first few months of current year rather than entering new data for current year, so sorry if I missed that.

**Comment by Gary-van-Breda** [comment]
Test site is on https://test-brc-ukbms.pantheonsite.io/
Same login as your Live credentials. Although the code is test, the data is Live, so be careful.
Many moons ago it was decided that if the current date is before the first week displayed (i.e. week -3) then the default year displayed is last year.

**Comment by marcbotham** [comment]
perfect thank you. works fine on test site for me, great stuff

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
For me, it's returning to the correct year, and if I start from WCBS-BC it returns to that location type. That's great.

However, you implied that it should keep track of the site ID. If I start from 'Transect' and select an individual transect - it goes back to all transects (the return URL only specifies the year, not the location type or ID).

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : additional change applied so that both the location type and site ID are passed to both the new and existing walks. Change deployed on Test for review.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda - looks good to me

**Comment by Gary-van-Breda** [comment]
Deployed to Live. Checked.
Closing.
