### ISSUE TITLE
No data showing on Annual Summary page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#26]
There seems to be a major problem with the Annual Summary page.

All counts from 2016 and 2017 have disappeared. The only things which show up are the Temp and Sun% on the Raw Data tab, but no counts (butterflies or others) are showing.

**Comment by Gary-van-Breda** [comment]
I accidently triggered a rebuild last night when uploading the SP4778 data. It should be finished by lunchtime.

**Comment by Gary-van-Breda** [comment]
This has now caught up: all figures have been rebuilt.
