### ISSUE TITLE
BBS Squares to add to UKBMS

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#261]
Hello, please can you add these new WCBS-BBS squares to UKBMS:
[BBS 2022 new squares_final.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/8015117/BBS.2022.new.squares_final.xlsx)
Many thanks, Megan

**Comment by Gary-van-Breda** [comment]
@MeganLowe : I've uploaded these Squares for you.

**Comment by MeganLowe** [comment]
Thanks very much @Gary-van-Breda
