### ISSUE TITLE
Google satellite map not fixed to co-ordinates?

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#263]
Hi @Gary-van-Breda 
A co-ordinator was adjusting a transect route and noticed that when he tried to move the map around (either by clicking an dragging, or using the up/down arrows) the route and the satellite map did not move in unison.
The transect in question is 'Runnymede, Egham (2015 route)' (location_ID 39781).

I tried it, and the same thing happened, however, if I switch to OpenStreetMap, then everything is fine. It seems that the Google Satellite image is not locking to the co-ordinates in this area (seem to be OK in other areas that I've checked).

Checking further, it seems to only be a problem when you are zoomed right in (as you are when you draw sections) - if you zoom back out a stop, the satellite map starts behaving properly again.

Is this a problem with our website, or with Google Maps? Is it something that we can rectify?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Note to self: I have seen issues with the last 2 zoom levels, when the satellite map seems to switch from an overhead view, to an oblique view.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook Fix deployed to Test for review (ensures that map tilt is forced to 0 - overhead).

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda - looks good to me

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Deployed to Live. Checked on Runnymeade: OK.
Closing.
