### ISSUE TITLE
WCBS-BC squares incorrectly showing on Holiday Square map

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#265]
Hello, there are a number of WCBS-BC squares that are currently showing on the Holiday Squares map (here: https://ukbms.org/holiday-squares) that shouldn't be there. Holiday squares have only been 'released' in Scotland, Wales, Yorkshire, and North England, but the map is including squares from all around the country. I haven't managed to identify a pattern as to why the squares that aren't meant to be holiday squares are showing up. On their individual Site Details pages the 'Holiday Square' tickbox is already unticked, so I don't how to remove them. For an example see SP5078 - this square isn't a holiday square, but is appearing on the holiday square map. On it's site details page (https://ukbms.org/site-details?id=126995) the 'holiday square' box is unticked. 

Could it be a 'bug'? Please can you help? Thanks, Megan

**Comment by Gary-van-Breda** [comment]
@MeganLowe Bugfix applied to Test site for review.

**Comment by MeganLowe** [comment]
That's looking much better on the test website, thanks Gary.

**Comment by Gary-van-Breda** [comment]
Deployed to Live. Closing.
