### ISSUE TITLE
Annual Summary - summary chart - Show all/hide all not working

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#266]
Hi there,  Show all /hide all not working on summary chart. It is working on estimates chart however. 

Love the new copy to clipboard function.

**Comment by Gary-van-Breda** [comment]
@RachaelConway : can you make sure that you clear your browser cache, and then can you try again?
If you are still having problems, could you let me know which browser you are using, and on what type of machine?
Thanks.

**Comment by RachaelConway** [comment]
Hi @Gary that has worked thank you.
