### ISSUE TITLE
Annual Summary Hide all/ show all 

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#267]
Hi there, 

When using Annual Summary - show all/hide all.

Hide all selected - then single species selected e.g Green veined white - all OK
Show all - all Ok
Hide all again - hides all except Green Veined White (and other species if previously selected)

Required to  untick one by one or come out of annual summary and come back in again to clear

**Comment by Gary-van-Breda** [comment]
@RachaelConway Fix deployed to Live.

**Comment by RachaelConway** [comment]
@Gary-van-Breda Thanks Gary

**Comment by Gary-van-Breda** [comment]
@RachaelConway : As the person who raised this issue, are you happy that we close it now?

**Comment by RachaelConway** [comment]
Hi @Gary-van-Breda thank that all seems to working Ok now
