### ISSUE TITLE
UKBMS transect inbox - not receiving new registrant notification emails. 

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#268]
Hi I'm not receiving notification of new account emails,

**Comment by IanMiddlebrook** [comment]
@BirenRathod @DavidRoy 
Hi, it's not just BC that are not receiving notifications of new accounts, but the new Users are not receiving an email to say their Account is pending approval. This has been ongoing for a week or so.

Thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook I just tested email system on Drupal to check if it works fine or not and it works fine. see below a screenshot.

![image](https://user-images.githubusercontent.com/5941255/158396479-946097f6-b76b-46bd-9afa-96858feb6585.png)

**Comment by IanMiddlebrook** [comment]
@BirenRathod - No, it's not working fine.

We have had about 20 new Users in the last week - we received no emails for any of them, and many of those users contacted us to say they'd not received an email (the others probably just gave up).

I've just set up a new account with my private email address. I didn't receive an email, and the transect@butterfly-conservation.org address did not receive a notification.

It is not working fine.

Best wishes, Ian

**Comment by IanMiddlebrook** [comment]
If it helps - when we Unblock the new accounts, the users do receive their email about logging in and setting a password.

**Comment by BirenRathod** [comment]
@IanMiddlebrook Yes, so email system works fine. that is what I mean but when user registered, no email delivers. Are you aware of any change? 
I'm adding @Gary-van-Breda here. Has your last changed impacted to this?

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod 
I'm not aware of any change - I looked at the configuration (as much as I could understand it), and it looked OK.

**Comment by BirenRathod** [comment]
Thanks @IanMiddlebrook. I will wait for @Gary-van-Breda to say on this as he made changes a week ago in the code and that might have impacted on this.

**Comment by RachaelConway** [comment]
Hello all, just to update that the problem still exists and in addition as users are not receiving confirmation emails they are assuming something is wrong their end and are creating additional accounts. We are at a very busy time of year for processing new registrations ahead of the UKBMS season. In the past week I have had to enter almost 50 accounts to get the email address out to send confirmations and apologies, it's tripling the time taken to process a registration. Many thanks in advance for your help, Rachael

**Comment by IanMiddlebrook** [comment]
@DavidRoy

**Comment by Gary-van-Breda** [comment]
No - nothing I've done this year has had anything to do with the user registration process.

**Comment by BirenRathod** [comment]
@Gary-van-Breda This has stopped working once you updated code here -> https://dashboard.pantheon.io/sites/8d698669-7160-4231-b162-bddb55751b05#dev/code. not sure why?

**Comment by BirenRathod** [comment]
@Gary-van-Breda For your info, registration process works fine but it has stopped sending a notification email for some reason.

**Comment by BirenRathod** [comment]
@Gary-van-Breda Also, email system works fine too, I already checked.

**Comment by Gary-van-Breda** [comment]
> @Gary-van-Breda This has stopped working once you updated code here -> https://dashboard.pantheon.io/sites/8d698669-7160-4231-b162-bddb55751b05#dev/code. not sure why?

@BirenRathod : which commit you mean? - this link just shows all the commits deployed to Dev.

**Comment by BirenRathod** [comment]
@Gary-van-Breda This is the commit -> 9b94b6591c

**Comment by RachaelConway** [comment]
Hello all, the problem still remains,
Some users are trying to set up multiple accounts, asking for accounts to be deleted and also raising concerns about personal information safety. One user described receiving phising emails after attempting to set up a UKBMS account 3 times. As processing new registrants is now taking much longer, I do not have the capacity to inform local co-ordinators of new walkers in their patch, which is causing frustration at their end . Is it possible to get some idea of of when this might be resolved. Many thanks in advance, Rachael

**Comment by Gary-van-Breda** [comment]
@RachaelConway Fix deployed to Live.
The change for the finished field messed up which form was used to register a user.

**Comment by RachaelConway** [comment]
@Gary-van-Breda Thank you Gary I can see those notifications coming in this am. Great news

**Comment by Gary-van-Breda** [comment]
@RachaelConway : As the person who raised this issue, are you happy that we close it now?

**Comment by BirenRathod** [comment]
Thanks @Gary-van-Breda for fixing this. Will wait @RachaelConway to response on this.

**Comment by BirenRathod** [comment]
Sorry @RachaelConway, I didn't see your response. you can close this issue please.
