### ISSUE TITLE
SP0381

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#27]
Hi SP0381 is a non-random square that has been walked for three years. Please can this be added to the system and the historical data uploaded too?

Thanks

**Comment by Gary-van-Breda** [comment]
Is this a WCBS-BBS or WCBS-BC site?

**Comment by zrandle** [comment]
WCBS-BC

**Comment by Gary-van-Breda** [comment]
SP0381 already exists as a BC square. Next stage is the upload of historic data.

**Comment by Gary-van-Breda** [comment]
Historic data loaded.
Please check and close issue?
