### ISSUE TITLE
Remove test data

### ISSUE THREAD

**Issue by MeganLowe** [BiologicalRecordsCentre/UKBMS-online#270]
Hello, when I was testing the 'Enter Count' function earlier this year I submitted a dummy data entry form. Problem being that it was for a date in February and I now can't find a way to delete it (due to the My Walks calendar starting in March). Are you able to delete it directly from the database please? It's for WCBS-BC SU7797 (CCC-Andridge Common) on 28/02/2022
Thank you, Megan

**Comment by Gary-van-Breda** [comment]
Walk now deleted, and Annual summary checked to ensure data no longer visible.

It is possible to get to the walk outside the calendar by

- going into Annual summary
- filter by the location/year in question
- then go to the "Raw data". You should then be able to see all the walks for the year/site combination, even those outside the calendar.

The date in the grid header will be a link to return to the walk data entry page for that walk (provided you either created it or have sufficient privs), and you can use the "Delete" button to delete the walk.

**Comment by MeganLowe** [comment]
Thank you @Gary-van-Breda Good to know about the 'Raw data' options too!
