### ISSUE TITLE
Data Entry Warnings

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#271]
Hi @Gary-van-Breda @DavidRoy 

Do you know what has happened to the warnings on the data entry page, which were the first line of defence against data entry errors - the 'out of area' or 'outside flight period' warnings? 
They are no longer there.

Thanks, Ian

**Comment by DavidRoy** [comment]
@IanMiddlebrook the butterfly rules were updated recently. 
@JimBacon could you investigate this please

**Comment by JimBacon** [comment]
Hi @IanMiddlebrook, Could you tell me which data entry page should have these warnings?

**Comment by IanMiddlebrook** [comment]
Hi @JimBacon 
It's the Walk Data Entry pages (for Transects, WCBS-BC and WCBS-BBS sites).
See attached guidance, page 7, point 15.
[Getting Started with UKBMS Data Entry.pdf](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/8514474/Getting.Started.with.UKBMS.Data.Entry.pdf)

Thanks, Ian

**Comment by JimBacon** [comment]
Thanks Ian, that clarified the problem beautifully.
I think I see where @Gary-van-Breda has introduced the problem in commit [e85e7361df](https://dashboard.pantheon.io/sites/8d698669-7160-4231-b162-bddb55751b05#)

```
            $metadata = data_entry_helper::get_population_data(array(
                'table' => 'verification_rule_metadatum',
                'extraParams' => $readAuth + array('view' => 'detail',
                    'verification_rule_id' => $rule['id'])
            ));
```
has been replaced by 
```
            $metadata = $rulesMetaData[$rule['id']];
```
which does not contain all the metadata records for the given verification rule.

I have a problem with fixing this though as, it appears to me, the standard Drupal iform module does not contain the same changes, as if UKBMS has its own version, and I am not keen on perpetuating that divergence. I'm also wondering where you are, @johnvanbreda, with the development of the iform module. I had the impression a release was imminent.

**Comment by Gary-van-Breda** [comment]
I'll look at this...

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda @JimBacon 
I wonder if this issue also had a bearing on issue #272 on the same Data Entry page, where undefined excessive count warnings are being generated - apparently at random.

Thanks, Ian

**Comment by JimBacon** [comment]
No, #272 is an unrelated bug. (Also, it is not at random. It will affect species where the attribute defining the maximum number of a species expected in a section has not been set.)

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook Code fixed and deployed to Live.
