### ISSUE TITLE
Warn when recording rare migrants

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/UKBMS-online#273]
The following species do not have a value configured for the taxon attribute, 'UKBMS Section Limits'

_Nymphalis polychloros_, Large Tortoiseshell
_Danaus plexippus_, Monarch
_Lycaena dispar_, Large Copper
_Nymphalis antiopa_, Camberwell Beauty
_Colias hyale_, Pale Clouded Yellow
_Colias alfacariensis_, Berger's Clouded Yellow

In consequence, you can record any number of them without warning.

Ian says 

> They are all rare migrants - they certainly need some sort of warning on them, and I've a feeling they don't all have verification rules for flight period or distribution (due to lack of data). Perhaps set a maximum of 1 (or zero) for these species, but really they need a different message - "This is a rare migrant species - only record if you are certain of the identification".

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @JimBacon @RachaelConway
Change deployed to Live.
Setting the Section limit attribute for a taxon to the text 'Rare Migrant' (rather than a number) will cause the message given by Ian to appear whenever anyone enters data for that taxon.
The Section limit for the 6 taxa given above have all been set to 'Rare Migrant'.

**Comment by JimBacon** [comment]
Thanks, Gary. That works well.
I've updated the attribute description on the warehouse to make a note of this.

Excuse my ignorance but is there a mobile app that submits to this survey? If so, does it use the section limit to provide warnings? And if it does that, does it handle 'Rare Migrant' gracefully?

**Comment by Gary-van-Breda** [comment]
I don't know about any App (someone else will have to answer that!), though probably not. This attribute driven way of doing the section limits is a recent development (previously it was hardcoded into the form defintition). I haven't seen any issues raised which would imply its incorporation into an App.

**Comment by DavidRoy** [comment]
There is no app currently for the UKBMS
