### ISSUE TITLE
Test UKBMS Drupal 7 site: variable initialisation errors

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/UKBMS-online#28]
Occasionally I am seeing the following errors:

    Notice: unserialize(): Error at offset 2 of 40 bytes in variable_initialize() (line 1184 of D:\web sites\drupal\v7\multisite\includes\bootstrap.inc).
    Notice: unserialize(): Error at offset 333 of 24679 bytes in variable_initialize() (line 1184 of D:\web sites\drupal\v7\multisite\includes\bootstrap.inc).
    Notice: unserialize(): Error at offset 405 of 514 bytes in variable_initialize() (line 1184 of D:\web sites\drupal\v7\multisite\includes\bootstrap.inc).

**Comment by Gary-van-Breda** [comment]
The 40 length one looks like an invalid length for variable file_directory_path.
The 514 length one looks like an invalid length for the logo_path in variable theme_ukbms_settings.
The 24679 length one looks like an invalid length for the logo_path in variable theme_indiciatheme_settings.

**Comment by Gary-van-Breda** [comment]
I believe all 3 of these variables can be deleted completely. This would have to be done via the phpAdmin interface - I do not have access to this.

**Comment by BirenRathod** [comment]
@Gary-van-Breda- Yes,  This comes up generally after migration of Drupal sites. I have deleted all three variables now.
