### ISSUE TITLE
Site very slow, with intermittent red WARNING/NOTICE message

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#283]
![image](https://user-images.githubusercontent.com/88440885/186118319-c8e84d7a-0817-40bb-807c-011abc921725.png)

**Comment by DavidRoy** [comment]
@RachaelConway this is a known issue for this page.  It struggles due the number of sites to query.  The page should still function - i.e. if you scroll to the bottom the site or section downloads still work for me

**Comment by RachaelConway** [comment]
Yes thanks @David Ian advised me of the scrolling so I have been able to access.

**Comment by Gary-van-Breda** [comment]
@RachaelConway @DavidRoy : I've deployed a new version of the report grid where the underlying issue causing the red warnings and notices has been addressed (I think the reporting of these may have been switched off).
I've also deployed a new version of the report underneath the All Sites page, which should be about twice as fast - I was seeing about 5secs when run just now with Blank code filter = No, and 1sec with Blank code filter = Yes.

**Comment by RachaelConway** [comment]
@Gary-van-Breda 
Thanks, that is much faster now.

**Comment by Gary-van-Breda** [comment]
@RachaelConway : are you happy to close this issue?
