### ISSUE TITLE
Species data entry page very slow to load

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#288]
Hi @DavidRoy @Gary-van-Breda (@RachaelConway)

We've had quite a few comments/complaints this week about the data entry page.
The first Walk Data Entry page is fine, but when you click Next it takes an age to load up the Species/Section grid before you can enter data.

Eg. this comment:
_I am trying to enter my walks for two sites for most of the season - it took 2 minutes plus just to load the walk sheet and then timed out before registering the data I had put in - altogether 10 minutes wasted!!  Apologies but I am totally frustrated by this - is there a problem with the site, how can I put in my data without wasting time?_

I've just had a few goes, and it's taken a minimum of 30 secs with a good internet connection. 

This will be a particular issue for those who have saved up all their data to enter in one sitting at the end of the season.

Many thanks,

Ian

**Comment by RachaelConway** [comment]
More feedback re slow website this week.

**Comment by DavidRoy** [comment]
@Gary-van-Breda @JimBacon anything to speed up this page?  I think the slow part is loading up the species lists, e.g. 'species recorded at this site'?

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @RachaelConway : Re the delays in displaying the species section grid - is this before the page is displayed, or after it is displayed, but still has the spinner showing (when it is going away to get the geographic and flight dates range validation rules)?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
The big delay is after the list is displayed, but hiding behind the spinner.
A few goes this morning, it took between 10-15 secs to initially load the page, then averaged over a minute before the spinner disappeared.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @DavidRoy 
Effectively a duplicate for #305
"
I have deployed a updated version of the Walk DE page onto the Test system, which has been optimised for performance. The range checking has also been switched on on Test (https://test-brc-ukbms.pantheonsite.io), though with this new version, there will be little to no difference in speed between the range checking being switched on and off.
Can you check, and if you are happy I'll push it through to Live.
"

**Comment by Gary-van-Breda** [comment]
See comments in #305, now closed. Closing this as well.
