### ISSUE TITLE
data not presenting on annual aummary + 'could not identify specific site' error message in walks 

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#289]
Hi 

There are a number of problems with this transect: Stoke Park Bristol  user Stoke Park

Data is not presenting  in the annual summary
When clicking on a submitted walk via 'my walks' - message 'could not identify specific site' appears
Species/count page has 2 columns per section

![could not identify site] Image

(https://user-images.githubusercontent.com/88440885/199253248-41dede68-b01f-4f21-ab71-8335bfd31b39.JPG)

**Comment by IanMiddlebrook** [comment]
Resolved via #324
