### ISSUE TITLE
more new BBS squares to add 

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#29]
Hi 

Please can these new BBS squares be added to the system. Thanks Zoe
[BBS squares to add to system.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/961355/BBS.squares.to.add.to.system.xlsx)

**Comment by zrandle** [comment]
There are these to add too please. Thanks 
[more BBS squares.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/964468/more.BBS.squares.xlsx)

**Comment by Gary-van-Breda** [comment]
63 Squares above added. The following 4 squares were not added as they already existed as BBS squares:
NH9800
NH9801
NT2148
SD7233

**Comment by Gary-van-Breda** [comment]
@zrandle : can I have a definitive list of all the squares that are either current or historic, for both BC and BBS?

**Comment by zrandle** [comment]
@Gary-van-Breda do you want ones that are as yet un-allocated too? This will be more tricky as I don't know what's been allocated for the coming season so it maybe best for me to send you all of them...

**Comment by zrandle** [comment]
@Gary-van-Breda  please can you let me know what squares you want and I'll get them to you asap.

**Comment by Gary-van-Breda** [comment]
This part of the work under #13 has been completed.
Close?
