### ISSUE TITLE
Can an admin please make me a collaborator

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#290]
Hi 
I am not able to add labels to issues I open. I think this because I don't have 'collaborator' status. Please can an admin of the repository make me a collaborator or other status which would allow me to add labels. Thanks

**Comment by DavidRoy** [comment]
That should be done. Can you confirm and close this issue if ok

**Comment by RachaelConway** [comment]
That doesn't seem to have fixed it.

**Comment by DavidRoy** [comment]
You need to accept the invite?  Can you check your notifications?

**Comment by RachaelConway** [comment]
Yes that's it now David thanks
