### ISSUE TITLE
file name for downloads

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#292]
Hi, 
A branch co-ordinator has noted that the three 'Grid' downloads (annual summary page) no longer include the site name in the download file name.
He found this very useful for filing purposes.

I'm not sure why this has changed but, assuming that he's correct, would it be possible to change this back please?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Fix deployed to Live. @IanMiddlebrook could you check, and if happy close this issue?

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda
