### ISSUE TITLE
Branch Walks page drop-down Sites list

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#294]
Hi @DavidRoy @Gary-van-Breda 

A branch co-ordinator has pointed out that on 'Branch Walks' page there is a 'Filter by Site' box, which should have a drop-down list of all his Branch Sites so that he can filter the display. But his list was empty.

I checked a few other Branch Co-ordinators, and those that had drop-down lists only corresponded to sites on their 'My Sites' list rather than 'Branch Sites' list.

I think this is a mistake, that we've missed, unless the page has recently changed.

Could we please remedy this so that the drop-down list on 'Branch Walks' page corresponds to the Users 'Branch Sites' list.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook : a fix for this has been deployed to Live. Could you check, and if happy, close this issue?

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda
