### ISSUE TITLE
Section Level download not working

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#298]
Hi , 
I have been trying  to access the section level download for several hours and have received the following error report. All other downloads working.

![image](https://user-images.githubusercontent.com/88440885/207957830-1a896523-d7ed-4a08-a596-e6ccee26181b.png)

Thanks 
Rachael

**Comment by DavidRoy** [comment]
@BirenRathod can you look into this please

**Comment by BirenRathod** [comment]
@RachaelConway can you send me the download page link?

**Comment by BirenRathod** [comment]
@RachaelConway I have implemented the settings on the database, so it should work. It will take about 5 to 6 minutes to download about 517761 records. This depends on your internet connection.

**Comment by RachaelConway** [comment]
Hi @BirenRathod  I have tried today, now receiving the following error:

![image](https://user-images.githubusercontent.com/88440885/208458540-5bfff8ef-1f74-4a02-8c71-c6a9fb698d4b.png)

**Comment by DavidRoy** [comment]
@RachaelConway it's a large query and download.  If it fails first time it often works second time as the database has cached the query. I've just download the file

**Comment by RachaelConway** [comment]
Thanks David, I have tried several times, maybe its an internet speed issue my end?

**Comment by DavidRoy** [comment]
@BirenRathod any ideas?
@RachaelConway I'll email you the latest downloads

**Comment by BirenRathod** [comment]
@RachaelConway yes, it is down to internet speed.
