### ISSUE TITLE
WCBS Previous Data upload: number of sections.

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/UKBMS-online#30]
The data uploaded from the old system has an issue with the 2007 and before data: this data looks like there can be upto 20 sections per transect. As sections 11 and above do not exist, the data for these sections has not been uploaded.

**Comment by zrandle** [comment]
Can we double them up IE sections 1&2 = section 1, sections 2&3 = section 2 and so on?

**Comment by DavidRoy** [comment]
Yes, but we loose information doing this.  An alternative is:
- Change configuration to allow more sections per transect?  But keep the validation for <=15 sections for new transects being setup?

@Gary-van-Breda - which is easier?

**Comment by Gary-van-Breda** [comment]
At the moment the system assumes that there are route location records, that the section samples are attached to. I do not know how all the individual bits would react if we were to break that assumption. At the moment the WCBS locations all have 10 section routes.
In the light of this, the easiest would be to do the doubling up.

**Comment by DavidRoy** [comment]
Agreed.  Can you do the summing up, or do you want us to?  Just to be clear, what's needed is to sum the species counts for original section 1+2 into section 1 count, 3+4 for section 2 etc etc.

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you advise on what action now needed?

**Comment by Gary-van-Breda** [comment]
I have a spreadsheet which converts between the files, and which produces a csv file which can be uploaded into the warehouse. It also loads in the existing data, so it can make sure there is no duplicate data created. I just need to tweak this for years prior to 2007 to add the data together, and then run the whole schebang again. I will probably ask to have all 2007 and prior data removed, but that will just be a single SQL query to be run against the warehouse.

**Comment by DavidRoy** [comment]
Thanks.  Can you also provide some documentation on the upload process once the input files are in the right format

**Comment by Gary-van-Breda** [comment]
This has been incorporated into the latest data load.

Re how the data load itself is done: due to the use of a subsample to hold the section data, this has to be done in 2 stages.
Stage 1 is load the visits: This involved creating files with the following columns (one for BBS and one for BC): 
SAMPLEKEY | SURVEY | LOCATION | Grid Ref | Grid Ref System | RECORDER | DATE | TEMPERATURE | WIND_SPEED | WIND_DIRECTION | START_TIME | END_TIME | % Sun
The samplekey is an optionalexternal key, and I mapped this to the vVISIT number from the provided data. The survey is used to identify the data in the file to prevent confusion, but is not used in the data load itself. The location is the name of the Indicia Transect/Square, and is derived from the Grid Ref in the visits data by doing a download of all the Transects/Squares and mapping them. The others are self explanatory. 
This was then loaded into the warehouse using the upload CSV functionality at the bottom of the samples tab in the warehouse itself, filling in the various fields as appropriate,with care that the LOCATION was mapped to the location (lookup), and the existing record lookup used the location and date.
A similar process was followed to create a set of survey/Sref system/taxxon list specific files for the subsamples/occurrences: these files contained the following information: 
Sample Date | Survey | Grid Ref | OSGB | Location | Parent Sample ID | % Sun | Taxon | Count
Where the location points to the name of the section within Indicia, taking into account the fact that some have Hyphens in. The Parent Sample ID has to be the Indicia ID, and was derived by downloading all the samples for the surveys in question from the warehouse. The taxon is the preferred taxon in the warehouse, and was derived from downloaded taxa_taxon_lists.
This was then loaded into the warehouse using the upload CSV functionality at the bottom of the occurrences tab in the warehouse itself, filling in the various fields as appropriate,with care that the LOCATION was mapped to the location (lookup), and the existing record lookup set as appropriate.

**Comment by DavidRoy** [comment]
Thanks.  Now closing
