### ISSUE TITLE
data access language on data entry pages

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#300]
Hi @DavidRoy 

A matter was raised whilst reviewing the privacy notice on Monday. 
The data entry pages on UKBMS website still refer to **creative commons license**, but this should now read **Open Government License**
Could we please make that change, wherever required?

Many thanks,

Ian

**Comment by DavidRoy** [comment]
Needed on: 

- [ ] https://ukbms.org/my-walks
- [ ] https://ukbms.org/input-data
- [ ] https://ukbms.org/my-timed-counts
- [ ] https://ukbms.org/input-timed-counts?

Wording needed:
By submitting these records you confirm that they contain data that you have collected, give permission for the records to be used for research, education and public information, and to be made generally available for re-use for any other legal purpose under the terms of the Open Government Licence (/[privacy-notice](https://ukbms.org/privacy-notice)), and agree that your name will be associated with the record.

**Comment by Gary-van-Breda** [comment]
Also needed on the WCBS BC and BBS walk data entry pages.
Not sure it is applicable to the branch walks page.

**Comment by Gary-van-Breda** [comment]
All pages updated. Please check and close if happy. (no existing message on branch walks page)
