### ISSUE TITLE
Masquerading 

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#303]
@BirenRathod @IanMiddlebrook 

Opening thread just for masquerading as suggested by @DavidRoy 

@BirenRathod It seems to be as Ian says, a problem with the Branch Coordinator role. It isn't because I didn't unmasquerade.   I don't seem to have the other masquerade entry you described

**Comment by BirenRathod** [comment]
@RachaelConway Thanks for opening this issue. you already got admin role. Are you trying to resolve this for people who has got "Branch coordinator role" ?

**Comment by RachaelConway** [comment]
> @RachaelConway Thanks for opening this issue. you already got admin role. Are you trying to resolve this for people who has got "Branch coordinator role" ?

Hi @BirenRathod  I'm referring to the online users, after a search and select - if they are a **normal user** then the masquerade drop down is present, however if they are a **branch coordinator** the masquerade drop down is not present. Please see both **roles** as below

<img width="898" alt="image" src="https://user-images.githubusercontent.com/88440885/234066579-63582119-db40-45d2-b15e-30dc74a06a1d.png">


<img width="914" alt="image" src="https://user-images.githubusercontent.com/88440885/234066279-51905ee9-6331-4b66-9dfe-4f048a17f9f2.png">

**Comment by BirenRathod** [comment]
@RachaelConway That is interesting, I didn't see that. I just enabled permission for authenticated users but permission doesn't consider role "branch coordinator" as authenticated users. I have implemented that.

**Comment by DavidRoy** [comment]
@BirenRathod normal users should not be able to masquerade as others

**Comment by BirenRathod** [comment]
@DavidRoy masquerading option only appears for "admin" user, so admin users can masquerade as "authenticated users" but not vice versa.

**Comment by IanMiddlebrook** [comment]
@BirenRathod 
Now not able to masquerade for any user

**Comment by BirenRathod** [comment]
@IanMiddlebrook somebody else is changing the permission setting which I did yesterday. I reverted it back now. Can you check it again, please?

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod  that's back to normal.

**Comment by BirenRathod** [comment]
@IanMiddlebrook & @RachaelConway Please close this if you satisfy.
