### ISSUE TITLE
Data Entry - speed of website

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#305]
Hi @DavidRoy 

It doesn't look like this issue is going way. There may be some spells when it's quicker, but lots of times when it is causing a problem.

Typical comment received today:

_We are finding that entering data into UKBMS is generally slow ...  A couple of people in the New Forest group have reported that their system timed out when trying to enter some results. I just timed an entry and it took 1 min 10 seconds to load the species page._ 

I've had similar experiences at various times this week.

Is this something than can be given serious thought?

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
latest comment from a disgruntled user:

_You may be aware and I don’t know who to contact, UKBMS is currently running very slow and unusable. I noticed this last night and it is still the same this morning, most actions just time out._

**Comment by DavidRoy** [comment]
We'll look into this.  One option is to limit the functionality temporarily as the page is very complex

**Comment by DavidRoy** [comment]
We’ve deactivated the rule checks during data entry until we can review if this can be optimised. @IanMiddlebrook can you ask if this improves performance

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @DavidRoy 
I have deployed a updated version of the Walk DE page onto the Test system, which has been optimised for performance. The range checking has also been switched on on Test (https://test-brc-ukbms.pantheonsite.io), though with this new version, there will be little to no difference in speed between the range checking being switched on and off.
Can you check, and if you are happy I'll push it through to Live.
(See also #288)

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda - that looks lightning fast on the test site.
@RachaelConway tagged in here to test as well.

One quick thing, if possible. When we initially had the species highlighted for out of range/date etc, the pink warning colour stretched all the way along that row. That was lost at some point . Would it be easy to reinstate this before we go live?
It just makes any data entry error less likely if the cell itself is highlighted.

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : I've tweaked the colours - would you like to have another look on Test?

**Comment by IanMiddlebrook** [comment]
Perfect - thanks @Gary-van-Breda

**Comment by Gary-van-Breda** [comment]
@RachaelConway : Are you able to do some testing on this?

**Comment by RachaelConway** [comment]
Hi @Gary-van-Breda 

This seems to be working well. The only issue I encountered was if I did try to enter an 'out of range' species, the spinning arrows appeared for 30+ secs , but subsequent attempts to submit 'out of range/date' seemed fine, probably just an internet speed problem.

**Comment by Gary-van-Breda** [comment]
I have not been able to replicate the spinner for the out of range species.
Pushed to Live. Out of range checks enabled. Closing
