### ISSUE TITLE
Failed to connect to warehouse1.indicia.org.uk port 443: No route to host

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#306]
Hi @DavidRoy @BirenRathod

There seems to be  major problem with the website this morning, with users unable to enter data or do anything related to their account.

Pages like My Walks, My Sites, Annual Summary, Site Assignment etc. are coming up with the message:

_Failed to connect to warehouse1.indicia.org.uk port 443: No route to host_

Thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook Our server is down which is unexpected. It is now back on live.

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod
