### ISSUE TITLE
Sites - very slow to load or times out- https://ukbms.org/sites

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#307]
Hi @DavidRoy 

User complaint about **Sites** page, slow to load or times out. 

Took me three attempts to get in 
Thanks Rachael

**Comment by DavidRoy** [comment]
@RachaelConway this is a known problem and we need to simplify the page.  How often is it used and what is the key information you need from this.  For example, do you need to know the number of samples?

**Comment by RachaelConway** [comment]
Our regional coordinators use it to help volunteers find a transect/WCBS near them. I use infrequently myself but would be for the same purpose.

**Comment by RachaelConway** [comment]
Hi @DavidRoy maybe you were referring to 'All Sites' not the 'Sites' map. If so then I nearly always use 'all sites' to look up a transect or square when I don't know which county/branch it is in, basically a search function to find the site in the system
