### ISSUE TITLE
Annual Summary page - validation error

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#308]
Hi @DavidRoy 

Since the upgrade to PHP 8, there is a problem with the Annual Summary page - if I (or a branch co-ordinator) change the ‘Filter by Recorder’ to either Branch Data or Combine Data for all Recorders, then I just get a message saying ‘validation error’. 
As Admin, I'm not able to view any data other than my own, and Branch Co-ordinators are unable to review their Branch data.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook Are you still having this problem? If so, could you let me know what Browser you are using and which Operating system - thanks.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 

No, this was resolved fairly quickly - I think via email, which is why it wasn't closed on here.

Thanks, Ian
