### ISSUE TITLE
Timed Count Data Entry not working

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#309]
Hi @DavidRoy @Gary-van-Breda

The timed count data entry page is not working - 
the Year field is not being populated automatically from the Date, so it is not possible to progress beyond the first page.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook Can you confirm which browser you are using, and which operating system?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
I've just checked on MS Edge, and all now seems to be OK.
I've not received any complaints about this since June, and several counts have successfully been entered since the issue was raised, so I guess it has resolved itself!

I'll close for now, unless I hear of any more problems.

Thanks, Ian
