### ISSUE TITLE
late and 2016 NT data upload

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#31]
Hi 

As far as I remember this data needs adding to the system.

Thanks
[late data for new system.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/962079/late.data.for.new.system.xlsx)

Zoe

**Comment by Gary-van-Breda** [comment]
Some of this data has been included in the data load just completed under #13 . @zrandle I take it you want the remainder loaded as well?

**Comment by zrandle** [comment]
Yes please add the remainder too. Thanks

**Comment by Gary-van-Breda** [comment]
Do you know what BMSCODE 13 and 284 are?  I can work out the rest.

**Comment by DavidRoy** [comment]
13 is High Brown Fritillary
284 is Silver Y 

The latter being a moth

**Comment by Gary-van-Breda** [comment]
@DavidRoy : can you confirm the 284 is Silver Y? Records in the other lists provided have 384 as Siler Y.
Thanks

**Comment by DavidRoy** [comment]
@Gary-van-Breda yes, 284 is Silver Y.  It was a mistake in the original online capture system coding as far as I can determine.  
Note: based on entry in ukbms_widercountry_species_old table within ORACLE at CEH

**Comment by Gary-van-Breda** [comment]
@DavidRoy : So how does this impact all the records that I uploaded that had a BMSCode of 384? Are we effectively saying that Silver Y is both 284 and 384?

**Comment by DavidRoy** [comment]
@Gary-van-Breda Yes, two codes have been used for the same species.  No impact on data already loaded as code 284 has not been used for any other species.

**Comment by Gary-van-Breda** [comment]
Now confirmed done.
@zrandle : Review and close?

**Comment by zrandle** [comment]
In my WCBS access database Silver Y is 384. Nothing down as 284.

**Comment by Gary-van-Breda** [comment]
@zrandle The 284s I have are in the file provided by you at the top of this issue: rows 391, 392
Visit number 34381, sections 4 and 9. These map to SJ5508 (NT-SJ5508), date 17/08/2016

**Comment by zrandle** [comment]
Ah! Can you change them to 384 so they are are same as all other Silver Y's. The reason why they're not in my main WCBS database is because I keep the NT squares in a separate access database.

Cheers

Zoe

**Comment by Gary-van-Breda** [comment]
The Indicia system doesn't keep track of the BMSCODE: they have been mapped to the Indicia taxon "Silver Y" as part of the upload, the same as the 384s, so will be identical.

**Comment by zrandle** [comment]
Ok no worries.
