### ISSUE TITLE
Error report on **my sites**

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#312]
<img width="645" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/43278afc-98e5-4050-9810-d40ec37a029e">
****
@IanMiddlebrook @DavidRoy

**Comment by IanMiddlebrook** [comment]
Similar for 'My Walks'
![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/24699793/8b2de0b1-c6bd-4757-a85b-dc679a197e03)
