### ISSUE TITLE
No 'count' data in Year by Year plot

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#315]
Hi  @IanMiddlebrook @DavidRoy 

Index loads OK as below

<img width="605" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/9d2138be-aaad-46b5-bcb5-d30ef3ad6556">

On selecting count - 'no data available' message

<img width="586" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/4fe462b5-76c6-453b-a2a6-6a3d8a635d93">

**Comment by IanMiddlebrook** [comment]
Thanks @RachaelConway - this is a result of the same issue covered in #314
