### ISSUE TITLE
Pre-emptive data entry

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#318]
Hi @DavidRoy @Gary-van-Breda 

On the Data Entry page, a recorder has noted a 'magic 2' appearing every time he clicks on a box to enter a count. This can result in a count of 2 being entered by accident. 
I think it's possibly the browser remembering a previous figure and suggesting it for every new entry. I get a similar thing, but it's more obvious to ignore - screenshots shown:

![Screenshot 2023-07-27 084941](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/24699793/c116130c-f273-47f4-9283-0a8d7bf2aedb)

![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/24699793/d951b16d-3b75-4921-ac03-9717dffdbf2a)

Is there away to block this feature on this page - either at source or through advice we can give to recorders?

Thank, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : I've deployed a tweak to the code to Live, which switches off "autocomplete" on the fields on the species tab. Could you see if this has prevented the popup appearing in the browser? If it doesn't, I'll need the browser details so I can provide instructions on how to turn it off - this is browser specific functionality.
(Unfortunately the popup is website specific, and the test environment has a very different URL to Live, so if the pop up does not appear in test, there is no guarantee it won't appear on Live)

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
It's worked for me. I've asked the recorder who raised the issue to test it out - I'll let you know what he says.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
Have heard back from the recorder, and it's all good for him.

Many thanks, Ian
