### ISSUE TITLE
Duplicate walks issues

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#319]
Hi @JimBacon

Duplicate issue again from the 26th. Two walks with different counts
<img width="635" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/301a9866-cd25-4047-9948-25ddbb31371d">
<img width="568" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/07b52ea3-c501-45cb-a876-07d66dc09406">

Again a new user so my have fallen foul of the default transect page - but why different counts?

**Comment by JimBacon** [comment]
Sample 23090978 was created on 2023-07-27 11:41:34. 
It has 10 sub-samples, one for each each section.
Occurrences are recorded for all sections except S5, S8, S9, S10
The occurrences were created between 11:43:03 and 11:45:11

Sample 23091118 was created on 2023-07-27 11:49:03 and updated further at 11:57:00
It has 10 sub-samples, one for each each section.
Occurrences are recorded for all sections except S5
The occurrences were created between 11:49:52 and 11:52:30

I would hazard a guess that the user submitted an incomplete record, was unable to edit it in order to complete it, and therefore created a second record. This might arise if, as previously mentioned in #317, the walk did not appear immediately after submission.

There are no errors in the indicia warehouse log file around those times.
The web server log also does not indicate errors nor even particularly long response times - each occurrence taking from 0.5 to 3.5 seconds to save.

Did the user report having any dificulties?

**Comment by RachaelConway** [comment]
Hi Jim, 

I got this second hand from a coordinator so I don't have a lot of detail I'm afraid. I think I agree with you that it is new WCBS users landing on the 'transect' calendar after clicking 'finish and return to walk list'. A enhancement which lands them on the correct survey page showing the walk just entered would fix this problem (if it can be done).

**Comment by JimBacon** [comment]
Hi Rachael,

It already has that feature when I add walks. It is only when deleting WCBS walks that you drop back to Transect walks as far as I am aware. Is there a way of adding walks that bypasses the calendar? That might be another route to duplication. Do you promote links direct to the recording form like https://ukbms.org/input-bbs-data, for example?

**Comment by RachaelConway** [comment]
Hi Jim sorry for the delay in responding. 

Yes there is another route for submission that bypasses the calendar .  'Enter Count' in the header bar of the home page navigates to a page with 4 survey options as below. On clicking one of these you are taken directly to the walk details form 
<img width="656" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/a4715cb6-aaee-48f7-90a4-1a975d255ae7">

**Comment by JimBacon** [comment]
Ah, well, isn't that inevitably going to lead to new users creating duplicates? If you start entering data by this route and then something happens to interrupt you, you're going to come back and create a duplicate, not realising you could edit what you have already done by My Data > Walks > My Walks > WCBS-BC.

**Comment by RachaelConway** [comment]
Hi Jim, I can see how that could happen, especially when the system times out, but I think most users who reported, went back to the calendar to check if the walk was there found it wasn't and resubmitted. I think a few WCBS/BBS folk are victims of the default transect calendar.

I'll do a piece in the newsletter to advise how to check/ edit walks along with the pitfalls described above.

Would it be worth/is is possible to make the following change 'Enter Count' , select survey type ( as above) and then instead of landing on the walk details page, land on calendar instead?

**Comment by JimBacon** [comment]
> Would it be worth/is is possible to make the following change 'Enter Count' , select survey type ( as above) and then instead of landing on the walk details page, land on calendar instead?

I think that should be possible, easy, and worthwhile for us. Do you think it would be okay with the users? For them, it is just a different way of choosing the date but with the opportunity to edit an existing record. It may be a little slower overall.

**Comment by RachaelConway** [comment]
Hi Jim,  Megan requested this new feature as WCBS users couldn't find the walk entry page, I suppose its balancing the number of problems with duplicates v number of  problems with people scuppered by a new 'enter count' landing page. There is also another route to data submission via the 'links' tab in 'site details'. 

<img width="528" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/c10368c1-4d63-499e-a022-c8a223d69b9e">

Now I understand the various ways people can accidentally create a duplicate, it might be better just to deal with these as and when they occur. I'll give it some thought and discuss with Ian. Thanks

**Comment by RachaelConway** [comment]
@IanMiddlebrook can we discuss this at soem stage please

**Comment by Gary-van-Breda** [comment]
@RachaelConway @IanMiddlebrook : I'm going to add a check so that when the user enters a date/transect combination on the first page of the walk data entry, it looks up to see if there are any other walks with the same date and transect. It will then display a warning if it found any - the user can then cancel out.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda , sounds like a good idea

**Comment by JimBacon** [comment]
If it were a date-site-user check then you could offer them the choice of editing the existing record, if it is their own, as well as cancelling out. Do you allow the option to continue and create a duplicate?

**Comment by IanMiddlebrook** [comment]
I guess they should still be able to create a 'duplicate' if it was genuinely a second walk on the same day - ie. at a different time of day.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @JimBacon 
Code change pushed to Test site - can you check you are happy before I push to Live?
A dialog is displayed if there is already a walk on that site/date combination, allowing the user 3 options
* Cancel out of the walk entry and edit the existing record (only available if the user is the one who entered the data)
* Cancel out of the walk entry
* Continue with walk entry - emphasizes that the user is adding an extra walk of that day.

**Comment by IanMiddlebrook** [comment]
Sorry @Gary-van-Breda , I rarely see the test site and can never find it, could you give me a link?

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : its https://test-brc-ukbms.pantheonsite.io/

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 

I've just tried this, and had no trouble at all creating a duplicate entry for Wyke Regis on 25th September 2023 - no dialog was displayed.
This was true from using the 'Enter Count' button, and also via the My Walks page (selecting the site on the Data Entry page). 
However, if I filter the My Walks page to only show Wyke Regis, I don't get an option to add a walk on a date that is already occupied.

Do I have over-riding privileges as an Admin to create duplicates? Should I masquerade as a regular User to test this out?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook I think there was a caching issue - can you try again?

There are no special privileges for this. The My Walks has not been changed - I think it has always not shown an option to add a walk on a date when filtering by a site and there is an existing walk there.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda, yes it's working now.

Seems to work well, as per design. The only slight drawback is the second dialog box that comes up. 

So, if I choose to 'Cancel' the current walk (either in full, or by editing the previous walk), I get a second dialog box as below. 
![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/24699793/07179f34-2121-4ed3-a49a-9084214d87f5)
If I know what I'm doing, I should click on 'Leave' and carry on. 
But it would be easy for recorders to think, "I don't want to leave the site, I want to cancel the walk, so I'll click 'Cancel'." In which case, the page acts as if I've chosen to continue entering the duplicate walk.

I don't know if this second dialog box is generated by the browser or the website, or if there's anything that can be done about it, but it might cause some confusion.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : a fix for the second popup has been deployed to the test site. Could you have another look?

**Comment by IanMiddlebrook** [comment]
That's great @Gary-van-Breda  - that works well

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook This is now deployed to Live. Is this all we need to do to finish this issue?

**Comment by IanMiddlebrook** [comment]
That's great, thanks @Gary-van-Breda 
I think we can close this one now.
