### ISSUE TITLE
Incorrectly defined transect

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/UKBMS-online#321]
The transect [Great Holland Pits EWT](https://ukbms.org/site-details?id=266385) has no path defined for any of its sections except S7. There are occurrences recorded against all sections.

@IanMiddlebrook are you able to arrange for this to be corrected?

**Comment by IanMiddlebrook** [comment]
Hi @JimBacon 

I've set up a provisional route as a placeholder for now.
I've asked the recorder to let me have a copy of the exact route, so I'll tidy it up when he responds.

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
The correct route has now been received from the recorder and mapped online.
