### ISSUE TITLE
Annual Summary/Year by Year plot - 'Copy to clipboard function' - stuck on 'copying please wait'

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#323]
<img width="401" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/6df1f1f8-9c40-4a3d-95a9-64941d0ef4c1">

**Comment by Gary-van-Breda** [comment]
JS error: Uncaught ReferenceError: html2canvas is not defined

@andrewvanbreda Do you know why the html2canvas resource was dropped when the PHP 8.1 update was done?

**Comment by andrewvanbreda** [comment]
Hi @Gary-van-Breda 

@BirenRathod might know?

From my perspective the PHP 8.1 update was simply an iForm update, however it was a slightly messy one as I had to do some rejigging as some of the files were out of date in indicia-team, so it wasn't a pure iform update.
I have never dealt with html2canvas and it wasn't dropped deliberately.

Are you able to reinstate it?

**Comment by BirenRathod** [comment]
@andrewvanbreda, @Gary-van-Breda it may have been due to Drupal 9 not because of PHP 8.1 update. See below...
https://www.drupal.org/project/html2canvas, do you just want a library?

**Comment by Gary-van-Breda** [comment]
We don't need the Drupal module just the JS from the CDN. I've reinstated the resource in helper_base. 

Pushed through to Dev/Test/Live, testing Annual Summary and Year plot on Chrome at each stage.

@RachaelConway : could you check you are happy that this issue is now fixed?

**Comment by andrewvanbreda** [comment]
Hi @Gary-van-Breda 
You previously asked if I had an idea how this issue occurred.
I can see now from your fix.
This issue has occurred because the html2canvas code is only in helper_base develop in indicia-team and would have been overwritten by the PHP 8 iForm update I did.
I can only presume it won't be long before this ends up in Master so we won't have that issue again once that happens.

**Comment by RachaelConway** [comment]
@Gary-van-Breda  Grand job, that's working beautifully thank you.
