### ISSUE TITLE
'Copy chart to clipboard' not working

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#325]
Hi @DavidRoy @JimBacon 

A recorder has noted that the 'copy ... to clipboard' function on the Annual Summary page is not working for the Summary Chart and Estimates Chart.

It appears to be OK for the Tables, but not the coloured charts.

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
Ah, @BirenRathod @Gary-van-Breda @andrewvanbreda

I see this is almost certainly linked to issue #323 

Perhaps whatever fix you applied for the Tables needs to be applied to the Charts?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
This is actually a duplicate of #323 : both refer to copying of charts to the clipboard.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : #323 now fixed. Can you confirm you are happy that this is is now fixed?

**Comment by IanMiddlebrook** [comment]
That's great - thanks @Gary-van-Breda
