### ISSUE TITLE
'Finished for the year' - how does this reset?

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#328]
Morning, 

How does the 'finished for the year' status reset please? 

Some coordinators report that people in the branch list who have not been active for a year or two have a status of yes or no. For example a coordinator has not submitted any of his own data this year but can see himself on the branch list with a 'yes' status. 

Thanks

**Comment by Gary-van-Breda** [comment]
Hi @RachaelConway,
The 'finished for the year' status flag was added as part of issue #226, and that issue includes the instructions on how do the bulk reset for everyone each year. This is a manual process (that should really be done every January), so I assume that it has slipped through the cracks this year, and we have forgotten to do it.

FYI @IanMiddlebrook @DavidRoy

**Comment by RachaelConway** [comment]
Thanks @Gary-van-Breda 

I have managed to navigate to here

<img width="356" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/91c89434-93cd-4750-a68b-7e4e6cebf21b">

But can't find a fields option, is this due to my level of permissions or am I in the wrong place?

**Comment by DavidRoy** [comment]
@Gary-van-Breda this has slipped through the net.  Can you implement the reset of the field

**Comment by Gary-van-Breda** [comment]
@DavidRoy Can you confirm you'd like it done now?

**Comment by DavidRoy** [comment]
@IanMiddlebrook @RachaelConway 
Can you confirm.  I think 'yes'

**Comment by RachaelConway** [comment]
I think it's best to wait until January as the Regional Coordinators are currently using the system to chase data.  They will have to start over if it is reset now. @IanMiddlebrook do you agree?

For the conscientious users they will change their own status via My Account

**Comment by IanMiddlebrook** [comment]
I agree to leave this alone for now. 
I just looked at the list for Dorset, and the majority of Users are showing as NOT finished for the year. 
It's possible some reset themselves at the start of the season, if it didn't happen automatically.
I don't think we should interfere with what's happened already this autumn.

**Comment by RachaelConway** [comment]
Hi @DavidRoy and @Gary-van-Breda 

Please can we now do the reset of 'finished for the year', 
many thanks Rachael

**Comment by Gary-van-Breda** [comment]
Done.
Got an error (something wrong in Drupal itself) when following the instructions in #226, so did a direct sql change in the database.
**UPDATE `user__field_finished_for_year` set field_finished_for_year_value=0;**
