### ISSUE TITLE
Species trend figures out of date

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#329]
Hi @DavidRoy 

Spotted by a recorder - 
It looks like all the species trend figures and plots have not been updated with the 2022 results:
https://ukbms.org/species 

Could we arrange for them to be updated please?

Many thanks, Ian

**Comment by DavidRoy** [comment]
yes, we'll look into this

**Comment by burkmarr** [comment]
The trend, trend summary and phenology data are up to date now (i.e. include 2022 data). We have also made some updates that will make it much easier to update this information annually.

**Comment by IanMiddlebrook** [comment]
That's great - thanks @burkmarr
