### ISSUE TITLE
Northern Ireland squares for upload

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#33]
Hi s
[NI to be added.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1022512/NI.to.be.added.xlsx)
ome of the NI squares were not added in the last upload of new squares. Please can the attached squares be added asap. They are all WCBS-BC squares. Many thanks Zoe

**Comment by zrandle** [comment]
Hi people are registering for squares that I cannot link them to due to the squares not being on the system yet. Please can these be added asap? Thanks Zoe

**Comment by zrandle** [comment]
hi Can this be implemented asap please. Recorders are getting irritated!

**Comment by Gary-van-Breda** [comment]
These Squares now uploaded.

For future reference I used the following Excel macro enabled spreadsheet to convert the squares list in a CSV file that can uploaded directly into warehouse using the CSV upload facility.
[New Squares.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1109157/New.Squares.zip)

**Comment by zrandle** [comment]
Great thanks :)
