### ISSUE TITLE
People List- change 'last active' to a date 

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#334]
@DavidRoy @IanMiddlebrook

 Please can the 'last access' field be changed to a date rather than  #day/week/month/year. We produce mailing lists from those users last active within last 2 years and the CSV download is difficult to work with in its current format. 

When admin masquerade as user, this registers as activity. Is it possible for masquerading **not** to register as activity in the users 'last active' status. 

Thank you

**Comment by RachaelConway** [comment]
Hi @DavidRoy I'm hoping this may be a quick job to change last active 'text' to a short date. I get quite few requests for updated mailing lists from coordinators and this change would make things a lot easier my end.  If it is easy to do - could I please bump it up the list of priorities. Thank you

![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/3b592407-f624-4dad-89da-8a2325eea527)

**Comment by RachaelConway** [comment]
Hi @DavidRoy 
Could someone take a look at this request for me please, I think it might be a quick fix which could save me loads of time. When I download the _people_ list to create a mailing list,  I can only use those active in the last two years - for GDPR reasons. It would be very much easier if I could sort the downloaded list via a date rather than the text '3 years 2 months' etc. Thank you

**Comment by Gary-van-Breda** [comment]
Just to confirm we are talking about page https://ukbms.org/people/list and the associated CSV download.
I've changed the output format of the last accessed date to be a short date on both these, no time included.

I do not think it is possible to ignore masquerading in.

Note it displays "1970-01-01" for never.

**Comment by RachaelConway** [comment]
@Gary-van-Breda  Amazing thank you, that change will help me no end.

Not sure what you mean by this   "I do not think it is possible to ignore masquerading in."

Noted re 1970..etc 

Many thanks
Rachael

**Comment by Gary-van-Breda** [comment]
@RachaelConway In the original comments you mentioned: "When admin masquerade as user, this registers as activity. Is it possible for masquerading not to register as activity in the users 'last active' status?"
Unfortunately there is no way to prevent masquerading registering as activity.
