### ISSUE TITLE
People - search function to include name in addition to username/email

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#335]
@DavidRoy @IanMiddlebrook 

Please can the search function below include ability to search by 'own' name in addition to username and email 

<img width="768" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/bb61f6fb-4d92-4aba-8822-a11bcde5bbfe">

**Comment by Gary-van-Breda** [comment]
@RachaelConway "People" view on live updated: now searches username, email, first and last names, though first and last names are not included in the displayed fieldlist.

**Comment by RachaelConway** [comment]
@Gary-van-Breda 

Excellent! Thank you
