### ISSUE TITLE
Walk data entry - sample details - explanatory note on % sunshine

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#337]
@DavidRoy @IanMiddlebrook 

Please can we add an infotip or explanatory text below the % sunshine field.

Something along lines of:

The % sunshine entered here will autofill all sections on the next page. Individual sections can be changed. 

or

This is a shortcut to autofill all sections with the same % sunshine e.g 100%. Leave blank if you wish to submit individual % sunshine for each section. 

or an alternative @IanMiddlebrook

**Comment by Gary-van-Breda** [comment]
Help text added, and CSS tweaked so page still looks OK.
Deployed to Live: @RachaelConway can you check if you are happy?

**Comment by RachaelConway** [comment]
@Gary-van-Breda 

great job thanks
