### ISSUE TITLE
No historical data for SP4359

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#34]
Hi 
There isn't any historical data for SP4359 on the new system. Can it be added please?
Thanks

Zoe

**Comment by zrandle** [comment]
nor for SP5078. This may be a wider issue - how can we check this?

**Comment by Gary-van-Breda** [comment]
Two visits now uploaded for SP4359 in 2009
Two each in 2009 and 2010 for SP5078.
Checked in Annual Summary, and confirmed that this was all that was included in the historic data load.
Close?

**Comment by zrandle** [comment]
Great thanks
