### ISSUE TITLE
Branch users - last active column

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#340]
@DavidRoy  @IanMiddlebrook 

In Branch Users is it possible to have a column which shows the date the user was last active. There are many branch lists with inactive users, which will show 'not finished for the year'. This will will help coordinators better manage their network and workload when chasing data.

<img width="719" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/ded3eabb-447b-40bb-aa1c-d30eece8e001">

If it is an easy job, is it possible to lighten the red rows or darken text in the table to aid reading.  Thanks

**Comment by Gary-van-Breda** [comment]
Code change done: last accessed column added to the list of users, and striping removed from table.
Deployed to Live.
@RachaelConway : please check if OK

**Comment by RachaelConway** [comment]
@Gary-van-Breda excellent thanks
