### ISSUE TITLE
Maximum number of Sections on a transect

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#344]
Hi @DavidRoy 

There should be a maximum of 15 sections to a transect, and I'm sure that was originally built into the Site Details page for any new sites being set up.

However, it looks like that's no longer the case, as a recorder has managed to set up a new transect with 17 sections:
https://ukbms.org/site-details?id=332611

Could we please make sure the Site Details page only allows 15 sections?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Fix deployed to Live

- Config set to max number of sections=15 for Transects, previously using 20 (is fixed at 10 for WCBS)
- Max value enforced on number of sections field on main page. 
- Insert and Delete section buttons removed when number of sections fixed.
- Insert section button now disabled when max number of sections reached.

If there are more than 15 sections already, then no more can be added, but some can be removed.

@IanMiddlebrook can you have a look, and check if you are happy?
