### ISSUE TITLE
Confidential Sites have disappeared from Annual Summary Page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#345]
Hi @DavidRoy @Gary-van-Breda @JimBacon 

Anyone who can help?

The Annual Summary page no longer lists any of the Sites that have been marked as 'Confidential', which means I'm unable to access their 2023 counts.

These Sites used to be listed there in italics (in the drop-down list 'filter by site'). They should be visible to Admin, and they should be visible to anyone who has been assigned to those sites, either as a User or a Branch Manager.

This is critical for my final data download.

Many thanks, Ian

**Comment by DavidRoy** [comment]
@johnvanbreda is this an unintended consequence of the wider work on handling sensitive/confidential data?

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy @johnvanbreda 
Is there any progress on this -it's a matter of extreme urgency?

In fact, the situation has become worse, as I'm now no longer able to see any data for sites in the Raw Data tab, which means I've lost the direct link to any walks that I may need to review/edit.

We are also finding that many downloads for individual sites are completely blank, despite being able to see data in the Summary Table.

Please advise.

Thanks, Ian

**Comment by johnvanbreda** [comment]
@IanMiddlebrook I've fixed the inclusion of sensitive sites so that it works as before. Hopefully that will fix the other issues as they may have the same underlying cause - please can you check?

**Comment by johnvanbreda** [comment]
@DavidRoy FYI The change goes back to October - when the way a 0 parameter value was treated for report parameter filters that didn't specify a value was altered. The way UKBMS does it here is a bit ambiguous, hence the change, but I've reset the warehouse code to as it was before (but tidied, which was the intention of recent changes in this area).

**Comment by IanMiddlebrook** [comment]
Brilliant - thanks @johnvanbreda - sensitive sites have returned and it looks like the Raw Data Table has returned to normal. 

I've asked a colleague to check the problems she was having, and will close if all OK.

I don't know exactly when this problem first occurred, but we were definitely able to see/download sensitive site data just a few weeks ago.

Thanks, Ian
