### ISSUE TITLE
Year by Year Index Plot - messy axis

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#346]
Hi @DavidRoy 

We've had a few comments about the labelling on the x-ais of the Year-by-Year Index Plot.
With lots of years data, the four figure years overlap, leaving quite a mess (see image).

Would it be possible to either reduce the years to two figures (76, 77, 78 ... 20, 21, 22) or to turn the labels by 90 deg for vertical alignment?

<img width="802" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/24699793/7904df60-00d5-4b38-9a26-4cde75ba8579">

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
Code fixed: if over 30 years displayed, switches to 2-digit year, if over 50 years displayed, only shows every second year. There are no options to rotate the labels.
Deployed to Live: @IanMiddlebrook can you check if you are happy?
