### ISSUE TITLE
Transect data is not coming up on walk data entry page

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/UKBMS-online#348]
@Gary-van-Breda James is having difficulty getting data on "Walk Data Entry" page. See the screenshot.
![Screenshot 2024-04-23 093845](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/5941255/fbf3a44e-c8b2-4afd-b777-6edd2d446332)

**Comment by BirenRathod** [comment]
@Gary-van-Breda or @DavidRoy Can you amend my permission on this repo, please? I can't able to assign somebody or add labels.

**Comment by DavidRoy** [comment]
@BirenRathod we need more information I think. Which url is this from so we know the transect site etc

**Comment by BirenRathod** [comment]
@DavidRoy It is from this -> https://ukbms.org/input-data?sample_id=25413406 page

**Comment by BirenRathod** [comment]
@DavidRoy Do you need his userID? I can email you.

**Comment by Gary-van-Breda** [comment]
The Fontmell Down site has no child section locations.

**Comment by Gary-van-Breda** [comment]
It looks like this is the first walk that is being entered on this site using the front end - the others look like data uploads.
We will need to create the section location records first, before any walk data can be entered.

**Comment by BirenRathod** [comment]
@Gary-van-Breda I forwarded his email to you, so if you can respond to him would be great.

**Comment by DavidRoy** [comment]
@IanMiddlebrook this might need you to support the recorder in terms of how to setup the transect?

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Is it worth me putting in the section records themselves (without any route or details data)? This would allow the walk itself to be entered.

**Comment by Gary-van-Breda** [comment]
It looks like the recorder is covering for someone else, and has been (temporarily) allocated the wrong transect: they have been given "Fontmell Down ST880170" when it should have been "Fontmell Down (DWT) ST885180"
I have allocated them to the DWT site, and asked them if (a) they are happy deleting the walk and (b) whether they want to to have "Fontmell Down ST880170" removed from their list.

@DavidRoy @IanMiddlebrook I think we should leave "Fontmell Down ST880170" as it is - there is no need to set it up as part of this issue, neither will I upload blank sections.

**Comment by Gary-van-Breda** [comment]
So In summary:
1) I have assigned the user "Fontmell Down (DWT) ST885180"
2) The recorder has deleted the initial walk
3) The recorder has re-entered the walk against the correct Transect, complete with occurrences
4) I have removed "Fontmell Down ST880170" from their assignment list

The user has been kept informed via email.
Closing as complete.
