### ISSUE TITLE
Apache URL length limit breached

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/UKBMS-online#35]
Zoe Randle has had problems accessing her data on the annual summary page.

I believe that we have hit a limit in apache (the webserver software). The request to fetch the location list for a user includes a filter defining all the location IDs that have been assigned to the user: for Zoe this has gone over the (approx.) 8177 character limit.
The temporary work around would be to deassign Zoe from some locations.
This is not UKBMS specific.
 
On a technical front, we may have to rewrite some of the code to do a POST request, not a GET request (helper_base.php line 2169)

**Comment by Gary-van-Breda** [comment]
I've dropped a codefix into develop and a hotfix branch.
@BirenRathod : Do you know what code version of IForm we have on the the Live UKBMS (D7) site?

**Comment by BirenRathod** [comment]
I just copied the iForm module from test site. So basically it has got all your changes copied from my machine. It is difficult maintain direct from the repository due to nature of development.

**Comment by Gary-van-Breda** [comment]
@BirenRathod Could I have a zipped/tarred copy of the current Live iform? that way I can send you an updated version of helper_base.php which has a fix for this (which has been put into the client_helpers github)

**Comment by BirenRathod** [comment]
@Gary-van-Breda , I have attached the zip file here.
[iform.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1187951/iform.zip)

**Comment by Gary-van-Breda** [comment]
@BirenRathod : could you deploy the following file into the UKBMS site? Thanks
[helper_base.php.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1268479/helper_base.php.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda - This has diployed.
