### ISSUE TITLE
site map isn't loading 

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#353]
@DavidRoy @IanMiddlebrook 

Map missing from Sites https://ukbms.org/sites.

Map fails to load.

![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/1378607a-d7e4-4c33-94e6-f553d021d5dc)

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : this looks like it is no longer an issue. Can we close it?
