### ISSUE TITLE
Timed counts - upload timing out. 

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#354]
Hi @DavidRoy @IanMiddlebrook 

I have received three complaints that the timed count submit page keeps timing out. The data doesn't appear to have saved.  I have tried myself and experienced same.

Thanks 
Rachael

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you look at this please

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy @Gary-van-Breda 
There still seems to be a big problem with this Timed Count data entry page, particularly when going back to look at an existing count.
The first page uploads OK, but when you click next to see your previous count or add a new count for the same site, the page is timing out.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : I've deployed a performance improvement when displaying the second page for existing data (it now uses a different, more efficient report to fetch the list of occurrences from the database.)
Can you check to see if this has sorted the issue, or is there another situation where the performance of this page is lacking?

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 

That seems to have done the trick.
