### ISSUE TITLE
Newly assigned sites not appearing in Enter Count drop down

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#355]
Hi @IanMiddlebrook @DavidRoy 

Not sure how widespread this is -  but a user has reported that a newly assigned transect is not appearing in the Enter Count https://ukbms.org/enter-count   or via the My walks https://ukbms.org/my-walks . The **enter walk for this site** option via link tab in site details route is possible. See below 

![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/5c118389-d67d-411b-a626-be65be39bbc7)
![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/54d81d54-7bb3-45c3-a36d-45cc9b1eadcb)

Thanks

**Comment by RachaelConway** [comment]
Hi @DavidRoy more reports of this coming in now - so I have added urgent label - thanks

**Comment by Gary-van-Breda** [comment]
@RachaelConway Fix deployed (removed the caching used in the walk DE page on the lists of sites allocated to a user as either a normal recorder or at a branch level).

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 

Rachael has moved on, so please assign myself to any of the issues that she raised.

Best wishes, Ian
