### ISSUE TITLE
Data Entry Options not working

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#356]
Hi @DavidRoy @Gary-van-Breda 

On the Data Entry page - the second page where you enter the counts - it seems that none of the option buttons are working.

The page loads with the default species list (Species Known at this Site), but clicking on any of the other options - either different taxa or different butterfly species list is having no effect. 

Also, the search box for new species is not functioning.

This means it's currently not possible for recorders to enter moth records or enter counts for new species.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
It would appear that the Bootstrap theme was updated today. Following this, the page is raising a javascript error when trying to access the table sticky header functionality (which displays the species table header including the species autocomplete when scrolled out of view).
I am investigating how to fix this.
FYI @BirenRathod

**Comment by Gary-van-Breda** [comment]
Actually, in Drupal 10.3.0 (also updated today) the tableheader functionality was changed from JS to CSS based. This means that
1) I will have to rewrite some of this code.
2) The contrib Bootstrap 3.31 theme (and hence the UKBMS custom theme built on top of it) is not strictly compatible with Drupal 10.3.0, as it too relies on tableheader being JS.

FYI @BirenRathod

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook In the mean time, I have changed the form config to move the species autocomplete to under the relevant grids: this should allow entry of new species and all the other controls/options should work.

**Comment by BirenRathod** [comment]
@Gary-van-Breda @johnvanbreda has made some changes, so these control/options should work. I'm at present in the process of releasing the code, so should not take long.

**Comment by BirenRathod** [comment]
@IanMiddlebrook I updated the code, can you check all is working as expected, please?

**Comment by BirenRathod** [comment]
@Gary-van-Breda There is a deprecated function error generated consistantly. If you can resolve that would be appreciated.
See this log -> https://ukbms.org/admin/reports/dblog/event/1448841

**Comment by andrewvanbreda** [comment]
@BirenRathod @DavidRoy 
I have just checked the UKBMS data entry form due to the raising of https://github.com/BiologicalRecordsCentre/ABLE/issues/701 and it is reacting OK unlike EBMS.
This is just a simple test to make sure the Javascript is reacting, obviously wait for Ian's own comment, but that is my observation.

**Comment by andrewvanbreda** [comment]
Be aware that Gary has mentioned he put in a workaround for EBMS and UKBMS as part of https://github.com/BiologicalRecordsCentre/ABLE/issues/701
I am not sure if this might be the reason UKBMS was OK for me, as I may have tested after he did that.
Either way it should be working OK.

**Comment by Gary-van-Breda-EdiUni** [comment]
@andrewvanbreda : yes it is the reason. I'll apply the changes to both UKBMS and EBMS (they use the same form) before switching the config back over on both sites.

**Comment by IanMiddlebrook** [comment]
Appears to be  working OK for me now - though, following the posts above, not sure which version is currently live.

Thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook it is on latest version.

**Comment by Gary-van-Breda** [comment]
Proper fix (as opposed to work around above) deployed to Live. Now uses CSS based sticky headers. Form has been reconfigured back so that the species autocomplete is now above the species grid, as it was up to yesterday.
@IanMiddlebrook : if you are happy, this can now be closed.

FYI @andrewvanbreda : I'm just about to implement the same change on EBMS.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
All looks to be working well again.

Thanks for quick response, Ian

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
Sorry to re-open this one.
I have a recorder who insists he is still unable to enter his moth data.
He is using Microsoft Edge (as am I). He has rebooted his computer.
I've masqueraded as him, and been able to bring up the moth list.

Is there any obvious reason why he might still be having a problem?

Robin Griffiths - Indicia Warehouse User ID 97048

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook The most likely reason is that his browser has cached an old file version. If possible, he should clear his browser cache.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda  
I made a couple of suggestions and all is resolved.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
Sorry to re-open this one again.

We have one user whose problems seem to be a continuation of this problem from last week, although he has only come across it this week. He is unable to add new species, and the moths etc buttons are not working.

Ken Orpe - Username: butterflyken  Indicia warehouse ID: 76159
![UKBMS QUERY](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/24699793/1d95681a-62cd-4b4d-92f0-3e78da3a35cc)

He is using an Acer Desktop PC with Windows 10.
He has tried clearing the cache and refreshing the page - but still no change.

He is happy for someone to get access to his computer via Team Viewer if necessary.

Is there anything that can be done to help?

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
The fact that the species box is small means that there has been a Javascript error somewhere (the autocomplete setup has failed), also backed up by the presence of the Top link.

I take it he has tried clearing their browser cache?

I have reset the caches on the server, and set the JS aggregation on: could they try again?

**Comment by IanMiddlebrook** [comment]
Many thanks @Gary-van-Breda 

Whether it was what you did, or what Ken did, I've no idea, but I had a message from him on Saturday to say that he'd cleared his cache from the last month rather than the last week, and the problem has resolved.

Thanks again, Ian
