### ISSUE TITLE
Annual Summary page unavailable

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#357]
Hi @DavidRoy @Gary-van-Breda 

I've not been able to access the Annual Summary page for a couple of days.

Every time I try, I get the message:
_The website encountered an unexpected error. Try again later._

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook 
I haven't had joy trying to replicate this - masquerading in as you shows the page as normal for me. Can you confirm that this is still happening to you, and if possible include a screen shot with an approximate time you had a instance of the problem - this may help us when looking at the logs.

Thanks, Gary

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 
It's been doing it all day, and again after you commented.

But I've just logged out, cleared my cache and logged back in, and now it all seems to be OK.

Apologies, Ian
