### ISSUE TITLE
Data entry not working for WCBS-BBS sites

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#358]
Hi @DavidRoy @Gary-van-Breda 

There seems to be an issue with data entry for WCBS-BBS sites.

Trying to enter data via 'Enter Count' and selecting WCBS-BBS, or via My Walks, or trying to edit an existing walk (e. via [https://ukbms.org/input-bbs-data?sample_id=26694962](https://ukbms.org/input-bbs-data?sample_id=26694962) ) just takes the recorder to a Welcome page - seems like the links are broken somewhere.

As a consequence, WCBS-BBS recorders are currently unable to enter any counts.

Transect and WCBS-BC data entry seems to be working fine.

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook 
The WCBS-BBS data entry page had been deleted (node 295).
I have re-constructed it in a new node (367) from a backup.

I can't tell when the deletion occurred (other than it was after March 23rd), nor by whom.

Please let me know if any links are still pointing to the old page (which would be in "node/295" format) and I can change them - there shouldn't be any, and I can't see any in the database.

FYI @DavidRoy

**Comment by IanMiddlebrook** [comment]
Many thanks @Gary-van-Breda
