### ISSUE TITLE
website not functioning

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#359]
Hi @DavidRoy @BirenRathod @Gary-van-Breda 

There seems to be a fatal issue with the website at the moment, with most pages returning this message:

_The website encountered an unexpected error. Try again later._

I suspect you're already onto this, as it looks like the same is true of iRecord.

Thanks, Ian

**Comment by DavidRoy** [comment]
@BirenRathod any insight on this?

**Comment by BirenRathod** [comment]
@DavidRoy the same issue causing on iRecord and @johnvanbreda is implementing a code to resolve this.

**Comment by johnvanbreda** [comment]
@BirenRathod I've added the temporary fix to the dev environment so you can test and deploy it.

**Comment by BirenRathod** [comment]
@DavidRoy & @IanMiddlebrook It has resolved now. @johnvanbreda I will update that soon.

**Comment by IanMiddlebrook** [comment]
Hi @johnvanbreda @BirenRathod 

This has resolved for me on almost all pages, but the exception is the Annual Summary page [https://ukbms.org/annual-summary](https://ukbms.org/annual-summary) which continues to bring up the same error message.

Thanks, Ian

**Comment by johnvanbreda** [comment]
@BirenRathod - see email just sent, I hope the solution to this is to clear both the following folders:
* /files/reportsDownloads (any file older than 1 hour)
* /files/private/indicia/cache/httpswarehouse1indiciaorguk

**Comment by BirenRathod** [comment]
@johnvanbreda I sent you an email already at 16:48, it is still working, so please wait for my next update.

**Comment by BirenRathod** [comment]
@johnvanbreda I removed files from both folders now. it took 4 hours 50 minutes to clear files from /files/reportDownloads folder. 
@IanMiddlebrook I checked the Annual summary page. First, it showed "The application did not respond in time" error, so I refreshed the page and it worked fine. It may cause more trouble in accessing reports.

**Comment by johnvanbreda** [comment]
@BirenRathod I can see that the cache folder is empty now, but FileZilla thinks there are still 31,571 files in reportsDownloads  (approx. 74Mb), going back as far as March. I am still unable to delete any of them.

I can recreate the problem still - go to the annual summary page, then select Data set: Full data set (all users).

**Comment by BirenRathod** [comment]
@johnvanbreda That is because you opened it earlier and did not refresh the folder from FileZilla. Check again and see if that make any difference. I checked again this morning and there are only 112 files created this morning in reportsDownload folder. no files from yesterday at all.

**Comment by johnvanbreda** [comment]
I did refresh my FileZilla and also I was having the same problem still, but I think that was related to file system caching between containers so your file deletions were not apparent yet. This morning it seems OK, so I'm implementing a cron hook in the iform module right now which will automatically clear the files.

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod @johnvanbreda 

The problem has resolved for me.

Best, Ian

**Comment by BirenRathod** [comment]
> I did refresh my FileZilla and also I was having the same problem still, but I think that was related to file system caching between containers so your file deletions were not apparent yet. This morning it seems OK, so I'm implementing a cron hook in the iform module right now which will automatically clear the files.

It happened same with me last night too but then I completely close my Sftp and logged back in which refreshed the folder.
