### ISSUE TITLE
Walk data Entry - order of butterflies

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#36]
The order of butterflies on the new Walk Data Entry page appears to be random.

Please re-instate the previous order, which was an old taxonomic order, which will then relate more closely to the recording forms that volunteers are using.

**Comment by Gary-van-Breda** [comment]
Related to new ability for users to select sort order of species. Fix corrects this. Note that the Moths/Odonata/Others pages also had "taxonomic sort order" sorting, but the UK master list does not have this set, so the sort order would be undefined (but not random). After this change is put in place, and the forms configuration set, these pages will be sorted by the common name. The main Butterflies page will have the ability to sort by either the taxonmic sort order or by the common name.

@BirenRathod 
Can you drop the **develop** branch versions of the following files into the UKBMS D7 and EBMS sites?
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/ukbms_sectioned_transects_input_sample.php
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/js/ukbms_sectioned_transects_input_sample.js

**Comment by BirenRathod** [comment]
@Gary-van-Breda & @DavidRoy - These files have been updated on both sites.

**Comment by Gary-van-Breda** [comment]
Looks OK to me now.

**Comment by IanMiddlebrook** [comment]
Thanks Gary,

Looks OK to me.
