### ISSUE TITLE
Data Entry not working for WCBS-BC squares

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#360]
Hi @DavidRoy  @Gary-van-Breda 

There is an issue with data entry for WCBS-BC sites.

Trying to enter data via 'Enter Count' and selecting WCBS-BC, or via My Walks, or trying to edit an existing walk just takes the recorder to a Welcome page - seems like the links are broken somewhere.

As a consequence, WCBS-BC recorders are currently unable to enter any counts.

**This seems to be an exact replica of the problem we had with WCBS-BBS squares a couple of weeks ago (#358 ) which was a result of the data entry page having been deleted from the website.**

How is it that these critical pages are being deleted?

Transect and WCBS-BBS data entry seems to be working fine.

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
I can confirm that the WCBS-BC walk DE page has been deleted. I will reconstruct it, as I did the other.

**Comment by Gary-van-Breda** [comment]
Note that anyone with "administrator" or "admin user" role can delete the iform contents - I will remove the permission from "admin user" as that is more widely assigned.

**Comment by IanMiddlebrook** [comment]
> Note that anyone with "administrator" or "admin user" role can delete the iform contents - I will remove the permission from "admin user" as that is more widely assigned.

I see, so we think that someone with 'admin user' rights has deleted the form by accident - probably thinking that they were just deleting a single sample?

Hopefully removing those rights will mean this doesn't happen again.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda  is there any update on this? I imagine there maybe a lot of recorders trying to upload WCBS data over the weekend.

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
I've re-instated the page, and tweaked the permissions to make it more difficult to delete in the future.
@IanMiddlebrook : Can you check it all looks ok?

**Comment by zrandle** [comment]
hi there, WCBS data entry is still not working - there are no species listed... I've attached  screenshots 
![Screenshot 2024-08-09 150428](https://github.com/user-attachments/assets/9cbbd39a-267b-4f33-88fa-8e11305ebf25)
![Screenshot 2024-08-09 145924](https://github.com/user-attachments/assets/3d85f870-2ed7-40bd-8ace-98b1b83a85d4)
Data were entered for ST7202 last Friday - I tried to review today but nothing showing. Tried to enter data today for SY6598 but unable to!  Thanks Zoe

**Comment by Gary-van-Breda** [comment]
@zrandle : I've cleared the caches and it's now looking OK to me. Can you try again?

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda 
I can see Zoe's data from last Friday.

As for the permissions - it looks like an 'admin user' will still see the Delete tab - I didn't dare touch it, but would it be ineffective?
<img width="564" alt="image" src="https://github.com/user-attachments/assets/9ca38518-f8e7-42e5-ba03-d5d6b942b1b8">

Thanks, Ian

**Comment by zrandle** [comment]
> @zrandle : I've cleared the caches and it's now looking OK to me. Can you try again?

Yes, looks good now thanks!

**Comment by zrandle** [comment]
> Thanks @Gary-van-Breda I can see Zoe's data from last Friday.
> 
> As for the permissions - it looks like an 'admin user' will still see the Delete tab - I didn't dare touch it, but would it be ineffective? <img alt="image" width="564" src="https://private-user-images.githubusercontent.com/24699793/356973791-9ca38518-f8e7-42e5-ba03-d5d6b942b1b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTU1NDQsIm5iZiI6MTcyMzQ1NTI0NCwicGF0aCI6Ii8yNDY5OTc5My8zNTY5NzM3OTEtOWNhMzg1MTgtZjhlNy00MmU1LWJhMDMtZDVkNmI5NDJiMWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA5MzQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NjEwYjFmMGM2ZGQwYThkOGNmNjRmNDJlY2ExMWNlZDJmNjkyNjM3OTUyMGIxN2UzODg4OGY1MGI5MmZhYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ivEBwRtquwEYz-eeHliogS8ShWSj3VOEv2qhoNlw8OM">
> 
> Thanks, Ian

I can still see the delete button too and I will NOT touch it (again??!!)

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @zrandle : I've just removed the "Administer content", "Administer content types" and "Bypass content access control" from the "admin user", "site editor" and "verifier". Masquerading in, it looks like the Delete tab is now gone for you @zrandle .

If these roles need access to certain content types, the permissions should be granted at a content type/operation level - some of which are already granted, so hopefully there will be no impact other than preventing accidental deletion of the IForm pages.

**Comment by zrandle** [comment]
The delete button has gone from my view! Phew! Thanks

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda
