### ISSUE TITLE
Annual Summary page filters

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#361]
Hi @DavidRoy @Gary-van-Breda 

There has been a slight change in behaviour on the Annual Summary page, when changing some of the filters.

Previously, if you selected one of your sites under 'Filter by Site' and then moved to select the Full Data Set, the selected site would be remembered, so you would see all walks just for that site.
But now, when you move to select Full Data Set - you lose the selected site, and it shows you the full data set for all sites, so you then need to select your individual site again to get what you were looking for.
The same happens if you select Branch Data.

Is it possible to get  this page to remember your selected site?

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook Fix applied to Live. Also now keeps the same location when the year is changed.

**Comment by IanMiddlebrook** [comment]
That's great - thanks @Gary-van-Breda
