### ISSUE TITLE
Problem with Timed-count data entry

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#362]
Hi @DavidRoy @Gary-van-Breda 

There seems to be a problem in selecting species for the Timed-Count data entry page, which is preventing recorders from saving their counts.

Recorders can set up their site and get through to the second page, but when they start typing the name of their Species, nothing happens - the autofill is not working, there are no suggested species to choose from, and they are not able to save their count.

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook Fix deployed to Live - now looks OK to me. Was related to recent change re display of grid reference in map on front page.
(You may need to clear browser cache)

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda
