### ISSUE TITLE
UKBMS website - drop down filters and buttons not working

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#367]
Hi @DavidRoy @Gary-van-Breda @andrewvanbreda

Not sure who is best placed to look at this urgent problem, but the website is failing on a few fronts this morning.

On the Annual Summary page, none of the drop-down menus are having any effect. If you try to change the year or the data set or look at an individual site, nothing happens.

On the Data entry page, once you get through to page 2, none of the buttons work - ie. you can't change the species list, you can't enter data for moths/odonota/others.

This has been reported by a few co-ordinators over the weekend, and is making it very difficult for them to validate local data.

Any help appreciated.

Many thanks, Ian

**Comment by andrewvanbreda** [comment]
I have put the site into maintenance mode.

@BirenRathod
Would you be able to look at this please? It looks like lots of Javascript errors, I can only assume related to Friday's Drupal updates. Cheers

@IanMiddlebrook 
If this is blocking your work, please use my developement site here.

https://avb-iform-brc-ukbms-d10.pantheonsite.io

It is a clone of live as it was just before Gary fixed the confidential sites not showing problem, so that fix is not on there.
If you desperately need that fix, let me know and I will look to see if it is possible to bring it to my development site without the other breakages.

Actually I would be interested in your impressions of how well this development site is working, as it includes major changes in the background that will eventually go onto live (the functionality is the same, it is just changes related to running the latest version of particular modules).

**Comment by BirenRathod** [comment]
@andrewvanbreda & @IanMiddlebrook  I'm looking into that. 
@andrewvanbreda  Can I ask you to check other website like NPMS, if similar issues are exist?

it seems like these are specific to iForm module.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod
Will do. I will let you know, although I already very briefly checked EBMS/NPMS and they seemed OK on first glance.

If we find it is a problem with UKBMS running old code again, let me know and we can discuss what to do, as actually I have been doing quite a lot of work in the area of that, I just haven't got round to posting my findings to you and John yet as been too busy.

**Comment by BirenRathod** [comment]
@andrewvanbreda  The errors are generating from an old jquery module. And I know that John had already upgraded the module in the latest iform release, so please plan to release your changes if possible.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
OK. I will look into this now.

I have checked some of the other sites.
They seem OK as far as I can tell, apart from one issue. Sometimes the map isn't displaying.
This includes on UKPoMS data entry forms
e.g. this one https://ukpoms.org.uk/enter-fit-count

The SPRING transect editor also doesn't show its map
https://pollinator-monitoring.net/transect-setup?id=325611

On iRecord, on the enter casual record page i had the same issue, but on the second load it showed OK.
I can only assume this issue affects all sites but it isn't always visible.

There are no errors about it the javascript notices.
I am not sure if this is related but I saw this in the SPRING logs:
Message 	User warning: The following theme is missing from the file system: jquery_ui_resizable in Drupal\Core\Extension\ExtensionPathResolver->getPathname() (line 63 of /code/web/core/lib/Drupal/Core/Extension/ExtensionPathResolver.php) 

Anyway, I will look at what needs to be down about getting UKBMS updated right now. I will let you know, probably in about an hour or two.

**Comment by IanMiddlebrook** [comment]
Hi @andrewvanbreda @BirenRathod 
The maps are also not displaying on the UKBMS - eg. Site Details page and Section Route tabs

**Comment by BirenRathod** [comment]
@andrewvanbreda  The error on SPRING website suggest, it needs to enable the jquery_ui_resizable module. I just enabled that module on spring which should stop generating that error.

**Comment by BirenRathod** [comment]
@andrewvanbreda I sent you an email with more details.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod (note this is the same message I accidently just pasted into the UKPoMS Github thread too),

I have finished checking a cloned version of the site from about a week or 2 ago with iForm update, and it looks OK.
So I think we can do a UKBMS full iForm update if needed.
Note there is some risk to this, as I can't test some elements of the site (such as site assignments).
Gary was going to take a look at this, but I think this is getting urgent enough not to wait for him.

However, as noted in my email to you, doing that will not fix the other errors being experienced this morning. Things like missing maps/Drupal Javascript errors are occurring on other sites such as UKPoMS. The errors also still occurred on my UKBMS multidev site even after it was manually iForm updated.

I suggest getting those problems fixed on all sites before we do an iForm update on UKBMS though......unless we need to iForm update UKBMS to get it working.

If you need help from John, I might suggest contacting him directly (although I did mail him).

Note that the following sites are all in maintenance mode at the moment

UKBMS
SPRING
UKPOMS

**Comment by BirenRathod** [comment]
@andrewvanbreda thanks for these update.

I suggest we fix issues related to the map first. I already emailed to @johnvanbreda about it.

**Comment by BirenRathod** [comment]
@johnvanbreda I have removed the jQuery from the theme on https://dev-brc-ukbms-d10.pantheonsite.io/

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
The site is behaving much better now with the maps and Annual report working.

There is still an error, but it does not seem to stop the pages being used.
Uncaught ReferenceError: $ is not defined
<anonymous> https://dev-brc-ukbms-d10.pantheonsite.io/themes/custom/ukbms/js/scripts.js?snveeu:1

**Comment by BirenRathod** [comment]
@andrewvanbreda I will release the code for now. It seems like the jQuery added in the theme is the main culprit. On all those sites above mentioned have got similar issue.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Yes please do, let me know when done so I can check and take sites out of maintenance mode.

**Comment by BirenRathod** [comment]
@andrewvanbreda I updated the theme and removed the site from maintenance mode.
@IanMiddlebrook please check if everything is working as expected.

**Comment by andrewvanbreda** [comment]
@BirenRathod
Thanks Biren.
This looks like it is working to me.
Perhaps while waiting for any feedback from Ian, the fixes could be prepared for released to other affected sites like UKPoMS/SPRING
Thanks

**Comment by IanMiddlebrook** [comment]
Thanks @andrewvanbreda @BirenRathod for resolving this so quickly.

All those issues now seem to be working as normal.

Best wishes, Ian

**Comment by BirenRathod** [comment]
[like]  Biren Rathod reacted to your message:
________________________________
