### ISSUE TITLE
Walk data Entry - movement within entry form

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#37]
Up/down keys were previously useful in moving from one row to the next on the Data entry grids.

These no longer seem to work, only left-right keys.

Please allow use of up/down keys to navigate around the grid.

**Comment by Gary-van-Breda** [comment]
Related to change in jQuery version, and identifying the correct field in the following and previous rows.
Fix included with code that will be deployed for #36.

**Comment by IanMiddlebrook** [comment]
This was not fixed with the code for #36

**Comment by Gary-van-Breda** [comment]
What browser are you using?
It looks OK to me: http://www.ukbms.org/mydata/input-data?sample_id=2338552 on Firefox. I can navigate around the grid using the arrow keys (both separate keys and the numberpad)

**Comment by DavidRoy** [comment]
Works for me on chrome but I had to update to latest version first.

**Comment by BirenRathod** [comment]
looks good on IE too.
