### ISSUE TITLE
Walk Data Entry - Moths and Odonata

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#38]
Previously recorded Moths and Odonata should appear on the relevant data entry pages by default.

It seems that these have now migrated to the 'Others' entry page. 

Please move them back to their relevant data entry pages.

**Comment by Gary-van-Breda** [comment]
Also related to new ability for users to select sort order of species.
Fix included with code that will be deployed for #36

**Comment by IanMiddlebrook** [comment]
This was not fixed with the code for #36

**Comment by Gary-van-Breda** [comment]
What browser are you using? Can you give an example of a visit where this shows up?
If I look at http://www.ukbms.org/mydata/input-data?sample_id=2406868 (using Fiefox), then is shows Moths and Odonata in their grids, and fills in the counts correctly as well.

**Comment by DavidRoy** [comment]
All looks for for me on Chrome

**Comment by IanMiddlebrook** [comment]
My walk at Lulworth yesterday http://www.ukbms.org/mydata/input-data?sample_id=2577740 

![image](https://user-images.githubusercontent.com/24699793/27330685-670ddcf4-55b2-11e7-9cff-3903bf3ad8ae.png)

Using Google Chrome

**Comment by IanMiddlebrook** [comment]
Version 58.0.3029.110

**Comment by DavidRoy** [comment]
Goto: chrome://settings/help 
to update Chrome?
Fine for me on Version 59.0.3071.104 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/2699478/27330836-f5e74032-55b2-11e7-843b-cdbdf9f70dd5.png)

**Comment by IanMiddlebrook** [comment]
It just updated automatically after I checked the version! 
Now working for me on
Version 59.0.3071.104

**Comment by DavidRoy** [comment]
Great.  Close if now resolved?
