### ISSUE TITLE
New User Notification

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#39]
Please add the fields: _First Name, Last Name _and_ About Your Transects_ to the notification emails I receive from brc@ceh.ac.uk each time a new User registers.

**Comment by BirenRathod** [comment]
Notification emails have been implemented. Fields name have been added.

**Comment by DavidRoy** [comment]
Thanks.  @IanMiddlebrook please close if issue now resolved

**Comment by IanMiddlebrook** [comment]
Thanks
