### ISSUE TITLE
Recorder Name

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#40]
On the Walk Data Entry page, the Recorder Name defaults to the account Users name, but it is possible to over-write this if someone else walks the transect.

If you have used a different recorder's name before, this box used to work with auto-complete in order to save time.

What seems to happen now, if you try to over-write the name, is that there is no auto-complete and you just get a continuous rotating arrow in the box, even if you finish writing the name and move onto another field.

I presume that's not the way's it's intended to work?

Perhaps someone could take a look.

**Comment by Gary-van-Breda** [comment]
No. The name lookup report is returning a null name when run by you, this is causing the filter functionality to fall over. I will update the report to ensure no nulls are returned.

**Comment by IanMiddlebrook** [comment]
I assume this is still outstanding, and does not just affect me, as per this email received today:

_Hi Ian,
When recording walks for other walkers in the rotas, I need to change the Recorder Name from my own. The behavior of the entry field as soon as I start to add the new name is to spin the two arrows as if it were trying to look up the name...but it never completes. Is this just down to performance as I recall it did work in the past?
Cheers,
Kelvin Richards_

**Comment by Gary-van-Breda** [comment]
Code lodged into warehouse - see pull request 266.

**Comment by Gary-van-Breda** [comment]
Code deployed (warehouse 1.39.7) & checked on Live - both for you @IanMiddlebrook and Kelvin.
Close?

**Comment by IanMiddlebrook** [comment]
Thanks Gary
