### ISSUE TITLE
Site Assignment page freezing

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#41]
HI 

Is there a problem with the site assignment page? I've been linking a Branch Champion to squares, the page has frozen and all allocation for the Branch Champion have been lost :(

**Comment by zrandle** [comment]
typical technology - that issue has passed. HOWEVER, the Branch Champion has also be allocated as the recorder for the squares!

**Comment by zrandle** [comment]
Right then. Branch Champion un-allocated as recorder for all squares.

**Comment by Gary-van-Breda** [comment]
@zrandle : have you continued to have problems with this page?

**Comment by zrandle** [comment]
@Gary-van-Breda it seems to be OK now although when allocating several branch admins one after another the select all button appears as another deselect all button. 
![image](https://user-images.githubusercontent.com/23524520/29869767-3cef3cf4-8d7c-11e7-80fc-a4b538f2dd25.png)

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you deploy the files in the following zip into both the EBMS and UKBMS websites? Thanks

[ebms_transects_allocation.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1268421/ebms_transects_allocation.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda, This has diployed now.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : it doesn't look like the JS file in the zip has been deployed into UKBMS. Can you double check please?

**Comment by BirenRathod** [comment]
Yes, I missed that, Diployed it now.

**Comment by Gary-van-Breda** [comment]
@zrandle : Close?
