### ISSUE TITLE
WCBS-BC walk migrating to Transect page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#42]
Username 'RABGeorge' has entered a walk for WCBS-BC square ST8719 on 18th July 2017 (sample-id 2695984).

This square is designated as Site Type WCBS-BC and was assigned to him as such,  so he could only have entered the data through the WCBS-BC Walk Data Entry form.
However, on the My Walks page, this walk only appears in his calendar under Site Type: Transect.

The confusion continues on the Annual Summary page, where the walk data (sun, temp) sort of appears on the Raw Data tab under WCBS-BC, but the counts only appear when you change the Site Type to Transect , even though ST8719 does not appear in the drop down list under Transect.

Very confusing.

Any ideas how this has happened, and can it please be rectified?

**Comment by Gary-van-Breda** [comment]
There is a bug in the My Walks grid page, which meant he entered a WCBS location walk using the Transect walk entry page.

**Comment by Gary-van-Breda** [comment]
How to reproduce:
Make the WCBS-BC the default location type (Go to My Walks: select WCBS-BC; Navigate to My Sites: this shows WCBS-BC Sites)
Navigate back to My Walks: this shows WCBS-BC walks.
Choose a BC location in the sites filter: the page is redisplayed, but with the site type Transect, and no location in the location filter. All the "add walk" links now point to the "add transect walk" form, but with the BC location.

**Comment by Gary-van-Breda** [comment]
Updated / simplified how to reproduce cause:
Make the WCBS-BC the default location type (Go to My Walks: select WCBS-BC; Navigate to My Sites: this shows WCBS-BC Sites)
Navigate back to My Walks: this shows WCBS-BC walks.
Refresh Page: Page now shows transects - it has lost the cookie data storing the location type.

**Comment by Gary-van-Breda** [comment]
2 stages:

- Update the my walks and branch walks reports: Code in warehouse awaiting deployment (see warehouse Pull request 267)
- After these deployed, then update the report calendar grid form so it does not set the location_type_id in the extraParams (which causes the cookie data to be removed).

**Comment by Gary-van-Breda** [comment]
Reports have been deployed to Live (1.39.7).
@BirenRathod or @JimBacon : can you deploy the following file to the UKBMS website: Thanks
[report_calendar_grid.php.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1263149/report_calendar_grid.php.zip)
After this is done, I'll fix the data.

**Comment by BirenRathod** [comment]
@Gary-van-Breda, This has now deployed onto UKBMS.

**Comment by Gary-van-Breda** [comment]
Data Fix:

@BirenRathod or @JimBacon : Could someone run the following sql against the warehouse?
UPDATE indicia.samples
SET survey_id = 305, update_on = now(), updated_by_id = 1
WHERE (id in (2699836, 2704803, 2673512, 2700308, 2669621, 2690716, 2702833, 2611135, 2628877)
OR parent_id in (2699836, 2704803,2673512, 2700308, 2669621, 2690716, 2702833, 2611135, 2628877))
AND deleted = false AND survey_id=64;
 
UPDATE indicia.samples
SET survey_id = 306, update_on = now(), updated_by_id = 1
WHERE (id in (2697385, 2702354, 2702031, 2703296, 2695984, 2687753, 2601317, 2688218, 2650277)
OR parent_id in (2697385, 2702354, 2702031, 2703296, 2695984, 2687753, 2601317, 2688218, 2650277))
AND deleted = false AND survey_id=64;


The cache tables should update automatically. The summary_builder tables will require some level of rebuilding : I will sort this out once the data scripts above are run. 

Location NT2466 (id 182539) has been added as a Transect, but the name is the same as a WCBS-BBS square. It has 2 walks in the Transects survey: 2710089, 2832730. Is this correct @IanMiddlebrook ?

In addition I will do the deletes for the following: 

- BC location NT4164 (id 120593), has a duplicate walk on the same date (18/06/17) in both the Transects and BC surveys: Check and delete sample 2702299.
- BC location NT-SO2817 (id 179906), has a duplicate walk on the same date (18/05/17) in both the Transects and  BC surveys: Check and delete sample 2561990.
- BC location NT-SS9901 (id 175430), has a duplicate walk on the same date (21/06/17) in both the Transects and BC surveys: Check and delete sample 2611023.
- BC location NT-ST7834 (id 175452), has a duplicate walk on the same date (05/07/17) in both the Transects and BC surveys: Check and delete sample 2670882.
- BC location NY1847 (id 118954), has a duplicate walk on the same date (08/07/17) in both the Transects and BC surveys: Check and delete sample 2681962.
- BBS location SU5375 (id 96194), has a duplicate walk on the same date (17/07/17) in both the Transects and BBS surveys: Check and delete sample 2702321.
- BC location TL8339 (id 117909), has a duplicate walk on the same date (06/07/17) in both the Transects and BC surveys: Check and delete sample 2686359.

**Comment by IanMiddlebrook** [comment]
"Location NT2466 (id 182539) has been added as a Transect, but the name is the same as a WCBS-BBS square. It has 2 walks in the Transects survey: 2710089, 2832730. Is this correct @IanMiddlebrook ?"

Unfortunately this is the recorder's error - they failed to find their WCBS square and set up a duplicate site as a transect. This is one for @zrandle  to sort out with the recorder at some point.

**Comment by BirenRathod** [comment]
@Gary-van-Breda and @IanMiddlebrook 
I have updated records by running above query. Total 99 records have been updated.
Please check if everything is ok or not.

**Comment by Gary-van-Breda** [comment]
NT-ST7834 : @zrandle or @IanMiddlebrook : Can you look at the following and tell me if I should merge the observations? The times on the samples don't match up so I don't know about their status as duplicates.
http://www.ukbms.org/mydata/input-bc-data?sample_id=2670841
http://www.ukbms.org/mydata/input-data?sample_id=2670882

**Comment by IanMiddlebrook** [comment]
Yes, looking at the counts, he has split data entry between 2 walks, one for sections 1-5 and the other for sections 6-10. They should just form one walk, starting at 12:05 and finishing at 14:25.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Another one perhaps for @zrandle ? There is a transect called BBS1 (TL8747) with one walk on (2017-05-03)

**Comment by Gary-van-Breda** [comment]
I have done the 7 deletes mentioned above (which included some data merging).
I have checked the walks - they have been moved over.
I will now trigger the summary_builder re-calculation (for the annual summary page) - this is required to remove the data from the Transects survey, and add it to the BBS/BC surveys, as appropriate.

**Comment by Gary-van-Breda** [comment]
I've just checked some random samples in the BC and BBS data, and with the way the update was done (setting the updated_on date on the sample) these have already been incorporated into the annual summary page. (I had to clear the IForm cache).

**Comment by Gary-van-Breda** [comment]
I think we have 2 options re the Transect annual summary data:
1) there is a background query that rebuilds the data slowly. We can let this work its way through the data, and it will try to rebuild the data for these sites,  and find that the samples are no longer there, and remove the data. It does the oldest data first, and because this data is recently entered, it will be some time before this is done - it could be a couple of months.
2) we can do a full rebuild of the data. This means removing all the Annual summary data for the Transects survey and recreating it, and will take a several days, during which time the annual summary page will show incomplete data.

Neither is ideal: @IanMiddlebrook which do you prefer?

**Comment by Gary-van-Breda** [comment]
Given the time that has passed since my comment above, the entire dataset should now have been rebujilt.
Close?

**Comment by DavidRoy** [comment]
@zrandle @IanMiddlebrook please check and close if resolved

**Comment by zrandle** [comment]
@IanMiddlebrook I'm happy are you?
