### ISSUE TITLE
Historic WCBS data showing wrong sunshine %.

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#43]
comment from Graham Upton regarding some historic WCBS data that is showing on the system:

"For TF8016 on 4 Aug 2015 Sun is recorded as 39…. but it was 78. Likewise on Jul 21 it is recorded as 49 when it should be 98."

So for some reason the sun% has halved. Perhaps this is true for other data uploaded to the site at the same time?

Zoe has confirmed Graham's values from the original data entered on the old system.

**Comment by IanMiddlebrook** [comment]
comment from Graham Upton regarding some historic WCBS data that is showing on the system:

"For TF8016 on 4 Aug 2015 Sun is recorded as 39…. but it was 78. Likewise on Jul 21 it is recorded as 49 when it should be 98."

So for some reason the sun% has halved. Perhaps this is true for other data uploaded to the site at the same time?

Zoe has confirmed Graham's values from the original data entered on the old system.

**Comment by Gary-van-Breda** [comment]
In the CSV file I received with all the samples, this is what is in for TF8016:

SAMPLEKEY | LOCATION | RECORDER | VISIT_DATE | TEMPERATURE | WIND_SPEED | WIND_DIRECTION | START_TIME_10 | SUN
29376 | TF8016 | Graham Upton | 21/07/2015 | 22 | 4 | SW | 10:10 | 49.75
24695 | TF8016 | graham upton | 18/08/2014 | 17 | 4 | N | 11:10 | 10.75
23496 | TF8016 | Graham Upton | 26/07/2014 | 22 | 4 | N | 10:45 | 40.75
17945 | TF8016 | Graham Upton | 13/08/2013 | 19 | 4 | SW | 10:20 | 49.5
16846 | TF8016 | Graham Upton | 13/07/2013 | 28 | 4 | N | 13:20 | 50
29736 | TF8016 | graham upton | 04/08/2015 | 19 | 5 | SW | 10:45 | 39

Someone needs to look at how the CSV data file was created, as there is an issue at that point.

**Comment by Gary-van-Breda** [comment]
See #13.

**Comment by Gary-van-Breda** [comment]
Note that in the latest batch of data provided by @zrandle as part of #13, the average sunshine is given as follows:

29376 | TF8016 | 21/07/2015 | 36
29736 | TF8016 | 04/08/2015 | 60

There are no entries for the section sunshines to provide a different calculated value.
Yet another set of different values!

**Comment by Gary-van-Breda** [comment]
I'll backtrack on what I've written above. The data for the two dates above for TF8016 provided as part of #13 has the overall sunshine not set, but the values that will be used (using averages over the sections where appropriate) are as follows: 

Provided   Key | Provided Site Name | Date | % Sun
16846 | TF8016 | 13/07/2013 | 100
17945 | TF8016 | 13/08/2013 | 99
23496 | TF8016 | 26/07/2014 | 81
24695 | TF8016 | 18/08/2014 | 21
29376 | TF8016 | 21/07/2015 | 99
29736 | TF8016 | 04/08/2015 | 78
33500 | TF8016 | 24/07/2016 | 98
33765 | TF8016 | 05/08/2016 | 28

I think these are close enough? 78 is exact, 99 vs 98?
As part of #13 all the attribute values will be updated, including the sunshine values. 

Yes close enough!

**Comment by Gary-van-Breda** [comment]
All the historic samples have been reloaded, and the %Sun redone.
As a result the samples above now have their %Sun corrected.
As an aside, all the end times have now been filled in as well where available.
Can you confirm that you are happy? Close?

**Comment by DavidRoy** [comment]
@zrandle can you confirm and close if resolved?
