### ISSUE TITLE
Alternatives to Captcha

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#45]
What are out options for preventing SPAM accounts being setup.  We currently use Captcha for site registration and all logins.  This annoys some users.  Are there alternatives, such as:
- only use Captcha on account setup, not subsequent login?
- use alternative modules such as Honeypot, Spambot that are used on other Indica sites such as iRecord

**Comment by Gary-van-Breda** [comment]
Botcha, honeypot, spambot and spamicide are installed but not switched on.
Currently Captcha is set for forum posts, user login, registration, forgotten password, and adding comments to forums, iform nodes, pages and stories (last 3 not used by UKBMS).
I have switched it off for forum posts, user login, forgotten password, and adding comments to forums.
Is this OK?
Do you want details on what the other modules do?

**Comment by DavidRoy** [comment]
Thanks.  Closing for the time being.  Let's keep an eye on if Spam reappears
