### ISSUE TITLE
Timed Counts disappearing

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#46]
A User has found that old timed Count entries disappear from his Timed Count calendar after he has gone back to review them, although they still appear in the Download from the same page (see message below).

The account Username is 'Murlough' and the timed counts referred to are for Murlough NNR (Graying), Sample_ID 1897511 on 4 separate dates.

Presumably, if they are still listed in the download, then are still in the database, but they have become detached from his account?

_Hi Ian,

Slight hiccup with my timed count records for 2016. In preparation for an event at Murlough NNR last week I had checked my records for grayling counts in 2016. I checked back later and the entries were absent but they still appear on the downloaded portion of the site. I can only assume that I have unintentionally deleted them. Is it possible to recover the entries or should I reload the map/results.

Regards
Stephen_

**Comment by Gary-van-Breda** [comment]
There has obviously been some change in the way that dates are handled behind the scenes with the D7 update. This has introduced a bug, whereby the year recorded against the main parent sample was set to 2017 (ie this year), even though the timed counts themselves were for 2016.
The very act to going into the counts to look at them changed the year from 2016 to 2017 - the Next button saves the changes.
I've resurrected these changes by setting the year on the main sample to 2016. I suspect that the conflict in filtering for 2016 but the main sample being 2017, and the actual dates in 2016 meant they were not displayed.
This is also apparent in that the date of previously entered timed counts on the form is being displayed as 01/01/2017, even though they are in the database correctly.

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @JimBacon : can you deploy the following file into both UKBMS and EBMS websites? Thx
[timed_count.php.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1263024/timed_count.php.zip)
After this is deployed I will look at any data fixes

**Comment by BirenRathod** [comment]
@Gary-van-Breda , This has deployed on both sites.

**Comment by Gary-van-Breda** [comment]
I've updated 5 samples to put them back in 2016.
There are 3 which I can't tell which year they are meant to be on, as the counts themselves have been saved and the dates lost. Can you tell when they are from and what dates the counts where on? I will then change them.
http://www.ukbms.org/mydata/input-timed-counts?sample_id=1646434 (entered 2016-06-17)
http://www.ukbms.org/mydata/input-timed-counts?sample_id=1646445 (entered 2016-06-17)
http://www.ukbms.org/mydata/input-timed-counts?sample_id=2014777 (entered 2016-10-02)

**Comment by IanMiddlebrook** [comment]
http://www.ukbms.org/mydata/input-timed-counts?sample_id=1646434 - recorded 2016-06-17
http://www.ukbms.org/mydata/input-timed-counts?sample_id=1646445 - recorded 2016-06-17
http://www.ukbms.org/mydata/input-timed-counts?sample_id=2014777 - recorded 2016-07-21

**Comment by Gary-van-Breda** [comment]
All now corrected. Everything now looks consistent: all parent samples are in the same year as their children.
@IanMiddlebrook : Close?
