### ISSUE TITLE
Duplicate Records causing errors in Annual Summary tables

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#47]
There appears to be a critical problem with the data entry system, in that duplicate 'occurrences' are being stored in the database. IE. two or more entries for the same walk (Sample ID), species and section.
I'm attaching a couple of examples from Townsend Quarry and Stubhampton Bottom.
The Annual Summary tables (presumably) add up all the entries in the database, so show values higher than those entered on the datasheets.
It may be a result of recorders 'correcting' their values during the data entry process, but in any case, the database should surely remove previous values and only retain the last entered value for any sample/species/section combination. 
These particular duplicate occurrences have become a big issue since the change to the new version of the website a couple of months ago, and are being reported regularly by recorders.

There was already a smaller problem with duplicates, reported during the first year we went live, which is still there, but in that case the duplicates have separate occurrence IDs.

Manually correcting the old type of duplicate was just about manageable, but the new duplicate occurrences are much more prolific.
Could we please find a solution to this problem?

Thanks, Ian

[2017_AllRecorders_Transect_TownsendQuarryDWT_Occurrences_20170808163050.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1208678/2017_AllRecorders_Transect_TownsendQuarryDWT_Occurrences_20170808163050.xlsx)
[2017_AllRecorders_Transect_StubhamptonBottom_Occurrences_20170808162757.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1208677/2017_AllRecorders_Transect_StubhamptonBottom_Occurrences_20170808162757.xlsx)

**Comment by IanMiddlebrook** [comment]
Just to put the scale of this problem into context, I've just downloaded all the Transect data for 2017 so far.

There are 2141 duplicate Occurrence_IDs there.
There are a further 288 duplicate records (ie. same sample/section/species, but with separate Occurrence_IDs).

This doesn't include any non-butterfly data, or any WCBS data.

Manually correcting the old type of duplicates is a few days work each year.
Manually correcting the new type would be a few weeks work!

**Comment by DavidRoy** [comment]
This is clearly a major issue that is only like to get more significant.  @Gary-van-Breda - can you investigate the cause please.

**Comment by Gary-van-Breda** [comment]
Not expecting any comments to this: just a note to keep track of pertinent information: the problem appears to be that there are multiple "Abundance count" occurrence attribute values for each occurrence - not what should happen.

**Comment by Gary-van-Breda** [comment]
At the moment it looks like the warehouse is not handing back the correct ID for the attribute value,   so if the user then changes the value, the new value is put in the wrong place. Am investigating further.

**Comment by Gary-van-Breda** [comment]
I believe this is an issue with the audit module on the warehouse: see warehouse issue 264

**Comment by Gary-van-Breda** [comment]
Code lodged into warehouse; waiting for deployment, after which I will need to sort a data fix.
Also identified an issue when deleting data on form: fix in progress.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you unzip and deploy the following file into the UKBMS and EBMSwebsites.
[ukbms_sectioned_transects_input_sample.js.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1261749/ukbms_sectioned_transects_input_sample.js.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda This file have been deployed on to both these sites.

**Comment by IanMiddlebrook** [comment]
Has this file corrected the duplicate entry issue?
If so, can we arrange a data fix asap please? 
The recording season ends in 2 weeks and branch-co-ordinators are already starting to validate all the records.

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
Hi,
Where do we stand with this duplicate issue?
Now that the recording season has ended, and co-ordinators are downloading data (duplicates and all) it really is an urgent matter!

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
I've fixed the Audit code problem (see warehouse issue 264), and we have applied a data fix. This has reduced the number of duplicates from ~2770 to 58 in the occurrences report.
Is this level manageable, or would you like me to investigate for additional causes? I believe that at least some of the remaining duplicates are due to multiple %sun attributes on the Section level samples (e.g. the duplicates for occurrence ids 5793456, 5793459, 5793466, 5793473, 5793474, 5793475 are all due to 2 %sun attributes on subsample ID 2886471)

**Comment by IanMiddlebrook** [comment]
Thanks Gary, I can handle 58 duplicates.

Looks like most corrections are showing in the Raw Data table, but have not filtered through to the Annual Summary report yet. Do you have a rough timescale for everything to catch up?

**Comment by Gary-van-Breda** [comment]
I'd expect at this point it to have caught up: an data flag was put in to trigger the summary rebuild for the affected occurrences. I've cleared the Cache, just to ensure the updated Annual Summary data is picked up.
Can you give me an example of one where AS has not caught up?

**Comment by IanMiddlebrook** [comment]
The one I just checked is Grafton Wood, week 19, Meadow Browns (77 in Annual Summary, 45 in Raw Data).

**Comment by Gary-van-Breda** [comment]
I did see 77, but I have re-cleared the cache, and they look consistent to me now - both showing 45 to me just now, with and without the caching checkbox set.

**Comment by IanMiddlebrook** [comment]
Thanks Gary, same for me now.
