### ISSUE TITLE
Site Type or Location Type

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#48]
Hi,

A minor amendment, but there is a bit of inconsistency over the labelling of the 'Location Type' filter on different pages.

Location Type - on My Sites, Branch Sites, All Sites
Site Type - on My Walks, Branch Walks, Annual Summary, Section Plot, Year Plot

I guess it would be better if they were all the same. 
I think I prefer Location Type.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
This requires the creation (unless specified) or alteration of node specific language files for the following pages:

- My Walks - node 7 (file already exists)
- Branch Walks - node 624
- Annual Summary - node 678
- Section Plot - node 2131
- Year Plot - node 2132

In some cases these also refer to "Sites" - should this be changed as well?

For completness, the other page which reference sites or locations are:

- My Sites - node 4; This refers to a "Site name" in the grid 
- Branch Sites - node 623; This refers to a "Site name" in the grid
- All Sites - node 6; This refers to a "Site name" and "Site code" in the grid

Do you want these changed?

In addition:

- there are references to "Site Type", "Site name", "Site Code" and the phrase "site" in the help text in the location/site data entry form: 
- There are references to the phrase "site" in the timed counts pages.

Should these be changed to "Location *"?

**Comment by DavidRoy** [comment]
@IanMiddlebrook to advise

**Comment by IanMiddlebrook** [comment]
Looking briefly back at this, I can see that Site is the default term in most situations, so changing this would be cumbersome (and confusing for many).
Perhaps, changing the filter on on My Sites, Branch Sites and All Sites to show 'Site Type' is the quickest solution to get standardisation across the website?

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @johnvanbreda 
Can you deploy the master branch version of the project/ukbms directory of indicia-reports onto the warehouse please? Thx.
The 3 pages mentioned by Ian above actually get their "Location Type" from the parameters of the reports they run, so the fix involves tweak the 2 reports (the My Sites and Branch Sites ues the same report with different parameters).
This also includes a performance tweak for the All Sites report for #92

**Comment by johnvanbreda** [comment]
Done

**Comment by Gary-van-Breda** [comment]
Form configuration updated on My, Branch and All Sites pages: now refer to "Site Type".
Bouncing back to Ian for review, and closure?

**Comment by DavidRoy** [comment]
@IanMiddlebrook please review on Drupal 8 version on test
