### ISSUE TITLE
Site Filter on My Walks

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#49]
Not sure if this is linked the problem identified in issue#42 ...

We used to be able to filter the 'My Walks' page by individual sites, but now we can only filter by 'Site Type'.

This is also true of the 'Branch Walks' page, where you can now only view all the walks for every transect at once.

Is there a reason why the secondary filter was removed, and will it be re-instated?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Yes this is linked to #42. The site selection was removed deliberately as using this with WCBS site types led to the WCBS data being entered against the Transect survey.
Once #42 is fixed, the site selection filter will be reinstated.

**Comment by Gary-van-Breda** [comment]
Has now been reinstated on My walks
I'm not sure it ever was used on the Branch walks: the code looks like the location list is hard coded to use the normal user allocation, and there is (currently) no configuration setting which allows it to be switch the Branch allocation.

**Comment by IanMiddlebrook** [comment]
Thanks Gary
