### ISSUE TITLE
Rename WCBS sites in Northern Ireland to match Irish grid

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#5]
Northern Ireland WCBS squares were incorrectly loaded.  They need to be labelled with Irish Grid references, replacing OSGB grid references.  Attached is the renaming required.

@Gary-van-Breda

[WCBS Northern Ireland squares.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/597332/WCBS.Northern.Ireland.squares.xlsx)

**Comment by Gary-van-Breda** [comment]
I have renamed the squares in the spreadsheet to the value in the yellow rename column, with one exception.
The NW6019 square as it was originally created in the dataload has been deleted and replaced with another square IJ4864, which has been given the NW6019 grid reference (Indicia id 165822) in OSGB.
Can you confirm you wish me to rename this new square to J4864 and convert it to the OSIE to match the other squares?
I note the renaming convention does not include an 'I' on the front of the name.

**Comment by DavidRoy** [comment]
Yes, I confirm that the suggested changes are what is needed

**Comment by Gary-van-Breda** [comment]
I've also noticed that both NV3832 and NV6516 have been renamed to H2567, and NV 4451 and NV7135 have both been renamed to H3086. What do you want done with these?

**Comment by DavidRoy** [comment]
I'm not sure what's gone wrong with these translations but the following should be applied:
NV3832 to H2567
NV6516 to H5453
NV4451 to H3086
NV7135 to H5873

thanks

**Comment by Gary-van-Breda** [comment]
NW6019 now sorted, and the 4 squares above redone.
I believe this is now finished, and the issue may be closed - if you're happy

**Comment by DavidRoy** [comment]
@zrandle can you check this and close the issue if all ok
