### ISSUE TITLE
Site Code allocation failure

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#50]
Hi,

I allocate Site Codes to new Transects on the 'All Sites' page. 
I can restrict the 'list to blank code values', and then add the relevant Site Codes in the empty boxes on the left.

However, I've just tried to do this with some new 2017 transects, and the Site Codes are not sticking.
After I've entered the Code, I go to the Site Details page and it still says "The Site Code will be allocated by the Administrator."
If I refresh the All Sites page, the codes that I've entered disappear and the boxes are blank again.

Can this please be investigated?

Thanks, 
Ian

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you deploy the following file into the UKBMS D7 iform module client_helpers directory?
[report_helper.php.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1249561/report_helper.php.zip)
Thanks

**Comment by Gary-van-Breda** [comment]
(Oops - obviously unzipped first!)

**Comment by BirenRathod** [comment]
@

**Comment by BirenRathod** [comment]
@Gary-van-Breda, this has deployed.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : Close?

**Comment by IanMiddlebrook** [comment]
Thanks Gary
