### ISSUE TITLE
Scrolling through Years

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#52]
Hi, just adding suggested enhancements as they arise from volunteers:

On most pages where a year can be selected (My Walks, Branch Walks, Annual Summary), you can only change the year by clicking on the arrow and waiting for the page to load, one at a time. So it can take quite a while to go back a few years (unless you manipulate the URL).

Would it be possible to select the year from a drop-down list on these pages (as per the Section Plot page)?

**Comment by DavidRoy** [comment]
Closing as now implemented on new annual report page. Suggest other reports where required are raised as new issues
