### ISSUE TITLE
Annual Summary table failing to update

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#55]
Hi,

I've received some emails in the last few days about the Annual Summary table failing to reflect data that have been entered several days ago, although in most cases the Raw Data look OK. Sometimes a few species counts are missing from the Annual Summary table, and sometimes a complete walk is missing.

Examples:
Castle Hill NNR , week 17 only 2 species are shown, all subsequent weeks are missing from Annual Summary, though they were entered on 22/9/17 and the Raw Data are there.

Therfield Heath (various transects):
_>There seems to be some problems with UKMBMS entry over the last few 
>weeks for the Therfield Heath Transects.
>
>There is raw data for the last few weeks for Therfield Heath Church 
>Hill and Base of Church Hill (the zero return for this from yesterday 
>is true).  This has not fed through to the summary or estimate sheets.
>
>The data I entered last week for the other three transects have 
>appeared ok but yesterday's data is only in raw data not in the summary or estimate tables.
>Finally for Above Rifle Range the Peacock seen on S3 is not feeding 
>through to even the raw data although it is there in the walk._

Also in Dorset , several sites are reporting that weeks 25 and 26 are not showing up in Annual Summary, despite being in Raw Data (eg. Cashmoor new route), and some data corrections made last week are showing correctly in Raw Data but have not changed in Annual Summary.

The season is about to end and everyone is checking their data. This is going to cause an avalanche of queries.

Please help!

Thanks,

Ian

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you look into this please

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @JimBacon 
Can you check the logs / scheduled tasks run for warehouse1 please? The last successful run of the summary builder looks like it was on 2017-09-19 15:04:39.

**Comment by BirenRathod** [comment]
@Gary-van-Breda , I know there was a problem yesterday up to afternoon, but working fine in the evening and no problem reported this morning too. 
Below are the last logs found.
2017-09-26 09:21:32 +01:00 --- alert: Triggers & notifications scheduled task took 24.616842985153 seconds.
2017-09-26 09:21:38 +01:00 --- alert: Scheduled plugin cache_builder took 6.1464109420776 seconds
2017-09-26 09:22:01 +01:00 --- alert: Scheduled plugin spatial_index_builder took 22.869639873505 seconds
2017-09-26 09:22:11 +01:00 --- alert: Data cleaner rule WithoutPolygon took 7.8936140537262 seconds
2017-09-26 09:22:12 +01:00 --- alert: Scheduled plugin data_cleaner took 10.764019012451 seconds
2017-09-26 09:22:44 +01:00 --- error: Uncaught Exception: Invalid date type -D in file D:/web sites/warehouse1/application/helpers/vague_date.php on line 208

The only problem is that it is complaining about the invalid date type but this doesn't stop completing scheduled task. May be @johnvanbreda needs to look into this.

**Comment by johnvanbreda** [comment]
There was an upload a few days ago, which included a lot of records with dodgy dates. I've cleaned up the data this evening but the broken date values were causing some of the scheduled task processes to not get run. I'll raise a warehouse issue covering the underlying bug.

**Comment by Gary-van-Breda** [comment]
I notice that the last successful run was 21:44 last night. The scheduled tasks seem to be running, but not getting finished: e.g. since 01:18 today it looks like it hasn't finished the data_cleaner, and hasn't done of the tasks after it.
Is this related to your comments @johnvanbreda ? Is this something else?

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook 
Just an update for you: the run last night has caught up Castle Hill NNR and Therfield Heath.
We need the scheduled tasks running consistently in order to sort Cashmoor etc.

**Comment by johnvanbreda** [comment]
Hi @Gary-van-Breda - I've been working on the scheduled tasks problem. It should be working now and I'll also post up a fix to ensure the underlying problem does not recur.

**Comment by Gary-van-Breda** [comment]
The scheduled tasks seem to be running on a half hour cycle. 
I am running each of the UKBMS surveys (one at a time) in catch up mode, for 2 cycles. I've done the BC and BBS surveys, and just about to do the Transects Survey.

**Comment by Gary-van-Breda** [comment]
I believe this is now up to date. @IanMiddlebrook : do you want to confirm?

**Comment by IanMiddlebrook** [comment]
Looks OK to me, thanks
