### ISSUE TITLE
Samples download failing

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#56]
Hi,

The Samples download is producing an error 'Unable to Complete Request'. This seems to be true regardless of Site Type (Transect or WCBS-BC or WCBS-BBS).
All other downloads seem to be working fine.

Samples download is used for national data extraction, so very important at this time of year!

Many thanks,

Ian

**Comment by zrandle** [comment]
Can this be remedied ASAP. I need to analyse all of the WCBS data to present a talk in Northern Ireland next week!!! Thanks

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @JimBacon 
Noting this is flagged as critical, so doing a fast and dirty...
Can you change the twin double quotes `""` on line 648 of the warehouse1 application/helpers/ReportEngine.php to `$sql` ?
I will put this change into Git.

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda 

I can't do that as code pulled directly from GIT. if you commit your code to repository in master branch, I then can pull it from repository.

**Comment by Gary-van-Breda** [comment]
OK: dropped into master branch - sorry its in application/libraries/ReportEngine.php

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Done.

**Comment by IanMiddlebrook** [comment]
Thanks, that seems to be working now.
