### ISSUE TITLE
Branch Co-ordinators unable to review branch data

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#59]
Hi,

This problem was raised by Kelvin Richardson (username: kelvinr). When he looks at the Annual Summary page and filters by Branch Data he gets the following error message: 

Server Error
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
[errno] => 0 [status] => 404 [request] => index.php/services/data/summary_occurrence?mode=json&nonce=ffeca01dc0e7b8dc20bd2523129ad9d2cf207842&columns=date_start%2Cdate_end%2Cdate_type%2Ctype%2Cperiod_number%2Ctaxa_taxon_list_id%2Ctaxonomic_sort_order%2Ctaxon%2Cpreferred_taxon%2Cdefault_common_name%2Ctaxon_meaning_id%2Ccount%2Cestimate&user_id=NULL&auth_token=8e0fd210c76294d42a28835d10aec1a5788a5bad&year=2016&survey_id=64&taxon_list_id=51&query=%257B%2522in%2522%253A%255B%2522location_id%2522%252C%255B%25222058%2522%252C%25222056%2522%252C%25223477%2522%252C%25222237%2522%252C%252216645%2522%252C%252216343%2522%252C%25222182%2522%252C%25222184%2522%252C%25223463%2522%252C%25222246%2522%252C%252216265%2522%252C%252
etc....

I've tried masquerading as him, and I get the same message. 
I checked a few other co-ordinators and most are OK, although 'Hampshire UKBMS' has the same problem. As they are the same branch I wondered if there was a limit to the number of branch sites, but I see that it's working OK for Andy Barker and Linda Barker (both also Hampshire) (although I did reduce the number of Hampshire sites before I checked those 2 accounts - but the problem persisted for Kelvin).

Could you please find out the source of the problem?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
Can you deploy the following unzipped file into the iform/client_helpers directory on the Live UKBMS site ?
[report_helper.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1450656/report_helper.zip)

Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Copied on live UKBMS site.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I copied this file to EBMS too, which resolved this issue https://github.com/BiologicalRecordsCentre/eBMS/issues/45
