### ISSUE TITLE
Enter walk species list bug when switching between species lists

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#6]
The “species list bug”  will take ~1 hour to fix. It arises because when changing between species lists (e.g. common to full) any existing species on the grid are left on the grid (unless they do not have data and are not in the new list to be displayed), and any new ones are simply added to the bottom: the two are not currently meshed together into the taxanomic sort order. If you are prepared to wait, I can probably do this under the EBMS Luxembourg work (both sites use the same form).

**Comment by Gary-van-Breda** [comment]
This has now been deployed onto the D7 site.

**Comment by DavidRoy** [comment]
@imiddlebrook please test and close issue if resolved
