### ISSUE TITLE
species order on data entry pages

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#60]
The species are not listed in taxonomic order when entering them apart from under the all species option. They're jumbled up under the species known at this site; species I have recorded and common species headings.  Can they be listed in taxonomic order for all options please.

**Comment by Gary-van-Breda** [comment]
Taxon sort order enabled on BC and BBS walk data entry forms to match Transect walk DE.

Butterfly Tab: User can choose to sort the taxa by taxanomic sort order or by common name

Moth, Odonata, Others tabs: sorted by common name: note that the species on these 3 tabs come from the UK Master list, which does not have a taxanomic sort order defined, so it is disabled.
