### ISSUE TITLE
Verification on data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#62]
New verification checks on large values entered (e.g. give a warning if >10 Chequered skippers entered for a single walk).

Based on attached rules

[Data entry validation rules (002).pdf](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1572428/Data.entry.validation.rules.002.pdf)

**Comment by Gary-van-Breda** [comment]
Can you confirm whether these are data entry checks (i.e. take place on the front end as the user enters their data), or are verification checks (i.e. are generated by a back end process as part of the verification checks post data entry)?

**Comment by DavidRoy** [comment]
Checks on entry, thanks

**Comment by Gary-van-Breda** [comment]
Issues #63, #62, #61 are being deployed together

**Comment by Gary-van-Breda** [comment]
This has been configured on the main transect survey data entry form for Live, using the figures given in the PDF attached above.

Should the same checks be applied to data entered against the the WCBS squares?

**Comment by DavidRoy** [comment]
Thanks.  Yes, also to be deployed on WCBS

**Comment by Gary-van-Breda** [comment]
Now configured on Transect and both WCBS data entry forms.
Please review, then close?

**Comment by DavidRoy** [comment]
@ianmiddlebrook and @zrandle to test

**Comment by IanMiddlebrook** [comment]
Hi, just looking at this and, following a comment from a recorder, it's acting somewhat differently to the old Transect Walker.
I think these validation rules were mainly intended as a measure against fat fingers hitting extra zeros, so applied to numbers in each section (ie. each individual entry). That's how it worked in the old Transect Walker.
However, the deployment here seems to check cumulative figures each week.
Eg. entering Common Blue figures of (3, 8, 5, 6, 6, 3, 1, 7) is throwing up a warning by section 6 and subsequent sections.

This will produce a lot more warnings.

I realise now that the old spec is not clear in this respect.

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you apply this to the individual counts within cells of the input form.
@IanMiddlebrook the alternative is to up the values triggering a warning?

**Comment by IanMiddlebrook** [comment]
@DavidRoy  I think ideally it's better applied just to individual section entries. 
We could up the triggering values for weekly totals, but allowing for 15 section transects, we might need to increase them beyond values that would pick up individual section errors.

**Comment by DavidRoy** [comment]
ok, agreed

@Gary-van-Breda please disable until this is resolved to avoid triggering too many unnecessary warnings
@Gary-van-Breda please confirm how these values are configured in case of needing to alter them in future

**Comment by Gary-van-Breda** [comment]
OK will do.
Do you want the same figures used for the individual section values that were given in the PDF above, or do you want to come up with a new set? (given that the figures above are at a walk level so should be larger that the equivalent section level values)
Because the original intention was to sum them at a walk level where there was no equivalent validation rule in the warehouse, the values are configured within the data entry form in the website, by attaching the value to the taxon_meaning_id within a widget on the "edit form"

**Comment by IanMiddlebrook** [comment]
Hi, I think stick with the figures given in the PDF. 
These were the figures applied to section level data in the old Transect Walker, so are what the older recorders are familiar with.
Thanks

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
Can you unzip the following and deploy? The php file goes into the UKBMS iform module client_helpers/prebuilt_forms directory, and the js into client_helpers/prebuilt_forms/js.
Thanks
[Issue62.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/2260724/Issue62.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Both files uploaded on to UKBMS live site.

**Comment by Gary-van-Breda** [comment]
All figures changed from walk level to section level checks, on all 3 data entry forms - Transect, WCBS-BBS, WCBS-BC.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda , I've come in to a flurry of emails this morning which suggest the new code isn't working as planned. 

_"On entering data for meadow browns on the Lynchcombe transects I warnings that the values I was entering (between 4 and 6) exceeded the expected maximum of 30. "
"there is a strange error message popping up when I entered my results for ST8719 today.  It says The value entered (3) exceeds the expected maximum (200). "
"I keep getting a message coming up when trying to process transect results on the website. Sometimes this message is palpable nonsense, saying I have counted over 100 individuals when I'm only putting in a couple!"
"Just entered 4 speckled woods in my Ryton species transect. It told me it was too many and over 30?"_

I've just had a quick play, and the warning seems to be coming up on every value entered, regardless of the size of the count.

Thanks,

Ian

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
Can you unzip the following and deploy? The js file goes into client_helpers/prebuilt_forms/js.
Thanks
[ukbms_sectioned_transects_input_sample.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/2302650/ukbms_sectioned_transects_input_sample.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

All done.

**Comment by Gary-van-Breda** [comment]
I think this is now working correctly. All figures are now section level.
Check and Close?

**Comment by IanMiddlebrook** [comment]
That's great - thanks Gary

**Comment by DavidRoy** [comment]
@IanMiddlebrook close?

**Comment by IanMiddlebrook** [comment]
Yes - I would've, but I don't seem to have that option on this thread.
