### ISSUE TITLE
Verification checks on data entry

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#63]
Verification checks on data entry.  Report results of ‘out-of-range’ or ‘out-of-flight season’ for the data entered.  Use the rulecheck functionality already built into Indicia.  Either colour-code the table cells where the value entered, or give a pop-up warning or have a separate review/check/submit page before committing to the database.

**Comment by Gary-van-Breda** [comment]
There seems to be 2 sets of out-of-range verification checks: e.g. for Chequered Skipper, there is "Coordinate is outside known 10km range of Carterocephalus palaemon" and "Coordinate outside known range for Carterocephalus palaemon".
At the moment I am making the fields colour coded if they fail an check, and putting a warning mark next to the name, which the user can hover over to get the actual warning text. This is leading to 2 warnings for Checkered Skipper - are you Ok with this? Do you want me to filter either of these out?

**Comment by DavidRoy** [comment]
I've checked on the warehouse and I think there is an error, in including C. palaemon within a set of rules for moth species.

This one should be ignored:
http://warehouse1.indicia.org.uk/index.php/verification_rule/edit/22175

"Coordinate is outside known 10km range of Carterocephalus palaemon"

You can filter by using the latest out-of-range check.  The one in error is from 2014, the other one from 2015

thanks
David

**Comment by Gary-van-Breda** [comment]
Issues #63, #62, #61 are being deployed together

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you unzip the attached file and deploy the contained file to the UKBMS iform module client_helpers/prebuilt_forms directory?
Many thanks
[ukbms_sectioned_transects_input_sample.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/2242975/ukbms_sectioned_transects_input_sample.zip)
This addresses a bug causing a 500 server error when looking up the verification checks.

**Comment by BirenRathod** [comment]
I copied into UKBMS iform module client_helpers/prebuilt_forms folder.

**Comment by Gary-van-Breda** [comment]
Now working correctly on Transects and both WCBS walk data entry forms.
Please revirew, and close?

**Comment by DavidRoy** [comment]
@ianmiddlebrook and @zrandle to test

**Comment by IanMiddlebrook** [comment]
This looks really good. 

Although I haven't checked all individual species for every week, Those I've checked seem fine.

Many thanks

**Comment by DavidRoy** [comment]
Great.  Please close the issue if Zoe is also ok with this working.

**Comment by zrandle** [comment]
Seems OK to me. Thanks Zoe
