### ISSUE TITLE
Create and populate additional UKBMS reporting tables

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#64]
Create additional reporting table in Indicia (similar to ukbms_year_index_values) for including historic data within reports (annual/section totals).  Update existing reports to include historic and live data

**Comment by Gary-van-Breda** [comment]
Each entry in ukbms_year_index_values has the following information:

-   survey_id,
-   year,
-   location_id (ties to the Transect or Site IDs, not the section),
-   taxa_taxon_list_id,
-   index (the actual value)

In the initial email, it was mentioned that the new table should be "for including historic data within reports (annual/section totals)."
Can you confirm that the new table (if we decide to use a new table) should be identical to the above, with a date breakdown still at year level, but with the location_id pointing to the indicia section record?
Is there going to be historic data uploaded for locations (sites) not in the Indicia warehouse?
Prior to 2007, we have the situation where the data for WCBS had a different number of sections to the way the sites are currently set up. Historic data to be uploaded for <2007 has to have the sections merged before upload. Do I need to worry about this?

What reports do you want this data tied into?

**Comment by DavidRoy** [comment]
I confirm that the requirement is for two reports:

1. annual summary report (to populate existing report with data from earlier years where we won't have the full count data in the system).  http://www.ukbms.org/mydata/annual-summary
Likely fields required are 
- survey_id, 
- year, 
- week number,
- location_id (ties to Transect or Site IDs), 
- taxa_taxon_list_id
- Average count (if multiple samples per recording week)

2. section summary report.  A new report.  Shows total counts by site, by species, by year, by section
- survey_id, 
- year, 
- location_id (ties to Transect or Site IDs), 
- location_id (ties to sectionID/sub-sample within Transect/site
- taxa_taxon_list_id
- Total count (sum across samples)

There will not be new locations (sites) added to the Indicia warehouse.  We will provide the data in the required format, including necessary merger of WCBS sections <2007.
