### ISSUE TITLE
Branch Site not appearing in Annual Summary

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#65]
I've just added 2 sites in Cornwall to the branch of Username:  JimBCT

These are Lanhydrock and Respryn.

Both sites now appear in Branch Sites for Jim, and the walks also appear in Branch Walks.

However, on the Annual Summary page, when he filters by 'Branch Data' , Respryn does not appear on his drop-down list of Sites, although Lanhydrock does.

Not sure what's gone wrong there. The site is not sensitive, and it appears happily in the full list of sites in Annual Summary, but not in his Branch list.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
I suspect this was a caching issue of the drop down list: i.e. it was being cached. If this happens again, unselect the "Use cached data" checkbox on the filter bar, and try again.
Both Lanhydrock and Respryn are now available in the Branch sites location drop down for JimBCT on the Annual Summary page.
