### ISSUE TITLE
Website Security

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#66]
Hi,
A  comment from a new user, which I'm just posting here for comment really, as I would be interested in your views. I note that iRecord does have https, so I wondered why that's not the case with UKBMS.

"_I was very surprised to see that the site is not secure. (note, no https in the address) 

This is strange because UKBMS go to the trouble of prompting use of “strong” passwords in their registration process, but since their site is not encrypted, any log-in is vulnerable to eavesdroppers and/or hackers. This means that usernames, passwords and any information input can stolen.

I realise of course that I will not input much in the way of personal information and regular input by others is not particularly sensitive. Nevertheless, any chinks in cyber security should be avoided whenever possible and great care should be exercised when using vulnerable sites such as this one. 

Any users should avoid selecting a password that they may use for other sites, which in turn may carry sensitive information (bank or credit card details for example)._ "

Thanks,

Ian

**Comment by BirenRathod** [comment]
Hello @IanMiddlebrook 

BRC has already considered to update website security to all their websites including BRC own websites (www.brc.ac.uk). I can't exactly tell you when will this be implemented at present. One main reason is  that if we apply certificates to all of them, our server is not capable to support all its websites. And server implementation has already started.  So I could tell you that work is underway and we will soon be able to implement the security to all our websites.

Thanks for your concern.

**Comment by IanMiddlebrook** [comment]
Thanks Biren
