### ISSUE TITLE
Message text on data submission pages

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#68]
The following text to be displayed next to 'submit'/'save' buttons on all pages adding new data to the database.  Required by the end of March 2018, in time for the start of the main field season.

Pages to be update:
http://www.ukbms.org/mydata/input-data
http://www.ukbms.org/mydata/site-details
http://www.ukbms.org/mydata/input-timed-counts

By submitting these records you confirm that they contain data that you have collected, give permission for the records to be used for research, education and public information, and to be made generally available for re-use for any other legal purpose under the terms of the Open Government Licence (http://www.nationalarchives.gov.uk/doc/open-government-licence/), and agree that your name will be associated with the record.

**Comment by Gary-van-Breda** [comment]
On the normal walk data entry page, the grid of species/sections/counts is entered using AJAX, which means there is no submit/save button. Do you want this message displayed elsewhere on the page?

Response from David:
Below the ‘Finish’ button initially and we can then review.

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @JimBacon 
Can I have a list of all the node.*.en.php files in the iform/client_helpers/prebuilt_forms/lang directory on the UKBMS site?
Thanks

**Comment by Gary-van-Breda** [comment]
@DavidRoy Is this change required for EBMS as well?

**Comment by DavidRoy** [comment]
No, just ukbms

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

Attached has included node.*.en.php files.
[node.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1844743/node.zip)

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
Can you unzip and deploy the following files into the UKBMS iform/client_helpers/prebuilt_forms directory?
Thanks
Gary
[Issue 68and69.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1845806/Issue.68and69.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda, Copied on live site UKBMS site.

**Comment by Gary-van-Breda** [comment]
Confirmed: both pages of timed counts, all three pages of site details, all pages/tabs on transect walk data entry, and all pages/tabs on WCBS-BBS walk data entry. Hasn't worked for WCBS-BC walk data entry: am checking now.

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
Can you rename the node.2128.en.php to node.2130.en.php in the iform/client_helpers/prebuilt_forms/lang directory?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Done.

**Comment by Gary-van-Breda** [comment]
I think this has now been done: back to David for review/closure?

**Comment by DavidRoy** [comment]
thanks
