### ISSUE TITLE
Restrict taxon data entry to lower taxon ranks

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#69]
Restrict entry to taxon ranks lower than Genera, for all UKBMS input forms.

For examples, exclude 'Bombus' from list of species.

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
Can you unzip and deploy the following file into the iform/client_helpers/prebuilt_forms/js directory?
Thanks.
[ukbms_sectioned_transects_input_sample.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1847969/ukbms_sectioned_transects_input_sample.zip)

**Comment by Gary-van-Breda** [comment]
@DavidRoy 
The Genus rank has a sort order of 230, but there is also a "Genus aggregate" at 228 - do you want both included, or is the cut off at Genus?

**Comment by BirenRathod** [comment]
@gary-van-breda

I copied js file.

**Comment by DavidRoy** [comment]
Both Genus and Genus aggregate should be excluded from the species list on the input pages

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
Can you unzip and deploy the following file into the iform/client_helpers/prebuilt_forms directory?
Thanks.
[Issue 69 PHP.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1848519/Issue.69.PHP.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

I ahve copied that too.

**Comment by Gary-van-Breda** [comment]
Thanks.
Walk data entry forms (Transect, both WCBS) now configured wil a rank sort order limit of 235 on all tabs which use the UK Master List. Don't think it is needed on the Butterfly tab, as that uses a different species list.
Just about to do Timed Counts

**Comment by Gary-van-Breda** [comment]
Timed Counts only uses the UKBMS Butterflies species list, so this has the same implications as the main Data entry tab. It however does not have the "allow_data_entry" filter set to true, so allows the entry of the "Family"s.
@BirenRathod
Can you unzip and deploy the following file into the iform/client_helpers/prebuilt_forms/js
[timed_count.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1851093/timed_count.zip)
 directory?
Thanks.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Gone live.

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
It looks like the timed_counts.php file in  iform/client_helpers/prebuilt_forms has gone missing - can you investigate?

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda 
Sorry it was my mistake, reinstated now and copied js file in the js folder.

**Comment by Gary-van-Breda** [comment]
Thanks. checked, and all good. I think this is now complete.

There are "Family" groupings within the UKBMS Butterflies species list, but these are flagged as "not data entry", so are now not available on the timed count page (they have always been omitted from the main walk data entry pages). The only taxa that are now available in this list (main tab of data entry forms and the timed count) have a rank of "species" or "subspecies", though are are a few which do not have an allocated rank but which look like they are the "species" or "subspecies". The entire list of taxa which have no rank in UKBMS Butterflies is included below: note this includes the "Family" taxa which have an "f" in the final allow data entry column and which do not appear in the autocompletes. This is for reference only, and has no impact on the resolution of this issue.

```
id | preferred | taxon | preferred_taxon | default_common_name | allow_data_entry
283012 | t | Hesperiidae | Hesperiidae | f
418697 | f | Aglais io | Inachis io | Peacock | t
316475 | t | Leptidea juvernica | Leptidea juvernica | Cryptic Wood White | t
316476 | f | Cryptic Wood White | Leptidea juvernica | Cryptic Wood White | t
283068 | t | Lycaena dispar | Lycaena dispar | Large Copper | t
283069 | f | Large Copper | Lycaena dispar | Large Copper | t
283015 | t | Lycaenidae | Lycaenidae | f
283016 | t | Nymphalidae | Nymphalidae | f
283098 | t | Nymphalis polychloros | Nymphalis polychloros | Large Tortoiseshell | t
283099 | f | Large Tortoiseshell | Nymphalis polychloros | Large Tortoiseshell | t
283030 | t | Ochlodes sylvanus | Ochlodes sylvanus | Large Skipper | t
283031 | f | Large Skipper | Ochlodes sylvanus | Large Skipper | t
283013 | t | Papilionidae | Papilionidae | f
283014 | t | Pieridae | Pieridae |   | f
283082 | t | Polyommatus (Lysandra) bellargus | Polyommatus (Lysandra) bellargus | Adonis Blue | t
283083 | f | Adonis Blue | Polyommatus (Lysandra) bellargus | Adonis Blue | t
418698 | f | Polyommatus bellargus | Polyommatus (Lysandra) bellargus | Adonis Blue | t
283017 | t | Satyridae | Satyridae |   | f
283018 | t | Small/Essex Skipper | Small/Essex Skipper | Small/Essex Skipper | t
285451 | f | Small/Essex Skipper | Small/Essex Skipper | Small/Essex Skipper | t
418696 | f | Thymelicus lineola/sylvestris | Small/Essex Skipper | Small/Essex Skipper | t
```

Back to @DavidRoy for review and closure.

**Comment by DavidRoy** [comment]
@Gary-van-Breda There are still a lot of 'Bombus/Bumblee' records being entered.  e.g. ID 8876685
Has this been applied to 'All' surveys and taxon_groups in the system, i.e. not just butterflies. I should have been clearer in the original issue description

**Comment by Gary-van-Breda** [comment]
Problem appears to be the "previously recorded at this site" or "previously recorded by me" lists that are used to pre-load the tabs. The fixes above only sorted the autocomplete used to add new species to each list.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : Can you unzip the attached file and deploy the resulting JS file into the iform/client_helpers/prebuilt_forms/js directory? Thx
[ukbms_sectioned_transects_input_sample.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/2798181/ukbms_sectioned_transects_input_sample.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
This file gone on live now.

**Comment by DavidRoy** [comment]
@Gary-van-Breda looks good to close this issue now?

**Comment by Gary-van-Breda** [comment]
Yes, I think so - Bombus no longer appears unless viewing an existing walk where data already exists for it - when creating a new walk on a location where Bombus was previously recorded, it is not displayed.
I'm happy for it to be closed.

**Comment by DavidRoy** [comment]
Reopening this as a lot of 'Bombus' records have recently been entered for the Channel Islands.  This is causing a lot of frustration to verifers!
Relevant ID = 8889843

**Comment by Gary-van-Breda** [comment]
The last UKBMS Bombus record is 8889843. This was created on 2019-01-22 12:15:02 by Chambers, though it has been modified since (on Feb 17th).
The code fix for the above was deployed on 28th January: there have been no new records created since the fix was applied.
I think this can be re-closed.
