### ISSUE TITLE
Can the species recorded at this site be changed to species recorded in this square (on the drop down menu / data entry screen).  

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#7]

**Comment by DavidRoy** [comment]
Can we change to 'species recorded in this site/square'

so that it works for both WCBS and traditional transects?

**Comment by zrandle** [comment]
Hi

The change as should only apply to data entry for WCBS squares.

Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
This has now been done. Zoë, can you check you are happy?

**Comment by zrandle** [comment]
Looks fine to me.

Thanks

Zoe
