### ISSUE TITLE
Possile report error

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#70]
When user cbertrand@butterfly-conservation downloads her Northern Ireland WCBS-BC branch sites (74 are listed on screen) the entire list of WCBS BC squares (2019) is downloaded. Please can this be fixed and check that this issue is not occurring for other Branch Co-ordinators. Thanks Zoe

**Comment by Gary-van-Breda** [comment]
There is an issue in the warehouse: the filter on the user in the report is done using custom attribute filter on the branch user attribute. It unfortunately depends on the processing order within the report engine of this filter parameter relative to the parameter which says to give this attribute in the report. I haven't been able to figure out if it is predictable: The report works for the main grid itself, doesn't work for the download link, but does work if that link URL is copied and used directly.
Am investigating further.

**Comment by Gary-van-Breda** [comment]
Code lodged into Git (warehouse develop branch). Awaiting deployment

**Comment by Gary-van-Breda** [comment]
I think this has now been deployed: I've tried it and it works correctly.
Please check, then close?

**Comment by zrandle** [comment]
Great thank you.
