### ISSUE TITLE
BBS squares to add to the system

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#71]
Please can the squares listed in the attached be added to the system asap. Thanks Zoe 
[New BBS squares for WCBS for GVB 6_3_18.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/1826549/New.BBS.squares.for.WCBS.for.GVB.6_3_18.xlsx)

They are BBS squares.

**Comment by zrandle** [comment]
@Gary-van-Breda Is there any progress on this? Recorders are signing up and this is becoming urgent. 

Thanks Zoe

**Comment by Gary-van-Breda** [comment]
Of the 139 squares given:

- All the SKYE ones are already there (9 entries, possibly hidden in assignment by #72 )
- All the NBLD ones are already there (10 entries, possibly hidden in assignment by #72 )
- All others now loaded (120 in total).

Can be closed?

**Comment by Gary-van-Breda** [comment]
See #72 for details on how to get around the entries not showing up in the assignment if the branch filter is set.

**Comment by zrandle** [comment]
Great thanks for adding them.
