### ISSUE TITLE
Unable to register new account

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#73]
A message received today:
"I’m trying to register for an account on the online system, but when I put my details in it come back and says “The answer you entered for the CAPTCHA was not correct”  I have ticked the box that say I am not a robot but it doesn’t seem to be working."

I've just tried myself, and the same thing is happening - I fill in the details, tick the box to say I'm not a robot, but the page comes back with “The answer you entered for the CAPTCHA was not correct”. 
Should there be the picture puzzles and might my browser (Chrome) be blocking pop-ups?

Any help appreciated.

Thanks Ian

**Comment by BirenRathod** [comment]
Hello @IanMiddlebrook 

No sorry , I haven’t seen but when you generate issue, you do need to assign to somebody (for e.g @BirenRathod)

Sorry for this problem. I just checked in all three browsers IE, Chrome & Firefox. I found no problem. 

May be by clearing cookies could help to prevent this problem if you had problem before.

**Comment by IanMiddlebrook** [comment]
Thanks for your help @BirenRathod (just checking that I can assign!).
