### ISSUE TITLE
Registration emails

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#74]
Hi @BirenRathod 

Several new registrants over the last couple of weeks say they have not received an email after registering for a new account on the UKBMS site. They've also tried requesting a new password and not received an email.
I've mentioned that they might find the email in their SPAM/JUNK folder, but many fail to find anything in there either.
Could we firstly check that all the emails are being sent out (I always seem to receive the notification, so that part is OK).
Perhaps more importantly, If the emails are being sent out but not getting through, is there anything we can do to change the emails so that they are less likely to be blocked?

Thanks,

Ian

**Comment by BirenRathod** [comment]
Hello @IanMiddlebrook, @Gary-van-Breda , @DavidRoy 

Due to some reason using any CEH email stop sending email outside. This could be due to our internal email security system in action. So I changed that to no-reply@ukbms.org and it works. so I left the setting like that. So user will get an email. 

Also, I found there was no terms of condition page created. Because of that when every time new user registered, there was an error generated in the log. So I have created terms of use page. The page has got long list of text which might not require for UKBMS transact. please amend that to suitable text.

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod 
The only problem now is that I've stopped receiving notifications when new accounts are set up. I used to receive them from brc@ceh.ac.uk  and they were still coming through, but I see a few more (mostly spam) accounts have been set up in the last 3 hours, but I've not received any notification.

**Comment by BirenRathod** [comment]
Hello @IanMiddlebrook 

I have now added brc@ceh.ac.uk email to user registration notification. So you should be receive that.

**Comment by IanMiddlebrook** [comment]
Hi @BirenRathod 
Sorry, I receive the notifications at imiddlebrook@butterfly-conservation.org . They used to come FROM brc@ceh.ac.uk 

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod  They're coming though now

**Comment by IanMiddlebrook** [comment]
Hi @BirenRathod  
Just looking through the new registrations this morning, and it looks like I stopped receiving notification emails early this morning (after 3am) as there are a bunch of new accounts on the website that I've not received notification of. May just be a temporary problem, but it's ongoing.

@DavidRoy 
As an additional point, we've gone back to getting a lot of bogus/spam accounts now - dozens each day that I need to delete. Is there anything we could do to discourage this? For example, I'm sure they sign up for the forum, but is there any need for the forum to be visible to people before they login? I can't think of any, so if we removed the forum from the menu until people login I wonder if that would help?

thanks,

Ian

**Comment by IanMiddlebrook** [comment]
Sorry @BirenRathod 
I also see that none of the most recent registrations have accessed their accounts, so I assume they are not getting their registration emails either.

**Comment by BirenRathod** [comment]
@IanMiddlebrook 

To block bogus/spam accounts, please chnage the settings in the "acccount settings" of "people" to "Visitors, but administrator approval is required"

About email, first try to create account by your self and see if you receive any email.

**Comment by IanMiddlebrook** [comment]
Hi @BirenRathod  I've tried to create an account, and did not receive any email.

Re. blocking bogus accounts, that doesn't sound like it will reduce my workload - ie. will it actually reduce the number of people 'trying' to register.

**Comment by BirenRathod** [comment]
@IanMiddlebrook 

I will look into email bit.

Neither it reduces your workload nor it will reduce number of people trying to register (email goes to you anyway) but it will definitely stop the bogus account.

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod  it looks like emails are coming through again. I just received a new notification, so I tried to set up a new account and the notification was received at my other email address.

Regarding the issue of junk accounts - my main objective was to reduce my workload dealing with them, which your suggestion doesn't achieve. I'll raise it in a separate issue.

Thanks again,

Ian

**Comment by BirenRathod** [comment]
No problem.

That's right. it will increase your workload. Other solution is to block them by using forum by Captcha. The site had already enabled this module, you just need to configure for forum. if you want let me know.

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod  at the moment, most of the spam accounts are not even using real email addressess, so they don't get on to the site or contribute to the forum. 
It's just a real pain coming in every moving to see dozens of emails about accounts that I then need to delete. I don't know if that's also a problem on iRecord?

**Comment by BirenRathod** [comment]
Yes, same problem of Drupal. iRecord has got spambot module running in the background.

**Comment by BirenRathod** [comment]
but that is not an ideal solution in your case as you need to active their account after every registration.

**Comment by DavidRoy** [comment]
Closing this as registration email issue now resolved.  Spam account issue still to be address by #78
