### ISSUE TITLE
Duplicate sections in data entry

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#75]
@Gary-van-Breda 

A recorder has set up a new site, and on going to enter data for the first time found that there were duplicate columns in the data entry screen for sections 3 to 7 (out of 12).
The site is Packwood House (id=192766).

This issue was resolved previously for several sites.

Could we check the database to see if any other sites are currently affected, and remedy as appropriate?

Many thanks,

Ian

**Comment by Gary-van-Breda** [comment]
This has happened before. At that point it was identified that asynchronous service calls to the warehouse meant that timing of code on the page was tripping up - code was running too soon when data it relied on had not been returned from the warehouse. A fix was applied, which basically meant that all service calls to the warehouse from the page were switched over to a synchronous mode (where the following code was only executed after the data was returned).
It looks like the version of jQuery currently being used on the website is controlled by a module called by jQuery_update, rather than the version supplied by the iform Module. This is supplying version 1.8 as opposed to 1.7. As of version jQuery1.8, the method used to switch to the synchronous data transfer is deprecated, and no longer works.
I will have to rework the form (and the walk data entry form) to change the logic.
I will look at the data issue after.

**Comment by DavidRoy** [comment]
@Gary-van-Breda have you resolve the data duplication issue?

**Comment by JimBacon** [comment]
This sounds like it is the same issue that I had to deal with on the European BMS website. https://github.com/BiologicalRecordsCentre/ABLE/issues/317
I will follow the same process to clean up the database and to try to remedy the cause.

**Comment by JimBacon** [comment]
The following query returns all duplicate transect sections. These are listed in the subsequent table along with the choice of which to retain.

```sql
WITH ukbms_sections AS (
    SELECT l.* 
    FROM locations l
    JOIN locations_websites lw
        ON lw.location_id = l.id
        AND lw.website_id = 27
    JOIN locations p
        ON p.id = l.parent_id
    WHERE l.deleted = false
        AND p.deleted = false
        AND l.location_type_id = 778
)
SELECT l1.* 
FROM ukbms_sections l1
JOIN ukbms_sections l2
    ON l2.name = l1.name
    AND l1.parent_id = l2.parent_id
WHERE l2.id != l1.id
ORDER BY l1.parent_id, l1.code, l1.id
```

Parent ID | Section Name | Keep ID | Delete ID
-----------|-----------------|----------|----------
2573 | Cape Cornwall - S1 | 166777 | 166776
158410 | LBCP - East and North Field - S1 | 158419 | 158412
165512 | WWT Llanelli Millennium Wetlands - S2 | 165518 | 165514
171882 | TQ8078 S2 | 171934 | 171884
171882 | TQ8078 S3 | 171935 | 171885
171882 | TQ8078 S4 | 171936 | 171886
171882 | TQ8078 S5 | 171937 | 171887
171882 | TQ8078 S6 | 171938 | 171888
171882 | TQ8078 S7 | 171939 | 171889
171882 | TQ8078 S8 | 171940 | 171890
171882 | TQ8078 S9 | 171941 | 171891
171882 | TQ8078 S10 | 171942 | 171892
192766 | Packwood House Warwickshire - S3 | 192791 | 192781
192766 | Packwood House Warwickshire - S4 | 192792 | 192782
192766 | Packwood House Warwickshire - S5 | 192793 | 192783
192766 | Packwood House Warwickshire - S6 | 192794 | 192784
192766 | Packwood House Warwickshire - S7 | 192795 | 192785
193315 | Linn Park - S10 | 193328 | 193327
193389 | Whiteleaf Hill - S1 | 193392 | 193390
195916 | Raginnis - S1 | 195918 | 195917
202252 | Blickling Mausoleum - S1 | 202258 | 202253
202252 | Blickling Mausoleum - S1 | 202258 | 202257
202252 | Blickling Mausoleum - S2 | 202259 | 202254
202252 | Blickling Mausoleum - S3 | 202260 | 202255
202252 | Blickling Mausoleum - S4 | 202261 | 202256
207205 | Kelsall1 - S2 | 207212 | 207209
207205 | Kelsall1 - S3 | 207213 | 207210
213057 | Poulton Wood - S1 | 213060 | 213058
213057 | Poulton Wood - S2 | 213061 | 213059
301909 | Stoke Park, Bristol - S1 | 301920 | 301910
301909 | Stoke Park, Bristol - S2 | 301921 | 301911
301909 | Stoke Park, Bristol - S3 | 301922 | 301912
301909 | Stoke Park, Bristol - S4 | 301923 | 301913
301909 | Stoke Park, Bristol - S5 | 301924 | 301914
301909 | Stoke Park, Bristol - S6 | 301925 | 301915
301909 | Stoke Park, Bristol - S7 | 301926 | 301916
301909 | Stoke Park, Bristol - S8 | 301927 | 301917
301909 | Stoke Park, Bristol - S9 | 301928 | 301918
301909 | Stoke Park, Bristol - S10 | 301929 | 301919
320054 | Bladnoch - S1 | 320066 | 320055
320054 | Bladnoch - S2 | 320067 | 320056
320054 | Bladnoch - S3 | 320068 | 320057
320054 | Bladnoch - S4 | 320069 | 320058
320054 | Bladnoch - S5 | 320070 | 320059
320054 | Bladnoch - S6 | 320071 | 320060
320054 | Bladnoch - S7 | 320072 | 320061
320054 | Bladnoch - S8 | 320073 | 320062
320054 | Bladnoch - S9 | 320074 | 320063
320054 | Bladnoch - S10 | 320075 | 320064

**Comment by JimBacon** [comment]
Looking at the above transect sections, there were 156 instances where two sub-samples had been created for a section rather than one. The spurious samples seem to be quite prevalent in UKBMS records and typically have no associated occurrences. (Although there was one sample with ID 13552151 which had two occurrences.) These were deleted by the following query to make the subsequent reassignment of samples to sections easier.

```sql
WITH ukbms_sections AS (
	SELECT l.* 
	FROM locations l
	JOIN locations_websites lw
		ON lw.location_id = l.id
		AND lw.website_id = 27
	WHERE l.deleted = false
		AND l.location_type_id = 778
),
duplicate_sections AS (
	SELECT DISTINCT ON (l1.parent_id, l1.code, l1.id) 
	l1.* 
	FROM ukbms_sections l1
	JOIN ukbms_sections l2
		ON l2.name = l1.name
		AND l1.parent_id = l2.parent_id
	WHERE l2.id != l1.id
	ORDER BY l1.parent_id, l1.code, l1.id
),
walks_with_multiple_samples_per_section AS (
	SELECT s.parent_id, s.location_id, count(s.id)
	FROM samples s
	JOIN duplicate_sections ds
		ON ds.id = s.location_id
	WHERE s.survey_id  in (64, 305, 306, 170)
	GROUP BY s.parent_id, s.location_id
	HAVING count(s.id) > 1
	ORDER BY parent_id, location_id
	),
samples_to_delete AS (
	SELECT DISTINCT ON (s.parent_id, s.location_id)
		s.parent_id, s.id, s.location_id, s.updated_on,
		(SELECT count(*) 
			FROM occurrences 
			WHERE sample_id = s.id
		) count_occ,
		snf.attrs_json
	FROM samples s
	JOIN walks_with_multiple_samples_per_section w
		ON w.parent_id = s.parent_id
		AND w.location_id = s.location_id
	JOIN cache_samples_nonfunctional snf
		ON snf.id = s.id
	ORDER BY s.location_id, s.parent_id, updated_on ASC
)
UPDATE samples s
SET deleted = true, updated_on = now(), updated_by_id = 2
FROM samples_to_delete std
WHERE s.id = std.id
```

**Comment by JimBacon** [comment]
Having removed duplicate samples for sections, the following query now correctly returns the number of samples needing each kind of treatment set out in my [strategy](https://github.com/BiologicalRecordsCentre/ABLE/issues/317#issuecomment-1184485996). The same common table expressions can be used to perform the updates which will follow.

```sql
with duplicate_pairs as (
    select * from (values 
    (1, 166777, 166776),
    (2, 158419, 158412),
    (3, 165518, 165514),
    (4, 171934, 171884),
    (5, 171935, 171885),
    (6, 171936, 171886),
    (7, 171937, 171887),
    (8, 171938, 171888),
    (9, 171939, 171889),
    (10, 171940, 171890),
    (11, 171941, 171891),
    (12, 171942, 171892),
    (13, 192791, 192781),
    (14, 192792, 192782),
    (15, 192793, 192783),
    (16, 192794, 192784),
    (17, 192795, 192785),
    (18, 193328, 193327),
    (19, 193392, 193390),
    (20, 195918, 195917),
    (21, 202258, 202253),
    (22, 202258, 202257),
    (23, 202259, 202254),
    (24, 202260, 202255),
    (25, 202261, 202256),
    (26, 207212, 207209),
    (27, 207213, 207210),
    (28, 213060, 213058),
    (29, 213061, 213059),
    (30, 301920, 301910),
    (31, 301921, 301911),
    (32, 301922, 301912),
    (33, 301923, 301913),
    (34, 301924, 301914),
    (35, 301925, 301915),
    (36, 301926, 301916),
    (37, 301927, 301917),
    (38, 301928, 301918),
    (39, 301929, 301919),
    (40, 320066, 320055),
    (41, 320067, 320056),
    (42, 320068, 320057),
    (43, 320069, 320058),
    (44, 320070, 320059),
    (45, 320071, 320060),
    (46, 320072, 320061),
    (47, 320073, 320062),
    (48, 320074, 320063),
    (49, 320075, 320064))
	as t(pair_id, id_to_keep, id_to_delete)
),
samples_of_location_to_del as (
	select dups.pair_id, s.parent_id, s.id, count(o.id) count_occ
	from duplicate_pairs dups
	left join samples s
		on s.location_id = dups.id_to_delete
		and s.survey_id in (64, 305, 306, 170)
		and s.deleted = false
	left join occurrences o
		on o.sample_id = s.id
	group by dups.pair_id, s.parent_id, s.id
	order by dups.pair_id, s.parent_id, s.id
),
samples_of_location_to_keep as (
	select dups.pair_id, s.parent_id, s.id, count(o.id) count_occ
	from duplicate_pairs dups
	left join samples s
		on s.location_id = dups.id_to_keep
		and survey_id in (64, 305, 306, 170)
		and s.deleted = false
	left join occurrences o
		on o.sample_id = s.id
	group by dups.pair_id, s.parent_id, s.id
),
samples_to_relocate as (
	-- Section to delete is present but section to keep is absent.
	select d.pair_id, d.id
	from samples_of_location_to_del d
	left join samples_of_location_to_keep k
		on k.parent_id = d.parent_id
		and k.pair_id = d.pair_id
	where k.id is null
	order by d.pair_id, d.id
),
samples_to_delete as (
	-- Section to delete and section to keep are present but
	-- section to delete has no occurrences.
	select d.pair_id, d.id
	from samples_of_location_to_del d
	join samples_of_location_to_keep k
		on k.parent_id = d.parent_id
		and k.pair_id = d.pair_id
	where d.count_occ = 0
	order by d.pair_id, d.id
),
samples_with_occ_to_relocate as (
	-- Section to delete and section to keep are present but
	-- section to keep has no occurrences and section to delete does.
	select d.pair_id, d.id
	from samples_of_location_to_del d
	join samples_of_location_to_keep k
		on k.parent_id = d.parent_id
		and k.pair_id = d.pair_id
	where k.count_occ = 0 and d.count_occ > 0
),
samples_without_occ_to_delete as (
	-- Section to delete and section to keep are present but
	-- section to keep has no occurrences and section to delete does.
	select k.pair_id, k.id
	from samples_of_location_to_del d
	join samples_of_location_to_keep k
		on k.parent_id = d.parent_id
		and k.pair_id = d.pair_id
	where k.count_occ = 0 and d.count_occ > 0
),
samples_which_may_be_a_sod as (
	-- Section to delete and section to keep are present and
	-- both section to keep and section to delete have occurrences.
	select d.pair_id, d.id d_id, k.id k_id
	from samples_of_location_to_del d
	join samples_of_location_to_keep k
		on k.parent_id = d.parent_id
		and k.pair_id = d.pair_id
	where k.count_occ > 0 and d.count_occ > 0
)

select
	dups.pair_id,
	(select count(id) total from samples_of_location_to_del x
	where x.pair_id = dups.pair_id),
	(select count(id) relocate from samples_to_relocate x
	where x.pair_id = dups.pair_id),
	(select count(id) del from samples_to_delete x
	where x.pair_id = dups.pair_id),
	(select count(id) occ_rel from samples_with_occ_to_relocate x
	where x.pair_id = dups.pair_id),
	(select count(id) occ_del from samples_without_occ_to_delete x
	where x.pair_id = dups.pair_id),
	(select count(d_id) sods from samples_which_may_be_a_sod x
	where x.pair_id = dups.pair_id)
from duplicate_pairs dups
````

**Comment by JimBacon** [comment]
I've reassigned samples to the locations we are keeping and deleted the duplicate locations using the [same queries as previously](https://github.com/BiologicalRecordsCentre/ABLE/issues/317#issuecomment-1187638771).

This is a slow, tedious and error-prone  condition to fix. The lesson is to always fix a transect with duplicate sections before allowing recording to be carried out. While the oldest duplicate was created on 5/5/2016, the most recent was from 30/5/2023, indicating that there is still a risk of them being created.

**Comment by JimBacon** [comment]
@IanMiddlebrook if you review the recording forms for the transects where there were previously duplicate sections you should find that this is now fixed. If you agree, this issue can be closed. I'll now return to [#316](https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/316) which, sadly, is not magically cured.

**Comment by IanMiddlebrook** [comment]
Thanks @JimBacon, it looks like the existing duplicate sections are resolved.
Is there a fix to avoid them being created again with new sites (as per your previous comment)?

**Comment by JimBacon** [comment]
I can't see a mechanism for creating the duplicates so I cannot propose a fix.
If you know how you can create them please open a new issue with the details.
Fortunately it seems to be a rare thing.

**Comment by IanMiddlebrook** [comment]
OK, thanks @JimBacon  - I'm certainly not aware of any way to create them purposefully!
