### ISSUE TITLE
Branch Sites page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#76]
@Gary-van-Breda 

Hi,

It's been pointed out to me that the Branch Sites page has changed recently (for those with lots of Sites in their Branch). Where there used to be a set of page numbers below the list, so you could navigate directly to page 3 or 4 etc, there is now just a 'Next' and 'Previous' button. So it can take longer to find relevant sites (each page can take quite a while to load).

Another co-ordinator found that the site list behaved oddly as he clicked through the pages. Those sites with zero records appeared in random order. Sometimes a site would appear on 2 different pages, while other sites would not appear at all.

Could someone take a look at this please.

Thanks,

Ian

**Comment by Gary-van-Breda** [comment]
Part 2: additional sort put in so sites with zero records sorted by name.

**Comment by Gary-van-Breda** [comment]
Part 1:
Warehouse
File: data_service_base.php
Function: get_response_structure
line number 200:
    if ($wantCount && !isset($data['parameterRequest'])) {

Email sent to John to query the logic behind second part of the condition.

**Comment by Gary-van-Breda** [comment]
Following conversation with John, the isset clause in the above line has been removed.
Code committed to dev branch of the warehouse.
Awaiting Deployment

**Comment by Gary-van-Breda** [comment]
Pager fix has been deployed.
Bounce back to @IanMiddlebrook to review (& close?)

**Comment by IanMiddlebrook** [comment]
Looks good, thanks @Gary-van-Breda
