### ISSUE TITLE
problems logging in

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#77]
Hi @BirenRathod  @Gary-van-Breda  @DavidRoy 

I've had a couple of UKBMS users overnight failing to login, because when they go to the login page, they are redirected to an 'install' page ...   ukbms.org/mydata/install.php (see attached).

![ukbmslogin](https://user-images.githubusercontent.com/24699793/39296366-a69a879e-4938-11e8-9a86-471dd7c12844.JPG)

I can't replicate the problem here, but these users have tried Chrome, Edge and Firefox between them.

What could the problem be?

Thanks,

Ian

**Comment by DavidRoy** [comment]
@BirenRathod Is this related to the security patching last night?  Users trying to access the site at this time. Please close the issue if so

**Comment by IanMiddlebrook** [comment]
I was speaking to one of them on the phone last night (about 5pm), and while he had the problem repeatedly, I was logging in at the same time without any trouble.

**Comment by BirenRathod** [comment]
@DavidRoy , @Gary-van-Breda & @IanMiddlebrook 
After number of possibilities tried by myself, I figured out that that could have only happened if somebody have typed ukbms.org/MYDATA/insall.php or got stored old cookies (with capital letters of mydata as we resolved that long time ago) in their browsers. Anyway I now have closed the gap, so it won't end up there. Also, just to let you know that if anybody go beyond by clicking "Save and continue", might have ended up at dead end.

**Comment by BirenRathod** [comment]
Sorry bit wrong type it is http://ukbms.org/MYDATA/install.php

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod , I'll get back to the recorders and ask them to try again. 
I know one of them should not have old cookies stored, as he only registered yesterday, but then had the problem logging in. 

Nobody would have typed http://ukbms.org/MYDATA/install.php in order to login, but it's possible they were trying to get to http://www.ukbms.org/MYDATA/user/login 

I'll let you know how they get on.

**Comment by BirenRathod** [comment]
Again if they have tried without www and capital MYDATA than end on above screen. Anyway I resolved it. I surprised too, as It should not have happened.
