### ISSUE TITLE
Replace BC branch boundary shapefile

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#79]
BC to supply new version to resolve issues in Scotland #72

**Comment by DavidRoy** [comment]
@zrandle to investigate supply of new layer

**Comment by zrandle** [comment]
Hi We have edited the Branch Boundaries. The geopackage is too big to send via Github even when zipped up. I will send it to Gary and David via wetransfer.


. Please can you use it an let me know if it is any better? Thanks Zoe

**Comment by DavidRoy** [comment]
Downloaded ok.

@BirenRathod this is stored in W:\PYWELL_SHARED\Pywell Projects\BRC\BMS\Website\BC Branch layer
Can you evaluate:
- how import a .gpkg format file into the data warehouse.  Do we convert to shapefile first, or can we load direct into GeoServer (i.e. not use the warehouse importer)?
- whether the layer is 'clean', i.e. no slithers, non-enclosed polygons etc

**Comment by DavidRoy** [comment]
Awaiting further update from BC via Katie Cruickshanks, as needed for wider BC use. No action to be taken yet

**Comment by zrandle** [comment]
Please can you check they layer as it is. Does it do what we need it to? If so I'm happy with that! Cheer Zoe v

**Comment by Gary-van-Breda** [comment]
Can I just reiterate the problems I can identify with the existing boundaries:

- Isle of White not covered
- Isle of Mann not covered
- Anglesey not covered
- All the islands of the Inner and Outer Hebrides not covered
- Orkney and Shetland not covered
- Dundee not covered
- Lundy not covered
- Isle of Walney not covered
- Isles of Scily not covered
- Whole section of Lothians and Borders south of the Forth to the border not covered.

**Comment by zrandle** [comment]
Does the new boundary file we supplied a month or so ago have the same problems?

**Comment by DavidRoy** [comment]
@burkmarr can you pick up this issue related to GIS layers - used within the UKBMS and iRecord.  A reminder of the current situation.

Latest boundary from BC is stored in W:\PYWELL_SHARED\Pywell Projects\BRC\BMS\Website\BC Branch layer

Can you evaluate:

how to import a .gpkg format file into the data warehouse. Do we convert to shapefile first, or can we load direct into GeoServer (i.e. not use the warehouse importer)?
whether the layer is 'clean', i.e. no slithers, non-enclosed polygons etc

**Comment by burkmarr** [comment]
@zrandle - I'm just looking at the file you sent against @Gary-van-Breda's list. The only one I can see that isn't included in the new layer is Isle of Man - is that intentional?

**Comment by burkmarr** [comment]
@zrandle @DavidRoy I could supplement the layer with IoM boundary taken from the Vice County dataset if it is required?

**Comment by DavidRoy** [comment]
@burkmarr yes, please go ahead and add in IoM as the UKBMS includes transects from there

**Comment by zrandle** [comment]
Yes please add IoM. Thanks Zoe

**Comment by burkmarr** [comment]
I've created a new layer from the old: W:\PYWELL_SHARED\Pywell Projects\BRC\BMS\Website\BC Branch layer\BC areas updated rjb 20190604.shp

I added IoM from VC layer and fixed some bad geometry that I noticed in Shetland, Bristol Channel and around Chipping Sodbury (see images below). I'm unlikely to have found all the geometry problems - many of which have their roots in the original VC data, but it should be okay for us to proceed.

So the next thing is probably for me to try some updates on the development Warehouse and see if there are any issues.

Shetland problem:

![shetland](https://user-images.githubusercontent.com/9275178/58895758-9ca56680-86ec-11e9-87d0-06a4eedbb52b.png)

Bristol Channel problem:

![Bristol Channel](https://user-images.githubusercontent.com/9275178/58895776-a6c76500-86ec-11e9-929a-6487fdecd8d7.png)

Chipping Sodbury area problem:

![Chipping Sodbury](https://user-images.githubusercontent.com/9275178/58895819-b8a90800-86ec-11e9-89f7-397af74981a0.png)

**Comment by burkmarr** [comment]
Uploading the new Butterfly Conservation boundaries to the Development Warehouse has exposed an issue with the complexity of the site boundaries. Because the areas are derived from the very detailed Vice County boundaries, the resulting polygons are very complex. For example the polygon for the Highlands area comprises 4,145 separate sub-polygons (because of small islets) and 366,198 vertices (individual points that actually describe the polygons).

This has created problems with loading the data into the Warehouse and, even if we overcome these, @johnvanbreda  has noted that there could be serious performance implications when used for filtering. With the Vice Counties, these problems are mitigated because the coastline is buffered to 3 miles - resulting in considerably less complex polygons.

I want to propose adding a seaward buffer of 1 mile to all the Butterfly Conservation boundaries. This will mitigate these problems and should have no affect whatsoever on their effectiveness as filters.

@zrandle @DavidRoy @kitenetter - please let me know if you are happy for me to proceed on this basis.

**Comment by DavidRoy** [comment]
Agreed.  These boundaries do not need to be highly precise.  And lepidoptera can be recorded out to sea!

Also, there is an argument for simplifying the boundaries in any case to improve querying performance?

**Comment by burkmarr** [comment]
A good point @DavidRoy. The buffered seaward boundaries do not address the issue of the complex boundaries between adjacent areas which are not buffered. That's still the case with the VC boundaries too.

There are QGIS tools which can simplify boundaries by considering a tolerance and removing as many vertices as possible without causing the resulting new line to deviate by more than the specified tolerance from the original line. But running that changes the detailed shape of the polygon  with the result that the filtering could potentially assign borderline records to different polygons. However, at the sort of scale we're talking about (which you can judge from the image below), you may consider that is not significant.

The image shows the current boundary between the BC Cumbria and North East England areas in white, a simplified boundary in magenta created with a 10 m tolerance and a simplified boundary in yellow created with a 25 m tolerance. 

To take the Cumbria polygon as an example, which has 22,893 vertices (white) in the original, the 10 m tolerance produces a polygon with 10,189 vertices (magenta) and the 25 m tolerance produces a polygon with 2,170 vertices (yellow).

![vc-simplify](https://user-images.githubusercontent.com/9275178/59193713-80874680-8b7e-11e9-8f58-f9f84b3f5cbf.png)

I suggest that even the 25 m tolerance simplification wouldn't have much significant effect on the filtering results, but it reduces the polygon complexity by an order of magnitude which would benefit Indicia performance.

Should we consider a simplification on the BC areas and, if so, what tolerance? (We would obviously retain the original unsimplified boundaries for possible future use, but deploy the simplified boundaries to Indicia for filtering.)

**Comment by DavidRoy** [comment]
Thanks @burkmarr.  Your image shows the issue very clearly.  It is a trade-off between boundary complexity and query performance.  My inclination is that we should keep the full VC boundary as it is the primary unit for biological recording.  Any simplification can compromise how records should be assigned (i.e. on the riverbank in your example), particularly for some taxa (i.e. plants that don't move!).

However, for the BC boundary (and others in the system potentially), I think it is less critical to have them in their very precise format.  The 10m tolerance version seems acceptable to me for mobile organisms.   However, I would welcome the view of @zrandle and @kitenetter who would have a view from the butterfly and moth perspective

**Comment by kitenetter** [comment]
As far as I'm aware the county moth recording network does not make use of the BC branch boundaries, so I'm not sure it's an issue for moths.

The 10m tolerance seems like a reasonable compromise to me. The chance that a change of up to 10m will result in a record 'changing sides' seems to be quite low given that we have few records with a grid reference more precise than 10m (whereas a 25m tolerance would presumably result in shifts for some of our 10m records).

Given the somewhat approximate nature of the original source VC boundaries there is an argument for accepting a simplified VC layer; however, for compatibility with other systems I think we should stick with the 'definitive' digitised versions if at all possible.

**Comment by burkmarr** [comment]
The BC branch areas have how all been updated on the Dev Warehouse. So you can now look at any of these on irecord_dev, e.g. by specifying a filter. 

Simplifying - with 10 m tolerance - and adding a 1 mile buffer around the coast had a dramatic effect on the size of the spatial files without significantly compromising accuracy. 

1. Original size of file from BC - 42,008 kb
2. Size after some data repairs etc - 43,252 kb
3. Size after simplifying boundaries with a Douglas-Peuker tolerance of 10 m - 7,480 kb
4. Size after adding 1 mile seaward buffer - 2,900 kb

The resulting Shapefile was so small that I uploaded the whole thing to the Dev Warehouse in one step and it processed all 32 areas in less than a minute.

This was more work than originally anticipated because of the original data problems and the fact that adding the coastal buffers required manual editing where the buffers met.

Geopackages representing the stages 2-4 above have been deposited along with the original data from BC here: W:\PYWELL_SHARED\Pywell Projects\BRC\BMS\Website\BC Branch layer.

@kitenetter @DavidRoy @johnvanbreda @zrandle  - let me know if you've any concerns about proceeding with uploading to the live Warehouse.

**Comment by DavidRoy** [comment]
Thanks @burkmarr.  I have no concerns with these boundaries going onto the live site.  I'm not sure they would be tested on the dev warehouse.

**Comment by zrandle** [comment]
I'm involving Katie Cruickshanks in this as it is her area of work at BC and she understands these things better than I do! Can she be added to the group?

**Comment by DavidRoy** [comment]
yes, what is her Github account name?

**Comment by zrandle** [comment]
KLCruickshanks

**Comment by KLCruickshanks** [comment]
Hello all, I have gathered 2 separate issues from this thread:
1. The cleanliness of the original layer- we need a clean layer for our own purposes- can we have the layer ('Size after some data repairs etc - 43,252 bk') and then we will do some additional cleaning on it and send it back to you?
2. The format of the layer (copy) held in the warehouse for querying purposes- I am happy with the simplification tolerance of 10m coupled with coastal buffer
Thank you
Katie

**Comment by DavidRoy** [comment]
hello @KLCruickshanks.  Does it make sense to manage the layer through github so we all work from the same version?  Mirroring what's being done for the VC layer:
https://github.com/BiologicalRecordsCentre/vice-counties

**Comment by burkmarr** [comment]
@KLCruickshanks - I've sent the geopackage your asked for by wetransfer. Hopefully any further changes you make to that will be local and/or small enough that I won't have to repeat the whole simplification & buffering process.  If there are changes, I will attempt to incorporate them without redoing the whole thing.

I will hold off publishing the boundaries to the live site until I hear back from you. I think @DavidRoy idea of having a GitHub repository for the data is a good one, but we can proceed with this work before you make a decision on that.

**Comment by KLCruickshanks** [comment]
Thank you @burkmarr - received the layer.  I am happy with making any changes and sending the file back- do you have a deadline or as soon as possible?  I assume you will then simplify what I send you and load that version up.  Thank you.

**Comment by burkmarr** [comment]
Okay @KLCruickshanks. No deadline as far as I am aware, but this has been ongoing for over a year, so it would be good to get it sorted ASAP. Do you anticipate making any major changes?

**Comment by KLCruickshanks** [comment]
Dear All, we have had a look at the layer and we are all happy.  @burkmarr thank you so much for tidying it up.  No changes have been made to the layer that @burkmarr sent me via wetransfer.  We are happy for this to be used as the definitive layer and going forward, any simplified layers can be derived from this.  Great work!

**Comment by burkmarr** [comment]
Thanks @KLCruickshanks. I've just uploaded them to the live Warehouse, so available on iRecord now.

**Comment by burkmarr** [comment]
@DavidRoy - I don't have permission to close on this repository, so you have that pleasure!

**Comment by DavidRoy** [comment]
Good work!  Thanks
