### ISSUE TITLE
New Report: allocation of users to transects/WCBS

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#80]
Hi

Is it possible for a report to be written that outputs the square, allocated recorder (user name, proper name), email address, branch and county?

Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you deploy the file in the attached zip file into the UKBMS iform client_helpers/prebuilt_forms directory. Can you also update the reports/projects on the warehouse1 from the https://github.com/BiologicalRecordsCentre/indicia-reports
Thanks

[ebms_transects_allocation.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3007424/ebms_transects_allocation.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
This file gone onto live server and reports have been pulled down from the repository.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you confirm the form has deployed correctly please? It doesn't look like the page on the website is exhibiting the changes in the file. Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Which report have committed in here https://github.com/BiologicalRecordsCentre/indicia-reports? I can't see your report.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Ignore my above comment. 
Also, because this file name ebms_transects_allocation , I put it in butterfly-monitoring folder.  I now moved into ukbms.mydata folder.

**Comment by DavidRoy** [comment]
@BirenRathod The relevant page is throwing up errors: http://www.ukbms.org/mydata/branch-assignment

Can you resolve or is it best left to @Gary-van-Breda 

The equivalent page on ebms also throws up errors: http://www.butterfly-monitoring.net/transects-allocation

**Comment by Gary-van-Breda** [comment]
This is for me

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you drop the single file in the zip into both the butterfly-monitoring and ukbms.mydata iform/client_helpers/prebuilt_forms directories. Thanks

[ebms_transects_allocation.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3012826/ebms_transects_allocation.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Done.

**Comment by Gary-van-Breda** [comment]
I've checked this, and tweaked the form config, and it looks like it downloads OK now.
A note: it downloads the allocation type selected for the page - so if it has the "Allocation type" at the top selected to be "Normal Users (Transects)", it will download the Transect allocations at a User level, if it is "Branch Managers (WCBS-BC)" it downloads the WCBS-BC Branch manager allocations - these are not bundled together.
@BirenRathod : it looks like the last version hasn't been dropped into butterfly-monitoring. Can you do that please?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Not realising that file for ebms too. Done now.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you drop the updated version of the  https://github.com/BiologicalRecordsCentre/indicia-reports onto warehouse2 as well? Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Reports pulled on Warehouse2.

**Comment by Gary-van-Breda** [comment]
I think the EBMS actions for this issue should be transferred to https://github.com/BiologicalRecordsCentre/ABLE/issues/15 , and this issue should only deal with the UKBMS.
Are we happy that this is OK on UKBMS?

**Comment by DavidRoy** [comment]
@zrandle please review this does what you need

**Comment by Gary-van-Breda** [comment]
Just to clarify: the download is available from a button at the bottom right of the Transect Allocation form.

**Comment by zrandle** [comment]
Yes it does! I've checked the WCBS aspects. Some of the squares don't have a branch or a county but I guess this is due to the Branch Boundary layer (BBL) having a few slithers? Until such times as the BBL is tidier I can populate these fields manually.  As an aside it is a bit slow in running!

**Comment by DavidRoy** [comment]
Closing as the original issue has been resolved.  Any emerging issue to be raised as new
