### ISSUE TITLE
New report: interface to show allocated/unallocated transects/WCBS squares

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#81]
Implement a reporting page similar to the NPMS 'squares near me'
http://www.npms.org.uk/square-near-me-public

**Comment by zrandle** [comment]
Tom is really keen for this to be set up for the coming season. Is this achievable? We have some budget to pay for it to happen...
Thanks
Zoe

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
Can you deploy the files in this zipped archive into the iform module on the UKBMS live site. The ukbms_assign_transects.php file should go into iform/client_helpers/prebuilt_forms, and the ukbms_assign_transects.en.php file into iform/client_helpers/prebuilt_forms/lang.
Thanks
Gary

[prebuilt_forms.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/2641509/prebuilt_forms.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
These files have uploaded onto live site.

**Comment by zrandle** [comment]
Hi

Is there any progress with this? I need to start promoting the site. I would also like these squares added to the list of holiday squares:

NY1011
NY3106
NY3211
NY5026

We only want the holiday squares (yellow) listed and shown on the map at the moment. The labelling is a bit rough on the eyes too. Could the label (square ref) only show when zoomed in closer?

Will people need to register before they can see the map? We want people to be able to see the squares prior to registering. 

Is it possible to have a satellite / terrain base map too so people can see the lay of the land? 
After searching for a place name can the default zoom be wider so it is easier to see your nearest square?
****
Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
Extra 4 holidays squares flagged appropriately.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you deploy the files in the attached zip file into the UKBMS iform client_helpers/prebuilt_forms directory: there are 3 files in total, 2 of which are in subdirectories that should go into the relevant subdirectories of client_helpers/prebuilt_forms.
Thanks

[prebuilt_forms.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3000952/prebuilt_forms.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
These are now gone on live.

**Comment by Gary-van-Breda** [comment]
Thanks @BirenRathod : there are obviously a couple of differences between the production environment and my dev one, so apologies, but can you deploy the files in the attached zip file into the UKBMS iform client_helpers/prebuilt_forms directory: there are 2 files in total, 1of which is in a subdirectory that should go into the relevant subdirectory of client_helpers/prebuilt_forms.
Thanks

[prebuilt_forms.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3005333/prebuilt_forms.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
These files are gone on live too.

**Comment by Gary-van-Breda** [comment]
Thanks: that all looks good.
@zrandle : can you check that you are happy with the changes?
What email address do you want the notifications to go to?

**Comment by zrandle** [comment]
That looks good. Please send the notifications to survey@butterfly-conservation.org

**Comment by Gary-van-Breda** [comment]
Email changed.

**Comment by DavidRoy** [comment]
@zrandle please close issue when you are ready

**Comment by zrandle** [comment]
Do people need to be registered to see the holiday squares page?

**Comment by DavidRoy** [comment]
how did you specify it to work?  But I would say yes, because ultimately they’ll need to register to enter the data, I.e. show the commitment

**Comment by zrandle** [comment]
OK cool. I take it this finished and ready to go?

**Comment by Gary-van-Breda** [comment]
I've just noticed aother environment mismatch, so I'll need to send an updated JS file.
I've enabled it for anonymous users (non-logged in), and the is a new entry on the main menu bar. This should allow these users to do a search, with a note in the bottom saying they should register/log in in order to do the assignment - this is the bit that needs tweaking as it is allowing the them to do the assignment.

**Comment by zrandle** [comment]
ok

**Comment by Gary-van-Breda** [comment]
@BirenRathod : apologies again: can you deploy the file in the attached zip file into the UKBMS iform client_helpers/prebuilt_forms/js directory: there is just the 1 file. Thanks
[ukbms_assign_transects.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3022577/ukbms_assign_transects.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
This file gone on live site.

**Comment by Gary-van-Breda** [comment]
Thanks: this is looking better now.
@zrandle do you want to have a check now? I've left it enabled for anonymous users so they can check if a square is close to where they are going before they decide to register: They get shown a message to login/register beside each square in the table.
There has also been a tweak to the zoom on the map - it was repeatedly zooming out if the Search was run multiple times: now it only zooms out to ensure at least one square is shown.

**Comment by zrandle** [comment]
@Gary-van-Breda  @DavidRoy 

It certainly is looking better- thank you! I've checked it by logging in with my private test account and allocated myself a square NN0661. An email was sent to survey@butterfly-conservation.org but all it said was:

“has allocated themselves site NN0661 as a Holiday square.”

It would be useful if the user name and their email address came in with the email notification.

I cannot unassign myself from that square on that page - there isn't a button to press to say carryout  checked action. 
I can unassign the square when logged in as admin using my other account. 

There is also something weird with the squares shown on the map when you search – not all the squares in the vicinity come up every time…

A few more tweaks needed ASAP please.

Thanks

Zoe

**Comment by DavidRoy** [comment]
"There is also something weird with the squares shown on the map when you search – not all the squares in the vicinity come up every time…"

Can you give an example of what you expect to happen and what happens in practice, ideally with screenshots.  Will then be easier to investigate

**Comment by zrandle** [comment]
Ignore me- I've had another look, it depends on your view zoom. If you zoom out and press search for sites more are shown!

**Comment by DavidRoy** [comment]
Thanks for checking.  If you want to suggest any wording to make this more obvious, we can add it to the page

**Comment by zrandle** [comment]
It isn't obvious where the search for sites button is - can the wording give an indication e.g:  

Press the "Search for Sites" button (below the map) to display the squares within the displayed area. I'll get Ian and Tom to have a look they too. They may have additional comments. Thanks Z

**Comment by zrandle** [comment]
We've noticed that if when scrolling on the mouse whilst hovering over the map, it has a dual effect – the map zooms in or out, but also the webpage scrolls up or down at the same time. This is a bit disorientating.  

Please can this text be added to the page: 

The aim of the holiday squares webpage is to improve coverage of WCBS squares in the uplands of northern and western Britain. Few recorders live in these areas, but they are very popular holiday destinations. Squares are currently available in Cumbria, Lancashire, North East England, Scotland, Wales and Yorkshire. 

Thanks Zoe

**Comment by zrandle** [comment]
Is there any progress on this? I need to start promoting the site. Thanks

Zoe

**Comment by zrandle** [comment]
Is there any progress on this? I need to start promoting the site. Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
@zrandle : I can't reproduce the zoom issue - what type of machine / Operating system and Browser are you using?

**Comment by zrandle** [comment]
Windows 7 and google chrome. Ian had the same issue I think he uses the same.

**Comment by zrandle** [comment]
After the initial search for squares, and subsequently zooming out it would be good if the instructions indicated that pressing search again will show more squares further away from their initial search locations - does that make sense?

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you unzip the attached file, and deploy the files as follows:

- the .php file should go into UKBMS iform client_helpers/prebuilt_forms directory, replacing the existing file
- the .js file should go into UKBMS iform client_helpers/prebuilt_forms/js directory, replacing the existing file
- the .css file should go into UKBMS iform client_helpers/prebuilt_forms/css directory: this is new

Thanks

[ukbms_assign_transects.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3137809/ukbms_assign_transects.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
These files gone live now on ukbma/mydata site.

**Comment by Gary-van-Breda** [comment]
Thanks @BirenRathod 
@zrandle : can you have a look at the new version?

- The explanation text has had a significant rework
- I've had to switch off the scrollwheel zoom on the map for all users.
- The buttons under the map have been made more prominent
- The table format has been brought into line with the other tables on the site.
- The user details on the emails has been fixed.
- A Javascript bug has been fixed which would have prevented the "Carry out checked actions" button appearing, and also caused it to appear more than once.
- A fix has been applied which prevented more than one site from being (un)assigned at once.

**Comment by zrandle** [comment]
Some feedback:

Change text to read "The aim of the holiday squares initiative is to improve coverage of WCBS squares.  
Please number the instructions i.e.
1. Find your place
2. Select place
3. Search for squares

etc etc

Here are some comments from Tom - Tested with Ullapool. 

_Quite easy to use. However, only one square came up even when I zoomed out to the whole of Scotland, then UK.  There is no indication of what distance to Ullapool squares are being culled from. So it fails with a quick, simple test for me.

On other sites where you are matching your location to a feature eg the nearest Ikea/Burger King etc , you have a set of distance options eg within 10 miles, 30 miles, all etc and the number of visible localities features changes with this._ 

Once you've searched for your place can the squares be shown as you zoom out, rather than having to search for squares again after zooming out?

Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you unzip the attached file, and deploy the files as follows:

- the .php file should go into UKBMS iform client_helpers/prebuilt_forms directory, replacing the existing file
- the .js file should go into UKBMS iform client_helpers/prebuilt_forms/js directory, replacing the existing file
- the .css file should go into UKBMS iform client_helpers/prebuilt_forms/css directory, replacing the existing file

Thanks

[ukbms_assign_transects.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3195542/ukbms_assign_transects.zip)

@zrandle : when this is deployed, you will notice a few changes:

- All the sites are placed on the map when the page is loaded
- The under map search button now only searches for the 30 nearest to the map centre, irrespective of whether they are displayed on the map or not (it does not put the locations on the map): a distnace from the highlighted map centre to the site is now included on the grid
- The instructions have been changed, and reformatted as a numbered list

**Comment by BirenRathod** [comment]
@Gary-van-Breda , @DavidRoy , @zrandle 
These files gone on live now.

**Comment by Gary-van-Breda** [comment]
Looks good to me.
@zrandle : can you see what you think?

**Comment by zrandle** [comment]
Looks good. I'm waiting for feedback from some Branch Champions. One has already got back to me. These squares are already allocated to 'normal' recorders: 
NY4736 
NY 4934 
NY4709 
NY4307 
Please can this be reflected on the page? Thanks Zoe

**Comment by Gary-van-Breda** [comment]
@zrandle : can I clarify what you mean?
Do you want to treat "normal" users differently to "holiday" users? (at the moment, as soon as someone registers as a user in order to request the holiday square, they become a "normal" user, so there is no differentiation between "holiday" users and "normal" users)
Or do you just want the squares to be a different colour(s) if they are allocated to anyone ("holiday" users or "normal" users) and/or a note to that effect to be displayed in the grid?
Or maybe a combination of all of these?

**Comment by zrandle** [comment]
There isn't a differentiation between normal users and holiday users.  What I mean is that the squares listed above are already allocated so they are not available as holiday squares. The same goes for a couple of Highland ones (I'm waiting to find out which ones). Thanks Zoe

**Comment by Gary-van-Breda** [comment]
OK - I've removed the 4 squares above from the Holiday squares list, though the NY4307 square doesn't have any normal users assigned to it, only Branch managers.
I'll remove any others as and when you let me know.

**Comment by DavidRoy** [comment]
Closing as holiday squares now up and running
