### ISSUE TITLE
Slow speed of UKBMS website

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#82]
Hi @DavidRoy ,

I've received several comments recently about the speed of the website, and noticed it myself. some specifics below:

"Reading this coordinator's email below, I can fully sympathise. I too find it dreadfully slow..
I did a quick test - in Reporting / Annual Summary, switching Filter by Recorder from My Data to Branch Data took exactly 2 minutes.
Then in Filter by Site, switching from All Branch Sites to a single site Chard Junction  took 2 minutes 30 secs."

"For the last couple of months, UKBMS has become so slow for me that I sometimes give up. In particular, looking at the Annual totals e.g. to compare 2018 ytd with 2017 equivalent, can only occasionally be done.
 Is it me, or is there a more general problem with a solution (hopefully) coming down the line?"

Is there anything in the pipeline for speeding things up? Is it a server problem? I find iRecord can also be extremely slow at times on some reports.

Thanks,

Ian

**Comment by DavidRoy** [comment]
John and Gary to investigate moving reports to use ElasticSearch to improve performance

**Comment by johnvanbreda** [comment]
OK, I've had a look at this. Gary seems to have dramatically improved the performance on UKBMS annual summaries since this was written and the worst case I saw was a pause of approx 10 seconds while a new location was loaded. 
My Elasticsearch index doesn't currently hold the linked location details (child or parent sample) so that's the first change I'll make which comes out of this test. 
So, I can't do an exact comparison. However, I just ran a breakdown of the data as follows:
* Filtered to Dorset, taxon group insect - butterflies, year 2018
* Aggregate to count records, grouped by taxon (for the rows) and week number (for the columns).

This test reliably returns results in approx 0.1 seconds, even if I switch to a new county (so the caches are definitely "cold"). Note that Kibana can't visualise a pivot table nicely so we'll need to process the results in our own jQuery code.

Also note the elasticsearch server we are using is not currently getting any traffic, but on the other hand it only has 2 cores and 16GB RAM so it could be improved if necessary. I'd describe this as a very positive result then.

**Comment by DavidRoy** [comment]
@johnvanbreda can you re-evaluate ElasticSearch for UKBMS reporting performance now the new Index has been created?

**Comment by johnvanbreda** [comment]
On Kibana (http://192.171.199.207:5601/app/kibana) there is a visualisation called Annual summary example chart. This is configured for UKBMS butterfly data, for Lulworth Lakes. You can add a year filter by typing e.g. event.year:2017 into the search bar. I've checked the data and it seems correct (I've added a ukbms_week field to the index to make this output easy). Click inspect in the top right corner to see the raw data. Change the view drop down in this panel to request and you can see the request statistics (typically between 10 and 50ms to run), plus the request itself which will be needed when we get round to developing this.

So, it's taking between 1/50th and 1/20th of a second to run and the server is a basic configuration (2 core, 16MB RAM) which could be upgraded. Note that these times are for the query operation only (i.e. the time that Elasticsearch spends on the request), not the additional time required to move the data around etc, but it's still very promising. 

@Gary-van-Breda I'm not sure when you will be working on this, but for future reference here's an example test form that can either take a simple query string (for a GET request) or a POST body, both of which get passed to the Elasticsearch _search API end-point. If you want to use this you will need to ask me for the authentication secret and replace #secret# with it.

```php
<?php
<style>
form input[type="text"], textarea {
  width: 100%;
}
textarea {
  min-height: 400px;
}
</style>

<form method="POST">
<label>Search:
  <input type="text" name="search-get" value="<?php if (!empty($_POST['search-get'])) echo $_POST['search-get']; ?>" />
</label>
<label>Or, request body:
<textarea name="search-post"><?php if (!empty($_POST['search-post'])) echo $_POST['search-post']; else echo "{\n  \"size\": 0\n}"; ?></textarea>
</label>
<input type="submit" />
</form>
<?php

if ($_POST && (!empty($_POST['search-get']) || !empty($_POST['search-post']))) {
  $session = curl_init();
  $url='https://warehouse1.indicia.org.uk/index.php/services/rest/es-ukbms/_search';
  $headers = ['authorization: USER:W27:SECRET:#secret#'];
  if (!empty($_POST['search-get'])) {
    $url .= '?' . http_build_query(['q' => $_POST['search-get']]);
    echo $url;
    echo '<h2>GET</h2>';
  }
  else if (!empty($_POST['search-post'])) {
    curl_setopt($session, CURLOPT_POST, true);
    curl_setopt($session, CURLOPT_POSTFIELDS, $_POST['search-post']);
    $headers[] = 'Content-Type: application/json'; 
    echo '<h2>POST</h2>';
  }
  // Set the request options.
  curl_setopt ($session, CURLOPT_URL, $url);
  curl_setopt($session, CURLOPT_HEADER, false);
  curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($session, CURLOPT_HTTPHEADER, $headers);
  // Do the request and then close the session
  $response = curl_exec($session);
  curl_close($session);
  echo $response;
}
?>
?>
```

A couple of examples you could try in the search box:
* Lulworth
* taxon.vernacular_name:Peacock
* taxon.accepted_name:Inachis AND event.year:2017

A list of fields available to search is at https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/document-structure.md.
 

Here's an example request body for the annual summary which you can past into the texture:
```json
{
  "aggs": {
    "3": {
      "terms": {
        "field": "taxon.vernacular_name.keyword",
        "size": 40,
        "order": {
          "4": "desc"
        }
      },
      "aggs": {
        "2": {
          "histogram": {
            "field": "event.ukbms_week",
            "interval": 1,
            "min_doc_count": 0,
            "extended_bounds": {
              "min": -3,
              "max": 30
            }
          },
          "aggs": {
            "4": {
              "sum": {
                "field": "occurrence.individual_count"
              }
            }
          }
        },
        "4": {
          "sum": {
            "field": "occurrence.individual_count"
          }
        }
      }
    }
  },
  "size": 0,
  "_source": {
    "excludes": []
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [
    {
      "field": "@timestamp",
      "format": "date_time"
    },
    {
      "field": "event.date_end",
      "format": "date_time"
    },
    {
      "field": "event.date_start",
      "format": "date_time"
    },
    {
      "field": "identification.verified_on",
      "format": "date_time"
    },
    {
      "field": "metadata.created_on",
      "format": "date_time"
    },
    {
      "field": "metadata.updated_on",
      "format": "date_time"
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "event.year:2017",
            "analyze_wildcard": true,
            "default_field": "*"
          }
        },
        {
          "match_phrase": {
            "taxon.group.keyword": {
              "query": "insect - butterfly"
            }
          }
        },
        {
          "match_phrase": {
            "location.parent.location_id": {
              "query": 2785
            }
          }
        }
      ],
      "filter": [],
      "should": [],
      "must_not": []
    }
  }
}
```

**Comment by Gary-van-Breda** [comment]
Following a detailed conversation with @johnvanbreda this afternoon, can I possibly have the following queries run on the database with the intention of getting explain plans to see if they are using resonable indexes:

Users landing on Annual sumary page: My data, all my sites, year =2018:
SELECT date_start, date_end, date_type, type, period_number, taxa_taxon_list_id, taxonomic_sort_order, taxon, preferred_taxon, default_common_name, taxon_meaning_id, count, estimate
FROM summary_occurrences
WHERE year=2018
AND website_id=27
AND survey_id=64
AND user_id = 18532
AND taxon_list_id = 51
AND location_id IS NULL

Annual summary: All recorders data, all sites, year =2018:
SELECT date_start, date_end, date_type, type, period_number, taxa_taxon_list_id, taxonomic_sort_order, taxon, preferred_taxon, default_common_name, taxon_meaning_id, count, estimate
FROM summary_occurrences
WHERE year=2018
AND website_id=27
AND survey_id=64
AND user_id IS NULL
AND taxon_list_id = 51
AND location_id IS NULL

Year plot: specific site.
SELECT so.location_id, coalesce(so.default_common_name, so.preferred_taxon, so.taxon), so.preferred_taxon, so.taxon_meaning_id, so.year, so.count
      FROM summary_occurrences so
      WHERE so.location_id = 3094
      AND so.user_id is null
      AND so.count is NOT NULL
      AND so.website_id=27
      AND so.taxon_list_id = 51;

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @johnvanbreda : can I have the new version of the summary_builder module (available on https://github.com/Indicia-Team/warehouse/tree/feature-summary-builder) dropped into the testwarehouse? (I am assuming that the testwarehouse is realtively upto date).
I'd like to do some performance testing on it, in a system camparable to live.

I need to work out the suitable cost_estimates for the new job queues, and batch sizes.

**Comment by DavidRoy** [comment]
Not sure this is what you had in mind, but here are query results.  Not great performance?
1. 3-27-19 21:00:28
Date
646
Rows Affected
26 secs 552 msec
Duration

2. 3-27-19 21:05:03
Date
3,437
Rows Affected
1 min 5 secs
Duration

3. 3-27-19 21:06:47
Date
2,026
Rows Affected
2 min 45 secs
Duration

**Comment by DavidRoy** [comment]
I notice that the summary_occurrences table has 14 million rows!

**Comment by DavidRoy** [comment]
Is a cache table for UKBMS summary reporting an option to consider?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

I pulled summary_builder module on testwarehouse, see if your changes work.

**Comment by Gary-van-Breda** [comment]
The summary_occurrences table is effectively a cached tabled: it is not joined to anything when a query is carried out. The new version that has just been put on the test system puts all data for one taxon/year/location/user combination into a single row (rather than being a row per week entry), so this should reduce the amount of data by a factor of 20.
@DavidRoy , can you get the explain plans for the queries above, or do I need @BirenRathod or @johnvanbreda to do that? I want to see if any indexes are being used.

**Comment by DavidRoy** [comment]
I don't know how to access the explain plans so you'll need @BirenRathod or @johnvanbreda to either do it, or let me know how

**Comment by BirenRathod** [comment]
@DavidRoy 
you just need to click on "Explain" tab after running each of above query in PgAdmin.

**Comment by DavidRoy** [comment]
@Gary-van-Breda here are the query explains
[ukbms query explains.txt](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3017862/ukbms.query.explains.txt)

**Comment by Gary-van-Breda** [comment]
Could we put the following indexes on, then try the queries again?
CREATE INDEX ix_summary_occurrences_SYUL ON summary_occurrences USING btree (survey_id, year, user_id, location_id);
CREATE INDEX ix_summary_occurrences_WLU ON summary_occurrences USING btree (website_id, location_id, user_id);

**Comment by BirenRathod** [comment]
@Gary-van-Breda , @DavidRoy 

I created indexes on live warehouse.

**Comment by DavidRoy** [comment]
@Gary-van-Breda here is the update explain plan for these queries re-run
[ukbms query explains 2.txt](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3018564/ukbms.query.explains.2.txt)

**Comment by johnvanbreda** [comment]
As an aside, this site is very useful for visualising explains: https://explain.depesz.com/

**Comment by Gary-van-Breda** [comment]
OK, it looks like there was no change in the query plans. @BirenRathod : how often are the statistics on the database tables updated?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I'm expecting immediately after any change.

**Comment by DavidRoy** [comment]
@Gary-van-Breda @johnvanbreda where are we with overall performance on the UKBMS, particularly the annual summary tables.  

ABLE can be used to investigate these issues as we'll face the same when European BMS gest going.

I've had the following report of performance issues from yesterday (wednesday 17th April)

* Time of day – 15:00 i.e. have just been working in system
* User name – home@thelonsdales.co.uk
* Pages being accessed:
1. When entering my own data or checking others’ data (branch walks) there is a delay of about a minute going from page 1 to page 2 and a similar delay on exiting page 2.
2. When using the Annual Summary tool e.g. to check for a particular week in 2018 on one of the branch walks & see how the current week compares. This is extremely tedious with delays of several minutes as one goes through the different steps. The option of deselecting “use cached data” seems no longer to be effective.
Item 2 is much slower than item 1. It is probably only people with a group overview – like me – who look at annual data.

**Comment by Gary-van-Breda** [comment]
@Biren - is the version of the summary_builder mentioned above still on the testwarehouse? Has the module been switched off? - I can't see the summariser menu item under Admin on the warehouse.

**Comment by DavidRoy** [comment]
@BirenRathod can you respond to questions about summary-builder above.  I don't think the tag to 'at biren' would have reached you

**Comment by BirenRathod** [comment]
It has reached as @Gary-van-Breda commented but not as @biren tag. I'm investigating into it.

**Comment by BirenRathod** [comment]
@Gary-van-Breda  & @DavidRoy 
Summary builder been switched off on testwarehouse which I just switched it on.

**Comment by johnvanbreda** [comment]
The 2 indices mentioned above were missing from warehouse1. So, I've ran:
```
CREATE INDEX ix_summary_occurrences_SYUL ON summary_occurrences USING btree (survey_id, year, user_id, location_id);
CREATE INDEX ix_summary_occurrences_WLU ON summary_occurrences USING btree (website_id, location_id, user_id);

set default_statistics_target to 10000;
VACUUM VERBOSE ANALYZE summary_occurrences;
```

Now the queries are running as follows (I've summarised the quick ones as probably no need for full execution plans):
Users landing on Annual sumary page: My data, all my sites, year =2018:
Runs in 132ms, with an index scan on ix_summary_occurrences_SYUL;
```
SELECT date_start, date_end, date_type, type, period_number, taxa_taxon_list_id, taxonomic_sort_order, taxon, preferred_taxon, default_common_name, taxon_meaning_id, count, estimate
FROM summary_occurrences
WHERE year=2018
AND website_id=27
AND survey_id=64
AND user_id = 18532
AND taxon_list_id = 51
AND location_id IS NULL;
```

Annual summary: All recorders data, all sites, year =2018:
This one is still slow, takes 17s, although it does scan the syul index still.
```
SELECT date_start, date_end, date_type, type, period_number, taxa_taxon_list_id, taxonomic_sort_order, taxon, preferred_taxon, default_common_name, taxon_meaning_id, count, estimate
FROM summary_occurrences
WHERE year=2018
AND website_id=27
AND survey_id=64
AND user_id IS NULL
AND taxon_list_id = 51
AND location_id IS NULL;
```
Here's the execution plan for the above:
```
"Index Scan using ix_summary_occurrences_syul on summary_occurrences  (cost=0.56..436831.51 rows=218523 width=96) (actual time=142.814..17352.450 rows=3437 loops=1)"
"  Index Cond: ((survey_id = 64) AND (year = 2018) AND (user_id IS NULL) AND (location_id IS NULL))"
"  Filter: ((website_id = 27) AND (taxon_list_id = 51))"
"  Rows Removed by Filter: 26438"
"Planning Time: 0.247 ms"
"Execution Time: 17352.994 ms"
```

Note, for query 2 if you remove the unnecessary filter on website_id, then although the plan is the same, the filter is now simpler and it shaves a few seconds off (running in around 7s from cold). I also wonder if we should add taxon_list_id to the syul filter? So I tried:
```
DROP INDEX ix_summary_occurrences_SYUL;
CREATE INDEX ix_summary_occurrences_SYULT ON summary_occurrences USING btree (survey_id, year, user_id, location_id, taxon_list_id);
```
Then I ran query 2 again, with and without the website filter. It now runs in <1s in all cases and is slightly faster without the redundant website filter. I checked - this increases the index size by 10% but I think that is OK (it's now 550MB).

The final query, year plot: specific site, runs in 1.5s from cold and uses the wlu filter, so I think this one is fine.
```
SELECT so.location_id, coalesce(so.default_common_name, so.preferred_taxon, so.taxon), so.preferred_taxon, so.taxon_meaning_id, so.year, so.count
FROM summary_occurrences so
WHERE so.location_id = 3094
AND so.user_id is null
AND so.count is NOT NULL
AND so.website_id=27
AND so.taxon_list_id = 51;
```

I have left the SYULT and WLU filters in place.

**Comment by IanMiddlebrook** [comment]
Have you tested the Annual Summary page for 'Branch Data' or one of the larger branches?

I ask because I've generally been able to access 'All recorders, All Sites' (albeit very slowly) while some Branch Co-ordinators are consistently failing to load their Branch Data. Try masquerading as Martin Raper or Bill Downey.

thanks, Ian

**Comment by Gary-van-Breda** [comment]
Following this index reinstatement and analyze by John, I’ve checked Martin Raper's branch data pull : it took 20s (2018, or 2019, uncached, compared to previously timing out after 6minutes).
The All sites/All recorders took 10 seconds.
These figures may not be from "cold".

**Comment by IanMiddlebrook** [comment]
Can confirm Branch Data now loading very quickly.

**Comment by Gary-van-Breda** [comment]
As a point of note, the branch sites fetch is likely to take the longest. This is because the branches are not summarised, whilst individual locations and the whole country are - the branch sites data must fetch the data for all the individual locations in the branch.

**Comment by Gary-van-Breda** [comment]
Similar figures for Bill Downey.

**Comment by DavidRoy** [comment]
Closing issue.  Any performance issues to be raised as new issues
