### ISSUE TITLE
BBS squares to add to the system

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#83]
@Gary-van-Breda 

Hi Gary
[More BBS Squares 13_8_18.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/2282623/More.BBS.Squares.13_8_18.xlsx)

Please can you add the squares in the attached file to the BBS list. Thanks Zoe

**Comment by Gary-van-Breda** [comment]
@zrandle 
Done.

**Comment by zrandle** [comment]
great. Thank you.
