### ISSUE TITLE
Summary Table not updating

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#84]
Hi,
An issue raised by David Taft regarding his recent transect data.

_"Whilst I entered My Walks data re St. Wulstan's transect for weeks 21 and 22 some time ago; and in the case of week 21 over a week ago, they do not as yet appear in the annual summary at all."_

As far as I can see, the data were entered fine. They appear on Annual Summary if you select 'Raw Data', but not under 'Summary Table' or 'Estimate Table'. 

I presume the Summary Table is still updating at regular intervals, as I can see more recent data, but it appears to be missing these walks (and perhaps others?).

Could someone please investigate?

Thanks, Ian

**Comment by DavidRoy** [comment]
There is a delay in the background process to rebuild these tables, due to a large database update that the synchronisation needs to catch up with.  I will provide an update when this is resolved

**Comment by IanMiddlebrook** [comment]
Thanks David

**Comment by DavidRoy** [comment]
I've just realised the 'spike' in background processing is because Gary loaded the past WCBS data.  The scheduled task should catch up in a day or so

**Comment by Gary-van-Breda** [comment]
The WCBS and Transect surveys are treated separately within the summariser, as they are on differnet Indicia surveys. The ongoing upload of WCBS data should have no impact on the appearance of the Transect data in the Annual summary.
I will set the flag on the Transect survey to check for missed data.

**Comment by Gary-van-Breda** [comment]
I've set the missing data check on the Transects survey.
It does look like there is a possible other issue here as it looks like the last successful completion of the summariser was 3 hours ago. I'll keep an eye on this.

**Comment by Gary-van-Breda** [comment]
It has now processed these weeks for David, and they appear in the Summary table. I'm going to leave the missing check in place overnight, just in case anyone else is in the same position, and that should make sure everything is caught up.

**Comment by IanMiddlebrook** [comment]
Thanks Gary
