### ISSUE TITLE
Confusing scales on Year and Section Plots

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#85]
A co-ordinator has commented about some confusion on a few Year by Year Count Plots:

"_I was looking at annual Counts on Old Warden Tunnel transect on the UKBMS website and those for Comma seem a bit odd. I don’t know why but it is reporting fractional counts, e.g. 0.9, 1.8, 2.8, 7.4.  Other species seem okay except for Small Heath which also seems to have fractional counts. See attachments. These are Counts rather than Indices so it suggests a bug somewhere...?_"

On closer inspection, it's not the counts that are fractions, but the scale on the y-axis that is non-integer - ie. there are 7 grid lines for a scale of 8, so each grid line must be 1.14, 2.28 etc, but is rounded to the nearest integer, which gives the illusion of fractional counts.

Would it be possible to arrange the scaling for these plots such that each grid line always corresponds to  a true integer? I believe the scaling works the same on the Section Plots.

@Gary-van-Breda 

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you deploy the contents of the attached zip file into UKBMS? the PHP files go into iform/client_helpers/prebuilt_forms, and the contents of the js directory go into iform/client_helpers/prebuilt_forms/js
[Issue85.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/2928601/Issue85.zip)
Thanks.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
All these files now have gone to live ukbms/mydata site.

**Comment by Gary-van-Breda** [comment]
I've checked and it looks like the deployment is OK.
This changes the calculations of the Y-axis tickmarks on both the Year plot and the Section plot graphs. 
Bouncing back to @IanMiddlebrook to review and close?

**Comment by IanMiddlebrook** [comment]
Excellent job - thanks @Gary-van-Breda
