### ISSUE TITLE
Upload of UKBMS indices for >2016

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#86]
Hi @DavidRoy 

Is it possible to upload the UKBMS indices for 2016 & 2017 to feed into the Year by Year Index Plots?

Thanks,

Ian

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy 

... and 2018 & 2019 ... and 2020 when available.

Thanks, Ian

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy 

Would we be able to do this before we go live? I wouldn't want to hold up the launch just for this, but if it's a relatively quick job?

Thanks, Ian

**Comment by DavidRoy** [comment]
Yes, sorry being so tardy on this one.  Will prioritise this next...

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy 
I guess we can add 2021 indices to this issue now?

It's difficult trying to promote all the feedback features on the website, when some of them are 6-years behind with data.

Thanks, Ian

**Comment by DavidRoy** [comment]
@JimBacon can you pick up this one please.  There is a warehouse tool for uploading this data at:
http://warehouse1.indicia.org.uk/index.php/ukbms_year_index_value

I will send you the file to upload

**Comment by JimBacon** [comment]
I did a little test of this upload tool. 

All existing records in the ukbms_year_index_values table are linked to taxa in the UKBMS Butterflies species list and locations which belong to the UKBMS website. 

Using the CSV upload tool, taxa and locations were chosen indiscriminately, based only on a name match, without regard for species list or website.

I'll work directly in pgAdmin.

**Comment by JimBacon** [comment]
I was able to replace the previous indices with 524944 records from the file received.
377 records were omitted as they were for either very rare species or 'unknown', and not present in the UKBMS species list.
27457 records were omitted as they were for locations which could not be matched to transects present on the warehouse.

The records were inserted with the following query having first uploaded the file to the temporary table, ukbms_year_index_temp.
```
INSERT INTO ukbms_year_index_values
(survey_id, year, location_id, taxa_taxon_list_id, index, deleted)
	select 64, year, l.id, ttl.id, sindex, false
	FROM ukbms_year_index_temp u
	JOIN locations l
		ON l.code = u.site_code::text
		AND l.deleted = false
		AND l.location_type_id = 777
	JOIN locations_websites lw
		ON lw.location_id = l.id
		AND lw.deleted = false
		AND lw.website_id = 27
	JOIN cache_taxa_taxon_lists ttl
		ON ttl.taxon = u.sci_name
		AND ttl.taxon_list_id = 51
		-- Omit duplicate record of Small/Essex Skipper
		AND ttl.id != 285451
```

**Comment by DavidRoy** [comment]
@IanMiddlebrook can you check the reports that use this data are appearing as expected
