### ISSUE TITLE
Walks missing from Annual Summary

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#87]
Hi @Gary-van-Breda , @DavidRoy ,

Could you please set the flag on the Transect survey to check for missed data?

I've had a message from the Dorset co-ordinator about a missing walk:
"_Can you see anything wrong with Langton Westwood's data for Week 25 ?  Although entered on 17th, it has not appeared in summary._"

I can confirm that the walk data were entered a few days before some other walks that are already showing on Annual Summary, so it must have been missed (and there may be others).

Many thanks,

Ian

**Comment by Gary-van-Breda** [comment]
I've set the missing check flag for transects. I'll check the status after it has run the scheduled tasks.

**Comment by Gary-van-Breda** [comment]
This has now caught up. The Langton Westwood data for weeks 25 (and 26) is now displayed. It has run through several cycles in catch up mode, so should have swept up everything.
I have switched off the missed data mode.

**Comment by IanMiddlebrook** [comment]
Thanks Gary
