### ISSUE TITLE
server error message

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/UKBMS-online#88]
i ahve found the website to be getting slower and slower but generally workable until today when pages just won't load and finally when tryign to access my walks after a few minutes I received the following error message:
Sever Error message
500 – Internal sever error. There is a problem with the resource you are looking for, and it cannot be displayed.

BW, Marc

**Comment by DavidRoy** [comment]
Which page were you trying to access when you had this error message?

**Comment by Gary-van-Breda** [comment]
Can you confrm whether this is still a problem? I've tweaked one of the form parameters, and there has been a major warehouse update recently.

**Comment by DavidRoy** [comment]
Performance of the my walks page currently ok.  Close this issue and start new one if needed.
