### ISSUE TITLE
Home page error message

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#89]
Related to the home page map display. 

Intermittent error message (see below).  Suspect this is a time-out on queries.  Suggest an alternative approach is investigated.

cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
URL:http://warehouse1.indicia.org.uk/index.php/services/report/requestReport?report=reports_for_prebuilt_forms/UKBMS/ukbms_samples_for_map.xml&reportSource=local&mode=json&nonce=ef7debb1564750d135794101433a446830af8d1f&auth_token=b17d55f4a88362a6ffa6775215f93a153a36a177&wantColumns=1&wantParameters=1¶msFormExcludes=["sensAttr"]&&sensAttr=57
Server response
{"error":"general_errors.There was an SQL error: ERROR: canceling statement due to statement timeout - \n SELECT sp.entered_sref as \"entered_sref\",\nst_astext(st_centroid(sp.geom)) as \"geom\",\n5 as \"pr\",\n'black' as \"sc\",\n'circle' as \"gn\",\nmax(extract(year from sp.date_start)) as \"year\",\ncase max(extract(year from sp.date_start)) when extract(year from now()) then 0.6 else 0.4 end as \"fo\",\ncase max(extract(year from sp.date_start))when extract(year from now()) then 'red' else 'blue' end as \"fc\"\n FROM samples sp\n JOIN surveys su on su.id=sp.survey_id and su.deleted=false\n LEFT JOIN location_attribute_values sens on sens.location_id=sp.location_id and sens.location_attribute_id=57 and sens.deleted=false \n WHERE (su.website_id in (27) or su.website_id is null)\n AND sp.deleted=false AND sp.parent_id is null\n AND (sens.int_value is null or sens.int_value=0)\n \nGROUP BY sp.entered_sref, st_astext(st_centroid(sp.geom)), 5 ","code":44,"file":"D:\\web sites\\warehouse1\\system\\libraries\\drivers\\Database\\Pgsql.php","line":342,"trace":[]}
general_errors.There was an SQL error: ERROR: canceling statement due to statement timeout - SELECT sp.entered_sref as "entered_sref", st_astext(st_centroid(sp.geom)) as "geom", 5 as "pr", 'black' as "sc", 'circle' as "gn", max(extract(year from sp.date_start)) as "year", case max(extract(year from sp.date_start)) when extract(year from now()) then 0.6 else 0.4 end as "fo", case max(extract(year from sp.date_start))when extract(year from now()) then 'red' else 'blue' end as "fc" FROM samples sp JOIN surveys su on su.id=sp.survey_id and su.deleted=false LEFT JOIN location_attribute_values sens on sens.location_id=sp.location_id and sens.location_attribute_id=57 and sens.deleted=false WHERE (su.website_id in (27) or su.website_id is null) AND sp.deleted=false AND sp.parent_id is null AND (sens.int_value is null or sens.int_value=0) GROUP BY sp.entered_sref, st_astext(st_centroid(sp.geom)), 5

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @johnvanbreda
Can you deploy the master branch version of the project/ukbms directory of indicia-reports onto the warehouse please? Thx.
The report behind the map has been moved to indicia-reports, and had a performance tweak.

**Comment by johnvanbreda** [comment]
Done

**Comment by Gary-van-Breda** [comment]
It should be noted that the front page map is on an 8hour cache.
Map reconfigured to use new version of the report (with one less table join).
Bounce back to David for review and closure?

**Comment by DavidRoy** [comment]
Thanks
