### ISSUE TITLE
Switch live UKBMS online site from Drupal 6 to 7

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#9]
Test Drupal 7 site is at: http://192.171.199.230/ukbms/mydata/

To replace current Drupal 6 site at www.ukbms.org/mydata

Timing of switch-over to be agreed with IM and ZR

**Comment by DavidRoy** [comment]
@Gary-van-Breda are we ready to switch the site over from your perspective?

Note that test url is now:
http://test.brc.ac.uk/ukbms/mydata/

**Comment by Gary-van-Breda** [comment]
Yes-ish (subject to #28 ). There are some tasks that need to be done around the switching to go live, but the extact nature of these will depend on the final site location. We obviously have the old D6 site and this test site. Where will the new D7 site live?

- We need to ensure the user list on the new site reflects the current list on the D6 site.
- There are some form config entries that will have to be altered to reflect the change of URL.

**Comment by DavidRoy** [comment]
Biren will move across to the live server and connect to the live warehouse. We'll then do some testing before switching over.  He will liaise with you, Gary, as needed.

**Comment by Gary-van-Breda** [comment]
Additional item: The forum is also out of date.

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda 

I have just migrated Drupal 6 stuff on to Drupal 7. the URL is www.ukbms.org/mydata7. Only Branch walks page has got error. Rest, I checked all pages and they are all working. Please check and let me know, so than I will stop drupal 6 site and move drupal 7 URL to mydata.

**Comment by BirenRathod** [comment]
@Gary-van-Breda & @DavidRoy , Is it ok to move ukbms/mydata7 to ukbms/mydata? let me know.

**Comment by BirenRathod** [comment]
@Gary-van-Breda, I finally moved all users and profile data to drupal 7. Please have a look and let me know if anything left. We need to move this site as soon as possible.

**Comment by Gary-van-Breda** [comment]
I think it all looks OK.

**Comment by BirenRathod** [comment]
After I migrated all users yesterday, only one user has been registered on live ukbms/mydata. So I will create that on ukbms/mydata7 and moved the URL to ukbms/mydata. There will be small amount of downtime not more than 15 minutes max.

Are you both @Gary-van-Breda & @DavidRoy ok?

**Comment by DavidRoy** [comment]
I will run some checks today and over the weekend - to then switch over at the beginning of next week.  A major change such as this should ideally not be made on a friday.

**Comment by BirenRathod** [comment]
Ok, will do next week.

**Comment by DavidRoy** [comment]
Site generally seems ok, but a few issues with reports:
1. No charts appearing on annual summary pages, e.g. http://www.ukbms.org/mydata7/annual-summary, http://www.ukbms.org/mydata7/section-plot
2. Heading of year report pages not appearing correctly.  e.g. additional drop-down boxes appear.  Compare http://www.ukbms.org/mydata7/year-plot with http://www.ukbms.org/mydata/year-plot

thanks, David

**Comment by BirenRathod** [comment]
I think that was a jQuery problem. The site was in 1.10 and I moved it to 1.8. So both works fine. On the year-plot on drupal 7 works bit better compare to drupal 6. The dropdown lists only enabled if page found any data.

**Comment by DavidRoy** [comment]
Thanks.  That fixed all those problems.  I'm happy for the site to be switched over to drupal 7.

**Comment by BirenRathod** [comment]
Since, I moved site on Thursday, There are seven more users created on the ukbms/mydata site. So I will first move that put site into maintenance mode for a while and move new site to the live site.

Biren

**Comment by DavidRoy** [comment]
Yes, or block new registrations on the drupal 6 site?

**Comment by BirenRathod** [comment]
I blocked new users now on drupal 6 site.

**Comment by BirenRathod** [comment]
@DavidRoy & @Gary-van-Breda 

The site URL has moved and pointed to now drupal 7.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
field_about_transect has been added to profile fields but field hasn't been identified by easy login module. Is this behaviour expected by this module?

**Comment by BirenRathod** [comment]
@Gary-van-Breda, do you see any problem?
@DavidRoy, please close this , if resolved?

**Comment by DavidRoy** [comment]
Thanks Biren and Gary for all your help with this.  Now closing!
