### ISSUE TITLE
Walks disappearing

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#90]
Hi @DavidRoy  @Gary-van-Breda ,

I've had a call from the warden of Parsonage Down NNR, noting that walks keep disappearing from the UKBMS website. 
A little while ago he checked his Summary Page for 2018 and noticed that a few walks were missing, even though he was sure that they had all been entered.
He re-entered these walks but now on checking again, sees that several walks are again missing from his summary page as well as 'My Walks' page.

I've been able to check the current website against some data I downloaded a few weeks ago, and I can confirm that the following Walks (Sample_IDs) for Parsonage Down NNR have disappeared: 
4096674, 4096697, 4096707, 4096716, 4096731

(I had a similar problem from a different site a little while ago, but it was just a couple of walks that more people had access to, so i assumed they'd been deleted by accident, but I now suspect it was the same problem as this.)

Is there any way of checking what has happened to the Samples highlighted? Is it possible that other walks are disappearing, but the recorders have not yet noticed?

Please could this be investigated as a matter of urgency, as we are the time of year when all co-ordinators are checking data.

thanks,  Ian

**Comment by Gary-van-Breda** [comment]
Looking at the audit history of these records:
http://warehouse1.indicia.org.uk/index.php/logged_action?search_table_name=samples&search_key=4096674
Created by Sebastian_Allen-Mepham, 2018-10-10 14:46:57
Deleted by Michael_Fuller, 2018-10-25 10:53:43

http://warehouse1.indicia.org.uk/index.php/logged_action?search_table_name=samples&search_key=4096697
Created by Sebastian_Allen-Mepham, 2018-10-10 14:49:45 
Deleted by Michael_Fuller, 2018-10-25 10:26:23	

http://warehouse1.indicia.org.uk/index.php/logged_action?search_table_name=samples&search_key=4096707
Created by Sebastian_Allen-Mepham, 2018-10-10 14:50:49 
Deleted by Michael_Fuller, 2018-10-25 10:27:07	

http://warehouse1.indicia.org.uk/index.php/logged_action?search_table_name=samples&search_key=4096716
Created by Sebastian_Allen-Mepham, 2018-10-10 14:51:48 
Deleted by Michael_Fuller, 2018-10-25 10:28:04	

http://warehouse1.indicia.org.uk/index.php/logged_action?search_table_name=samples&search_key=4096731
Created by Sebastian_Allen-Mepham, 2018-10-10 14:52:54 
Deleted by Michael_Fuller, 2018-10-25 10:49:42	

Do these names look reasonable? Have these samples been deliberately deleted? It may be worth talking to Michael Fuller.

**Comment by IanMiddlebrook** [comment]
Thanks Gary,

Mike Fuller is the branch co-ordinator for Wiltshire. I'll contact him to see if/why he's deleted them.

Ian

**Comment by IanMiddlebrook** [comment]
Mike Fuller has now confirmed that he deleted these walks, on the basis that the weather was poor. (I've asked him not to do so again without reference to the recorder).

Thanks for your assistance with this problem. Good to know that we're not just losing walks randomly!

Ian
