### ISSUE TITLE
Section Totals

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#91]
Just thinking about possible enhancements, following a couple of recent emails.

How difficult would it be to add another tab to the Annual Summary page, for Section Totals?

A simple table with Section Nos. as column headings, Species as rows, and showing the total of each species in each section for that year. This is a table that was available in the old Transect Walker software.

I know these values are already used to produce the Section Plot, which is great, but the plot does not show the actual values and cannot be exported into a spreadsheet. 

Many recorders or site managers like to do their own thing with these section totals. At present the only way to get these values is to Export the 'Section Level' download and run a pivot report in Excel (which is beyond many of our volunteers).

thanks,

Ian

**Comment by Gary-van-Breda** [comment]
Given that it would be using the data generation reports for the section plot, I would think it would need about 1 days work to produce the grid.

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : rather than adding this to the Annual Summary, I've added the grid underneath the Chart on the Section plot.

Deployed to Test for review.

**Comment by IanMiddlebrook** [comment]
That looks great, thanks @Gary-van-Breda

**Comment by Gary-van-Breda** [comment]
Now pushed to Live. Changes confirmed as deployed.
Closing
