### ISSUE TITLE
Error on All sites page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#92]
http://www.ukbms.org/mydata/all-sites when logged in as 'David Roy'

returns the following timeout error message:
general_errors.There was an SQL error: ERROR: canceling statement due to statement timeout - SELECT l.id as "id", l.name as "name", l.centroid_sref as "centroid_sref", lsub.occurrences as "occurrences", lsub.taxa as "taxa", lsub.groups as "groups", l.code as "code", location57.id as attr_id_location_57, location57.int_value as attr_location_57 FROM ( SELECT lcount.id, COUNT(DISTINCT o.id) AS occurrences, COUNT(DISTINCT o.taxon_meaning_id) AS taxa, COUNT(DISTINCT o.taxon_group_id) AS groups FROM locations_websites lw JOIN locations lcount ON lcount.id=lw.location_id AND lcount.deleted=false AND (lcount.code = '' OR lcount.code IS NULL OR 'no'!='yes') LEFT JOIN locations section on section.parent_id=lcount.id LEFT JOIN cache_occurrences_functional o on o.location_id=section.id AND o.zero_abundance='f' WHERE lw.deleted=false AND lcount.location_type_id=777 AND (lw.website_id in (27) or lw.website_id is null) GROUP BY lcount.id ) AS lsub JOIN locations l on l.id=lsub.id LEFT JOIN location_attribute_values location57 ON location57.location_id=l.id AND location57.location_attribute_id=57 AND location57.deleted=false WHERE 1=1 ORDER BY occurrences DESC, taxa DESC, name LIMIT 2001

**Comment by zrandle** [comment]
I get this all of the time - the system times out. You have to bully it into submission. It isn't very satisfactory. Thanks

Zoe

**Comment by Gary-van-Breda** [comment]
Is it just this page (and the Annual Summary?), or are there other pages where this is seen?

**Comment by zrandle** [comment]
those two pages for me.

**Comment by Gary-van-Breda** [comment]
The All Sites page is being addressed with the code deployed for #48 
The Annual Summary is being addressed under #82

**Comment by DavidRoy** [comment]
Closing this issue as the time-out has been resolved
