### ISSUE TITLE
timed count data entry error

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#93]
Hi @Gary-van-Breda ,

A recorder has just sent me this message. I wonder if you can make sense of the error message?

_"I tried to enter a timed count which I did for 6-spot burnets in my front garden but the system fell over as below. Hope it means something!
Best wishes, David Dewsbury."_
![error](https://user-images.githubusercontent.com/24699793/48765967-45d5c380-ecab-11e8-9c1c-07761c25caf5.jpg)

**Comment by Gary-van-Breda** [comment]
A couple of things have contributed to this:

- the timed count form is currently set up to only accept species on the UKBMS Butterflies list, and as 6-spot burnets are moths, they are not on the list...
- There is something missing within the species autocomplete field vaildation whereby an unrecognised species is not flagged up by the front end. It is however caught by the backend, hence the "mismatch" message.

**Comment by DavidRoy** [comment]
@IanMiddlebrook please advise if the timed count form needs to include more species
@Gary-van-Breda please add field validation to the input form to capture this type of error

**Comment by IanMiddlebrook** [comment]
I don't think we need to include more species at this stage, but could perhaps use a message indicating the form is for butterflies only?

**Comment by Gary-van-Breda** [comment]
Message included at top of the data entry page.

**Comment by DavidRoy** [comment]
@IanMiddlebrook Please review and close if this is ok now

**Comment by Gary-van-Breda** [comment]
I am still working on the extra autocomplete validation.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you unzip the attached file and drop it into the UKBMS iform/client_helpers/prebuilt_forms/js directory. Thanks
[timed_count.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3114065/timed_count.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
This file gone to live ukbms/mydata site.

**Comment by Gary-van-Breda** [comment]
I've cleared the caches: looks OK to me.
Basically if someone enters an invalid taxon name in the autocompletes, it will now clear the field, rather than leaving the invalid name in place (which caused problems - the mandatory field was filled in when it shouldn't have been and the field name for the count was not set up correctly).
@IanMiddlebrook : can you have a look and see if its better?
