### ISSUE TITLE
Annual Summary Branch Data Error Message

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#95]
@DavidRoy @BirenRathod @Gary-van-Breda 

I'm not too sure who to direct this one to, but since the Server Maintenance it's been reported today that Branch Co-ordinators are unable to load up their Branch Data on the Annual Summary page. The request immediately brings up an Error Message as below (I've tried masquerading as co-ordinators and the same thing happens each time).

> 404 - File or directory not found.
> The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
> [errno] => 0 [status] => 404 [request] => index.php/services/report/requestReport?report=library/locations/locations_list_exclude_sensitive.xml&reportSource=local&mode=json&nonce=531b26cded851d9f2403a8540543eac88f6bd026&auth_token=26a2a33e325629d507782e37d8b16eacd9668b0c&website_id=27&location_type_id=777&sensattr=&exclude_sensitive=0&auth_token=26a2a33e325629d507782e37d8b16eacd9668b0c&nonce=531b26cded851d9f2403a8540543eac88f6bd026&locattrs=57&idlist=2722%2C2670%2C39781%2C39920%2C40260%2C40409%2C18839%2C134118%2C135178%2C135199%2C136536%2C134073%2C145850%2C41127%2C148243%2C152131%2C152242%2C158066%2C161837%2C125939%2C151812%2C167789%2C167884%2C167999%2C175766%2C175817%2C182557%2C169071%2C189863%2C189980%2C190904%2C191190%2C191302%2C191520%2C191754%2C192196%2C195900%2C195947%2C203951%2C203607%2C204533%2C176666%2C2673%2C2664%2C2700%2C2665%2C12952%2C2667%2C2721%2C2705%2C2707%2C2693%2C2670%2C2723%2C2710%2C2674%2C2717%2C2675%2C2709%2C12953%2C2699%2C2695%2C18839%2C2698%2C2729%2C23444%2C2677%2C2701%2C2702%2C2697%2C2679%2C20740%2C2681%2C2680%2C31227%2C2724%2C2716%2C23788%2C2715%2C2722%2C23180%2C2686%2C23801%2C2689%2C2687%2C2718%2C2683%2C18437%2C22575%2C2703%2C2714%2C33097%2C39781%2C40260%2C40409%2C41127%2C42325%2C42423%2C43489%2C133885%2C43613%2C43674%2C135178%2C134073%2C135199%2C22614%2C21404%2C2669%2C39920%2C42442%2C32930%2C22431%2C33688%2C134033%2C2706%2C136531%2C40129%2C148051%2C145850%2C2712%2C151710%2C152242%2C152487%2C153541%2C153901%2C153893%2C154177%2C155159%2C2711%2C2713%2C155241%2C155728%2C158066%2C154958%2C158650%2C146022%2C145568%2C21134%2C2708%2C25616%2C42627%2C21286%2C133859%2C151779%2C151812%2C136536%2C41118%2C148243%2C167506%2C167789%2C2666%2C167999%2C167884%2C169071%2C175766%2C175817%2C176479%2C178167%2C187129%2C189863%2C190904%2C133254%2C125752%2C125697%2C171255%2C125807%2C125829%2C126016%2C133243%2C125785%2C125983%2C188852%2C125906%2C125675%2C133232%2C125862%2C125972%2C133210%2C125928%2C125774%2C171805%2C133188%2C125686%2C125873%2C125939%2C125950%2C125961%2C125741%2C126049%2C125994%2C122166%2C133276%2C171827%2C126027%2C125884%2C125840%2C171849%2C189424%2C125851%2C133199%2C125796%2C125818%2C126005%2C133265%2C125719%2C125917%2C133221%2C133177%2C125708%2C126038%2C125730%2C189446%2C189457%2C171860%2C125895%2C126060%2C175727%2C125763%2C191302%2C191520%2C192196%2C187487%2C189980%2C191190%2C195900%2C195947%2C52766%2C77307%2C95083%2C76174%2C90969%2C86778%2C94500%2C108878%2C87449%2C71884%2C77285%2C102366%2C98109%2C198413%2C97537%2C203951%2C203607%2C191754%2C161837%2C198308%2C204533%2C176666 )

**Comment by zrandle** [comment]
I'm having the same problem

**Comment by BirenRathod** [comment]
@IanMiddlebrook and @zrandle 

Are you still experiencing this problem. I just checked annual summary page and it is working fine.

**Comment by IanMiddlebrook** [comment]
@BirenRathod 
Annual Summary page works fine if I filter by My Data or by All Recorders.
The problem is for Branch Co-ordinators, if they try to filter by Branch data - error message as above.
Is this what you tried?

**Comment by zrandle** [comment]
Yes, still having the problem. It happens to me when I  change the drop down to all recorders or branch data.

**Comment by BirenRathod** [comment]
Ok, thanks, I will have a look again and let you know.

**Comment by BirenRathod** [comment]
@IanMiddlebrook , @zrandle 
I have tried every possibilities but I don't see any errors like above one. 

Could you send me the steps to reproduce this error? Also, can I ask you before you access this site, please clean the cookies from your browser.

**Comment by IanMiddlebrook** [comment]
@BirenRathod 

Step 1 - Masquerade on the website as a branch co-ordinator (eg. **Bill Downey** or **Andy Barker**)
Step 2 - go to Annual Summary page, change 'Filter by Recorder' to 'Branch Data'

**Comment by BirenRathod** [comment]
Hello @IanMiddlebrook 

I just did by using Suzanne Halfacre user and saw no errors, however the user you mentioned, did throw same errors. So there must be some settings require for both these users which you mentioned above.

**Comment by IanMiddlebrook** [comment]
@BirenRathod 
Then I wonder if it is linked to the number of sites allocated to their branch?
Bill Downey and Andy Barker (and Zoe) all have a large number of sites allocated to their branch.
Has a limit been set which is too small?

**Comment by BirenRathod** [comment]
@IanMiddlebrook , @zrandle 

This has now resolved, please check it.

**Comment by IanMiddlebrook** [comment]
Hi @BirenRathod 

This looks good now from a transect co-ordinator point of view.

I did still have a problem with Branch Data when masquerading as Zoe Randle @zrandle  - she does have over 700 WCBS-BC squares allocated to her branch. But I think she can now see data from All Recorders.

**Comment by BirenRathod** [comment]
@IanMiddlebrook @zrandle 
That has resolved too.

**Comment by IanMiddlebrook** [comment]
Looks good, thanks @BirenRathod
