### ISSUE TITLE
Add new field to site details for site information

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#96]
Requirement to add a new site (location) attribute for land-owner contact details.  Text box.

Add to site details page (http://www.ukbms.org/mydata/site-details).  Add as new Tab labelled 'Site contact information'.  Page only available to users with roles:
- recorders with access to site-details page for given site
- branch coordinator with access to branch to which the site is associated
- admin with access to all sites

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you deploy the file in the following zip file into the UKBMS iform/client_helpers/prebuilt_forms directory please?
[ukbms_sectioned_transects_edit_transect.zip](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/3015660/ukbms_sectioned_transects_edit_transect.zip)

After this is done I'll create the attribute: can only do this after the form is deployed.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
This file gone on live for ukbms/mydata

**Comment by Gary-van-Breda** [comment]
Can I confirm this is for all site types: Transects, WCBS-BBS and WCBS-BC?

**Comment by DavidRoy** [comment]
Yes, all survey types

**Comment by Gary-van-Breda** [comment]
Attribute now all set up: checked and looks OK on the form (top level location types only, textarea control)

**Comment by DavidRoy** [comment]
Thanks
