### ISSUE TITLE
Add 'Full sites data download' and 'Full Site Sections data download' to UKBMS Sites page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#97]
Implement these reports on UKBMS
https://github.com/BiologicalRecordsCentre/ABLE/issues/17
https://github.com/BiologicalRecordsCentre/ABLE/issues/16

**Comment by Gary-van-Breda** [comment]
Links added to bottom of "All sites" page.
Equivalent links not on Branch page.
Equivalent links already exist on "My sites" page, but they have been hidden (display style set to none).

I've tested the "All sites" downloads: "Full Sites" works OK, "Full Site Sections" gives a memory error - so
I have put a new version of the "ebms_site_sections_download.xml" (sic) report into the indicia-reports repository under "reports/projects/ebms": @BirenRathod can we deploy this into warehouse1?

The new version does a reduced set of JOINS, so should use less memory and be faster.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

I pulled reports on live warehouse.

**Comment by DavidRoy** [comment]
Timeout occurring on: http://www.ukbms.org/mydata/all-sites

There was an SQL error: ERROR: canceling statement due to statement timeout - SELECT l.id as "id", l.name as "name", l.centroid_sref as "centroid_sref", CASE WHEN lsub.occurrences IS NULL THEN 0 ELSE lsub.occurrences END as "occurrences", CASE WHEN lsub.taxa IS NULL THEN 0 ELSE lsub.taxa END as "taxa", CASE WHEN lsub.groups IS NULL THEN 0 ELSE lsub.groups END as "groups", l.code as "code", location57.id as attr_id_location_57, location57.int_value as attr_location_57 FROM locations l JOIN locations_websites lw ON l.id=lw.location_id AND lw.deleted=false LEFT JOIN ( SELECT section.parent_id as id, COUNT(DISTINCT o.id) AS occurrences, COUNT(DISTINCT o.taxon_meaning_id) AS taxa, COUNT(DISTINCT o.taxon_group_id) AS groups FROM cache_occurrences_functional o JOIN locations section ON o.location_id=section.id AND section.deleted=FALSE WHERE o.zero_abundance='f' AND o.website_id in (27) GROUP BY section.parent_id ) AS lsub on l.id=lsub.id LEFT JOIN location_attribute_values location57 ON location57.location_id=l.id AND location57.location_attribute_id=57 AND location57.deleted=false WHERE l.deleted=false AND (l.code = '' OR l.code IS NULL OR 'no'!='yes') AND l.location_type_id=777 AND (lw.website_id in (27) or lw.website_id is null) ORDER BY occurrences DESC, taxa DESC, name LIMIT 2001

**Comment by BirenRathod** [comment]
It has taken little longer but I don't see any errors.
Here is a screenshot.
![image](https://user-images.githubusercontent.com/5941255/53820797-6aa52c80-3f64-11e9-8334-4b16862ca492.png)

**Comment by Gary-van-Breda** [comment]
There is a bug in the sections report - see https://github.com/BiologicalRecordsCentre/ABLE/issues/41
Fix waiting for deployment.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Have just checked this following the deployment, and both the downloads now work on the "All sites" page.

**Comment by DavidRoy** [comment]
Thanks Gary
@IanMiddlebrook @zrandle can you confirm downloads are ok for you both and close the issue if all ok

**Comment by DavidRoy** [comment]
Closing as this now resolved
