### ISSUE TITLE
Downloading Shapefiles

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#98]
@BirenRathod 

Hi, there seems to be a problem with downloading Shape Files (SHP) from the pages: My Sites, Branch Sites or All Sites.

The other GIS formats are OK (KML & GPX), but the SHP link is returning the following error message:

_"This site can’t be reached warehouse1.indicia.org.uk took too long to respond.
Search Google for warehouse1 indicia org 8080 geoserver wfs
ERR_CONNECTION_TIMED_OUT"_

Thanks, Ian

**Comment by BirenRathod** [comment]
@IanMiddlebrook 
This has resolved now, please check and close if all OK.

**Comment by IanMiddlebrook** [comment]
Thanks @BirenRathod
