### ISSUE TITLE
Upload new BBS squares

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#99]
Hi @Gary-van-Breda Please can you add these new BBS squares to the system. Thanks Zoe
[BBS spring 2019 new sqs- final.xlsx](https://github.com/BiologicalRecordsCentre/UKBMS-online/files/2905319/BBS.spring.2019.new.sqs-.final.xlsx)

**Comment by Gary-van-Breda** [comment]
@zrandle : what does "UNCOVERABLE (deleted from set)" mean?

**Comment by zrandle** [comment]
Ah, I forgot about that - no need to upload the two squares that have this note. Thanks

**Comment by Gary-van-Breda** [comment]
Now uploaded.
@zrandle : Review and close?
